### ISSUE TITLE
首页只提供  YAML front matter 的情况下，会得到一个 vue 的警告

### ISSUE THREAD

**Issue by John60676** [vuepress/vuepress-next#10]
`[Vue warn]: Component is missing template or render function.`

**Comment by meteorlxy** [comment]
https://github.com/vuejs/vue-next/issues/2463

**Comment by meteorlxy** [comment]
If you could help to translate the issue to English, it's OK to keep it open for reference

**Comment by John60676** [comment]
> If you could help to translate the issue to English, it's OK to keep it open for reference

done

**Comment by meteorlxy** [comment]
As the related issue is still pending, for now let's make a temp workaround for it
