### ISSUE TITLE
[Bug report] Container plugin inserted twice and duplicates content

### ISSUE THREAD

**Issue by KILLEliteMaste** [vuepress/vuepress-next#1002]
### Description

This bug does not happens when you are in development, only when you serve the `dist` via a webserver.
[Live preview](https://javacord.org/wiki/getting-started/download-installation.html)

See the linked repo for reproduction.
1. Run `yarn build`, place the content of the `docs/.vuepress/dist` folder in your webserver 
2. Open a link like `http://localhost/wiki/getting-started/download-installation.html`. 

There you can see that a section is duplicated and the container is inserted twice in the document. This does not happens when you click on a different article an come back. You have to visit the site via the link or reload the page. 
When removing the container Syntax
```
::: details
//text
:::
```
it works just fine. Note the `text` in the images, if your remove the text, the very first code group will be highlighted in a warning. and the 

Visiting another article and then click on the bugged site(works like it should):
![image](https://user-images.githubusercontent.com/31566807/181755749-0a9d0528-99c1-4b6d-abad-5be3740e48d8.png)

The bug when reloading the website:
![image](https://user-images.githubusercontent.com/31566807/181756019-5ad56006-b4bf-4e33-82cb-5641cb46ebd8.png)

### Reproduction

https://github.com/Javacord/Website

### Used Package Manager

yarn

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 12.23 GB / 31.95 GB
  Binaries:
    Node: 16.15.0 - ~\AppData\Local\Temp\yarn--1659095948391-0.27187034479048666\node.CMD
    Yarn: 1.22.19 - ~\AppData\Local\Temp\yarn--1659095948391-0.27187034479048666\yarn.CMD
    npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.35.1.
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.71)
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.49
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.49
    @vuepress/client:  2.0.0-beta.49
    @vuepress/core:  2.0.0-beta.49
    @vuepress/markdown:  2.0.0-beta.49
    @vuepress/plugin-active-header-links:  2.0.0-beta.49
    @vuepress/plugin-back-to-top:  2.0.0-beta.49
    @vuepress/plugin-container:  2.0.0-beta.49
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.49
    @vuepress/plugin-git:  2.0.0-beta.49
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.49
    @vuepress/plugin-nprogress:  2.0.0-beta.49
    @vuepress/plugin-palette: ^2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/plugin-prismjs:  2.0.0-beta.49
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: ^2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/plugin-search: ^2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.49
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.49
    @vuepress/theme-default: ^2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/utils: ^2.0.0-beta.49 => 2.0.0-beta.49
    vue:  3.2.37
    vue-loader: Not Found
    vue-router:  4.1.2
    vuepress: ^2.0.0-beta.49 => 2.0.0-beta.49
    vuepress-vite:  2.0.0-beta.49
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
I am not seeing this issue, maybe you should provide a repdocution link? Try adding a test page in your project and give that link to us.

**Comment by KILLEliteMaste** [comment]
> I am not seeing this issue, maybe you should provide a repdocution link? Try adding a test page in your project and give that link to us.

I already told you how to reproduce this in my issue description. 
1. Clone the repo https://github.com/Javacord/Javacord
2. Run `yarn build`, place the content of the `docs/.vuepress/dist` folder in your webserver
3. Open a link like http://localhost/wiki/getting-started/download-installation.html.

**Comment by meteorlxy** [comment]
Well, I didn't find any doc files in the repo you provided, so I did't remove the `need reproduction` label

**Comment by KILLEliteMaste** [comment]
> Well, I didn't find any doc files in the repo you provided, so I did't remove the `need reproduction` label

I am sorry, I dont know how but somehow I copied the wrong link. This is the correct repository https://github.com/Javacord/Website

**Comment by meteorlxy** [comment]
Alright, I'll look into it.

From your description, it's like a typical SSR-mismatch issue.

**Comment by meteorlxy** [comment]
> From your description, it's like a typical SSR-mismatch issue.

It's that. Use `yarn build --debug` to build your site and check the console in your browser.

I think it's caused by your `LatestVersion` component.

**Comment by meteorlxy** [comment]
This might help you to understand the issue better: https://vuejs.org/guide/scaling-up/ssr.html#hydration-mismatch

Check your component, or simply wrap it with our built-it `ClientOnly` component
