### ISSUE TITLE
[Feature request] Loading of v2.vuepress.vuejs.org makes 242 requests

### ISSUE THREAD

**Issue by vmihailenco** [vuepress/vuepress-next#1003]
### Clear and concise description of the problem

Loading https://v2.vuepress.vuejs.org/ without a cache makes 242 requests (both with Webpack and Vite)

![vuepress-requests](https://user-images.githubusercontent.com/290976/181758880-3e372787-2870-425b-aad8-6f2c1f61d6bd.png)

Loading https://vitepress.vuejs.org/ without a cache makes only 12 requests

![vitepress-requests](https://user-images.githubusercontent.com/290976/181759245-602ad453-188d-4d96-a871-5655a7825b31.png)

I can't be sure that the number of requests is the problem, but i am getting a lot of "500 Internal Server Error" responses from AWS CloudFront when initially loading the generated documentation. Just reloading the site fixes the problem so caching helps.

### Suggested solution

Reduce the number of requested files to 10-20 like VitePress does.

**Comment by Mister-Hope** [comment]
https://v2.vuepress.vuejs.org/reference/config.html#shouldpreload

https://v2.vuepress.vuejs.org/reference/config.html#shouldprefetch

Set those to false

**Comment by Mister-Hope** [comment]
Also you may check #952 and #953
