### ISSUE TITLE
2.0.0-beta.49 default theme issue on iPad

### ISSUE THREAD

**Issue by hschaefer123** [vuepress/vuepress-next#1004]
### Description

Hi,
using vuepress search on iPad, the search input field two times shows a magnifier icon.

The large first one is ok, but the second one is maybe comming from an input type (or something like this).

![vuepress-ios-issue](https://user-images.githubusercontent.com/2110971/182040068-32fc7e32-4fde-4e56-8c48-790038ee8c0f.png)

see
https://btp.udina.de

Regards
Holger
 

### Reproduction

open on iPad

### Used Package Manager

npm

### System Info

```shell
not needed
```

**Comment by Mister-Hope** [comment]
I do not have any apple pcs, so it’s hard for me to debug safari, any suggestions Hope to fix this? at least chrome is working

**Comment by hschaefer123** [comment]
Hi,
just figured it out.

Using 
.vuepress/styles/index.scss
with
```
input[type="search"] {
  -webkit-appearance: none;
}
```
is working fine for me (tested on iPhone and iPad).

I think browser default apperance is 'auto' which leads to the apple rendering off a magnifier icon.

BTW: would be great to get a tip concerning my DeepLink question (started a discussion for it),
to bring me into the right directtion.

Best Regards
Holger

P.S. Thanks for your work and the great product!
