### ISSUE TITLE
2.0.0-beta.49 how to avoid keymap "s" from search plugin issue

### ISSUE THREAD

**Issue by hschaefer123** [vuepress/vuepress-next#1005]
### Description

Hi,
adding a web component with custom search field, the vuepress search plugins always captures "s" keystrokes to focus search input.

See
https://btp.udina.de/development/api-explorer.html
![vuepre4ss-s-issue](https://user-images.githubusercontent.com/2110971/182040287-6fa16f87-f99a-4c4f-9cc3-01301bc0eb20.png)

### Reproduction

Try to enter a "s" character into search field, the input lost focus and vuepress search is focused

### Used Package Manager

npm

### System Info

```shell
not important
```

**Comment by Mister-Hope** [comment]
At least try reading docs plz?

https://v2.vuepress.vuejs.org/reference/plugin/search.html#hotkeys

**Comment by hschaefer123** [comment]
Hi,
sorry for bugging ;-)

At least, this was too easy and i did not expect a config option for this.

Works like  a charm.

Best regards
Holger
