### ISSUE TITLE
[Feature request]  provider js-ts switch by default

### ISSUE THREAD

**Issue by tonytony2020** [vuepress/vuepress-next#1006]
### Clear and concise description of the problem

Vue3 and related ecosystem all build by TypeScript, and more and more people start new project with TypeScript,
I think it is a good idea show a JavaScript-TypeScript switch on top-right of demo snippet in docs.

![image](https://user-images.githubusercontent.com/63030915/182126441-341b8e3b-ed8b-4dcd-93a9-d3d7236e772b.png)

### Suggested solution

![image](https://user-images.githubusercontent.com/63030915/182127957-fd5dbf94-896e-4c75-afdb-6b7c393e4692.png)

**Comment by Mister-Hope** [comment]
I think you may want something like this: https://vuepress-theme-hope.github.io/v2/

But IMO, a user who is familar with typescript should have no problem converting js codes to ts. It does be better to provide ts snippets, but it's not really necessary to do that.

I am not possitive to adding ts code demo to all code blocks.
