### ISSUE TITLE
[Feature request] Support vite 3.x

### ISSUE THREAD

**Issue by David-Mueller** [vuepress/vuepress-next#1008]
### Clear and concise description of the problem

During `vuepress build`, the build fails while using the vite 3.0.4 dependency with the following error:

`Missing "./preload-helper" export in "vite" package`

FYI: `vuepress dev` works fine.

### Suggested solution

Update `@vuepress/bundler-vite` to support vite 3

### Additional context

Build works with vite 2.9

**Comment by meteorlxy** [comment]
It's already planned and WIP. Didn't have enough time to finish it yet

**Comment by David-Mueller** [comment]
Great to hear that. Thanks for the amazing work so far!

**Comment by lzxb** [comment]
I need it too
