### ISSUE TITLE
Vuepress2.x 编译报错 TypeError: Invalid value used as weak map key[Bug report] 

### ISSUE THREAD

**Issue by 7foxx** [vuepress/vuepress-next#1011]
### Description

为什么vuepress2不支持使用 font 标签，中Markdown中大多数开发者都是使用 font 标签来标记文字，在大量使用的情况下我们无法快速的将 <font color=#e32d40></font>。 把标签换成 <span style="color:#e32d40"></span> ，请尽快解决

### Reproduction

dev

### Used Package Manager

yarn

### System Info

```shell
vuepress info
```

**Comment by 7foxx** [comment]
为什么vuepress2不支持使用 font 标签，中Markdown中大多数开发者都是使用 font 标签来标记文字，在大量使用的情况下我们无法快速的将 `<font color=#e32d40></font>` 把标签换成 `<span style="color:#e32d40"></span>` ，请尽快解决

**Comment by meteorlxy** [comment]
为什么有些用户不看文档，大多数开发者都是会看项目文档的，在大量不看文档的用户提问的情况下我们无法快速地维护项目，请尽快解决

https://v2.vuepress.vuejs.org/zh/guide/markdown.html#%E9%9D%9E%E6%A0%87%E5%87%86%E7%9A%84-html-%E6%A0%87%E7%AD%BE

**Comment by Mister-Hope** [comment]
干的漂亮hhhh
