### ISSUE TITLE
[Bug report] the html file link changes from "/" into "%2F", which cause 404 error

### ISSUE THREAD

**Issue by MoonLord-LM** [vuepress/vuepress-next#1017]
### Description

left click the link, it shows 404 error
right click and open link in new page, it shows ok

### Reproduction

this is the example page for this bug:
https://github.moonlord.cn/menu3/example.html

and this is the source：
https://github.com/MoonLord-LM/MyPages/blob/master/docs/menu3/example.md
https://github.com/MoonLord-LM/MyPages/blob/master/docs/.vuepress/public/html/example.html

### Used Package Manager

npm

### System Info

```shell
"vuepress": "^2.0.0-beta.49"
```

**Comment by MoonLord-LM** [comment]
this is the example page for this bug: 
https://github.moonlord.cn/menu3/example.html

and this is the source：
https://github.com/MoonLord-LM/MyPages/blob/master/docs/menu3/example.md
https://github.com/MoonLord-LM/MyPages/blob/master/docs/.vuepress/public/html/example.html

**Comment by MoonLord-LM** [comment]
**left click the link, it shows 404 error**
**right click and open link in new page, it shows ok**

**Comment by Mister-Hope** [comment]
You should modify the markdown syntax or config https://v2.vuepress.vuejs.org/reference/config.html#markdown-links to ensure that this is treated as an internal link

**Comment by MoonLord-LM** [comment]
I still think it's a bug. 🤣

**Comment by meteorlxy** [comment]
It would be treated as a dead link if we have a link-check plugin (#945)

**Comment by Mister-Hope** [comment]
then we cannot make this a plugin, instead we must be add it to core.

A plugin can only check existing file path.

**Comment by MoonLord-LM** [comment]
I found a temporary solution to this problem.
Change the ".html" file to ".htm", then the ".htm" link can be accessed perfectly.
