### ISSUE TITLE
[Feature request] Badges in sitemap titles

### ISSUE THREAD

**Issue by hschaefer123** [vuepress/vuepress-next#1020]
### Clear and concise description of the problem

In my site, i have situations using badges on title to show deprecated or retiring services

![fr](https://user-images.githubusercontent.com/2110971/183362011-5e8bf140-fd81-45d9-92fe-c05b02b37b48.png)

It would be great, to be able to add badges also to the sidemap title.

### Suggested solution

Allowing the usage of tags inside sidebar configuration text like
{
  text: "Web Analytics<Badge text=\\"RETIRING SOON\\" type=\\"danger\\" />",
  link: "/service/extension-suite/web-analytics.md",
},
{
  text: "Use Emoji :tada:",
  link: "..",
},
which would be be the most flexible option (even emojis would be possible).

### Alternative

Adding a badge property inside sidebar configuration like:
{
  text: "Web Analytics",
  badge: "Retriring soon",
  badgeType: "danger",
  link: "/service/extension-suite/web-analytics.md",
},
only helps for the requested scenario, but would fulfill my need.

### Additional context

Best Regards
Holger

**Comment by meteorlxy** [comment]
It's intended. Currently, the headers are extracted by the markdown parser as raw text, and won't be treated as vue template.

Your request is technically possible, but it might introduce some breakings, like:

- parsing vue template in client side, or
- extract headers in client side

Now I think we won't plan to implement it for the complexity 🤔
