### ISSUE TITLE
Using keyboard for searching takes to wrong URL

### ISSUE THREAD

**Issue by brc-dd** [vuepress/vuepress-next#1033]
### Reproduction

1. Go to https://v2.vuepress.vuejs.org/
2. Press cmd+k and search something.
3. Hit return. It goes to some URL like `https://v2.vuepress.vuejs.org/https:%2F%2Fvuepress.github.io%2Freference%2Fdefault-theme%2Ffrontmatter.html`

It doesn't happen if I click that.

**Comment by Mister-Hope** [comment]
#1024
