### ISSUE TITLE
[Bug report] Error: Dynamic require of "vuepress" is not supported

### ISSUE THREAD

**Issue by Big-Cake-jpg** [vuepress/vuepress-next#1034]
### Description

Failed to deploy VuePress via Vercel.

```
yarn run v1.22.17
--
16:31:51.264 | $ vuepress build docs
16:31:52.257 | Error: Dynamic require of "vuepress" is not supported
16:31:52.257 | at file:///vercel/path0/docs/.vuepress/config.js.5b2cce3c.mjs:7:9
16:31:52.257 | at docs/.vuepress/config.js (file:///vercel/path0/docs/.vuepress/config.js.5b2cce3c.mjs:16:28)
16:31:52.257 | at __require2 (file:///vercel/path0/docs/.vuepress/config.js.5b2cce3c.mjs:10:50)
16:31:52.258 | at file:///vercel/path0/docs/.vuepress/config.js.5b2cce3c.mjs:72:16
16:31:52.258 | at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
16:31:52.258 | at async Promise.all (index 0)
16:31:52.258 | at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
16:31:52.258 | at async loadUserConfig (file:///vercel/path0/node_modules/@vuepress/cli/dist/index.js:51:18)
16:31:52.258 | at async file:///vercel/path0/node_modules/@vuepress/cli/dist/index.js:175:26
```

Sometimes happens on my PC too.

Node.js v18.0 (PC), v17.0 (Vercel), VuePress 2.0-beta.49

### Reproduction

https://github.com/Big-Cake-jpg/mss-docs

### Used Package Manager

yarn

### System Info

```shell
> I'm unable to get system info via `vuepress info` command.

Windows 11 Insider Preview build 25179

⠋ Collecting Environment InfoTypeError: envinfo.run is not a function
    at info (file:///D:/mss-docs/node_modules/@vuepress/cli/dist/index.js:490:32)
    at CAC.wrappedCommand (file:///D:/mss-docs/node_modules/@vuepress/cli/dist/index.js:549:39)
    at CAC.runMatchedCommand (file:///D:/mss-docs/node_modules/cac/dist/index.mjs:610:34)
    at CAC.parse (file:///D:/mss-docs/node_modules/cac/dist/index.mjs:537:12)
    at cli (file:///D:/mss-docs/node_modules/@vuepress/cli/dist/index.js:567:11)
    at file:///D:/mss-docs/node_modules/vuepress-vite/bin/vuepress.js:8:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
```
```

**Comment by meteorlxy** [comment]
You are not providing a lockfile in the repo. Please add one, or we could not reproduce your enviroment

**Comment by Big-Cake-jpg** [comment]
> You are not providing a lockfile in the repo. Please add one, or we could not reproduce your environment

[yarn.lock.txt](https://github.com/vuepress/vuepress-next/files/9372380/yarn.lock.txt)

GitHub doesn't support uploading yarn.lock file, so I changed extention name to txt. Sorry about that.

**Comment by meteorlxy** [comment]
> GitHub doesn't support uploading yarn.lock file

It's in your `.gitignore` file..

**Comment by Big-Cake-jpg** [comment]
> > GitHub doesn't support uploading yarn.lock file
> 
> It's in your `.gitignore` file..

This one......
![image](https://user-images.githubusercontent.com/76810494/185389401-bde6ce3b-6154-40a4-ad0b-f004476fb1d3.png)

**Comment by Big-Cake-jpg** [comment]
> > GitHub doesn't support uploading yarn.lock file
> 
> It's in your `.gitignore` file..

@meteorlxy I'm pushed the lockfile. Sorry for the delay.

**Comment by meteorlxy** [comment]
So check your lockfile, you've installed the deperacated version

![image](https://user-images.githubusercontent.com/18205362/185411696-839119b2-0b1b-41b4-9bcb-8616822a018a.png)

**Comment by imaegoo** [comment]
Same issue, this should work:

`package.json`

```diff
  "devDependencies": {
-   "@vuepress/plugin-docsearch": "^2.0.0-beta.46",
-   "vuepress": "^2.0.0-beta.46"
+   "@vuepress/plugin-docsearch": "next",
+   "vuepress": "next"
  }
```
