### ISSUE TITLE
[Bug report] TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by feericu** [vuepress/vuepress-next#1041]
### Description

When I markdown files have special html label, This tag is <center></center>
Then I perform 'npm run doc:build'
The console error: TypeError: Invalid value used as weak map key

vuepress version:  2.0.0-beta.49

this is error link: https://github.com/feericu/babel/runs/7976123234?check_suite_focus=true

<img width="587" alt="image" src="https://user-images.githubusercontent.com/11989062/186192386-dd7be793-f691-45f4-8e1c-7f479c8a1bc5.png">

### Reproduction

https://github.com/feericu/babel/runs/7976123234?check_suite_focus=true

### Used Package Manager

npm

### System Info

```shell
vuepress version:  2.0.0-beta.49
node -v v14.20.0
npm --version 8.13.2
```

**Comment by meteorlxy** [comment]
Sorry? What the tag is ? And maybe you can refer to the docs for help:

https://v2.vuepress.vuejs.org/guide/markdown.html#non-standard-html-tags

**Comment by feericu** [comment]
It is useful to me, The error reminder, however, can be a bit more obvious?

**Comment by Mister-Hope** [comment]
> It is useful to me, The error reminder, however, can be a bit more obvious?

The error is thrown by vue, so if you think the error is not clear, report there. BTW, I think vue already changed related logic in newer versions.
