### ISSUE TITLE
[Bug report] Why the mjs file [app.f1603bd5.mjs] is in [\docs\.vuepress\dist] folder ???

### ISSUE THREAD

**Issue by MoonLord-LM** [vuepress/vuepress-next#1043]
### Description

Why the mjs file is in [\docs\.vuepress\dist] folder ???
This file is not necessary, is it?

https://github.com/MoonLord-LM/MyPages/

### Reproduction

https://github.com/MoonLord-LM/MyPages/tree/github-pages

### Used Package Manager

npm

### System Info

```shell
v2.0.0-beta.50
```

**Comment by meteorlxy** [comment]
Uh, thanks for reporting. It's necessary, but used to be inside the `assets` sub dir. We tweaked the output config for SSR build, but also changed the client build. Should be fixed.
