### ISSUE TITLE
[Bug report] The specifier only resolves to an ES module, which cannot be imported synchronously

### ISSUE THREAD

**Issue by azat-io** [vuepress/vuepress-next#1046]
### Description

<img width="1015" alt="Screenshot 2022-08-24 at 5 56 48 PM" src="https://user-images.githubusercontent.com/5698350/186479732-633209a2-2acb-429f-bcae-39bfee2e636c.png">

Not sure if this is a Vuepress issue. However, I'm asking for your help.

1. Clone [repo](https://github.com/azat-io/typescript-nodenext-module)
2. Install dependencies `pnpm install`
3. Run `pnpm test` 

### Reproduction

https://github.com/azat-io/typescript-nodenext-module

### Used Package Manager

pnpm

### System Info

```shell
VuePress v2.0.0-beta.50
Typescript v4.7.4
```

**Comment by meteorlxy** [comment]
You need to set `"moduleResolution": "NodeNext"`, or typescript won't resolve types according to the `exports` field of `package.json`.

However, it might be inconvenient. We are considering to revert the `./lib/client` entry as beta.49 and before :thinking:

**Comment by azat-io** [comment]
<img width="881" alt="image" src="https://user-images.githubusercontent.com/5698350/186896788-bbbb8505-4275-4aea-a3fd-62acf990a32f.png">

If I set `"moduleResolution": "node"` everything works well except VuePress plugins in `.vue` files. Looks like a problem with `vue-tsc` https://github.com/johnsoncodehk/volar/issues/1662.

But ``"moduleResolution": "node"`` still not working. I guess revert to `./lib/client` will temporarily fix issue.

**Comment by azat-io** [comment]
This is not stale issue 😞

**Comment by azat-io** [comment]
I think this is a critical issue. Typescript projects cannot be upgraded to version `beta.50` and above

**Comment by Mister-Hope** [comment]
Hey, in my test, if you convert layout.vue into layout.ts, everything works fine.

As the ts error is actually provided by volar service while it called ts language service internally, I do think that it might be a volar probem.

**Comment by azat-io** [comment]
@Mister-Hope Perhaps this is a problem on the volar side. I have created `esm` branch in my repo with updated Vuepress version. Now I am getting a lot of TypeScript errors in my `.ts` and `.vue` files.
https://github.com/azat-io/azat-io/tree/esm

```
git checkout esm
make install
make test
```

**Comment by azat-io** [comment]
Looks like this is volar problem
