### ISSUE TITLE
[Bug report] Is there any possibility that I can generate [.js] file instead of [.mjs] file ?

### ISSUE THREAD

**Issue by MoonLord-LM** [vuepress/vuepress-next#1050]
### Description

My front-end server does not support the [.mjs] file type.

So I have to replace the file name extension from [.mjs] to [.js] manually.

    cd ./docs/.vuepress/dist
    sed -i "s#.mjs#.js#g" `grep ".mjs" -rl ./`
    tmp1=`find ./ -name \*.mjs`
    tmp2=`echo $tmp1 | sed "s#.mjs#.js#g"`
    mv "$tmp1" "$tmp2"

### Reproduction

N/A

### Used Package Manager

npm

### System Info

```shell
v2.0.0-beta.50
```

**Comment by meteorlxy** [comment]
I thought you have reported it in #1043. Except the wrongly generated app.xxx.mjs file, do you still have any other .mjs files?

**Comment by MoonLord-LM** [comment]
Yes, I have read the code.
And I was wondering if the [ isServer ] can be a config that can be switched on or switched off or something ?
I see that the [.mjs] file type are the future trend, right?

**Comment by MoonLord-LM** [comment]
Maybe I'm thinking too much.
When ES6 is fully popularized, I think many servers should also be able to support mjs files.
