### ISSUE TITLE
[Bug report] Can't use the plugin in config.ts

### ISSUE THREAD

**Issue by feericu** [vuepress/vuepress-next#1051]
### Description

<img width="448" alt="image" src="https://user-images.githubusercontent.com/11989062/186683767-c3943573-d3b2-448c-8ca6-e4a3b7a5d6d3.png">

In docs/.vuepress/config.ts, Configure the plugins error

<img width="828" alt="image" src="https://user-images.githubusercontent.com/11989062/186684317-81a335f5-6480-4966-a1b2-0232aa54ab63.png">

npm run dev

<img width="949" alt="image" src="https://user-images.githubusercontent.com/11989062/186684655-28a45419-eb21-43ea-8e60-50de7d946b45.png">

### Reproduction

https://github.com/feericu/babel

### Used Package Manager

npm

### System Info

```shell
node version: 14.20.0
npm version: 8.13.2
"vuepress": "^2.0.0-beta.49"
"@vuepress/plugin-back-to-top": "^2.0.0-beta.50"
"@vuepress/plugin-google-analytics": "^2.0.0-beta.50"
```

**Comment by meteorlxy** [comment]
![image](https://user-images.githubusercontent.com/18205362/186686103-db1f65b7-1170-4a1f-8a41-73475034cc6f.png)

Use the same version please.
