### ISSUE TITLE
[Bug report] plugin-vue-export-helper in vite breaks github pages and increase output size

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#1061]
### Description

In some projects, a single line chunk called `_plugin-vue_export-helper.[hash].js`  will be extracted in production mode.

However this actually:

- Increase size
- Let project fail on github pages with default settings (as jekyll omit files starting with underscore by default)

We need to configure chunks generation like vitepress:

- Outputing vue, vue-router and @vuepress/client to a chunk
- Pack toll chunks like the one mention above in app.js or in another chunk

### Reproduction

Not needed

### Used Package Manager

npm

### System Info

```shell
Not needed
```

**Comment by kaosine** [comment]
@Mister-Hope where should it be added though? I was about to ask that when you closed it.

**Comment by Mister-Hope** [comment]
Add a empty file named `.nojekyll` in output folder.

**Comment by meteorlxy** [comment]
I thinks this should be fixed by #1101 right?

**Comment by azat-io** [comment]
#1101 was reverted
