### ISSUE TITLE
[Bug report] Documentation Issue (register-component)

### ISSUE THREAD

**Issue by properCase** [vuepress/vuepress-next#1064]
### Description

I'm just getting into VuePress, and one of the things I've found frustrating is the lack of clarity on what file we're talking about 

The documentation in question:
https://github.com/vuepress/vuepress-next/blob/main/docs/reference/plugin/register-components.md

Shows how to install the component and then it displays the contents of a file, but doesn't tell you want file it is supposed to be, or where that file is supposed to be located.  As someone new to VuePress it would sure be helpful if the documentation listed the file name and location above each example, like so:

_docs/.vuepress/fancyFileYouNeed.js_
```js
import { registerComponentsPlugin } from '@vuepress/plugin-register-components'

export default {
  plugins: [
    registerComponentsPlugin({
      // options
    }),
  ],
}
```

Meanwhile, could you please tell me how I can register and use a custom vue component 😁. None of the files in the documentation tell you what file we're talking about.

### Reproduction

https://github.com/vuepress/vuepress-next/blob/main/docs/reference/plugin/register-components.md

### Used Package Manager

npm

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.18 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Utilities:
    Git: 2.32.1 - /usr/bin/git
  Browsers:
    Chrome: 104.0.5112.101
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.6.1
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.49 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.49 
    @vuepress/client: ^2.0.0-beta.49 => 2.0.0-beta.49 
    @vuepress/core:  2.0.0-beta.49 
    @vuepress/markdown:  2.0.0-beta.49 
    @vuepress/plugin-active-header-links:  2.0.0-beta.49 
    @vuepress/plugin-back-to-top:  2.0.0-beta.49 
    @vuepress/plugin-container:  2.0.0-beta.49 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.49 
    @vuepress/plugin-git:  2.0.0-beta.49 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.49 
    @vuepress/plugin-nprogress:  2.0.0-beta.49 
    @vuepress/plugin-palette:  2.0.0-beta.49 
    @vuepress/plugin-prismjs:  2.0.0-beta.49 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.49 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.49 
    @vuepress/theme-default:  2.0.0-beta.49 
    @vuepress/utils:  2.0.0-beta.49 
    vue: ^3.2.37 => 3.2.37 
    vue-loader: Not Found
    vue-router: ^4.1.4 => 4.1.5 
    vuepress: ^2.0.0-beta.49 => 2.0.0-beta.49 
    vuepress-vite:  2.0.0-beta.49 
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
You'd better learn how to use a plugin in https://v2.vuepress.vuejs.org/guide/plugin.html

I don't think detailed infomation is needed in this page. Closing as no need to fix.

Welcomed to share ideas about this part if you have any improvements idea.
