### ISSUE TITLE
[Bug report] Missing exports in default-theme

### ISSUE THREAD

**Issue by stfsy** [vuepress/vuepress-next#1068]
### Description

Up until **Beta 49** I was overriding the `PageMeta` component in my project because I already have a `footer` in my custom layout and didn't want to have two `footer` elements on the same page.

Therefore, my custom [PageMeta](https://github.com/discue/ui-components/blob/main/docs/.vuepress/theme/components/PageMeta.vue#L101) is merely a copy of the original PageMeta component, with the `footer` element being replaced by a `div`.

Starting **Beta 50** only a limited set of paths is [exported](https://github.com/vuepress/vuepress-next/blob/main/ecosystem/theme-default/package.json#L22-L31) 
```json
  "exports": {
    ".": "./lib/node/index.js",
    "./client": "./lib/client/index.js",
    "./components/*": "./lib/client/components/*",
    "./layouts/*": "./lib/client/layouts/*",
    "./styles/*": "./lib/client/styles/*",
    "./templates/*": "./templates/*",
    "./lib/*": "./lib/*",
    "./package.json": "./package.json"
  },
```
which do not include the modules that are needed by [PageMeta](https://github.com/vuepress/vuepress-next/blob/main/ecosystem/theme-default/src/client/components/PageMeta.vue#L6-L12)

```js
import type {
  DefaultThemeNormalPageFrontmatter,
  DefaultThemePageData,
  NavLink,
} from '@vuepress/theme-default/lib/shared/index.js'
import { useThemeLocaleData } from '@vuepress/theme-default/lib/client/composables/index.js'
import { resolveEditLink } from '@vuepress/theme-default/lib/client/utils/index.js'
```

I'm adding a custom footer to be able to reuse the footer of the main page. The docs are deployed here: https://ui.discue.io/

Also, overriding Layout isn't possible anymore, because it's not exported too.

### Reproduction
https://github.com/discue/ui-components/runs/8144254669?check_suite_focus=true

### Used Package Manager

npm

### System Info

```shell
[/c/workspace/discue-io-ui ⎇ main] npx vuepress info
⠋ Collecting Environment InfoTypeError: envinfo.run is not a function
    at info (file:///C:/workspace/discue-io-ui/node_modules/@vuepress/cli/dist/index.js:516:32)      
    at CAC.wrappedCommand (file:///C:/workspace/discue-io-ui/node_modules/@vuepress/cli/dist/index.js:575:39)
    at CAC.runMatchedCommand (file:///C:/workspace/discue-io-ui/node_modules/cac/dist/index.mjs:610:34)
    at CAC.parse (file:///C:/workspace/discue-io-ui/node_modules/cac/dist/index.mjs:537:12)
    at cli (file:///C:/workspace/discue-io-ui/node_modules/@vuepress/cli/dist/index.js:593:11)       
    at file:///C:/workspace/discue-io-ui/node_modules/vuepress-vite/bin/vuepress.js:8:1
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
```

**Comment by stfsy** [comment]
So my questions would be: 

- Is there another way to replace the footer element without overriding the whole PageMeta component?
- Would you be willing to replace the footer element in the default PageMeta Component?
- Would it be possible to export other modules of the default-theme too?

**Comment by meteorlxy** [comment]
The `"./lib/*"` export is already added and will be published in next release.
