### ISSUE TITLE
[Bug report] How to iterate based on the default theme

### ISSUE THREAD

**Issue by qqlcx5** [vuepress/vuepress-next#1072]
### Description

<img width="940" alt="image" src="https://user-images.githubusercontent.com/31888710/188388559-4c306296-3a79-43c1-ba89-1716f2169d90.png">

![image](https://user-images.githubusercontent.com/31888710/188388822-538e0901-2413-40eb-b9ae-b812d5ff5565.png)

### Reproduction

https://github.com/qqlcx5/vuepress-next/tree/master/docs/.vuepress/theme-acme

### Used Package Manager

npm

### System Info

```shell
Environment Info:

  System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.52
    Edge: Not Found
    Firefox: Not Found
    Safari: 16.1
  npmPackages:
    @vuepress/core:  2.0.0-beta.51 
    @vuepress/theme-default:  2.0.0-beta.51 
    vuepress: ^2.0.0-beta.51 => 2.0.0-beta.51 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by meteorlxy** [comment]
`@vuepress/theme-default/components/*.vue`
