### ISSUE TITLE
[Feature request]  On startup, list Plugin like on VuePress 1.x

### ISSUE THREAD

**Issue by JulioJu** [vuepress/vuepress-next#108]
## Feature request

List Plugin used like on VuePress 1.x

### Description

On VuePress 1, when we run `yarn vuepress dev ./myproject` we have following output

```
$ vuepress dev myProject
wait Extracting site metadata...
tip Apply theme vuepress-theme-theme ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin medium-zoom (i.e. "vuepress-plugin-medium-zoom") ...
tip Apply plugin sitemap (i.e. "vuepress-plugin-sitemap") ...
tip Apply plugin seo (i.e. "vuepress-plugin-seo") ...
```

It's interesting as we have a list of all plugins used. It's interesting because often we use theme that embed some plugins.

When there was an erreor, we have a message like 

```
warning An error was encountered in plugin "nothing"
```

There is no much information when we use option `debug`. 

The only way to know which plugins are applied is to investigate Source Code (and sometime as a theme could depend to another, it could be not easy)

### Proposed Solution

Import this behavior from VuePress 1.x

If you accept, thanks in advance :-)

**Comment by meteorlxy** [comment]
`DEBUG=vuepress* yarn vuepress dev`

**Comment by JulioJu** [comment]
Thanks :-)
