### ISSUE TITLE
[Bug report] “error Element is missing end tag” when using angle brackets in md

### ISSUE THREAD

**Issue by wechiwin** [vuepress/vuepress-next#1114]
### Description

1. used angle brackets in the table of md file like this:

| 接口名               | 抽象方法                       | 描述                       |
| -------------------- | ------------------------------ | -------------------------- |
| Consumer<T>          | void accept(T t)               | 接收一个对象用于完成功能   |
| BiConsumer<T,U>      | void accept(T t, U u)          | 接收两个对象用于完成功能   |
| DoubleConsumer       | void accept(double value)      | 接收一个double值           |
| IntConsumer          | void accept(int value)         | 接收一个int值              |
| LongConsumer         | void accept(long value)        | 接收一个long值             |
| ObjDoubleConsumer<T> | void accept(T t, double value) | 接收一个对象和一个double值 |
| ObjIntConsumer<T>    | void accept(T t, int value)    | 接收一个对象和一个int值    |
| ObjLongConsumer<T>   | void accept(T t, long value)   | 接收一个对象和一个long值   |

2. or in heading:

#### void ifPresent(Consumer<? super T> consumer)

error occurred when running:

7:19:11 PM [vite] Internal server error: Element is missing end tag.
  Plugin: vite:vue
  File: /Users/raywei/template/.vuepress/.temp/pages/docs/java-2-senior/java-8-new-features.html.vue
  121|  <tbody>
  122|  <tr>
  123|  <td>Consumer<T></td>
     |      ^
  124|  <td>void accept(T t)</td>
  125|  <td>接收一个对象用于完成功能</td>

3. but it's ok when using it in code snippet:

```java
@Test
public void ifPresentTest() {
    Optional<String> optional = Optional.ofNullable("Macintosh");
    optional.ifPresent(System.out::println); // Macintosh
}
```

### Reproduction

https://stackblitz.com/edit/vuepress-2zfofu?file=docs/guide/README.md

### Used Package Manager

npm

### System Info

```shell
"devDependencies": {
    "vuepress": "^2.0.0-beta.51",
    "vuepress-theme-reco": "^2.0.0-beta.41"
  }

macos monterey 12.5
node v18.7.0
npm 8.15.0
```

**Comment by wechiwin** [comment]
tried on vuepress 1.x and this didnt happen

**Comment by Mister-Hope** [comment]
https://v2.vuepress.vuejs.org/guide/markdown.html#non-standard-html-tags

```md
<tag>

\<tag\>
```

<tag>

\<tag\>

**Comment by Mister-Hope** [comment]
Try not to be too noob, as you can see, your content even can not render correctly on GitHub, and that already gives you chance to check your syntax.
