### ISSUE TITLE
[Bug report] 在import '@wangeditor/editor-for-vue' 时,build编译报错Element is not defined

### ISSUE THREAD

**Issue by tomiaa12** [vuepress/vuepress-next#1126]
### Description

`✔ Compiling with vite - done
✖ Rendering pages - failed
ReferenceError: Element is not defined
    at D:\@kyx\node_modules\.pnpm\@wangeditor+editor@5.1.21\node_modules\@wangeditor\editor\dist\index.js:23656:8723
    at D:\@kyx\node_modules\.pnpm\@wangeditor+editor@5.1.21\node_modules\@wangeditor\editor\dist\index.js:23656:10426
    at o (D:\@kyx\node_modules\.pnpm\@wangeditor+editor@5.1.21\node_modules\@wangeditor\editor\dist\index.js:23648:517)
    at D:\@kyx\node_modules\.pnpm\@wangeditor+editor@5.1.21\node_modules\@wangeditor\editor\dist\index.js:23648:11538
    at D:\@kyx\node_modules\.pnpm\@wangeditor+editor@5.1.21\node_modules\@wangeditor\editor\dist\index.js:23648:18
    at D:\@kyx\node_modules\.pnpm\@wangeditor+editor@5.1.21\node_modules\@wangeditor\editor\dist\index.js:23648:61
    at createCommonjsModule$1 (D:\@kyx\node_modules\.pnpm\@wangeditor+editor@5.1.21\node_modules\@wangeditor\editor\dist\index.js:91:11)   
    at D:\@kyx\node_modules\.pnpm\@wangeditor+editor@5.1.21\node_modules\@wangeditor\editor\dist\index.js:23647:14
    at D:\@kyx\node_modules\.pnpm\@wangeditor+editor@5.1.21\node_modules\@wangeditor\editor\dist\index.js:2:66
    at Object.<anonymous> (D:\@kyx\node_modules\.pnpm\@wangeditor+editor@5.1.21\node_modules\@wangeditor\editor\dist\index.js:5:3)
 ELIFECYCLE  Command failed with exit code 1.`

### Reproduction

https://stackblitz.com/edit/vuepress-vaiu2y?file=package.json,docs%2Fvuepress.client.ts,docs%2FREADME.md,docs%2Fcomponents%2FTest.vue,docs%2F.vuepress%2Fconfig.ts

### Used Package Manager

pnpm

### System Info

```shell
Environment Info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\node_modules\yarn\bin\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.53)
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: ^2.0.0-beta.48 => 2.0.0-beta.49
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by Mister-Hope** [comment]
https://v2.vuepress.vuejs.org/advanced/cookbook/usage-of-client-config.html#use-non-ssr-friendly-features
