### ISSUE TITLE
[Feature request] Customizable default language directory

### ISSUE THREAD

**Issue by leisim** [vuepress/vuepress-next#1127]
### Clear and concise description of the problem

Currently all the language folders have to be in the docs folder together with the primary language markdown files.

My docs structure looks like this:
```
docs/
├── .vuepress
├── cn
├── de
├── ja
├── tutorials/
│   ├── quickstart.md
│   └── first_steps.md
├── README.md
├── faq.md
└── limitations.md
```

With three languages that already looks messy but with 15 it will be a nightmare. 

### Suggested solution

It would be awesome if the English files could also be in a folder:

```
docs/
├── .vuepress
├── cn
├── de
├── en/
│   ├── tutorials/
│   │   ├── quickstart.md
│   │   └── first_steps.md
│   ├── README.md
│   ├── faq.md
│   └── limitations.md
└── ja
```

### Alternative

Alternatively allow putting all the translations in a folder:
```
docs/
├── .vuepress
├── i18n/
│   ├── cn
│   ├── de
│   └── ja
├── tutorials/
│   ├── quickstart.md
│   └── first_steps.md
├── README.md
├── faq.md
└── limitations.md
```

**Comment by Mister-Hope** [comment]
Thanks for the advice, butwith `vuepress-plugin-redirect@next` (See https://vuepress-theme-hope.github.io/v2/redirect/guide.html#redirect-to-pages) you will be able to make redirects.

Our default design is based on one thing: default route path is redirectly transformed from file structure. So we will not consider path transformed here.

---

Solution:

1. Make your en docs under `/en/`, then redirect any pages which is not under i18n directory with `/en/` prefix.
2. Make your en docs under `/en/`, but use `extendsPage` to set permalink for all pages under `/en/` and make theme avaiable at root, then make `/en/xx` redirects to `/xx`
