### ISSUE TITLE
[Bug report] The syntax highlighter color produced by the compiler is incorrect. 

### ISSUE THREAD

**Issue by CikiMomogi** [vuepress/vuepress-next#1130]
### Description

This one is the result of running `docs:dev`:

![dev](https://user-images.githubusercontent.com/74030149/196050977-e998fa09-9652-4e6e-b49f-6e3b13dae7b4.png)

While this one is made by running `docs:build`:

![build](https://user-images.githubusercontent.com/74030149/196050993-1f1da452-3ad1-49e5-b9d9-f53757b1a06e.png)

### Reproduction

(1) Clone this repository. (2) Run `pnpm install`. (3) Run `pnpm build`. (4) Run `pnpm docs:dev`. (5) Run `pnpm docs:build`.

### Used Package Manager

pnpm

### System Info

```shell
Binaries:
  Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
  Yarn: Not Found
  npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
Browsers:
  Chrome: Not Found
  Firefox: 105.0.2
npmPackages:
  @vuepress/core: Not Found
  @vuepress/theme-default: Not Found
  vuepress: Not Found
npmGlobalPackages:
  vuepress: Not Found
```

**Comment by Mister-Hope** [comment]
We are using prism during dev and shiki on build. What's the problem?

**Comment by CikiMomogi** [comment]
I see, it is intended behavior then. So we need to install [shiki plugin](https://v2.vuepress.vuejs.org/reference/plugin/shiki.html) to use them in the production stage, right? Or is there any option to enable them in the config file?

**Comment by Mister-Hope** [comment]
See

https://github.com/vuepress/vuepress-next/blob/c63bd4a75fb61860e969e4bc229c2754b9aac0b6/docs/.vuepress/config.ts#L108
https://github.com/vuepress/vuepress-next/blob/c63bd4a75fb61860e969e4bc229c2754b9aac0b6/docs/.vuepress/config.ts#L181

You don't NEED to do this.

Shiki is more acurate (It's VSCode built-in highlighter) and prism support more language, choose it wisely yourself.
