### ISSUE TITLE
[Bug report] Markdown Order List Sub index letters don't list

### ISSUE THREAD

**Issue by devPaulRS** [vuepress/vuepress-next#1137]
### Description

Markdown List e.g

1. Item
a. sub item a
b. sub item b
2. Item 2
a. sub item a
3. Item 3

Vuepress 2:
1. Item a. sub item a b. sub item b

Looks like sub items are clumped in a single line even with line breaks between them, doesn't display like git or markdown.

### Reproduction

v2.vuepress.vuejs.org/new 

### Used Package Manager

npm

### System Info

```shell
Don't think this is required for the above problem.
```

**Comment by Mister-Hope** [comment]
Provide a snippet using code blocks please, e.g.:

```md
1. A
  1. A1
1. B
  1. B1
  1. B2
```

**Comment by devPRS** [comment]
@Mister-Hope I think that's unnecessary GitHub also uses markdown and you can clearly see in the top where under description that it states there what the problem is, it's not making a line break between a b and c, this is inconsistent to markdown files.. it's no where seen on VuePress docs where you use the same way, but this is a common use of order list.

**Comment by devPRS** [comment]
@Mister-Hope 

https://stackblitz.com/edit/vuepress-gbzt9p?file=docs/guide/README.md

**Comment by Mister-Hope** [comment]
We are using markdown-it, wjich support commonmark.

See http://markdown-it.github.io/

![Screenshot_2022-10-21-17-29-09-71_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/33315834/197163664-fed82c0d-99f2-4e9d-a1c2-efb603b206fc.jpg)

If you want to discuss whether the behavior is right or not, go to this repo.

Also I may remind you only number followed by dot and space at line start with or without whitespace prefix is considered as order list.

**Comment by vassudanagunta** [comment]
@Mister-Hope The issue here is a misunderstanding of how both Markdown lists actually work. The OP's description is simply wrong. See https://github.com/commonmark/commonmark.js/issues/266

**Comment by devPaulRS** [comment]
@vassudanagunta Pitty they deleted your awfully crude message so none of the repos you tagged can see your narrow perspective.

But to answer this issue: Dont waste time asking common mark developers to make changes to spec even though their all wrong; clearly displayed by all the documentation microsoft applications in general same with many other office suite software and documentation in general(the paperwork you sign on contracts) 🤷🏻‍♂️

But no need to worry, so far I've had to code everything myself and I find that rather worrisome, as none of you providedany solutions or assistance except "why we wont help you."

Up to the renderer's descretion..  when even the renderer doesnt want to, so its understandable, I cant force any of you to help so I do it myself. Simple.
