### ISSUE TITLE
[Bug report] Define permalink into Markdown broken

### ISSUE THREAD

**Issue by JulioJu** [vuepress/vuepress-next#114]
### Description

Define permalink into Markown as defined in dev mode or in prod mode https://vuepress2.netlify.app/reference/frontmatter.html#permalink or  https://vuepress.vuejs.org/guide/permalinks.html#configure-permalinks is broken . 

### Steps to reproduce

- Reproduction link / repo: https://github.com/JulioJu/vuepress-demonstrate-warning

#### Prepare
* Clone https://github.com/JulioJu/vuepress-demonstrate-warning
* `yarn install``

### In Dev

* `yarn dev`
* => localhost:8080
* in page http://localhost:8080, click to link `Link to page "test2" ` => all work well
* Reload page `Ctrl + r`  we have message
>  Page does not exist. This is a fallback content.

 Same problem if we use direct link to http://localhost:8080/test2

### In prod

* `yarn serve`
* => localhost:8000
* in page http://localhost:8000, click to link `Link to page "test2" ` => all work well
* Reload page `Ctrl + r`  
* => Firefox ask if we want download the page

 Same problem if we use direct link to http://localhost:8000/test2

### Expected behavior

`permalink` frontmatter should work

### Environment info

- Browser: Mozilla Firefox 87.0

- Output of `vuepress info`:

```bash
$ yarn vuepress info
yarn run v1.22.10
$ /tmp/essai/node_modules/.bin/vuepress info

  System:
    OS: Linux 5.10 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 886.16 MB / 7.53 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /tmp/yarn--1618162335393-0.27195924212408906/node
    Yarn: 1.22.10 - /tmp/yarn--1618162335393-0.27195924212408906/yarn
    npm: 7.8.0 - /usr/bin/npm
  Utilities:
    Git: 2.31.1 - /usr/bin/git
  Browsers:
    Chrome: Not Found
    Firefox: 87.0
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.8
    @vuepress/cli:  2.0.0-beta.8
    @vuepress/client:  2.0.0-beta.8
    @vuepress/core:  2.0.0-beta.8
    @vuepress/markdown:  2.0.0-beta.8
    @vuepress/plugin-active-header-links:  2.0.0-beta.8
    @vuepress/plugin-back-to-top:  2.0.0-beta.8
    @vuepress/plugin-container:  2.0.0-beta.8
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.8
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.8
    @vuepress/plugin-nprogress:  2.0.0-beta.8
    @vuepress/plugin-palette:  2.0.0-beta.8
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.8
    @vuepress/shared:  2.0.0-beta.7
    @vuepress/theme-default:  2.0.0-beta.8
    @vuepress/theme-vue: Not Found
    @vuepress/utils:  2.0.0-beta.8
    vue:  3.0.11
    vue-loader:  16.2.0
    vue-router:  4.0.6
    vuepress: ^2.0.0-beta.8 => 2.0.0-beta.8
    vuepress-vite: Not Found

Done in 1.08s.
```

**Comment by meteorlxy** [comment]
The reason is your permalink does not end with `'.html'` nor `'/'`.

- If permalink ends with `'.html'`, keep it as is.
- If permalink ends with `'/'`, add trailing `'index.html'`.
- If permalink does not end with `'.html'` nor `'/'` - we currently keep it as is, but I think we'd better add trailing `'/index.html'` to avoid the mistake.

I'd perfer to mark this as an enhancement rather than a bug.
