### ISSUE TITLE
Error in built docs: ``Referapp.c20e2fa1.js:1 Uncaught ReferenceError: Cannot access 'j' before initialization``

### ISSUE THREAD

**Issue by marwie** [vuepress/vuepress-next#1140]
### Description

Hello, 

followed the documentation and started a new vuepress project using ``2.0.0-beta.52`` 
Works fine and great in local dev but built docs throw errors and seems like all js fails because of it (e.g. search, selection of theme light<>dark)

STRP:
1. go to ``src``
2. run ``npm install``
3. run ``npm run docs:build``
4. Upload .vuepress dist folder to some FTP or deploy to github pages
5. observe error in console

![image](https://user-images.githubusercontent.com/5083203/197330896-5d43e3d2-c3c7-4079-a453-6964374de79e.png)

config:
```ts
import { defineUserConfig, defaultTheme } from 'vuepress'

export default defineUserConfig({
    base: "/wiki-test/",
    lang: 'en-US',
    title: 'Title',
    description: '....',
})
```

### Reproduction

https://github.com/marwie/wiki-test/tree/vuepress/build-error

[dist.zip](https://github.com/vuepress/vuepress-next/files/9843990/dist.zip)

### Used Package Manager

npm

### System Info

```shell
win 10
Chrome Version 106.0.5249.119
```

### Screenshots

app:
![image](https://user-images.githubusercontent.com/5083203/197331158-56a12730-d4ce-4332-8c0e-5139e80e5272.png)

vendor:
![image](https://user-images.githubusercontent.com/5083203/197331227-96f613e7-263f-4c91-9f34-0794cc6c2cef.png)

**Comment by Mister-Hope** [comment]
This is not a minimal reproduction, you are using 3rd party plugins, disable them and try to make another repro

**Comment by marwie** [comment]
Hello @Mister-Hope sorry about that - i wasnt using them in the config.ts

Remove them from package.json, cleared caches, built and got the same result.

The branch is updated

**Comment by azat-io** [comment]
![Screen Recording 2022-10-22 at 3 17 37 PM](https://user-images.githubusercontent.com/5698350/197338770-6a6826eb-742e-4f76-95d4-c419c0499d78.gif)

Same problem. Also, routing was broken after VuePress upgrading to v2.0.0-beta.52.

cc @Mister-Hope

**Comment by marwie** [comment]
@azat-io did it work on a previous version (if so which version did you use?)

**Comment by azat-io** [comment]
@marwie Everything works fine after downgrading to version v2.0.0-beta.51.

**Comment by marwie** [comment]
Thanks! Will do that for now :)

**Comment by marwie** [comment]
That gives me this error during local dev 🤔
![image](https://user-images.githubusercontent.com/5083203/197339092-db2f73b6-8815-4da0-9697-cd1609d31aca.png)

**Comment by marwie** [comment]
Doesnt work for me either unfortunately - getting another error in my local dev with 51 so blocks me even more (but this is with plugins again so maybe its something else)

![image](https://user-images.githubusercontent.com/5083203/197339202-88f4f09f-182a-4ea4-8857-97b4f309e9f4.png)

**Comment by Mister-Hope** [comment]
@meteorlxy  cc, may need some help here, I am really busy in the following 2 weeks.

**Comment by Mister-Hope** [comment]
@azat-io Nice catch, my project does have the same issue.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/33315834/197339437-c2b4d048-bef5-47bb-a811-0498cf0fcc3c.png">

<img width="200" alt="image" src="https://user-images.githubusercontent.com/33315834/197339453-7b39b3b8-5083-4a68-b1ca-94fda640d022.png">
<img width="246" alt="image" src="https://user-images.githubusercontent.com/33315834/197339463-afbbfa11-efd8-4f6f-ae88-21c9ff7c1c3e.png">


This is an error related to `vue` and `vue-router`, I am not sure whether it's caused by ventor or new optimize logic introduced in vite3.1 or my pr splitting some modules to a ventor. ( I personally prefer the first one, as I do need to write extra code to make my packages compatable with vite@3.1)

 we might get it checked when meteorlxy have time, I am really busy, sorry for that.

**Comment by Mister-Hope** [comment]
> Doesnt work for me either unfortunately - getting another error in my local dev with 51 so blocks me even more (but this is with plugins again so maybe its something else)
> 
> ![image](https://user-images.githubusercontent.com/5083203/197339202-88f4f09f-182a-4ea4-8857-97b4f309e9f4.png)

beta51 should work as we are not meating broken reports for this version during the whole month since it release, you may need to clear cache and temp to ensure your devServer is ok, also deleting lock file and a fresh install may help.

**Comment by marwie** [comment]
Thanks for the fast reply. That's exactly what I tried (deleted ``.cache`` and ``.temp`` in ``.vuepress`` + ``node_modules`` and ``package.json.lock`` - can try again later to verify

**Comment by CriticalRange** [comment]
> ~Thanks for the fast reply. That's exactly what I tried (deleted `.cache` and `.temp` in `.vuepress` + `node_modules` and `package.json.lock`) but can try again later to verify~
> 
> I must've missed something - works now in 51. Thanks!

How did you fix it ? I can't fix mine, even tried 50 but can't get it to work.

**Comment by Mister-Hope** [comment]
It seems that it dose cause by https://github.com/vuepress/vuepress-next/pull/1101 Some deps are supposed to be generated into "framework", but they are actually not.

Perhaps webpack bundler should work, has anyone try that?

**Comment by Mister-Hope** [comment]
Curious to find out that official docs are working as expected, it has a framework chunk which contains vue and vue-router:

![image](https://user-images.githubusercontent.com/33315834/197373954-36c2378a-bb63-4d67-b1f5-b7ca8c31436b.png)


Which is supposed to be the expected behavior, but the broken site seems not:

https://github.com/vuepress/vuepress-next/blob/00b83665182286185593cb03928d5c5b1e5867c5/packages/bundler-vite/src/plugins/mainPlugin.ts#L102-L110

**Comment by marwie** [comment]
> > ~Thanks for the fast reply. That's exactly what I tried (deleted `.cache` and `.temp` in `.vuepress` + `node_modules` and `package.json.lock`) but can try again later to verify~
> > I must've missed something - works now in 51. Thanks!
> 
> How did you fix it ? I can't fix mine, even tried 50 but can't get it to work.

Deleted node_modules package.lock, vuepress .temp and .cache directory, ran install and checked that all packages were on 51 and then build worked

**Comment by dragondyt** [comment]
Just change "@vuepress/bundler-vite": "2.0.0-beta.52" to "@vuepress/bundler-vite": "2.0.0-beta.51"

**Comment by meteorlxy** [comment]
The problematic commits have been reverted in v2.0.0-beta.53. Let me know if there are still some issues.

**Comment by CriticalRange** [comment]
> The problematic commits have been reverted in v2.0.0-beta.53. Let me know if there are still some issues.

I'm still having issue. Here's my GitHub action: https://github.com/CriticalRange/criticalrange.github.io/actions/runs/3313557930

**Comment by CriticalRange** [comment]
> > The problematic commits have been reverted in v2.0.0-beta.53. Let me know if there are still some issues.
> 
> I'm still having issues. Here's my GitHub actions run: https://github.com/CriticalRange/criticalrange.github.io/actions/runs/3313557930

@meteorlxy Did you have time to check this?
