### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by shentuzhigang** [vuepress/vuepress-next#1144]
### Description

my theme bundler with vite is no work but bundler with webpack is ok 
like:
<img width="864" alt="image" src="https://user-images.githubusercontent.com/46020123/197469472-84083d62-ad76-4d99-b225-ac5454617bdc.png">

i think problem in 
`packages/bundler-vite/src/plugins/mainPlugin.ts`
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/46020123/197469285-411d9bcb-b034-440e-9f59-80fa7c7aef2a.png">

### Reproduction

https://github.com/vuepress-star/vuepress-theme-star

### Used Package Manager

pnpm

### System Info

```shell
vuepress: 2.0.0-beta.52
```

**Comment by Mister-Hope** [comment]
Dumplicate of #1140
