### ISSUE TITLE
[Feature request] Import Markdown block/partial

### ISSUE THREAD

**Issue by onlime** [vuepress/vuepress-next#1151]
### Clear and concise description of the problem

Currently, we have this wonderful `markdown.importCode` built-in feature to [Import Code Blocks](https://vuepress.github.io/guide/markdown.html#import-code-blocks) like this:

```markdown
<!-- minimal syntax -->
@[code](../foo.js)

<!-- partial import, from line 1 to line 10 -->
@[code{1-10}](../foo.js)
```

It would be really nice if we could also import external Markdown content as "partials" which then just get rendered inline as regular Markdown.

This would e.g. be useful for a larger documentation structure with subfolders that each contain their individual `README.md`, which lists links to pages of that single subfolder/namespace. The same content could then be re-used on the root `README.md` in an individual section. Currently, I need to maintain such duplicate content.

### Suggested solution

Implement some similar Markdown include with the proposed syntax:

```markdown
<!-- minimal syntax -->
@[md](partials/foo.md)

<!-- partial import, from line 1 to line 10 -->
@[md{1-10}](partials/foo.js)

<!-- partial import, from line 3 to the end -->
@[md{3-}](partials/foo.js)
```

The content would just get rendered inline with the containing Markdown content, not placed in any block.

**Comment by Mister-Hope** [comment]
See https://vuepress-theme-hope.github.io/v2/md-enhance/guide/include.html
