### ISSUE TITLE
[Feature Request] Removing PWA

### ISSUE THREAD

**Issue by hschaefer123** [vuepress/vuepress-next#1171]
### Description

Hi,
for my productive site btp.udina.de, i currently saw some users issues with PWA and errors in the console.log.

How can i cleanly disable the plugin for running sites, because just removing the plugin from config does not work, because workbox is still running in clients and waiting for updates.

There is currently no info available on this topic.

How can i deliver code to browsers to unregister the PWA web worker/service worker, so that my vuepress site will be run without it (even for users, that currently have the web workers enabled).

Any help would be appreciated, because currently this blogs some users from updates, sadly without info on this.

Best regards
Holger

### Reproduction

The problem was seen in switzerland for live btp.udina.de site, but maybe concerning some company security restrictions.

### Used Package Manager

npm

### System Info

```shell
sadly no access to the users and there browser.

Just need a way of disabling PWA to get rid of this issues.
```

**Comment by Mister-Hope** [comment]
I will publish a plugin `vuepress-plugin-remove-pwa` very soon.

**Comment by hschaefer123** [comment]
Hi,
Thank you very much. That sounds very good. I also tried custom solutions, but nothing worked well.

Since yesterday in Switzerland a client showed me not beeing able to see latest updates, i decided to better disable it for public info sites.

Even the update popup was not recognized by some clients and linking from twitter to new pages was a little bit problematic.

Impatiently awaiting your fix.

Again thank you,
Holger

**Comment by Mister-Hope** [comment]
Track https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2452
