### ISSUE TITLE
Codeblock background is dark in colorMode: 'light' mode.

### ISSUE THREAD

**Issue by dmitrybv** [vuepress/vuepress-next#1172]
### Description

When I set colorMode: 'light' in in config.js 
the code blocks from prismjs are still Remain on a dark background.

I wonder if this is a bug or a feature.
If it's a feature, then how can I set a light theme for code sections?

### Reproduction
set colorMode: 'light' in config.js 

### Used Package Manager

yarn

### System Info

```shell
PS C:\DelphiStuff\_WebTech\EhLib-VCL-Help-With-VuePress> vuepress info
vuepress : The term 'vuepress' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ vuepress info
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (vuepress:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\DelphiStuff\_WebTech\EhLib-VCL-Help-With-VuePress>
```

**Comment by Mister-Hope** [comment]
This is expected, if you do want to customise it, achieve it by your own. Or you can try 3rd party themes like https://vuepress-theme-hope.github.io/v2/ which supports this.
