### ISSUE TITLE
��#� �H�e�l�l�o� �V�u�e�P�r�e�s�s� with Windows 11

### ISSUE THREAD

**Issue by JOduMonT** [vuepress/vuepress-next#1183]
### Description

I followed the manual installation for VuePress v2
https://v2.vuepress.vuejs.org/guide/getting-started.html#manual-installation
and it result with weird encoding: 
��#� �H�e�l�l�o� �V�u�e�P�r�e�s�s�

![image](https://user-images.githubusercontent.com/5204724/206151849-a27d3425-4082-4788-9a0d-a89743fbaffa.png)

OS: Windows 11 Pro
Terminal: PowerShell
Language OS and Navigator: English
Node JS: v18.12.1
NPM: 8.19.2

### Reproduction

https://stackblitz.com/edit/vuepress-xrekab?file=docs/README.md

### Used Package Manager

npm

### System Info

```shell
PS C:\Users\jodum\vuepress-starter> npm run dev     

> dev
> vuepress dev docs

✔ Initializing and preparing data - done in 99ms

  vite v3.1.8 dev server running at:

  ➜  Local:   http://localhost:8080/
  ➜  Network: http://172.30.32.1:8080/
  ➜  Network: http://192.168.1.252:8080/
info config docs\.vuepress\config.ts is modified
✔ Initializing and preparing data - done in 52ms

  vite v3.1.8 dev server running at:

  ➜  Local:   http://localhost:8080/
  ➜  Network: http://172.30.32.1:8080/
  ➜  Network: http://192.168.1.252:8080/
tip dev server has restarted, please refresh your browser
info page README.md is modified
11:21:19 a.m. [vite] hmr update /@fs/C:/Users/jodum/vuepress-starter/docs/.vuepress/.temp/pages/index.html.vue
```

**Comment by Mister-Hope** [comment]
Not sure if you are still facing this issue, welcome to provide a reproduction and we would like to reopen it.

**Comment by FrozenJun** [comment]
You may have used UTF-16LE in your editor, use UTF-8 instead.
