### ISSUE TITLE
[Bug report] Bundler webpack no longer output css chunk as expected when performing SSG

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#1189]
### Description

See https://mrhope.site as an example, css chunk is loaded inside js, so SSG render result has no styles, resulting a great CLS.

It do happens in other projects switching to webpack bundler.

### Reproduction

Not needed

### Used Package Manager

pnpm

### System Info

```shell
Not needed
```

**Comment by meteorlxy** [comment]
Should be a regression of [b0a7a0e](https://github.com/vuepress/vuepress-next/commit/b0a7a0e686b98dd8201dfed8effd6f7616e7d498)
