### ISSUE TITLE
⚠️ATTENTION:  Using version range like `^` or `~`  for packages in this repo will fail.

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#1195]
### Description

If you use `^2.0.0-beta.xx` for any packages in this repo, you may get an installation failure, or you may get your app broke when upgrading to latest `next` version.

This is because we published 2 test versions `2.0.0-beta.50-pre.0`, `2.0.0-beta.50-pre.1`, while `50-pre.x` is higher than any number `xx`.

## Solution

The easiest way to solve this is to upgrade vuepress with `vp-update`.

For:

```bash
npx vp-update

yarn dlx vp-update

pnpm dlx vp-update
```

## Manual solution

You can solve this issue by specifying exact version in package.json. e.g.:

```json
{
  "dependencies": {
    "@vuepress/client": "2.0.0-beta.62",
    "vue": "^3.3.4",
    "vuepress": "2.0.0-beta.62"
  }
```

Note that all the `^` or `~` marker shall be changed for packages in this repo, but you can keep others as is.

```diff
{
  "dependencies": {
-    "@vuepress/client": "~2.0.0-beta.62",
-    "@vuepress/client": "^2.0.0-beta.62",
+    "@vuepress/client": "2.0.0-beta.62",
    "vue": "^3.3.4",
-    "vuepress": "~2.0.0-beta.62",
-    "vuepress": "^2.0.0-beta.62",
+    "vuepress": "2.0.0-beta.62"
  }
```

Also you can use `next` tag (But we do not recommend this because we may introduce breaking changes in future versions)

```json
{
  "dependencies": {
    "@vuepress/client": "next",
    "vue": "^3.3.4",
    "vuepress": "next"
  }
```

**Comment by Mister-Hope** [comment]
> If use `Renovate` to manage package version, this configure may be helpful.
> 
> ```json
> 
> "packageRules": [
> 
>     {
> 
>       "packageNames": ["vuepress", "@vuepress/client"],
> 
>       "allowedVersions": "!/pre.*$/"
> 
>     }
> 
> ]
> 
> ```

Other official plug-in may be included as well

**Comment by domnantas** [comment]
Are there any plans to officially release v2? It has been in beta for 2+ years

**Comment by GreenImp** [comment]
If `2.0.0-beta.50-pre.0`, and `2.0.0-beta.50-pre.1` are no longer needed, a potential solution would be to deprecate them in npm, which should stop them from being installed:

https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions#deprecating-a-single-version-of-a-package

Something like this should do the trick:
```bash
npm deprecate vuepress@2.0.0-beta.50-pre "Old test version"
npm deprecate vuepress@2.0.0-beta.50-pre.1 "Old test version"
```

**Comment by Mister-Hope** [comment]
We already deprecated them, and deprecated version won't stop package manager installing them.

**Comment by Mister-Hope** [comment]
That's far worse than a version number like v2.0.0-chi.0 or v2.0.0-delta.0
