### ISSUE TITLE
[Bug report] layoutComponents 

### ISSUE THREAD

**Issue by Arhell** [vuepress/vuepress-next#1202]
### Description

v58

`[vite] Internal server error: Failed to resolve import "website/node_modules/@vuepress/theme-default/lib/client/layouts/404.vue" from "docs\.vuepress\.temp\internal\layoutComponents.js". Does the file exist?`

` File: website/docs/.vuepress/.temp/internal/layoutComponents.js:4:44
 export const layoutComponents = {
"404": defineAsyncComponent(() => import("website/node_modules/@vuepress/theme-default/lib/client/layouts/404.vue")),
                                    ^
Layout": defineAsyncComponent(() => import("website/node_modules/@vuepress/theme-default/lib/client/layouts/Layout.vue")),
 }
`

### Reproduction

on `npm run dev`

### Used Package Manager

npm

### System Info

npm
node v16.18.0

**Comment by init-qy** [comment]
@Arhell, the error messages looks like https://github.com/vuepress/vuepress-next/discussions/1197#discussion-4653606
you can try this
https://github.com/vuepress/vuepress-next/discussions/1197#discussioncomment-4378141

**Comment by Arhell** [comment]
i update to v59 and no errors
