### ISSUE TITLE
[Bug report] PNPM complain two errors but yarn haven't

### ISSUE THREAD

**Issue by nibazshab** [vuepress/vuepress-next#1216]
### Description

As [v2.vuepress.vuejs.org#as-easy-as-1-2-3](https://v2.vuepress.vuejs.org/#as-easy-as-1-2-3) say, I use  `pnpm add -D vuepress@next @vuepress/client@next vue` to install component and `pnpm docs:build`, but then I got this error

![image](https://user-images.githubusercontent.com/44338441/209699654-ffd3403c-4e1c-4ccd-ac05-89fc8ce96479.png)

So, I try to add it, I use `pnpm add -D vuepress@next @vuepress/client@next vue @vuepress/utils` to install component, it success to find `@vuepress/utils`, but I got another error

![image](https://user-images.githubusercontent.com/44338441/209700045-650778a4-53f0-4eae-994e-d8c4fd82baa8.png)

But if I use `yarn` but not `pnpm`, I use `yarn add -D vuepress@next` and `yarn docs:build`, all is well, I never got these two errors

### Reproduction

https://stackblitz.com/edit/vuepress-zp5dpg

### Used Package Manager

pnpm

### System Info

```shell
❯ vuepress info

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  Utilities:
    Git: Not Found
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.53 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.53 
    @vuepress/client: 2.0.0-beta.59 => 2.0.0-beta.59 
    @vuepress/core:  2.0.0-beta.53 
    @vuepress/markdown:  2.0.0-beta.53 
    @vuepress/plugin-active-header-links:  2.0.0-beta.53 
    @vuepress/plugin-back-to-top:  2.0.0-beta.53 
    @vuepress/plugin-container:  2.0.0-beta.53 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.53 
    @vuepress/plugin-git:  2.0.0-beta.53 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.53 
    @vuepress/plugin-nprogress:  2.0.0-beta.53 
    @vuepress/plugin-palette:  2.0.0-beta.53 
    @vuepress/plugin-prismjs:  2.0.0-beta.53 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.53 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.53 
    @vuepress/theme-default:  2.0.0-beta.53 
    @vuepress/utils: 2.0.0-alpha.1 => 2.0.0-alpha.1 
    vue: ^3.2.45 => 3.2.45 
    vue-loader: Not Found
    vue-router:  4.1.6 
    vuepress: 2.0.0-beta.59 => 2.0.0-beta.59 
    vuepress-vite:  2.0.0-beta.53 
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
Issue panel is not the place to ask questions. If you are a noob at front end, learn some basics first.

**Comment by Mister-Hope** [comment]
1. pnpm requires you to declare any package before importing it, see pnpm docs at pnpm.io for more details about pnpm islolated strategy. You import @vuepress/utils yet not install it.

2. All VuePress packages in this repo should all be installed with next flag.

3. Where does the ViteBunder variable from in your reproduction? If you want to use it, install @vuepress/bundler-vite@next then import it from the package, otherwise just omit it.
