### ISSUE TITLE
[Bug report] deply github workflow faild with @vuepress/utils error

### ISSUE THREAD

**Issue by ChaseWindYoungs** [vuepress/vuepress-next#1219]
### Description

use guide docs to build, push to github, but actions build failed because @vuepress/utils
<img width="975" alt="image" src="https://user-images.githubusercontent.com/79502857/209900230-7e51bc9b-49d2-468d-9235-5e809ddec729.png">

this is my package.josn, vuepress is `^2.0.0-beta.58`
<img width="511" alt="image" src="https://user-images.githubusercontent.com/79502857/209900440-2f96b546-f829-4fb6-b389-09203f6f1678.png">

### Reproduction

https://github.com/ChaseWindYoungs/leetcode-book/actions/runs/3798101329

### Used Package Manager

npm

### System Info

```shell
^2.0.0-beta.58
```

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/vuepress-next/issues/1216#issuecomment-1366326359 The first one.
