### ISSUE TITLE
[Bug report] Code snippet alignment issue

### ISSUE THREAD

**Issue by CikiMomogi** [vuepress/vuepress-next#1222]
### Description

I noticed that when I was browsing the [vuepress documentation](https://v2.vuepress.vuejs.org/reference/plugin/docsearch.html#get-search-index), the code snippets had some rendering issues. The text seemed to be slightly shifted down, so the line numbers and text were not on the same line.

![Screenshot 2023-01-05 at 05-37-23 docsearch VuePress](https://user-images.githubusercontent.com/74030149/210712761-e67ed56e-0332-4ce6-915d-a058d055bece.png)

### Reproduction

Visit https://v2.vuepress.vuejs.org/reference/plugin/docsearch.html#get-search-index

**Comment by Mister-Hope** [comment]
<img width="576" alt="image" src="https://user-images.githubusercontent.com/33315834/210768354-df43df3c-c1e7-4051-b835-653de0de1b2e.png">

Can nor reproduce, are u using safari?

**Comment by Mister-Hope** [comment]
Your browser version and platform info is needed before further invistigation.

**Comment by Mister-Hope** [comment]
A known issue is that safari only support interger pixel value of font size for `<pre>` blocks, even if you set `line-height: 20.9999px`, safari will still render 20px. So we made a fix months ago

I am not sure other browers's behavior with `<pre>` and `<code>` blocks. All these are not mentioned in W3C spec, so should be treated as browser rendering issues.

At lease Chrome is working well all times on Windows and Android.

**Comment by Mister-Hope** [comment]
An earlier discussion could be found at https://github.com/vuepress/vuepress-next/issues/1040

**Comment by CikiMomogi** [comment]
You are correct. It does not happen on Windows machines. I just tested them using Firefox 108.0.1 and the code was rendered correctly. Apparently, the issue only occurs on my Linux machine. You may close this issue if you wish, or If there is anything else I can do to assist, please let me know.

**Comment by digital-codes** [comment]
Looks fine in my Linux machine, Firefox 108 and Chromium 107. Also looks OK with Safari on my stone-age Ipad Mini (iOS 9.3)

**Comment by Mister-Hope** [comment]
> You are correct. It does not happen on Windows. I just tested them using Firefox 108.0.1 and the code was rendered correctly. Apparently, the issue only occurs on my Linux machine. You may close this issue if you wish, or If there is anything else I can do to assist, please let me know.

Actually, I don't know what to do either, it's the brower which as render issues or weird render behavior which is not mentioned (or obey) W3C standard. So I have no idea how to make work around. As you can see in the other issue which I resolved, safari's issue is werid enough.

TBH, I f**king hate these kind of bunders caused by browers......😅
