### ISSUE TITLE
[Bug report] Docsearch result incorrect

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#1223]
### Description

When deploying docs at mutiplce places with different base, the other site cannot gent a search result correctly.

For example, vuepress-theme-hope has documentation on:

- https://vuepress-theme-hope.github.io/v2/
- https://theme-hope.vuejs.press/

And currently docsearch is crawling the fiirst one, however, a `https://vuepress-theme-hope.github.io/v2/test.html` will be converted to a routerlink `/v2/test.html`

This will happens as long as docs are deployed at different base. 

### Solution

We may need a setting called `indexBase` so that when coverting to internal route link, the base can be removed correctly.

**Comment by meteorlxy** [comment]
Well, I do think it's not a common use case and should not be encouraged...

**Comment by Mister-Hope** [comment]
I do think it's a common usag for docs being deployed at multiple places, and let the craweler craw the "canonical link" while still support other sites to perform search.

Why shouldn't it a common usage? You mean people only deploy docs in one place? or people should only provide search on one site?

**Comment by meteorlxy** [comment]
I mean multiple deployments with different `base` sounds not so common.

> You mean people only deploy docs in one place?

Why do you think like that? We are using multiple deployments ourselves.

BTW, I suggest you not to be so aggressive when discussing

**Comment by Mister-Hope** [comment]
As I mentioned, a lot of authros may choose gitee to provide accelarations in China mainland, and custom domain for gitee pages is not free, so people do need base for their projrects as not everyone would like to create a new org for each project.
