### ISSUE TITLE
多个 md 文件引入同一张图片时，部署到服务器后点击左侧菜单，获取对应 js 文件时，Request Headers 不携带referer

### ISSUE THREAD

**Issue by kk305cs** [vuepress/vuepress-next#1231]
### Description

多个 md 文件引入同一张图片时，部署到服务器后点击左侧菜单，获取对应 js 文件时，Request Headers 不携带 referer， 如果服务器端配置了防盗链，就会报错，从而进入不了页面。
![image](https://user-images.githubusercontent.com/26682400/211238741-49314857-faa5-4812-956e-5abdcd19c0fa.png)

目前临时解决方案为：
复制图片后重命名，为多个文件进行引入。

但此方案会对项目代码增加打包容量，造成文件冗余。
之前已提Q&A，链接为 https://github.com/vuepress/vuepress-next/discussions/1225

官网也有此问题，下面附上官网链接。

### Reproduction

example：https://v2.vuepress.vuejs.org/zh/guide/assets.html

### Used Package Manager

npm

### System Info

```shell
build correctly
```

**Comment by meteorlxy** [comment]
Does [referrerpolicy](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#referrerpolicy) help with this case?

**Comment by meteorlxy** [comment]
Oops, so it's not related to images, but to js files?

Then we may need to support `referrerpolicy` in the generated `<script>` tags? 🤔

**Comment by meteorlxy** [comment]
Seems that I could not reproduce it. Please check it again, or provide more context.

**Comment by kk305cs** [comment]
> Seems that I could not reproduce it. Please check it again, or provide more context.

[referrerpolicy](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#referrerpolicy) 之前尝试过，没有作用，目前在官网确实无法复现出来，后续我再继续观察着，谢谢
