### ISSUE TITLE
[Bug report] Line numbers do not match code

### ISSUE THREAD

**Issue by KnorpelSenf** [vuepress/vuepress-next#124]
### Description

When using a code snippet in markdown, column with the line numbers on the left does not match the code block. This can be observed here: https://vuepress2.netlify.app/reference/default-theme/config.html#sidebar

### Steps to reproduce

Use a code block, i.e.

```c
// code here
```

### Expected behavior

The line numbers are aligned with the code.

### Screenshot

![image](https://user-images.githubusercontent.com/12952387/116542567-0afcfe80-a8ed-11eb-934e-01f95489e96b.png)

### Environment info

- Browser: Chrome and FF, but it's worse on Chrome

**Comment by meteorlxy** [comment]
It looks good here.

![image](https://user-images.githubusercontent.com/18205362/116557779-5cc77800-a931-11eb-9196-5fb9e9ebe152.png)


Please provide more context, e.g. OS, Browser version, etc.

**Comment by KnorpelSenf** [comment]
```bash
$ uname -a
Linux steffens-pc 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
$ google-chrome --version
Google Chrome 90.0.4430.93 
$ firefox --version
Mozilla Firefox 78.10.0esr
```
It works well on Android 10 (Chrome).

**Comment by meteorlxy** [comment]
> Could it be related to the fonts that are installed on the system?

That might be the reason.

Here's the related styles. We may need to provide a fallback for linux.

https://github.com/vuepress/vuepress-next/blob/e971d6aa216102befaa387e062d49b3632fe579c/packages/%40vuepress/theme-default/src/client/styles/code.scss#L156-L159

I don't hava a linux pc. Could you help for this?

**Comment by KnorpelSenf** [comment]
@meteorlxy I opened the PR #125
