### ISSUE TITLE
[Bug report] Package build went wrong

### ISSUE THREAD

**Issue by NeserCode** [vuepress/vuepress-next#1251]
### Description

I'm using my custom theme, bug came from when i tried to package this project.
I not sure it's caused by the tag 2.0.0-beta.50-pre.0 or pre.1.
Here is bug report.
---
PS D:\Code\Repo\vuepress-theme-nesercode> npm run build

> @vuepress/theme-nesercode@1.0.0-beta.1 build
> vuepress build docs

warning plugin @vuepress/plugin-git has been used multiple times, only the last one will take effect
✔ Initializing and preparing data - done in 383ms
✔ Compiling with vite - done in 4.53s
✖ Rendering 11 pages - failed in 54ms
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@internal/pagesData' imported from D:\Code\Repo\vuepress-theme-nesercode\node_modules\@vuepress\client\dist\chunk-E44UNXTX.js
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:951:9)
    at moduleResolve (node:internal/modules/esm/resolve:1000:20)
    at defaultResolve (node:internal/modules/esm/resolve:1214:11)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)

### Reproduction

https://github.com/NeserCode/vuepress-theme-nesercode.git

### Used Package Manager

npm

### System Info

```shell
PS D:\Code\Repo\vuepress-theme-nesercode> npm run info 

> @vuepress/theme-nesercode@1.0.0-beta.1 info
> vuepress info


  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1.18 GB / 7.85 GB
  Binaries:
    Node: 16.17.0 - D:\Code\NodeJs\node.EXE
    Yarn: Not Found
    npm: 8.15.0 - D:\Code\NodeJs\npm.CMD
  Utilities:
    Git: 2.37.1.
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.60
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.60
    @vuepress/client:  2.0.0-beta.60
    @vuepress/core:  2.0.0-beta.60
    @vuepress/markdown:  2.0.0-beta.60
    @vuepress/plugin-active-header-links:  2.0.0-beta.60
    @vuepress/plugin-back-to-top:  2.0.0-beta.60
    @vuepress/plugin-container:  2.0.0-beta.60
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.60
    @vuepress/plugin-git:  2.0.0-beta.60
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.60
    @vuepress/plugin-nprogress:  2.0.0-beta.60
    @vuepress/plugin-palette:  2.0.0-beta.60
    @vuepress/plugin-prismjs:  2.0.0-beta.60
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.60
    @vuepress/plugin-toc: 2.0.0-beta.60 => 2.0.0-beta.60
    @vuepress/shared:  2.0.0-beta.60
    @vuepress/theme-default:  2.0.0-beta.60
    @vuepress/utils:  2.0.0-beta.60
    vue:  3.2.47
    vue-loader: Not Found
    vue-router:  4.1.6
    vuepress: 2.0.0-beta.60 => 2.0.0-beta.60
    vuepress-vite:  2.0.0-beta.60
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
We do not have time to check your projects, create a repo with default theme and try reproducing it. If you still meet similar issues and you are sure you have correct deps, open a new pr then.
