### ISSUE TITLE
[Bug report] Pages not watched during dev if source directory contains parentheses

### ISSUE THREAD

**Issue by ctrueblood-epri** [vuepress/vuepress-next#1255]
### Description

If the source directory (absolute path) contains parentheses, then Markdown pages are not watched during `vuepress dev`. This issue can be reproduced by following these steps:
1. Create a folder that has parentheses in the folder's name. In the reproduction link, "docs(1)" is the folder name.
2. Inside that folder, create a new VuePress (2.0.0-beta.60) project.
3. `npm run dev` to launch VuePress dev mode.
4. Add or modify a Markdown file within the VuePress project's source folder. Save the file.

Normally, we expect the modified Markdown file to be detected by VuePress's page watcher and then it hot reloads automatically. However, when the source path contains parentheses, then the Markdown pages are not watched, and therefore, they do not hot reload. When this happens, we have to kill/restart `npm run dev` and manually reload the page in our browser.

### Cause
In [watchPageFiles.ts](https://github.com/vuepress/vuepress-next/blob/main/packages/cli/src/commands/dev/watchPageFiles.ts), when `pagesWatcher` is created, a `cwd` argument is passed into `chokidar.watch()`. If `cwd` contains a glob-like pattern, such as wildcards, parentheses, or brackets, then the watcher's absolute paths may be invalid after joining with `pagePatterns`. In chokidar, another user has raised a similar issue: https://github.com/paulmillr/chokidar/issues/1165. This seems to be a bug in chokidar, rather than a VuePress bug.

https://github.com/vuepress/vuepress-next/blob/fd2e241235fc87c66ce59ba22c8e27521c594fbd/packages/cli/src/commands/dev/watchPageFiles.ts#L43-L47

### Proposed Solution

Display a warning if `cwd` contains any glob-like wildcards `*` or `?`, parenthesis `(`, or bracket `[`. Perhaps add a line in [watchPageFiles.ts](https://github.com/vuepress/vuepress-next/blob/main/packages/cli/src/commands/dev/watchPageFiles.ts) before creating `pagesWatcher`:

```ts
// warn if source path contains glob special characters
if (/[\*\?\[\(]/.test(app.dir.source())) logger4.warn(`Some page files may not be watched during dev because source path contains a wildcard, parenthesis, or bracket:\n${app.dir.source()}`);

// watch page files
```

Other special characters `!`, `+`, `)`, `]`, `$` do not seem to be a problem if they appear in the source path. That's why the proposed regex only checks for `*`, `?`, `(`, `[`.

### Reproduction

https://stackblitz.com/edit/vuepress-pu92b1

### Used Package Manager

npm

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.60
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.60
    @vuepress/client:  2.0.0-beta.60
    @vuepress/core:  2.0.0-beta.60
    @vuepress/markdown:  2.0.0-beta.60
    @vuepress/plugin-active-header-links:  2.0.0-beta.60
    @vuepress/plugin-back-to-top:  2.0.0-beta.60
    @vuepress/plugin-container:  2.0.0-beta.60
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.60
    @vuepress/plugin-git:  2.0.0-beta.60
    @vuepress/plugin-google-analytics: 2.0.0-beta.60 => 2.0.0-beta.60
    @vuepress/plugin-medium-zoom:  2.0.0-beta.60
    @vuepress/plugin-nprogress:  2.0.0-beta.60
    @vuepress/plugin-palette:  2.0.0-beta.60
    @vuepress/plugin-prismjs:  2.0.0-beta.60
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.60
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.60
    @vuepress/theme-default:  2.0.0-beta.60
    @vuepress/utils:  2.0.0-beta.60
    vue:  3.2.45
    vue-loader: Not Found
    vue-router:  4.1.6
    vuepress: 2.0.0-beta.60 => 2.0.0-beta.60
    vuepress-vite:  2.0.0-beta.60
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
I do not think this hint is needed, however your issue is detailed and can be a good reference for others who use special characters in project path.

**Comment by ctrueblood-epri** [comment]
@Mister-Hope thank you for the suggestion.

For others who want to detect this issue, you can add an `onWatched` hook in your VuePress config file, like this:

```js
import { defineUserConfig } from 'vuepress'

export default defineUserConfig({

  onWatched: (app) => {
    if (!/[\*\?\(\[]/.test(app.dir.source())) {
      console.warn('WARNING: Some files may not be watched during dev because the source path contains a wildcard, parenthesis, or bracket:');
      console.warn(app.dir.source());
    }
  },

  // other config
})
```
