### ISSUE TITLE
[Bug report] Layout cannot be treeshaken

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#1265]
### Description

This is caused by https://github.com/vuepress/vuepress-next/pull/1053

Developers and users can extend a theme to override it's layout, or set it to the default layout to "delete it".

Also, users can add new layouts in user config.

However, in current api design, a layout will never be removed from output code once it's been added. All layouts will remain in the final output.

@meteorlxy  Can you explain why we should have  https://github.com/vuepress/vuepress-next/pull/1053? This only benefit HMR, but may slowdown app loading in both dev and prod in another way. 

### Workarounds for now

Now some possible workaround are

- For developers:  create alias for the original layouts, and recommand users to override through alias
- For developers: generated dynamic client config based on options
- For users: try adding alias to let the original layout import to be like `() => null`

In these case a layout will not be actually imported.  However, they will be the same as setting layouts options on node side as they all lost hot reload with layouts, so this is like we never have pr 1053

### Suggestions

I would suggest changing the logic to make layouts being tree-shakable, if we can not find some ways, maybe revert this pr and make layout settings be at node side again is the best choice, as layout can be quite large.

So what's your opinion on this situation? Shall we revert it to ensure a better tree-shaken with node side layouts, or we remain current one and use extra options or alias for users to perform "Advanced usage" to have them tree-shaken?

**Comment by meteorlxy** [comment]
I'm aware of that. It's a kind of tradeoff.

The main goal of the orginal PR is to make use of client config as possible, and layouts should be a good one as they are all client components.

IMO, overriding existing layout is just a "lazy" way for users who don't want to modify the source code of a theme. For those users, convenient might come first. Your idea about using aliases for layout sounds good, because it's the same way we introduced in our docs for overriding components.

But yes, if we could find a better way for that, it's worthwhile to improve it.

**Comment by Mister-Hope** [comment]
> IMO, overriding existing layout is just a "lazy" way for users who don't want to modify the source code of a theme

I don't think users should edit theme code unless they really need to. In my theme, all components are replaceable, and have necessary slots.

For components all they need to do is to add a new alias for that, and that's easy to accept, however for layout, it will be much more confusing as they need to set things both node and client side for overriding.
