### ISSUE TITLE
[Bug report] Head resources are loaded again when switching pages

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#1268]
### Description

When users set js and css resources through head option in config file, switching pages will cause these resources to relead.

I think this should be bug as we should diff the head list and try to avoid upgrading the unchanged one

### Reproduction

https://dromara.org/fast-request/

### Used Package Manager

npm

### System Info

```shell
Not related
```

**Comment by zuihou** [comment]
Refresh Page  will  also cause these resources to relead.

**Comment by Mister-Hope** [comment]
> Refresh Page will also cause these resources to relead.

Why isn't that expected?

**Comment by digital-codes** [comment]
Should normally be handled by the browser cache. You shouldn't see reloads in production mode. Browser dev mode has cache disabled frequently

**Comment by digital-codes** [comment]
Only when using browser dev mode. I am fine with current behavior, was just commenting..
