### ISSUE TITLE
[Bug report]     

### ISSUE THREAD

**Issue by Wangxingyin** [vuepress/vuepress-next#1276]
### Description

![Xnip2023-03-08_23-01-23](https://user-images.githubusercontent.com/47234340/223748446-41dfc633-72da-48e5-954b-77511c5bf753.jpg)
[[toc]] not working, I konw nothing about it ,

### Reproduction

2.0.0-beta.61

### Used Package Manager

npm

### System Info

```shell
"vuepress": "2.0.0-beta.61",
```

**Comment by Wangxingyin** [comment]
我看到管理员您是中国人、我没有配置任何内容的情况下.单纯用[[toc]] 右边括号为红色.我不知道怎么检查到底是哪里的问题

**Comment by Mister-Hope** [comment]
`[[toc]]` is not a standard common mark syntax.

**Comment by Wangxingyin** [comment]
文章中对于如何使用[[toc]]   并没有说明需要单独安装配置
vuepress2 如果需要单独配置用[[toc]] 才能使用, 希望把文章内容更新清楚一点

**Comment by Wangxingyin** [comment]
如何才能使用[[toc]] 我真的看了好久 都没有看懂
我直接输入[[toc]] 又没有效果.真的怀疑人生

**Comment by Wangxingyin** [comment]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/47234340/223757113-6ca9b917-b129-4eb1-baab-5ce98893627c.png">
[[toc]]最右边括号显示红色、再就是渲染页面也没有效果

**Comment by Wangxingyin** [comment]
[[toc]] The rightmost brackets are displayed in red, and rendering the page has no effect

**Comment by meteorlxy** [comment]
@Wangxingyin 一级标题是作为页面标题出现的，通常每页只会在最开头有一个，默认不会在目录里面展示

**Comment by meteorlxy** [comment]
有问题可以在 Discussion 中提问
