### ISSUE TITLE
[Feature request] support custom cli command

### ISSUE THREAD

**Issue by windylaugit** [vuepress/vuepress-next#1278]
### Clear and concise description of the problem

It is expected that vuepress can support customized cli commands or parameters so that I can do some pre-processing before running dev or build mode, such as switching site configuration, etc

### Suggested solution

examples: vuepress customDev sourceDir.
This command will execute the vuepress dev command after executing some of my custom logic

### Additional context

Reference: https://cli.vuejs.org/dev-guide/plugin-dev.html#add-a-new-cli-service-command

**Comment by Mister-Hope** [comment]
You can add your own scripts and run before any vuepress command. I don't think there is any difference

**Comment by windylaugit** [comment]
> You can add your own scripts and run before any vuepress command. I don't think there is any difference.
> 
> Furthermore, there are a lot differences between "It is expected" and "You are expecting"

Thanks for your reply.
I just found the usage of createDev in the source code, it can solve my problem.
-----
I am using a translator to translate my mother tongue, so...
