### ISSUE TITLE
[Bug report] Inconstant behavior across package manager

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#1283]
### Description

Reproduction is at readme.

The issue is thrown at `@vuepress/client`, and `vuepress-plugin-comment2` and `vuepress-shared` only reference `@vuepress/client` at client.

### Reproduction

https://github.com/Mister-Hope/vuepress-bug

### Used Package Manager

npm

### System Info

```shell
Not needed
```

**Comment by ykla** [comment]
Same with me.

see also https://github.com/FreeBSD-Ask/Handbook-Next/actions/runs/4741878849/jobs/8419495764

**Comment by Mister-Hope** [comment]
@meteorlxy Could you review this when you have time?

**Comment by Mister-Hope** [comment]
@meteorlxy Can you review this?

The problem is that client side code has reference with `@internal/pagesData` by importing `usePage` with in files controlled by alias, and only pnpm can done the SSR process correct.

I think the problem is:

1. `vuepress-plugin-comment2/client` is imported during SSR
2. `vuepress-plugin-comment2` use alias in it
3. The alias file import `usePageData`
4. `usePageData` access an alias called `@internal/pagesData`

Without step 2 all pm can work weel, but only pnpm can handle this with step 2.

**Comment by meteorlxy** [comment]
@Mister-Hope  I have no idea after reading your description 🤔 Sounds like a bug about alias resolving? Have you tested webpack?

**Comment by meteorlxy** [comment]
I just tested with webpack in your repro repo and it worked well with npm. So I think it could be a bug of vite

**Comment by meteorlxy** [comment]
I see. Adding this snippet can help:

```ts
  viteOptions: {
      ssr: {
        noExternal: ["vuepress-shared"],
      }
    }
```
