### ISSUE TITLE
[Bug report] plugin-active-header-links trigger route.path changes

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#1290]
### Description

When users scrolling pages, all watches with `route.path`  deps shall not be triggered, however `@vuepress/plugin-active-header-links` break this. Every computed value and watches with `route.path` will be recalculated or rerun when hash changes or page scrolling to top.

### Reproduction

https://stackblitz.com/edit/vuepress-ewt9uy?file=package.json,docs%2Fguide%2FREADME.md%3AL40,package-lock.json

### Used Package Manager

npm

### System Info

```shell
Not related
```

**Comment by Mister-Hope** [comment]
Could you explain why `force: true` is needed when changing hash? @meteorlxy

**Comment by meteorlxy** [comment]
This should have been fixed.
