### ISSUE TITLE
[Feature request] Custom plugin loading order

### ISSUE THREAD

**Issue by DreamOfIce** [vuepress/vuepress-next#1294]
### Clear and concise description of the problem

目前插件的hook似乎是按照数组的顺序来执行的，并且主题添加的插件优先于用户的。
但开发过程中时不时遇到希望在某个插件之前/之后运行的情况，目前只能要求用户添加时注意顺序，而且如果其中一个插件为主题所添加就无能为力了。

## 新API
为插件API添加以下内容以允许控制hook `extends*`和 `on*`的顺序：
```ts
interface PluginObject {
  /** 期望在哪些插件前加载 */
  before?: string[]
  /** 期望在哪些插件后加载 */
  after?: string[]
 }
```
## 加载行为
1. 读取所有插件对象的 before 和 after，如果某个插件的before和after包含了同一个值，则抛出错误
2. 根据 before 和 after 进行排序
3. 出现冲突时遵循靠后的插件，并向用户发出警告

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/vuepress-next/discussions/1240
