### ISSUE TITLE
[Bug report] Page.title is not type guarded

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#1306]
### Description

```md
---
title: 1
---
```

```md
---
title: {}
```

There will be noob users who set titles like this, and `page.title` (with `string` type) will have other types, and this may break the application.

Unless we set `page.title: unknown` , we should guard the types of it.

### Reproduction

Not needed

### Used Package Manager

npm

### System Info

```shell
.
```

**Comment by meteorlxy** [comment]
It's too verbose to use `Record<string, unknown>` for all frontmatter properties. We'd better assume that user use it correctly.

BTW, does `title: 1` result in `number` or `string`?

**Comment by Mister-Hope** [comment]
number, so that's why I want this. No trim, replace or other functions are on numbers, so an errror will be thrown while it bypass typescript checks.
