### ISSUE TITLE
[Feature request] Integrate rowspan in vuepress

### ISSUE THREAD

**Issue by tiziodcaio** [vuepress/vuepress-next#132]
## Feature request

It would be possible to add the rowspan to the default theme, see example for clarification

### Description

![immagine](https://user-images.githubusercontent.com/61084118/117535173-dc6dda80-aff4-11eb-8dfb-bd98a60f2a54.png)

As the [markdown-it-multimd-table](https://github.com/redbug312/markdown-it-multimd-table) doesn't work on vuepress 2 (if you know how to enable it, i would very happy too! 😊

### Proposed Solution

I'm not so expert, so i ask to you if there is a method...

**Comment by meteorlxy** [comment]
Put this snippet in your config file:

```js
module.exports = {
  extendsMarkdown(md) {
    md.use(require('markdown-it-multimd-table'));
  },
}
```

**Comment by tiziodcaio** [comment]
And in vuepress 2? I tried with rowspan but it doesn't work...

**Comment by meteorlxy** [comment]
This is for vuepress2. Remember `extendMarkdown` is renamed to `extendsMarkdown`

**Comment by tiziodcaio** [comment]
okok no problem ✌
