### ISSUE TITLE
[Feature request] SidebarConfigObject should have a fallback option

### ISSUE THREAD

**Issue by wxsms** [vuepress/vuepress-next#1321]
### Clear and concise description of the problem

we can use sidebar object  to define sidebar for different pages, like:

```js
export default {
  theme: defaultTheme({
    // 侧边栏对象
    // 不同子路径下的页面会使用不同的侧边栏
    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          children: ['/guide/README.md', '/guide/getting-started.md'],
        },
      ],
      '/reference/': [
        {
          text: 'Reference',
          children: ['/reference/cli.md', '/reference/config.md'],
        },
      ],
    },
  }),
}
```

but if we only want some of these routes to use special sidebar, others keep `auto`, I have to add `auto` to every other pages in frontmatter, because there're no fallback.

### Suggested solution

```js
export default {
  theme: defaultTheme({
    // 侧边栏对象
    // 不同子路径下的页面会使用不同的侧边栏
    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          children: ['/guide/README.md', '/guide/getting-started.md'],
        },
      ],
      '/reference/': [
        {
          text: 'Reference',
          children: ['/reference/cli.md', '/reference/config.md'],
        },
      ],
     '*': 'auto'
    },
  }),
}
```

**Comment by Mister-Hope** [comment]
'/' is fallback

**Comment by wxsms** [comment]
> '/' is fallback

But looks like we can not use `'/': 'auto'` syntax, The signature of `SidebarConfigObject` not allow so.

anyway I close this because I finally found out that it's not very important to my project. but it may still be a problem for others.
