### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by hyvyys** [vuepress/vuepress-next#137]
### Description

Doesn't work with Vite (or I don't know how to configure it). I get a 404.

### Steps to reproduce

`yarn add -D vuepress@next`
`echo '# Hello VuePress' > README.md`
Then run `yarn vuepress dev` so that `.vuepress` is created. It uses webpack and loads up fine. Stop it, add config.js

```
module.exports = {
  bundler: '@vuepress/vite',
  bundlerConfig: {
    // vite bundler options
  },
}
```
Install vite  `yarn add -D -D vuepress-vite` (btw you guys tell us to install Vite with npm [here](https://vuepress2.netlify.app/guide/bundler.html#vite) – yikes).

Run again – 404.

- Reproduction link / repo: https://github.com/hyvyys/vuepress-vite-repro

### Expected behavior

Should work with Vite after nothing more than adding vuepress-vite and the config.

### Environment info

- Browser: Firefox
- Output of `vuepress info`:

```bashEnvironment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz
    Memory: 1.07 GB / 7.92 GB
  Binaries:
    Node: 14.13.0 - ~\AppData\Local\Temp\yarn--1621148507658-0.4510613217205177\node.CMD
    Yarn: 1.19.0 - ~\AppData\Local\Temp\yarn--1621148507658-0.4510613217205177\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.21.0.
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Spartan (44.18362.1533.0)
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.6
    @vuepress/bundler-webpack:  2.0.0-beta.14
    @vuepress/cli:  2.0.0-beta.14 (2.0.0-beta.6)
    @vuepress/client:  2.0.0-beta.12 (2.0.0-beta.6)
    @vuepress/core:  2.0.0-beta.14 (2.0.0-beta.6)
    @vuepress/markdown:  2.0.0-beta.13 (2.0.0-beta.5)
    @vuepress/plugin-active-header-links:  2.0.0-beta.14 (2.0.0-beta.6)
    @vuepress/plugin-back-to-top:  2.0.0-beta.14 (2.0.0-beta.6)
    @vuepress/plugin-container:  2.0.0-beta.14 (2.0.0-beta.6)
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.14 (2.0.0-beta.6)
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.14 (2.0.0-beta.6)
    @vuepress/plugin-nprogress:  2.0.0-beta.14 (2.0.0-beta.6)
    @vuepress/plugin-palette:  2.0.0-beta.14 (2.0.0-beta.6)
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.14 (2.0.0-beta.6)
    @vuepress/shared:  2.0.0-beta.4 (2.0.0-beta.7)
    @vuepress/theme-default:  2.0.0-beta.14 (2.0.0-beta.6)
    @vuepress/theme-vue: Not Found
    @vuepress/utils:  2.0.0-beta.11 (2.0.0-beta.5)
    vue:  3.0.11
    vue-loader:  16.2.0
    vue-router:  4.0.8
    vuepress: ^2.0.0-beta.14 => 2.0.0-beta.14
    vuepress-vite: ^2.0.0-beta.6 => 2.0.0-beta.6
```

**Comment by nsznsznjsz** [comment]
You should only add one of `vuepress` and `vuepress-vite`, otherwise you need to manually keep the version.

For now, it probably because two versions of packages of vueprss in your `yarn.lock`, this may fixed after you clean `yarn.lock` and `node_modules`

**Comment by meteorlxy** [comment]
Alright, please remember using `@next` tag, i.e.

```
yarn add -D vuepress-vite@next
```

**Comment by hyvyys** [comment]
I installed vuepress-vite@next alone, and I get this in the browser:

```
Uncaught ReferenceError: can't access lexical declaration 'defineClientAppSetup' 
```

On a side note, it is slightly schizophrenic that I have to run the dev server once so that it creates `.vuepress` and the needed catalogues and only then can I create the `config.js`. Unless I'm missing something. Either way, it is silly for the vite package to require choosing the bundler in the config if it doesn't support webpack on its own anyway.

**Comment by meteorlxy** [comment]
@hyvyys 

> Uncaught ReferenceError: can't access lexical declaration 'defineClientAppSetup' 

It would be helpful if you could report it in a new issue with a reproduction.

> Either way, it is silly for the vite package to require choosing the bundler in the config if it doesn't support webpack on its own anyway.

Yes it's silly indeed.

But I hope you could understand the reason why it works this way: Both `vuepress` and `vuepress-vite` is simply a wrapper of the `@vuepress/core`, `@vuepress/cli`, `@vuepress/theme-default` and `@vuepress/bundler-webpack-or-vite`. Currently they cannot do anything to the default value of the `bundler` option.

In fact you can manually install `@vuepress/core`, `@vuepress/cli`, `@vuepress/theme-default` and `@vuepress/bundler-vite` yourself, then you might feel it's not so silly lol 😅 .

We already have a plan to make the cli be aware of the default bundler. Be patient :wink:
