### ISSUE TITLE
headtxt add  head

### ISSUE THREAD

**Issue by pridejoy** [vuepress/vuepress-next#1378]
### Clear and concise description of the problem

希望能增加一个头部的配置。目前只有配置logo。要是能加上配置个文字就完美了

![image](https://github.com/vuepress/vuepress-next/assets/45122088/bc9a98de-0576-4082-adc0-85e37713c2c3)

### Suggested solution

增加文字配置

export default {
  head: [['link', { rel: 'icon', href: '/images/logo.png' }]],
}
export default {
  headtxt: ['123123',   }],
}

**Comment by pridejoy** [comment]
![image](https://github.com/vuepress/vuepress-next/assets/45122088/e6f075e0-992d-4bb2-9164-d4c0588e330c)

这样增加了很多还没有效果。不想要logo。只要有简单的文字显示也好
![image](https://github.com/vuepress/vuepress-next/assets/45122088/ed45c31c-1551-4e43-a974-8438bcb934a7)
看起来空荡荡的。根据官放的配置比较麻烦

**Comment by Mister-Hope** [comment]
Set title
