### ISSUE TITLE
[Bug report] 生产环境与开发环境的侧边栏点开不同

### ISSUE THREAD

**Issue by afl-lxw** [vuepress/vuepress-next#1379]
### Description

当我在开发环境时 目录结构与地址如下
<img width="492" alt="image" src="https://github.com/vuepress/vuepress-next/assets/56349292/2c6228fe-5d6a-4eba-8cf8-8b741d420dc1">
<img width="1553" alt="image" src="https://github.com/vuepress/vuepress-next/assets/56349292/1145b5b8-f325-4bf1-b64f-40fbd15b2b60">

当我点击文章的时候 是正常显示的 是有侧边栏的 
但是当我部署到正式环境之后
点击 
<img width="1748" alt="image" src="https://github.com/vuepress/vuepress-next/assets/56349292/5956cd98-780d-4cb4-88ae-da63695f7069">
<img width="1660" alt="image" src="https://github.com/vuepress/vuepress-next/assets/56349292/1bca661e-9c6d-475d-ad2a-fb8cd0eead09">
左边栏消失 文章居中了  

我确认 生产与开发环境是同一套代码
不止这个目录 所有生产环境的目录结构的文章点击都会居中  开发环境则不会  请问是什么原因导致 

文件目录如下
<img width="1716" alt="image" src="https://github.com/vuepress/vuepress-next/assets/56349292/98b61c0f-46ab-47e4-89e0-0e619a89659e">

生产地址 https://toplus.vip/

### Reproduction

...

### Used Package Manager

yarn

### System Info

```shell
"@vuepress/client": "2.0.0-beta.62",
    "@vuepress/plugin-active-header-links": "2.0.0-beta.62",
    "@vuepress/plugin-search": "2.0.0-beta.62",
    "markdown-it-disable-url-encode": "^1.0.1",
    "markdown-it-front-matter": "^0.2.3",
    "vue": "^3.3.4",
    "vuepress": "2.0.0-beta.62",
    "vuepress-vite": "2.0.0-beta.62"
```

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress/vuepress-next/assets/33315834/67bc6d53-96c8-4393-9fbe-d934155b2fae)

![image](https://github.com/vuepress/vuepress-next/assets/33315834/c901ebe3-482f-4939-aed9-6b069929b788)


Your server and sidebar configuration are case sensitive in links (renders 404 page for `/web/Javascript/xxx`, but your project links and vuepress router are not.

Make sure all your links satisfies the original casing should solve the problem
