### ISSUE TITLE
怎么动态注册components下面所有文件的组件实例

### ISSUE THREAD

**Issue by ChYuanJinlin** [vuepress/vuepress-next#1391]
### Clear and concise description of the problem

我我想动态获取components下面所有文件的组件实例，这个要怎么搞

### Suggested solution

vite 可以用import.meta.glob  但是这个不行

**Comment by Mister-Hope** [comment]
Sounds to be the same problem as https://github.com/vuepress/vuepress-next/issues/1226.

Try `import.meta.glob('@source/.vuepress/compnoents/**)` and see if it works.

**Comment by Mister-Hope** [comment]
Any update?
