### ISSUE TITLE
[Feature request] 我希望能够增加路由选项，以md中文文件名作为路由来设置

### ISSUE THREAD

**Issue by wsrfde** [vuepress/vuepress-next#1392]
### Clear and concise description of the problem

因为我每次在文件中还要手动添加title，我的文章太多这太繁琐了。

### Suggested solution

if(pathInferred !== null){
   if(pathInferred.substring(1) === filePathRelative.replace(/\.md$/, ".html"))  {
     let newTitle = filePathRelative.replace(/\.md$/,'').split('/').pop();
     routeMeta.title = newTitle;
   }
  }

我尝试在@vuepress/core/dist/index.js  第110行，增加代码判断，把routeMeta改为文件名，但并没有起到作用。

**Comment by wsrfde** [comment]
<img width="772" alt="image" src="https://github.com/vuepress/vuepress-next/assets/50875031/6ac8c581-be8e-4594-9810-f39aef928f7f">
我在文档中找到了这个，还是希望能够再增加一下，如果不是#一级标题。
可以选择文件名作为标题来展示，谢谢

**Comment by Mister-Hope** [comment]
Override `Page.title` in `extendsPage` hook
