### ISSUE TITLE
mac os 启动后一片空白

### ISSUE THREAD

**Issue by Ivorzk** [vuepress/vuepress-next#1397]
### Description

mac 安装依赖没有报错，启动后一片空白

windows 运行正常，mac 无法正常运行

windows normal

mac os exception

package.json

```json
{
  "name": "docs",
  "version": "1.0.0",
  "description": "project document",
  "main": "index.js",
  "scripts": {
    "dev": "vuepress dev ./",
    "build": "vuepress build ./"
  },
  "author": "ivorzk@qq.com",
  "license": "MIT",
  "dependencies": {
    "@vuepress/plugin-search": "^2.0.0-beta.66",
    "vuepress": "^2.0.0-beta.66"
  }
}
```

vuepress.config.ts

```js
import { defineUserConfig, defaultTheme } from 'vuepress'
// import { docsearchPlugin } from "@vuepress/plugin-docsearch";
import { searchPlugin } from '@vuepress/plugin-search'

export default defineUserConfig({
  lang: 'zh-CN',
  title: 'ext-ui',
  description: 'ext-ui',
  base: '/ext-ui/',
  plugins: [
    searchPlugin({})
  ],
  theme: defaultTheme({
    navbar: [
      {
        text: '开发指南',
        link: '/guide'
      },
      {
        text: '组件',
        link: '/components'
      },
      {
        text: '更新日志',
        link: '/change-log'
      }
    ]
  })
})
```

md 文件 

<img width="347" alt="image" src="https://github.com/vuepress/vuepress-next/assets/7390138/cd0f0e01-9889-47ae-83ac-7f81acfceff7">

启动

<img width="449" alt="image" src="https://github.com/vuepress/vuepress-next/assets/7390138/6f475e01-3258-4b19-8594-ebad4665c5fd">

预览

<img width="1280" alt="image" src="https://github.com/vuepress/vuepress-next/assets/7390138/92558397-b654-4205-969c-a7780bdaac82">

控制台

<img width="956" alt="image" src="https://github.com/vuepress/vuepress-next/assets/7390138/d2a674d3-4d01-4366-bb9d-ed2c00cae70a">

### Reproduction

https://v2.vuepress.vuejs.org/zh/

### Used Package Manager

yarn

### System Info

```shell
➜  Local:   http://localhost:8080/ext-ui/
  ➜  Network: http://192.168.100.41:8080/ext-ui/
  ➜  Network: http://198.18.0.1:8080/ext-ui/
Failed to load url /Users/user/work/longtimeproject/ext-ui/docs/.vuepress/.temp/internal/layoutComponents (resolved id: /Users/user/work/longtimeproject/ext-ui/docs/.vuepress/.temp/internal/layoutComponents) in /Users/user/work/longtimeproject/ext-ui/docs/node_modules/@vuepress/plugin-search/node_modules/@vuepress/client/dist/chunk-V3MKNX2O.js. Does the file exist?
```

**Comment by Mister-Hope** [comment]
> Reproduction
>
> https://v2.vuepress.vuejs.org/zh/

# ?

**Comment by Mister-Hope** [comment]
# Check https://github.com/vuepress/vuepress-next/issues/1195
