### ISSUE TITLE
[Bug report]  Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by Arhell** [vuepress/vuepress-next#1405]
### Description

https://github.com/consolidation/website/actions/runs/6017723638/job/16324502586

### Reproduction

npm run docs:dev

### Used Package Manager

npm

### System Info

```shell
windws
node 16
```

**Comment by Mister-Hope** [comment]
Provide a MININAL reproduction.

This is open source and others do not have any interest reading your source code, especially the problem is 99.9% on your side.

**Comment by Arhell** [comment]
> Provide a MINIMAL reproduction.
> 
> This is open source and others do not have any interest reading your source code, especially the problem is 99.9% on your side.

I use https://www.npmjs.com/package/@vuepress/plugin-search
forgot to update to latest version 67, sorry for wasting time
