### ISSUE TITLE
[Bug report] No response for a long time when building Thousands of markdown files

### ISSUE THREAD

**Issue by javastacks** [vuepress/vuepress-next#1409]
### Description

hello, No response for a long time when building Thousands of markdown files...

![1](https://github.com/vuepress/vuepress-next/assets/13480010/3d2c97d0-5315-4984-9ff0-dfa3383bc752)

### Reproduction

Reproduction

### Used Package Manager

yarn

### System Info

```shell
info Initializing VuePress and preparing data...
⠼ Compiling with viteUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
```

**Comment by meteorlxy** [comment]
Duplicate of #994
