### ISSUE TITLE
[Bug report] official NPM warehouse did not find this dependency @types/highlight.js-9.7.0

### ISSUE THREAD

**Issue by SKT1yang** [vuepress/vuepress-next#1411]
### Description

Internal network environment installation dependencies vuepress@1.9.10 When prompted @ types/highlight.js-9.7.0 not match, but the official NPM warehouse did not find this dependency, address: https://registry.npmjs.org/ @Types/highlight.js/-/highlight.js-9.7.0.tgz,

Can you upgrade the @ types/highlight.js dependency

没有复现环境，可以查看依赖，依赖关系如下：
<img width="950" alt="image" src="https://github.com/vuepress/vuepress-next/assets/34095649/29c4ba06-119d-4e14-8eb1-62f0d0a11cf7">
<img width="996" alt="image" src="https://github.com/vuepress/vuepress-next/assets/34095649/631cdaab-5da6-4c98-ad56-3e2fae50b1c1">

### Reproduction

https://stackblitz.com/edit/vuepress-3vngve?file=package.json

### Used Package Manager

npm

### System Info

```shell
macos 11.4
```

**Comment by Mister-Hope** [comment]
Wrong repo, ask it in https://github.com/vuejs/vuepress
