### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by yusongh** [vuepress/vuepress-next#1424]
### Description

After installing through the following command, a missing webpack error will appear. For specific errors, please see the picture below.

```shell
pnpm add -D vuepress@next @vuepress/client@next vue
```

![image](https://github.com/vuepress/vuepress-next/assets/45997005/27be1168-3229-4bec-9937-ae2ca51f4518)

### Reproduction

https://stackblitz.com/edit/vuepress-rj8mvn?file=package.json

### Used Package Manager

pnpm

### System Info

```shell
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises
    at new NodeError (internal/errors.js:322:7)
    at Loader.builtinStrategy (internal/modules/esm/translators.js:285:11)
    at new ModuleJob (internal/modules/esm/module_job.js:63:26)
    at Loader.getModuleJob (internal/modules/esm/loader.js:258:11)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)
    at async Promise.all (index 1)
    at async link (internal/modules/esm/module_job.js:83:9) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
```

**Comment by meteorlxy** [comment]
Weird. `sass-loader` is set as optional peer dep.

https://github.com/vuepress/vuepress-next/blob/7823c3c0f73b6eb30c93459d2527a860e599d0af/ecosystem/theme-default/package.json#L67-L70

What's your node version? The system info is broken.

**Comment by yusongh** [comment]
> Weird. `sass-loader` is set as optional peer dep.
> 
> https://github.com/vuepress/vuepress-next/blob/7823c3c0f73b6eb30c93459d2527a860e599d0af/ecosystem/theme-default/package.json#L67-L70
> 
> What's your node version and pnpm version? The system info is broken. I think your node version might be lower than v16

yes, node version is 14.19.0, pnpm version is 7.33.5
