### ISSUE TITLE
[Bug report] Unable to modify packaging directory

### ISSUE THREAD

**Issue by Adicwu** [vuepress/vuepress-next#1428]
### Description

When I modify viteOptions.build.outDir, then an error will be reported

> $ vuepress build docs
✔ Initializing and preparing data - done in 155ms
✔ Compiling with vite - done in 2.67s
✖ Rendering 2 pages - failed in 2ms
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'F:\test\vp2-test\docs\.vuepress\.temp\.server\app.eb1f25d2.mjs' imported from F:\test\vp2-test\node_modules\@vuepress\utils\dist\index.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:327:11)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1132:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:524:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:36:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Reproduction

https://github.com/Adicwu/vp2-test

### Used Package Manager

yarn

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 13.60 GB / 31.29 GB
  Binaries:
    Node: 18.18.0 - ~\AppData\Local\Temp\yarn--1698393361628-0.6736116922921371\node.CMD
    Yarn: 1.22.19 - ~\AppData\Local\Temp\yarn--1698393361628-0.6736116922921371\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.38.1.
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.61)
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.67 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.67
    @vuepress/client:  2.0.0-beta.67
    @vuepress/core:  2.0.0-beta.67
    @vuepress/markdown:  2.0.0-beta.67
    @vuepress/plugin-active-header-links:  2.0.0-beta.67
    @vuepress/plugin-back-to-top:  2.0.0-beta.67
    @vuepress/plugin-container:  2.0.0-beta.67
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.67
    @vuepress/plugin-git:  2.0.0-beta.67
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.67
    @vuepress/plugin-nprogress:  2.0.0-beta.67
    @vuepress/plugin-palette:  2.0.0-beta.67
    @vuepress/plugin-prismjs:  2.0.0-beta.67
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.67
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.67
    @vuepress/theme-default:  2.0.0-beta.67
    @vuepress/utils:  2.0.0-beta.67
    vue:  3.3.7
    vue-loader: Not Found
    vue-router:  4.2.5
    vuepress: ^2.0.0-beta.67 => 2.0.0-beta.67
    vuepress-vite:  2.0.0-beta.67
    vuepress-webpack: Not Found
```

**Comment by meteorlxy** [comment]
Please use [dest](https://v2.vuepress.vuejs.org/reference/config.html#dest) option

**Comment by Adicwu** [comment]
> Please use [dest](https://v2.vuepress.vuejs.org/reference/config.html#dest) option

it's work, thanks
