### ISSUE TITLE
[Bug report] Webpack not working

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#1429]
### Description

Related to https://github.com/vuepress/vuepress-next/commit/acbdc7f5c03030fb7fdc32beef898a879fbf8e48

### Reproduction

https://github.com/vuepress/webpack-bug

### Used Package Manager

pnpm

### System Info

```shell
Not needed
```

**Comment by meteorlxy** [comment]
It should have been fixed by 2ac78bda6299639b8bd15935decc884335d53e02. May need a new release
