### ISSUE TITLE
[Bug report] Error: usePageFrontmatter () is called without provider.

### ISSUE THREAD

**Issue by recoluan** [vuepress/vuepress-next#1432]
### Description

When I bump the vuepress dependencies of the custom theme to 2.0.0-rc.0 from 2.0.0-beta.67 , I reported the error "chunk-DHNSDB55.js?v=dbacff81:43 Uncaught (in promise) Error: usePageFrontmatter () is called without provider."

![image](https://github.com/vuepress/vuepress-next/assets/18067907/138b6026-59cc-4007-bd74-2a996ba32a08)

### Reproduction

https://github.com/vuepress-reco/vuepress-theme-reco/tree/feature/bump-dependencies-to-2.0.0-rc.0

### Used Package Manager

pnpm

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 468.98 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.7.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
  Utilities:
    Git: 2.36.1 - /opt/homebrew/bin/git
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Safari: 17.1
  npmPackages:
    @vuepress/bundler-vite: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/bundler-webpack: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/cli: Not Found
    @vuepress/client: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/core: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/markdown: Not Found
    @vuepress/plugin-active-header-links: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-back-to-top: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-container: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-docsearch: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-external-link-icon: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-git: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-nprogress: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-palette: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-prismjs: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-search: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared: 2.0.0-rc.0 => 2.0.0-rc.0 
    @vuepress/theme-default: Not Found
    @vuepress/utils: 2.0.0-rc.0 => 2.0.0-rc.0 
    vue: ^3.3.4 => 3.3.8 
    vue-loader: Not Found
    vue-router: ^4.2.5 => 4.2.5 
    vuepress: Not Found
    vuepress-vite: Not Found
    vuepress-webpack: Not Found
```

**Comment by ntnyq** [comment]
https://github.com/vuepress/vuepress-next/issues/885

**Comment by meteorlxy** [comment]
![image](https://github.com/vuepress/vuepress-next/assets/18205362/f15c423a-e9c2-4f45-8297-9a499f1277ad)

It seems that you have two different copies in your node_modules with different typescript version. Please consider:
- Check your tyescript version and make them consistent.
- Run `pnpm dedupe`

**Comment by recoluan** [comment]
After I upgraded the version of 'typescript', I reported the following exception：

<img width="1243" alt="image" src="https://github.com/vuepress/vuepress-next/assets/18067907/2a5bccdb-aed7-43ab-845b-3354f07dd782">

**Comment by recoluan** [comment]
> After I upgraded the version of 'typescript', I reported the following exception：
> 
> <img alt="image" width="1243" src="https://user-images.githubusercontent.com/18067907/284068046-2a5bccdb-aed7-43ab-845b-3354f07dd782.png">

I found that this error occurs in plugin only, so I implemented useThemeLocaleData in plugin to solve this problem, but I don't know if there is any other good way. Similar issue in the past have been for a long time and have no reference value.

![image](https://github.com/vuepress/vuepress-next/assets/18067907/f7fe969e-ed34-4605-9d85-ca9d985d2e8e)

**Comment by Mister-Hope** [comment]
I believed this is also because multiple package instances in your repo. Double check that. At least we have no issues in vuepress-theme-hope repo, which probably has 3x lines comparing to your repo and also with a lot of plugins.
