### ISSUE TITLE
[Bug report] after setting base, vite failed to handle assets with absolute paths in dev mode

### ISSUE THREAD

**Issue by WangJincheng4869** [vuepress/vuepress-next#1442]
### Description

当配置 base 后不会处理图片地址，导致图片无法显示

![image](https://github.com/vuepress/vuepress-next/assets/41162158/bf3e23c6-dc7e-4aa7-b968-8cb8fb783d59)

### Reproduction

https://stackblitz.com/edit/vuepress-theme-hope-4jgewz?file=docs%2Fdemo%2FREADME.md,docs%2F.vuepress%2Fclient.ts,docs%2F.vuepress%2Fconfig.ts

### Used Package Manager

pnpm

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 14.43 GB / 31.56 GB
  Binaries:
    Node: 20.9.0 - D:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.2.0 - D:\Users\jcwang\AppData\Roaming\npm\npm.CMD
  Utilities:
    Git: 2.43.0.
  Browsers:
    Chrome: Not Found
    Edge: Chromium (119.0.2151.72)
  npmPackages:
    @vuepress/bundler-vite: 2.0.0-rc.0 => 2.0.0-rc.0
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli: Not Found
    @vuepress/client: 2.0.0-rc.0 => 2.0.0-rc.0
    @vuepress/core: Not Found
    @vuepress/markdown: Not Found
    @vuepress/plugin-active-header-links: Not Found
    @vuepress/plugin-back-to-top: Not Found
    @vuepress/plugin-container: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon: Not Found
    @vuepress/plugin-git: Not Found
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom: Not Found
    @vuepress/plugin-nprogress: Not Found
    @vuepress/plugin-palette: Not Found
    @vuepress/plugin-prismjs: Not Found
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: 2.0.0-rc.0 => 2.0.0-rc.0
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data: Not Found
    @vuepress/plugin-toc: Not Found
    @vuepress/shared: Not Found
    @vuepress/theme-default: Not Found
    @vuepress/utils: Not Found
    vue: ^3.3.9 => 3.3.9
    vue-loader: Not Found
    vue-router: ^4.2.5 => 4.2.5
    vuepress: 2.0.0-rc.0 => 2.0.0-rc.0
    vuepress-vite: Not Found
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
cc  @meteorlxy  A real repro here: https://stackblitz.com/edit/vuepress-theme-hope-pbl7xt?file=package.json,README.md

Seems to be a serious bug.

**Comment by WangJincheng4869** [comment]
> Can you provide details with production? The above information is devServer.

我将你的复现换成了 vite4，图片可以正常显示了 https://stackblitz.com/edit/vuepress-theme-hope-umxnhe?file=package.json,docs%2FREADME.md


![image](https://github.com/vuepress/vuepress-next/assets/41162158/f1898e08-6e8c-42ab-ab25-383ea9a3e23f)

**Comment by WangJincheng4869** [comment]
经过测试 `build` 后的结果是正常的，添加上了 `base`，这个问题只是在 dev 环境下存在

**Comment by Mister-Hope** [comment]
cc @meteorlxy

**Comment by XiSenao** [comment]
The parsing template is not provided to `Vite` for parsing, and the processing process of `Vite` should be [as expected](https://github.com/vitejs/vite/pull/5657). It seems that `markdown-it` does [not support base URL](https://github.com/markdown-it/markdown-it/issues/741), so I think it may be more appropriate to implement a similar plugin for markdown-it.

**Comment by meteorlxy** [comment]
Maybe we can port the fix https://github.com/vuejs/vitepress/issues/3239

**Comment by meteorlxy** [comment]
The current fix only works on vite. A better solution might be a markdown-it plugin as @XiSenao proposed.
