### ISSUE TITLE
When to support Import Code Snippets

### ISSUE THREAD

**Issue by John60676** [vuepress/vuepress-next#15]
this will help manage common code snippets

**Comment by meteorlxy** [comment]
The code snippets support of v1 is not so perfect. And it's still marked as **beta** in v1 docs:

![image](https://user-images.githubusercontent.com/18205362/102055949-95553200-3e26-11eb-80cd-ec0212f6b662.png)


An enhanced version comes from this PR: https://github.com/vuejs/vuepress/pull/1336 , and this one may be implemented in v2.

**Comment by meteorlxy** [comment]
Finally we decided to support this proposal:

https://github.com/vuejs/vuepress/pull/538#issuecomment-394579033
