### ISSUE TITLE
Can't get local theme to work

### ISSUE THREAD

**Issue by hyvyys** [vuepress/vuepress-next#153]
### Description

I'm trying to set up a local theme and all I get in the html is `<div id="app" data-v-app=""><layout></layout></div>`.

### Steps to reproduce

Clone my repo, run `yarn` and `yarn dev`, observe lack of content.

- Reproduction link / repo:
https://github.com/hyvyys/vuepress-vite-local-theme
### Expected behavior
Layout component is resolved correctly or an error is raised.

### Environment info

- Browser: Firefox
- Output of `vuepress info`:

```bashEnvironment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz
  Binaries:
    Node: 14.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.1533.0
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: Not Found
  npmGlobalPackages:
    vuepress: Not Found
```

I wonder what those Not Found entries mean...

**Comment by meteorlxy** [comment]
Use `module.exports` in your theme entry
