### ISSUE TITLE
[Bug report] Cannot override layouts for default theme

### ISSUE THREAD

**Issue by digisomni** [vuepress/vuepress-next#166]
### Description

Following any and all official documentation from vuepress or vuepress-next, I am unable to override the 404 page.

### Steps to reproduce

Try to override the 404 page by creating the file `.vuepress/theme/index.js` and filling it in with...

```js
const { path } = require('@vuepress/utils')

module.exports = {
  name: 'vuepress-theme-local',
  extends: '@vuepress/theme-default',
  layouts: {
    404: path.resolve(__dirname, 'layouts/404.vue'),
  }
}
```

Then create a file from there in the `layouts` folder called `404.vue`.

When I do this, the default error page still shows up.

- Reproduction link / repo: https://github.com/vircadia/vircadia-dev-docs/tree/bug/no-override

### Expected behavior

I expect my new component to show up instead of the default error page.

### Environment info

- Browser: Firefox 88.0.1 (64-bit)
- VuePress 2.0.0-beta.14

**Comment by digisomni** [comment]
Found the problem, none of the documentation that I found outlines that this must also be done first so this line should be referenced somewhere, probably in the cookbook (https://vuepress2.netlify.app/advanced/cookbook/extending-a-theme.html#extend-default-theme) next to where it's telling us how to do this in the first place:

`theme: path.resolve(__dirname, 'theme'),`

Is a required line to get it to find your theme.

**Comment by meteorlxy** [comment]
We put the cookbook in the "Advanced" part, assuming that you have read the basic guide

https://vuepress2.netlify.app/guide/theme.html#community-theme
