### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by DigitalCop** [vuepress/vuepress-next#171]
## Bug report[full https repo variable is not respected if not to GitHub]
Setting repo variable to url other than organizaton/repository/GitHub is not respected by dev environment

### Description
We run GitLab internally at https://gitlab.<ourdomain>.no. I add repo: https://gitlab<ourdomain>.no/<reponame> to config.js
I have added repoLabel, editLink and editLinkText to config.js
Edit this page is not displayed when rendered by npm run dev(vuepress dev docs)

If I change the repo value to organizaton/repository, it displays and the link is to GitHub as expected.

### Steps to reproduce
Add this to config.js:
- repo: full url to something else than GitHub
- repoLabel: "Anything"
- editLink: true
- editLinkText: "Anything"

- Reproduction link / repo: Private OnPrem

### Expected behavior

Same behaviour as for gitHub url

### Screenshots

No screenshots 

### Environment info

- Browser: Chrome 90.0.4430.93
- Output of `vuepress info`:

```bash
System:

    OS: Linux 3.10 CentOS Linux 7 (Core)

    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz

    Memory: 879.01 MB / 7.64 GB

    Shell: 4.2.46 - /bin/bash

  Binaries:

    Node: 14.16.1 - /usr/bin/node

    Yarn: Not Found

    npm: 6.14.12 - /usr/bin/npm

  Utilities:

    Git: 2.18.4 - /opt/rh/rh-git218/root/usr/bin/git

  Browsers:

    Chrome: 90.0.4430.93

    Firefox: 78.10.0esr

  npmPackages:

    @vuepress/bundler-vite:  2.0.0-beta.14

    @vuepress/bundler-webpack:  2.0.0-beta.14

    @vuepress/cli:  undefined (2.0.0-beta.14)

    @vuepress/client:  2.0.0-beta.12

    @vuepress/core:  2.0.0-beta.14

    @vuepress/markdown:  2.0.0-beta.13

    @vuepress/plugin-active-header-links: ^2.0.0-beta.14 => 2.0.0-beta.14

    @vuepress/plugin-back-to-top: ^2.0.0-beta.14 => 2.0.0-beta.14

    @vuepress/plugin-container: ^2.0.0-beta.14 => 2.0.0-beta.14

    @vuepress/plugin-debug: Not Found

    @vuepress/plugin-docsearch: Not Found

    @vuepress/plugin-git: ^2.0.0-beta.14 => 2.0.0-beta.14

    @vuepress/plugin-google-analytics: Not Found

    @vuepress/plugin-medium-zoom: ^2.0.0-beta.14 => 2.0.0-beta.14

    @vuepress/plugin-nprogress: ^2.0.0-beta.14 => 2.0.0-beta.14

    @vuepress/plugin-palette:  2.0.0-beta.14

    @vuepress/plugin-prismjs:  2.0.0-beta.14

    @vuepress/plugin-pwa: Not Found

    @vuepress/plugin-pwa-popup: Not Found

    @vuepress/plugin-register-components: Not Found

    @vuepress/plugin-search: Not Found

    @vuepress/plugin-shiki: Not Found

    @vuepress/plugin-theme-data:  2.0.0-beta.14

    @vuepress/plugin-toc: Not Found

    @vuepress/shared:  2.0.0-beta.7

    @vuepress/theme-default:  2.0.0-beta.14

    @vuepress/theme-vue: Not Found

    @vuepress/utils:  2.0.0-beta.11

    vue:  3.0.11

    vue-loader:  16.2.0

    vue-router:  4.0.8

    vuepress: ^2.0.0-beta.14 => 2.0.0-beta.14

    vuepress-vite: ^2.0.0-beta.14 => 2.0.0-beta.14
```

**Comment by meteorlxy** [comment]
Sorry we cannot reproduce your problem.

You can reopen it once you provide a valid reproduction.

**Comment by DigitalCop** [comment]
Consider to reopen based on these observations:
we run GitLab OnPrem at https://gitlab.<ourdomain>.no
This is not supported, the editLink does not render
Testet to write different content with syntax https://gitlab.com, https://github.com. They work, but as soon as we use https://gitlab.<ourdomain>.no, it fails to render.
This works in Vurepress 1.8.2

Tested on Mac and Ubuntu

**Comment by meteorlxy** [comment]
See [editLinkPattern](https://v2.vuepress.vuejs.org/reference/default-theme/config.html#editlinkpattern)

**Comment by DigitalCop** [comment]
Sorry, my bad. It worked
