### ISSUE TITLE
[Bug report] .vuepress/styles/palette.scss overrides ignored in 2.0.0-beta.16

### ISSUE THREAD

**Issue by d34dman** [vuepress/vuepress-next#177]
## Bug report

Overrides in .vuepress/styles/palette.scss  ignored in 2.0.0-beta.16

### Description
Following the instruction in this guide https://vuepress2.netlify.app/reference/default-theme/styles.html#palette-file, you can update the default colors used for the site.
However, latest version of vuepress 2.0.0-beta.16 ignores palette.scss and serves default colours.

### Steps to reproduce

- On a fresh installation of vuepress@next
- Add a readme file with some content that shows primary colour (eg. the frontpage matter of this repo itself)
- follow the instruction in the guide https://vuepress2.netlify.app/reference/default-theme/styles.html#palette-file and in pallete.scss change the `$accentColor` to `#ff0000`.
- run `vuepress dev` and visit the site
- The buttons should still be in default green

- Reproduction link / repo:
Repo: https://github.com/d34dman/vuepress-2.0.16-pallete-bug
Build Output on netlify: https://zealous-goldberg-9cc5c4.netlify.app/

### Expected behavior

- The buttons should be red as shown below

### Screenshots

| Wrong (As is) | Good (To be) |
|---|---|
|![image](https://user-images.githubusercontent.com/1006481/120088668-47da3200-c0f3-11eb-982d-1af4cec02cb8.png)|![image](https://user-images.githubusercontent.com/1006481/120088656-35f88f00-c0f3-11eb-8b96-8b5f0282088e.png)|
|Actual screenshot | modified the colours by  hand to show what it should be like|

### Environment info

- Browser: 
- Output of `vuepress info`:

```bash
yarn run v1.22.5
$ /home/shibin/work/github/vuepress-2.0.16-pallete-bug/node_modules/.bin/vuepress info

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 212.82 MB / 15.18 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.2.0 - /tmp/yarn--1622336657776-0.321099111899821/node
    Yarn: 1.22.5 - /tmp/yarn--1622336657776-0.321099111899821/yarn
    npm: 7.14.0 - /usr/local/bin/npm
  Utilities:
    Git: 2.25.1 - /usr/bin/git
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 88.0.1
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.15 
    @vuepress/cli:  2.0.0-beta.15 
    @vuepress/client:  2.0.0-beta.15 
    @vuepress/core:  2.0.0-beta.15 
    @vuepress/markdown:  2.0.0-beta.15 
    @vuepress/plugin-active-header-links:  2.0.0-beta.15 
    @vuepress/plugin-back-to-top:  2.0.0-beta.16 
    @vuepress/plugin-container:  2.0.0-beta.15 
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.15 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.16 
    @vuepress/plugin-nprogress:  2.0.0-beta.16 
    @vuepress/plugin-palette:  2.0.0-beta.15 
    @vuepress/plugin-prismjs:  2.0.0-beta.15 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.15 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.7 
    @vuepress/theme-default:  2.0.0-beta.16 
    @vuepress/theme-vue: Not Found
    @vuepress/utils:  2.0.0-beta.15 
    vue:  3.0.11 
    vue-loader:  16.2.0 
    vue-router:  4.0.8 
    vuepress: ^2.0.0-beta.16 => 2.0.0-beta.16 
    vuepress-vite: Not Found

Done in 0.88s.

```

**Comment by d34dman** [comment]
Seems like this was introduced in 2.0.0-beta.15 actually.

**Comment by meteorlxy** [comment]
Please read changelog and docs
