### ISSUE TITLE
[Bug report] Darkmode enhance

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#179]
![image](https://user-images.githubusercontent.com/33315834/120164305-0483de80-c22d-11eb-89da-3bd26959e83c.png)

This is weird

**Comment by Mister-Hope** [comment]
Addtional: 

![image](https://user-images.githubusercontent.com/33315834/120164531-42810280-c22d-11eb-9a0b-1fd5769da00f.png)


This is also weird

**Comment by Mister-Hope** [comment]
Besides, no offense, I think it makes no sence that we should use a dark blug bgcolor. Please search why do Google develop reading mode on Android and why we should use warm colors at night.🤔

A grey color should be much more good to peoples eyes.

**Comment by meteorlxy** [comment]
Need enhancement of course.

**Comment by setaman** [comment]
Hello,
many thanks for the dark mode feature. I have two points so far.

First, i also find the container colors in the dark mode a little too offensive. But it's straight forward to adjust with the color palette. I'am not a color expert, but here is what my eyes have found acceptable:
![Screenshot from 2021-06-01 07-22-11](https://user-images.githubusercontent.com/15034996/120339659-240d1c80-c2aa-11eb-8c3e-3ffd86067704.jpg)
Just experimented with the opacity.

Furthermore, I wonder why dark mode cannot be controlled programmatically. I think there should be an option in the config to enable dark mode by default, or hide the toggle button.

**Comment by meteorlxy** [comment]
@setaman You can submit a feature request for what you think is really useful

**Comment by meteorlxy** [comment]
Closing as this issue does not report any solid bug or propose any features. We can move to discussion panel.

**Comment by Mister-Hope** [comment]
I do think this issue is reporting bugs. But it's totally up to you to just regard these as "discussion".🤔

Also a new one.

![image](https://user-images.githubusercontent.com/33315834/121289785-18f46500-c918-11eb-8f6e-e663d8fae037.png)
