### ISSUE TITLE
Please ReAdd Your Missing Plugin URLs

### ISSUE THREAD

**Issue by DMiradakis** [vuepress/vuepress-next#18]
VuePress Team,

I just created [this issue](https://github.com/vuepress/vuepress-community/issues/65) in a different repository because that repository was originally the source code for the `https://vuepress.github.io/` website, but I now see that this repository is the new source code for that website.

That being said, can you please look at my ticket and see what I requested? You have removed all of the documentation for the VuePress Community plugins (for example, vuepress-plugin-container), and it would be really nice to have that documentation back ASAP.

Thanks.

**Comment by DMiradakis** [comment]
Since this issue has been closed, does that mean you will be readding the content mentioned above?

**Comment by meteorlxy** [comment]
@DMiradakis 
1. It does not follow the template
2. It is duplicated
3. It is not related to this project
