### ISSUE TITLE
[Feature request] Start directory support for the literal value of the sidebar

### ISSUE THREAD

**Issue by bosens-China** [vuepress/vuepress-next#185]
## Feature request
``` js
    sidebar:  ['/engineering/']
```
Display the ## and ### of the current md file on the page

### Description

In current version,This will only display an h1 title on the page

### Proposed Solution

``` js
 sidebar:  [['/engineering/', true]]
```

**Comment by bosens-China** [comment]
我想问一下，什么时候会发布新的版本

**Comment by nsznsznjsz** [comment]
FYI: #68 

> Hope we can release VuePress v2 before or at end of 2021 Q2, after which vue3 will become the default version of vue package.
