### ISSUE TITLE
[Feature request] Enhance the sidebar

### ISSUE THREAD

**Issue by bosens-China** [vuepress/vuepress-next#188]
## Feature request
test.md
``` html
# Title
## Secondary heading
### Three-level heading
### Four-level heading
## Secondary heading
### Three-level heading
### Four-level heading
```

I want it to display only two second-level headings on the page. After clicking the second-level heading, it will display the sub-headings below the second-level heading.

### Description

I want to sort out the page structure a bit to avoid displaying them all at the same time.

### Proposed Solution
Add configuration items in the sidebar

**Comment by nsznsznjsz** [comment]
Actually it's supportted in default theme, here is [docs what you are finding](https://vuepress2.netlify.app/reference/default-theme/config.html#sidebar)

**Comment by bosens-China** [comment]
> It's already supportted in default theme, here is [the docs what you are finding](https://vuepress2.netlify.app/reference/default-theme/config.html#sidebar)

Can you give an example

**Comment by meteorlxy** [comment]
https://vuepress2.netlify.app/reference/default-theme/config.html#sidebardepth

**Comment by bosens-China** [comment]
I mean in the same md file, is there an option to collapse all subtitles under the secondary menu?
Only clicking on the parent heading will expand all the children
