### ISSUE TITLE
[Bug report] A plugin cannot be disabled with `false`

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#194]
As theme-default is enabling git and medium-zoom.

Just try adding:

```ts
import type { UserConfig } from "@vuepress/cli";
import type { DefaultThemeOptions } from "@vuepress/theme-default";

const config: UserConfig<DefaultThemeOptions> = {
  base: "/",
  plugins: [["@vuepress/git", false], ["@vuepress/medium-zoom", false], ],
};

export default config;
```

You wil find out that both plugins are still enabled.

This is not the behaviour in v0 and v1.

**Comment by meteorlxy** [comment]
This is the currently expected behavior.

"Setting `['@vuepress/git', false]`"

means

"Do not call `app.use(require('@vuepress/plugin-git'))`"

PS: This should be part of the discussion #193. BTW, v0 does not support plugins at all.

**Comment by Mister-Hope** [comment]
So if a plugin is required by other theme and plugins, this plugin cannot be disabled anyway if these theme and plugins don't allow to do so?

This is  what you mean, right? 

Users config should have the hightest priority shouldn't it?

**Comment by meteorlxy** [comment]
> if these theme and plugins don't allow to do so

Yes, theme and plugin should determine whether and how it could be customized by their options, and should not be influenced by unexpected side effects.
