### ISSUE TITLE
Can i use `enhanceApp` do something?

### ISSUE THREAD

**Issue by bestvist** [vuepress/vuepress-next#20]
### Description

I want config something with global, can i use `enhanceApp.ts` ?

And it's work `components ` dir files ?

**Comment by meteorlxy** [comment]
1. You need to set it explicitly in `.vuepress/config.ts` like this:

```ts
import { path } from '@vuepress/utils'
import type { UserConfig, DefaultThemeOptions } from 'vuepress'

const config: UserConfig<DefaultThemeOptions> = {
  clientAppEnhanceFiles: path.resolve(__dirname, 'clientAppEnhance.ts'),
}

export = config
```

It's possible to be auto loaded, but the conventional filename will change to `.vuepress/clientAppEnhance.ts`.

2. `components` dir won't auto register components for you. You need to register them manually in `clientAppEnhance.ts`.

It might be supported via a plugin, but I don't think it's a good idea to make it built-in.

**Comment by meteorlxy** [comment]
`.vuepress/clientAppEnhance.ts` will be auto loaded in v2.0.0-alpha.13

**Comment by bestvist** [comment]
Thanks a lot.
