### ISSUE TITLE
[Feature request] Yarn 2 support

### ISSUE THREAD

**Issue by tiziodcaio** [vuepress/vuepress-next#200]
### Description

At the moment yarn (not classic) it doesn't work with vuepress! Why?

**Comment by Mister-Hope** [comment]
Vuepress is requiring other plugins and themes, and obviously it can not know and pre-declare those you are using and add them to package.json before publishing

**Comment by meteorlxy** [comment]
@Mister-Hope I'm not familiar with yarn v2. So maybe we could put a tip like pnpm?

https://github.com/vuepress/vuepress-next/blob/b220524f1534a1ada3b896854dba181e8ea36221/docs/guide/getting-started.md#L8-L10

**Comment by Mister-Hope** [comment]
If a plugin or theme author only requires the packages that is actually declaring all the deps, we may let it work if the theme you are using, is manually requiring all the plugins, and you are requiring the theme in config files. Only in that way can we lake it work under strict mode under yarn2 or pnpm.

But we encourage you to use strings to represent the plugin and theme you are using, in that way vuepress will require the module itself and it won't be able to work under strict mode.

Is this description clear enough for you?

**Comment by Mister-Hope** [comment]
I think he actually wants to work in strict mode, which won't extract node_modules, but directly read them through plug'in'play.

That do have a lot benefits including fast installing, modules bundle to git and better performance (also less chance to damage or break node_modules folder)

**Comment by Mister-Hope** [comment]
Maybe we can consider to use :

```js
[require('vuepress-plugin-xxx'), {

**Comment by meteorlxy** [comment]
It's already supported for plugins.

Could not get the reason why we need to drop string support 🤔 . Users could just do not use string if they want to use yarn v2.

**Comment by Mister-Hope** [comment]
Try to read this  @meteorlxy  https://yarnpkg.com/features/pnp

pnpm is similiar.

Under this mode, a package could only visit the packages list in it's deps.

And here is a support table: https://yarnpkg.com/features/pnp#native-support

**Comment by Mister-Hope** [comment]
Here is this content in pnpm:

![image](https://user-images.githubusercontent.com/33315834/121501431-d31bc780-ca11-11eb-84fc-3b552ce70178.png)

**Comment by Mister-Hope** [comment]
> It's already supported for plugins.
> 
> Could not get the reason why we need to drop string support 🤔 . Users could just do not use string if they want to use yarn v2.

I got you, this is not the actually problem.

The actuall problem is that plugins and themes may need to declare packages like `@vuepress/core` `@vuepress/client` in it's deps

**Comment by Mister-Hope** [comment]
i am not very familiar with it too because I only have some "demo" project running under this mode.

A lot of deps may actually missing some deps which they should declare. It's kind a historical problem in my opinion.

**Comment by meteorlxy** [comment]
It's more compilicated. We are using absolute file paths heavily, e.g. clientAppEnhanceFiles.

If you confirm that loose mode could work, we can put a tip in docs.

**Comment by Mister-Hope** [comment]
> It's more compilicated. We are using absolute file paths heavily, e.g. clientAppEnhanceFiles.
> 
> If you confirm that loose mode could work, we can put a tip in docs.

Emm, yes it is compilicated. This is definitely not the thing we should focus now, but I still hope we can make it in todo list and try if we can support it in the future.

Losse mode will work. Because it's fully compatable with V1.

**Comment by tiziodcaio** [comment]
Can we open an issue called PNP support?

**Comment by tiziodcaio** [comment]
Only to remember the problem

**Comment by Mister-Hope** [comment]
As the issue mentioned, currently no plans to supoort. And it's also hard to support because it requires changes on themes side.
AA

**Comment by tiziodcaio** [comment]
> Also there is a workaround

Which, nodelinker?

**Comment by Mister-Hope** [comment]
> Here is this content in pnpm:
> 
> ![image](https://user-images.githubusercontent.com/33315834/121501431-d31bc780-ca11-11eb-84fc-3b552ce70178.png)

here
