### ISSUE TITLE
[Bug report] Vercel seems not work well with VuePress Next with stucked deployment

### ISSUE THREAD

**Issue by imgradeone** [vuepress/vuepress-next#209]
## Bug report

> This issue may need to create into vercel/vercel, sorry for confusing
> Currently I can only deploy by Vercel CLI with `vercel --prod`

edited: For now, if you need to use VuePress v2 with automatic builds, you need to try Netlify or Tencent Cloud CloudBase. (at least I tested)  
> Also, Cloudflare Pages didn't work well too.

### Description

While I was deploying a VuePress-Next website with Vercel, Vercel stucked in `info Initializing VuePress and preparing data...` and didn't continue deploying

### Steps to reproduce

1. Deploy a VuePress-Next Project in Vercel
2. It stucks

- Reproduction link / repo:
1. https://github.com/imgradeone/glzxsgyk
2. https://github.com/imgradeone/vuepress-v2-test
3. https://glzxsgyk-k8st3mvcs-imgradeone.vercel.app/

### Expected behavior

It should be deployed correctly as VuePress 1.0 doesn't have this problem

### Environment info

- Browser: *not deployed*
- Output of `vuepress info`:

```bash


<!--StartFragment-->
System:
--
16:53:37.988 | OS: Linux 4.14 Amazon Linux 2
16:53:37.988 | CPU: (4) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
16:53:37.988 | Memory: 9.01 GB / 15.38 GB
16:53:37.988 | Shell: 4.2.46 - /bin/bash
16:53:37.988 | Binaries:
16:53:37.988 | Node: 14.16.1 - /tmp/yarn--1623488016906-0.06970557184669901/node
16:53:37.988 | Yarn: 1.22.10 - /tmp/yarn--1623488016906-0.06970557184669901/yarn
16:53:37.988 | npm: 6.14.12 - /node14/bin/npm
16:53:37.988 | Utilities:
16:53:37.988 | Git: 2.23.4 - /usr/bin/git
16:53:37.988 | Browsers:
16:53:37.988 | Chrome: Not Found
16:53:37.989 | Firefox: Not Found
16:53:37.989 | npmPackages:
16:53:37.989 | @vuepress/bundler-vite: Not Found
16:53:37.989 | @vuepress/bundler-webpack:  2.0.0-beta.18
16:53:37.989 | @vuepress/cli:  2.0.0-beta.18
16:53:37.989 | @vuepress/client:  2.0.0-beta.18
16:53:37.989 | @vuepress/core:  2.0.0-beta.18
16:53:37.989 | @vuepress/markdown:  2.0.0-beta.18
16:53:37.989 | @vuepress/plugin-active-header-links:  2.0.0-beta.18
16:53:37.989 | @vuepress/plugin-back-to-top:  2.0.0-beta.18
16:53:37.989 | @vuepress/plugin-container:  2.0.0-beta.18
16:53:37.989 | @vuepress/plugin-debug: Not Found
16:53:37.989 | @vuepress/plugin-docsearch: Not Found
16:53:37.989 | @vuepress/plugin-git:  2.0.0-beta.18
16:53:37.989 | @vuepress/plugin-google-analytics: Not Found
16:53:37.989 | @vuepress/plugin-medium-zoom:  2.0.0-beta.18
16:53:37.989 | @vuepress/plugin-nprogress:  2.0.0-beta.18
16:53:37.989 | @vuepress/plugin-palette:  2.0.0-beta.18
16:53:37.989 | @vuepress/plugin-prismjs:  2.0.0-beta.18
16:53:37.989 | @vuepress/plugin-pwa: Not Found
16:53:37.990 | @vuepress/plugin-pwa-popup: Not Found
16:53:37.990 | @vuepress/plugin-register-components: Not Found
16:53:37.990 | @vuepress/plugin-search: Not Found
16:53:37.990 | @vuepress/plugin-shiki: Not Found
16:53:37.990 | @vuepress/plugin-theme-data:  2.0.0-beta.18
16:53:37.990 | @vuepress/plugin-toc: Not Found
16:53:37.990 | @vuepress/shared:  2.0.0-beta.18
16:53:37.990 | @vuepress/theme-default:  2.0.0-beta.18
16:53:37.990 | @vuepress/theme-vue: Not Found
16:53:37.990 | @vuepress/utils:  2.0.0-beta.18
16:53:37.990 | vue:  3.1.1
16:53:37.990 | vue-loader:  16.2.0
16:53:37.990 | vue-router:  4.0.8
16:53:37.990 | vuepress: ^2.0.0-beta.18 =&gt; 2.0.0-beta.18
16:53:37.990 | vuepress-vite: Not Found

<!--EndFragment-->


```

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/121771095-cfb64680-cb9f-11eb-8a36-8115c4a34806.png)
We don't have access for the third link. Could you paste the vercel log in your issue?

**Comment by Mister-Hope** [comment]
And where is your config file?

**Comment by imgradeone** [comment]
> ![image](https://user-images.githubusercontent.com/33315834/121771095-cfb64680-cb9f-11eb-8a36-8115c4a34806.png)
> We don't have access for the third link. Could you paste the vercel log in your issue?

Sorry, I changed the URL to https://glzxsgyk-k8st3mvcs-imgradeone.vercel.app/

and the log:

```bash
16:56:29.859  	Cloning github.com/imgradeone/glzxsgyk (Branch: main, Commit: 667556b)
16:56:30.106  	Cloning completed: 246.555ms
16:56:30.123  	Analyzing source code...
16:56:31.099  	Installing build runtime...
16:56:33.438  	Build runtime installed: 2.339s
16:56:36.397  	No Build Cache available
16:56:37.434  	Detected package.json
16:56:37.434  	Installing dependencies...
16:56:37.778  	yarn install v1.22.10
16:56:37.847  	[1/4] Resolving packages...
16:56:38.046  	[2/4] Fetching packages...
16:56:44.158  	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
16:56:44.159  	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
16:56:44.159  	[3/4] Linking dependencies...
16:56:44.159  	warning "vuepress > @vuepress/theme-default > sass-loader@12.1.0" has unmet peer dependency "webpack@^5.0.0".
16:56:47.107  	[4/4] Building fresh packages...
16:56:48.061  	Done in 10.29s.
16:56:48.448  	yarn run v1.22.10
16:56:48.485  	$ vuepress build docs
16:56:48.815  	info Initializing VuePress and preparing data...
```

**Comment by imgradeone** [comment]
> And where is your config file?

Config: https://github.com/imgradeone/glzxsgyk/blob/main/docs/.vuepress/config.js

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/121771186-6f73d480-cba0-11eb-9e5c-9a9930e65acd.png)

Still 404. 

```
16:56:48.815  	info Initializing VuePress and preparing data...
```

If the above is your last line, please wait. Something(e.g.: timeout error) is expected to be thrown and logged. That may help finding out the reason.

**Comment by meteorlxy** [comment]
I had ever reported this to Vercel, but they could not get it solved at that time, so I went back to Netlify.

I think you'd better send a feedback to Vercel instead of here.

**Comment by imgradeone** [comment]
> I had ever reported this to Vercel, but they could not get it solved at that time, so I went back to Netlify.
> 
> As I remember, it would just get stuck and timeout after about 40 mins, without any logs.
> 
> I think you'd better send a feedback to Vercel instead of here, because we can work well with Netlify, GitHub Actions, etc.

OK, I've sended a feedback to Vercel.

then also, there aren't any logs, truly.

![image](https://user-images.githubusercontent.com/30969327/121772086-e3fd4200-cba5-11eb-8e19-6a7e984754a2.png)

**Comment by yegorgunko** [comment]
I can reproduce it and I've already submitted a ticket to Vercel support.
I will share their response here when I get it.

**Comment by imgradeone** [comment]
Well, using Vercel CLI with `vercel --prod` is OK, without this problem.

**Comment by imgradeone** [comment]
For now, if you need to use VuePress v2 with automatic builds, you need to try Netlify or Tencent Cloud CloudBase. (at least I tested)  

Also, Cloudflare Pages didn't work well too.

**Comment by ENDsoft233** [comment]
i've meet the same issue, and my repository url is `https://github.com/ENDsoft233/51book`, hoping to bring some help to you.

**Comment by yegorgunko** [comment]
Tried latest beta (23) - still the same: `info Initializing VuePress and preparing data...`.

@vercel-support any news about this issue?

**Comment by yansongda** [comment]
maybe vercel has solved the issue. My project work well just now

**Comment by meteorlxy** [comment]
Yeah, just succeed to deploy our docs on Vercel:

https://vuepress-next.vercel.app/

**Comment by fh-combo** [comment]
> Yeah, just succeed to deploy our docs on Vercel:
> 
> https://vuepress-next.vercel.app/

After my site is published, except the home subdirectory is the resource path error 404, I would like to ask where should be modified to fix this problem
