### ISSUE TITLE
[Bug report] Cannot get it work on yarn 2

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#21]
### Description

```sh
command not found: vuepress
终端进程“/bin/bash '-c', 'yarn run dev'”已终止，退出代码: 127。
```

### Steps to reproduce

- Reproduction link / repo: https://github.com/Mister-Hope/vuepress2-plyagound

### Environment info

- Browser:
- Output of `vuepress info`:

```sh
# Paste output of `vuepress info` here
# Unable to do so, command not found, but I am do using the latest alpha13
```

**Comment by meteorlxy** [comment]
Not familiar with yarn v2 yet.

**Comment by Mister-Hope** [comment]
Meanwhile, I am having some troubles with yarn 1.

When requiring vuepress in a workspace with vuepressV1:
![image](https://user-images.githubusercontent.com/33315834/103330142-20a20a80-4a58-11eb-835e-43d3d37f5123.png)

```json
{
  "name": "demo",
  "scripts": {
    "build": "vuepress build src",
    "clean-serve": "vuepress dev src --no-cache",
    "eject": "vuepress eject-hope src",
    "serve": "vuepress dev src"
  },
  "devDependencies": {
    "vuepress": "1.7.1",
  }
}
```

But I can not get a bin folder with vuepress 2

![image](https://user-images.githubusercontent.com/33315834/103330180-4b8c5e80-4a58-11eb-9d60-d3ba830e4175.png)

I both tried on Windows20H2 and WSL2(Ubuntu 20.04) with Node 14.15.3 and Yarn 1.22.5.

I am able to run vuepress in the root folder(the bin folder has `vuepress`), while the projects inside it are catching issues.

Could you check the package.json for vuepress2?

I think 

```json
  "bin": {
    "vuepress": "cli.js"
  },
```

is required for everything working fine. @meteorlxy

**Comment by meteorlxy** [comment]
The `vuepress` command is provided by `@vuepress/cli`.

So the `@vuepress/cli` that required by `vuepress` did not take effect when using yarn v2? 🤔

**Comment by Mister-Hope** [comment]
> The `vuepress` command is provided by `@vuepress/cli`.
> 
> So the `@vuepress/cli` that required by `vuepress` did not take effect when using yarn v2? 🤔

It's even not working with yarn V1 in my case. The screenshot I provides are all with v1

**Comment by Mister-Hope** [comment]
I think we should metion it through docs, that if we are using workspace, we should require `@vuepress/cli` to get the vuepress command. @meteorlxy

**Comment by Mister-Hope** [comment]
I am afraid the yarnV2 issue is related to it too. Yarn 2 only extracts command which is directly required by the project.

**Comment by meteorlxy** [comment]
We need to confirm if the fix works in next release
