### ISSUE TITLE
[Feature request] Debounce in docsearch

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#216]
## Feature request

Currently, every type change in input box will send a search request, so the result list earlier will finally display if it's ending at last.
Also this cause the result list shrink when typing. I think a debounce with delay should be added.

**Comment by meteorlxy** [comment]
Not sure if this could be resolved in user side, or could only be changed inside docsearch package.

**Comment by meteorlxy** [comment]
Closing as it seems that this could only be implemented in docsearch.

**Comment by Mister-Hope** [comment]
See https://docsearch.algolia.com/docs/api#transformsearchclient

Demo here: https://codesandbox.io/s/docsearch-v3-debounced-search-gnx87
