### ISSUE TITLE
[Bug report] Docsearch not working

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#217]
Here is my website: https://waline.js.org (It has a lang attr on `html`)

It's not working because `@vuepress/docsearch` plugin is force adding `facetFilters: ['lang:xxx']` while the default vuepress2 docsearch template (I am not sure how docsearch is generating clawer config files for vuepress2 website) is not supporting it.

I will post on this repo first. @meteorlxy  @shortcuts

**Comment by meteorlxy** [comment]
We have a note in the docs:

https://github.com/vuepress/vuepress-next/blob/207014b087d29f43bd01604954e33277b6b19150/docs/reference/plugin/docsearch.md#L53

Submit a PR directly to that repo: https://github.com/algolia/docsearch-configs/blob/master/configs/waline.json

**Comment by Mister-Hope** [comment]
Got it, but I recommand you to move it outside the details block. That's why I missed it. I will also try to warn algolia for that when sites using vuepress2 are requesting docsearch.

![image](https://user-images.githubusercontent.com/33315834/121891548-2792b000-cd4e-11eb-96f4-9b49655a4192.png)

**Comment by meteorlxy** [comment]
Hi @shortcuts, could your team help to add those fields when a site is using VuePress 2?

You can identify the generator according to the `<meta name="generator">` tag:

![image](https://user-images.githubusercontent.com/18205362/121892011-c7e8d480-cd4e-11eb-9e42-f101b0b49945.png)

**Comment by shortcuts** [comment]
Hey @Mister-Hope, @meteorlxy 

I just realized that our config generator didn't picked the vuepress template, I'll dig in our scraper to see where's the issue!

Thanks to both of you for pointing that out!
