### ISSUE TITLE
[Bug report] Issue with types

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#22]
## Bug report

https://github.com/vuepress/vuepress-next/blob/607112cd2d8b9536554296470eba20e9e181e661/packages/%40vuepress/theme-default/src/types/options.ts#L2

The `DefaultThemeOption` is using types from `plugin-docsearch`, while it is not installed by default.

https://github.com/vuepress/vuepress-next/blob/607112cd2d8b9536554296470eba20e9e181e661/packages/%40vuepress/theme-default/src/node/resolveDocsearchPluginOptions.ts#L19-L20

So errors will be trigged if the plugin is not installed.

**Comment by meteorlxy** [comment]
Uh nice catch. Maybe we should remove docsearch options from default theme
