### ISSUE TITLE
[Feature request] Support multiple <meta name="theme-color">

### ISSUE THREAD

**Issue by Unbinilium** [vuepress/vuepress-next#221]
### Description

For better user experience, the browser should get color hex before the page loaded, but it seems `vuepress-next` does not currently supported the duplicated meta tags like this:

```ts
['meta', { name: 'theme-color', content: '#3eaf7c', media: '(prefers-color-scheme: light)' }],
['meta', { name: 'theme-color', content: '#22272e', media: '(prefers-color-scheme: dark)' }],
```

Related with #215 and #218

### Proposed Solution

We are using following snippet to dedupe `<meta>` tag:

https://github.com/vuepress/vuepress-next/blob/33c9a2145eeaf53429f2ae784e393074d1a9edd5/packages/%40vuepress/shared/src/utils/resolveHeadIdentifier.ts#L11-L14

But I think that supporting multiple `<meta name="theme-color">` tags should be another issue.

There's another problem.

Meta tags set in user config will be injected to client with `useSiteData`. So we also have to update the sitedata ref, or the tag will be reset once navigating to another page.

_Originally posted by @meteorlxy in https://github.com/vuepress/vuepress-next/issues/218#issuecomment-860658563_

**Comment by meteorlxy** [comment]
According to the [spec](https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color):

> There must not be more than one meta element with its name attribute value set to an ASCII case-insensitive match for theme-color per document.

So this is a non-standard support of [Safari 15](https://css-tricks.com/safari-15-new-ui-theme-colors-and-a-css-tricks-cameo/).
