### ISSUE TITLE
[Feature request] Support `prefersColorScheme` 

### ISSUE THREAD

**Issue by nsznsznjsz** [vuepress/vuepress-next#224]
### Description

Since #183 discussions, we supported an `darkMode` option and released in v2.0.0-beta.19, but we still need to [manually set the mode](https://github.com/vuepress/vuepress-next/discussions/183#discussioncomment-882887), we all hope there is a more elegant way to got it.

### Proposed Solution

A brand new option `prefersColorScheme`

- Type: `'light' | 'dark' | 'auto'`
- Default: `'auto'`

Dark mode has just been supported, it may not be too late to change it, users can easily migrate to the new option, just change `darkMode: false` to `prefersColorScheme: 'light'`.

New option also have better scalability, suppose we create a new mode for AMOLED screen, we can simply add a type 'Amoled Black'.

If it fine I could pull a request, thanks for reviewing.

**Comment by meteorlxy** [comment]
That's a little different. `darkMode: false` disable dark mode totally, including the toggle button.

**Comment by nsznsznjsz** [comment]
If author specify `prefersColorScheme` and is not automatically switched, this usually means that the author does not want this page to support switching perfers color scheme, toggle button should be hidden.

**Comment by meteorlxy** [comment]
Users may also ask for "support switching light/dark mode, and set default mode to dark".

I think we can be a little opinionated on such feature.

**Comment by Mister-Hope** [comment]
No offence, why can't we support features like this: https://vuepress-theme-hope.github.io/guide/interface/darkmode/#options

(A new value named 'dark' with only dark theme can be added as well)

These features I am providing are all in use in my users sites.

**Comment by meteorlxy** [comment]
> No offence, why can't we support

If you didn't use a "why can't" sentence as above, people wouldn't take it as an offense 😅

**Comment by Mister-Hope** [comment]
I would like to open a pr similiar like [this](https://vuepress-theme-hope.github.io/guide/interface/darkmode/#options), the config key name can be dicussed later.

Does this config look good to you ? @meteorlxy
