### ISSUE TITLE
[Bug report] Search is not working.

### ISSUE THREAD

**Issue by CeruttiMaicon** [vuepress/vuepress-next#226]
### Description

I did the installation of vuepress 2, as in the documentation, and after following the plugin installation instructions, the search still doesn't appear.

### Screenshots

![image](https://user-images.githubusercontent.com/25940408/122650620-6045d700-d10a-11eb-9588-c5506c1a9cb8.png)

### Settings in my project

docs/.vuepress/config.js
```
module.exports = {
    ...
    plugins: [
    [
      '@vuepress/plugin-search',
      {
        locales: {
          '/': {
            placeholder: 'Search',
            // allow searching the `tags` frontmatter
            maxSuggestions: 10,
            hotKeys: ['s', '/'],
          }
        },
      },
    ],
  ],
}
```

this should have worked right?

https://v2.vuepress.vuejs.org/reference/plugin/search.html#local-search-index

**Comment by syahrulright** [comment]
I have the same issue, please help..

**Comment by meteorlxy** [comment]
Closing as you didn't provide any reproduction and env info

**Comment by Mister-Hope** [comment]
You should install this plugin yourself.

**Comment by CeruttiMaicon** [comment]
I updated to the beta version of plugin [2.0.0-beta.19](https://www.npmjs.com/package/@vuepress/plugin-search).

Now it's working.

Mark here just to make it documented in case anyone else experiences this problem.

Sorry for not providing all essential information to resolve the issue. :)

https://www.npmjs.com/package/@vuepress/plugin-search
