### ISSUE TITLE
[Feature request] Automatically disable code line numbers for code blocks with <= 3 lines

### ISSUE THREAD

**Issue by vmihailenco** [vuepress/vuepress-next#231]
Small code block don't benefit from line numbers and look neater without them.

**Comment by meteorlxy** [comment]
You can add `:no-line-numbers` on them

**Comment by vmihailenco** [comment]
And any reasons this can't be done automatically?

**Comment by KnorpelSenf** [comment]
I like my code blocks with line numbers. Also if there's just one line. That makes it very obvious we have a code block, and not some other ASCII art or whatever. It's consistent with the other code blocks around that have four lines.

If this becomes a “feature”, there should be a way to restore the old behaviour. But honestly, at that point it is easier just not to do it in the first place.

**Comment by vmihailenco** [comment]
>That makes it very obvious we have a code block

How number "1" to the left of the line makes anything obvious?

>some other ASCII art or whatever

Some other ASCII art or whatever have line numbers too. Oops.

**Comment by KnorpelSenf** [comment]
Line numbers don't really exist anywhere, except in code. So if there's a line number, it's more obvious than if there isn't one.

I disable line numbers for ASCII art. It's actually pretty simple to do that. No need for arbitrary auto-disabling. Oops.

You may or may not agree with my style preferences. Perhaps a plugin can give you what you want. Please just don't remove the existing behaviour.

Or if you're extremely keen on letting a rule system automatically toggle line numbers, at least give us a `:line-numbers` flag. I will just `sed` all files and add it everywhere.

For example, JS and TS have sometimes a different number of lines. Then the JS tab doesn't have line numbers but the TS one does. So we'd really want to detect if that's the case and consistently apply line numbers for shorter snippets. Or consistently hide them. Unless we have three tabs, out of which two would display them, in which case they should be shown again. And so on.

**Comment by meteorlxy** [comment]
Calm down. That should be a personal taste.

If we are going to support, we'll make the `markdown.code.lineNumbers` to also accept `boolean | number`. (now it only accepts `boolean`), which won't cause any breaking change. Then the number would be the threshold.

But I'm not sure if there are many users who need this feature.

**Comment by KnorpelSenf** [comment]
Thanks, that sounds good

**Comment by Mister-Hope** [comment]
Agree that's good

**Comment by jiazengp** [comment]
I think it's a good idea
