### ISSUE TITLE
Local search box not show [Bug report]

### ISSUE THREAD

**Issue by shengzhou1216** [vuepress/vuepress-next#237]
## Bug report 
Local search box not show

### Description
Search box for Local Search Index is not showing in the navbar.  I follow [this document](https://v2.vuepress.vuejs.org/reference/plugin/search.html#local-search-index )

### Steps to reproduce
1. init vuepress 2 project
I am followed [this document](https://v2.vuepress.vuejs.org/guide/getting-started.html#manual-installation)
2. add dependency
 ```bash
 yarn add -D @vuepress/plugin-search
 ```
3. config search plugin
```bash
 plugins: [
        [
            '@vuepress/plugin-search'
        ]
    ]
```

### Expected behavior

can seeing a  search box in navbar.

### Screenshots
![FireShot Capture 044 - Hello VuePress - - localhost](https://user-images.githubusercontent.com/30176131/123506883-0ceb0000-d699-11eb-83b2-6d0d28c6d89f.png)
as you can see , there is no search box show in navbar.

### Environment info
- node version
```
v16.4.0
```
- Browser: Firefox 89.0.1 (64-bit)
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 11.01 GB / 62.73 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.4.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.18.1 - /usr/bin/npm
  Utilities:
    Git: 2.32.0 - /usr/bin/git
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.1
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.19 
    @vuepress/cli:  2.0.0-beta.19 
    @vuepress/client:  2.0.0-beta.19 
    @vuepress/core:  2.0.0-beta.19 
    @vuepress/markdown:  2.0.0-beta.19 
    @vuepress/plugin-active-header-links:  2.0.0-beta.19 
    @vuepress/plugin-back-to-top:  2.0.0-beta.19 
    @vuepress/plugin-container:  2.0.0-beta.19 
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.19 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.19 
    @vuepress/plugin-nprogress:  2.0.0-beta.19 
    @vuepress/plugin-palette:  2.0.0-beta.19 
    @vuepress/plugin-prismjs:  2.0.0-beta.19 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: ^1.8.2 => 1.8.2 
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.19 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.19 
    @vuepress/theme-default:  2.0.0-beta.19 
    @vuepress/utils:  2.0.0-beta.19 
    vue:  3.1.2 
    vue-loader:  16.2.0 
    vue-router:  4.0.10 
    vuepress: ^2.0.0-beta.19 => 2.0.0-beta.19 
    vuepress-vite: Not Found
```
- package.json
```json
"devDependencies": {
    "@vue/component-compiler-utils": "^3.2.2",
    "@vuepress/plugin-search": "^1.8.2",
    "@vuepress/shared-utils": "^1.8.2",
    "vuepress": "^2.0.0-beta.19"
  },
```

**Comment by Mister-Hope** [comment]
Use v2 with next gflag please

**Comment by shengzhou1216** [comment]
you mean `yarn add -D vuepress@next` ? i

**Comment by Mister-Hope** [comment]
I mean

```
yarn add -D @vuepress/plugin-search@next
```

Why do you think a `next` version plugin should be under the `latest` tag intead of  the same `next` flag.

**Comment by Mister-Hope** [comment]
Just a kind reminder, if you are not familiar with node and vue3, I personally do not recommand you to try things which has not yet touched stable.

**Comment by shengzhou1216** [comment]
It's works now. I didn't know the difference between the different tags and thought it should be backward compatible.
I am not familiar with vue3 , and  new to vuepress , so choose the latest version.
Thank you for you remind.

**Comment by Mister-Hope** [comment]
You can try vuepress@v1 (latest), which you would not likely to run in to some issues, and switch to v2 later when it is published as `latest`.
