### ISSUE TITLE
[Feature request] Theme palette support

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#25]
## Feature request

Can the `@vuepress/plugin-palette-stylus` add support for theme palette?

Currently We can only config users' palette. But it would be nice to add theme palette support to let theme provides fallback value for stylus variables. Becase some variables are using accross the theme components, and it's not graceful to import a common file at the beginning of style block or write fallbacks in every file.

### Description

I have to write like this in most of my components now:

```html
...
<style lang="stylus">
@require '../styles/palette'
...
</style>
```
or

```html
...
<style lang="stylus">
$variableName1 ?= value
$variableName2 ?= value

...
</style>
```

### Proposed Solution

Add a theme `themePaletteFile` option

**Comment by meteorlxy** [comment]
I don't understand what you mean by "theme palette".

Palette is a feature provided by theme, which allows theme users to customize colors or other style variables.

**Comment by Mister-Hope** [comment]
It was a feature provided in V1.

i appreciated for your work bring V2 to us, but it's really werid that you "don't understand" a V1 feature instead of giving some reasons removing it.

**Comment by Mister-Hope** [comment]
IMO, taking over others work is on understanding what others did.

I will explain why we need the feature:

First of all, the `palette.styl` is designed to let users config the theme more easily by setting stylus variables. So, these variables should have fallback value if users not config them.

A theme `palette.styl` is designed for providing fallback values:

```styl
$variable1 ?= defaultvalue1
$variable2 ?= defaultvalue2

...
```

---

Though it's ok to remove it, I think there are pros remaining it.

Pros:

- Theme providers can manage all the configuable variables in one place
-  Users can take better understand of all the configuable styles and view their default value by visiting this file
- A lot of varibles are using in serveral components, so theme providers won't need to import a `palette.styl` at the beginning of the style block or set default value in every components which are using style varables ( And that also means mistakes cound be made when changing default value by droping some components variables unchanged)

And I can not think out any cons. @meteorlxy

**Comment by meteorlxy** [comment]
Again, you should read the code before commiting FR

https://github.com/vuepress/vuepress-next/blob/main/packages/%40vuepress/theme-default/src/styles/_variables.styl

**Comment by meteorlxy** [comment]
OK, the only thing is that "so theme providers won't need to import a palette.styl at the beginning of the style block or set default value in every components which are using style varables".

- It's not a good idea to use implicit stylus variables. You should import it when you want to use it.
- You can use CSS variables, which would be more universal, like our nprogress and back-to-top plugins. The default theme is difficult to migrate, so we still use stylus.
