### ISSUE TITLE
[Bug report] [[toc]] outputs with `#` preceding headers

### ISSUE THREAD

**Issue by rnwolfe** [vuepress/vuepress-next#251]
### Description

The `[[toc]]` renders the headers with the preceding `# `.

### Steps to reproduce
Build any page with headers and put a ``[[toc]]`` in it.

- Reproduction link / repo:
  - You can actually see this on the `alpha.20` docs site for the Table of Contents section: https://vuepress2.netlify.app/guide/markdown.html#table-of-contents
  - Screenshot: https://gyazo.com/636132f7bb3aa3e943a72a8bdc05e4f9

### Expected behavior

The Table of Contents should not render the anchoring `#`.

### Screenshots
Screenshot: https://gyazo.com/636132f7bb3aa3e943a72a8bdc05e4f9

### Environment info

- Browser: 91.0.4472.124 (Official Build) (64-bit)
- Output of `vuepress info`:

```bash
  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 21.01 GB / 25.01 GB
    Shell: 3.2.2 - /usr/bin/fish
  Binaries:
    Node: 14.17.0 - ~/.local/share/nvm/v14.17.0/bin/node
    Yarn: Not Found
    npm: 6.14.13 - ~/.local/share/nvm/v14.17.0/bin/npm
  Utilities:
    Git: 2.32.0 - /usr/bin/git
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.20 
    @vuepress/cli:  undefined (2.0.0-beta.20)
    @vuepress/client:  2.0.0-beta.20 
    @vuepress/core:  2.0.0-beta.20 
    @vuepress/markdown:  2.0.0-beta.20 
    @vuepress/plugin-active-header-links:  2.0.0-beta.20 
    @vuepress/plugin-back-to-top:  2.0.0-beta.20 
    @vuepress/plugin-container:  2.0.0-beta.20 
    @vuepress/plugin-debug: ^2.0.0-beta.20 => 2.0.0-beta.20 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.20 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.20 
    @vuepress/plugin-nprogress:  2.0.0-beta.20 
    @vuepress/plugin-palette:  2.0.0-beta.20 
    @vuepress/plugin-prismjs:  2.0.0-beta.20 
    @vuepress/plugin-pwa: ^2.0.0-beta.20 => 2.0.0-beta.20 
    @vuepress/plugin-pwa-popup: ^2.0.0-beta.20 => 2.0.0-beta.20 
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: ^2.0.0-beta.20 => 2.0.0-beta.20 
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.20 
    @vuepress/plugin-toc: ^2.0.0-beta.20 => 2.0.0-beta.20 
    @vuepress/shared:  2.0.0-beta.20 
    @vuepress/theme-default:  2.0.0-beta.20 
    @vuepress/utils:  2.0.0-beta.20 
    vue:  3.1.2 
    vue-loader:  16.3.0 
    vue-router:  4.0.10 
    vuepress: ^2.0.0-beta.20 => 2.0.0-beta.20 
    vuepress-vite: Not Found
```

**Comment by meteorlxy** [comment]
Caused by an internal breaking change of markdown-it-anchor.

[Before](https://github.com/valeriangalliat/markdown-it-anchor/blob/828401d92c29ccf2420ed454c9c0cc6616aadedb/index.js#L24): using `html_block`

```js
Object.assign(new state.Token('html_block', '', 0), { content: opts.permalinkSymbol }),
```


[After](https://github.com/valeriangalliat/markdown-it-anchor/blob/f5c0844dbb0ea127fc158249411c1400a060c039/permalink.js#L81): using `html_inline`

```js
Object.assign(new state.Token('html_inline', '', 0), { content: opts.symbol }),
```

**Comment by rnwolfe** [comment]
Given that, is this something that should be fixed in `@vuepress/plugic-toc` or `@vuepress/markdown`? 

Is it better to fix the problem closer to the source (in `@vuepress/markdown`) or just keep the behavior and compensate for it in `@vuepress/plugic-toc`?

Happy to give it a go with a bit of guidance. Otherwise I can just wait it out.

**Comment by meteorlxy** [comment]
You are in the right place. Now the problem is how to identify the symbol token (`#` in our case).

We could not simply identify it using `item.content !== '#'`, because users may use other symbol via the options of markdown-it-anchor. Further more, users may even write a `html_inline` with `#` in the markdown heading intentionally.

I'm asking the author of markdown-it-anchor for advices: https://github.com/valeriangalliat/markdown-it-anchor/issues/98
