### ISSUE TITLE
[Bug report] Fail to resolve images in `<img>` tag when using relative file path

### ISSUE THREAD

**Issue by chris-dura** [vuepress/vuepress-next#254]
### Description

We sometimes need to use regular HTML `<img>` elements in Markdown files, instead of the standard markdown image `![foo](foo.png)` syntax. However, whenever using `<img>` with relative paths, I get a webpack compilation error. If I use absolute URLs, the project compiles with `npm run dev`; however, the images are not displayed.

```bash
ERROR in ./.vuepress/.temp/pages/index.html.vue?vue&type=template&id=0dd0b7d1 (./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./.vuepress/.temp/pages/index.html.vue?vue&type=template&id=0dd0b7d1) 2:0-34
Module not found: Error: Can't resolve './foo.png' in '/sandbox/.vuepress/.temp/pages'

webpack compiled with 1 error
```

### Steps to reproduce

- Reproduction link / repo: https://codesandbox.io/s/vuepress-next-img-element-eg68h?file=/README.md

### Expected behavior

I would expect to be able to use standard HTML tags in Markdown files, in particular to this case, the `<img>` element, with relative or absolute URLs:

```md

Some **markdown** content...

<img src="foo.png" />
<img src="./foo.png" />
<img src="../../foo.png" />
<img src="/foo.png" />

Some _more_ markdown content...

```

### Screenshots

<img width="760" alt="Screen Shot 2021-07-02 at 11 35 07 AM" src="https://user-images.githubusercontent.com/3680914/124310591-9f702100-db29-11eb-8023-7328f652351d.png">

### Environment info

- Browser: n/a
- Output of `vuepress info`:

```bash
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 471.71 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: Not Found
    npm: 7.16.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Utilities:
    Git: 2.31.0 - /usr/local/bin/git
  Browsers:
    Chrome: 91.0.4472.114
    Edge: 91.0.864.64
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.17 
    @vuepress/cli:  2.0.0-beta.17 
    @vuepress/client:  2.0.0-beta.15 
    @vuepress/core:  2.0.0-beta.17 
    @vuepress/markdown:  2.0.0-beta.15 
    @vuepress/plugin-active-header-links:  2.0.0-beta.17 
    @vuepress/plugin-back-to-top:  2.0.0-beta.17 
    @vuepress/plugin-container:  2.0.0-beta.17 
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.17 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.17 
    @vuepress/plugin-nprogress:  2.0.0-beta.17 
    @vuepress/plugin-palette:  2.0.0-beta.17 
    @vuepress/plugin-prismjs:  2.0.0-beta.17 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.17 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.7 
    @vuepress/theme-default:  2.0.0-beta.17 
    @vuepress/theme-vue: Not Found
    @vuepress/utils:  2.0.0-beta.15 
    vue:  3.1.1 
    vue-loader:  16.2.0 
    vue-router:  4.0.8 
    vuepress: ^2.0.0-beta.17 => 2.0.0-beta.17 
    vuepress-vite: Not Found
```

**Comment by Mister-Hope** [comment]
This is not a bug.

When you write `<img src="foo.png" />`, we will regard you are requiring a package called `foo.png`

**Comment by chris-dura** [comment]
> When you write <img src="foo.png" />, vuepress will regard you are requiring a package called foo.png

... but it's not a package, it's standard HTML image. Markdown is a superset of HTML, so any valid HTML page is _also_ a valid Markdown page.

> I think this is not a bug.

I disagree, HTML is valid Markdown, and VuePress (being a Markdown-based static site generator), the expectation would be that valid, standard HTML should at least not break the build. So, imo, it _is_ a bug, because it breaks a core piece of HTML.
I am not a Webpack expert, but in most other Webpack projects, there's no extra configuration needed to get Webpack to resolve `<img src="" />` properly...

> you must place the image in the public folder.

Yeah, that's a workaround I'm using for now, but that experience isn't great... imo, static assets should be stored as close to the content referencing it. Generally, the `public` folder is used to " provide static assets that are _not_ directly referenced in any of your Markdown files"... so it seems a little smelly to put the image in `public` when the MD file is deeply nested.

```
.vuepress/public/foo.png
doc/path/to/some/deep/section/README.md
```
It'd be much cleaner to be able to put the image near the content, like this:
```
doc/path/to/some/deep/section/images/foo.png
```

**Comment by Mister-Hope** [comment]
>  but in most other Webpack projects, there's no extra configuration needed to get Webpack to resolve <img src="" /> properly...

I doubt that. I don't think `<img src="foo.png" />` works in webpack, only `<img src="./foo.png" />` works in my experiences. 

VuePress 0.x and 1.x requires `./` to declare it's a relative path, so does v2. VuePress is a vue powered site generator. It supports people to write both markdown and vue file and also themes and plugins to make them together as a site, and it also support Vue in markdown. So it's OK (and since it's born) that it is not a standard markdown parser.

From main page:

> Vue-powered Static Site Generator

See here https://vuepress2.netlify.app/guide/assets.html#packages-and-path-aliases, VuePress is providing ability to import packages, that why a `./` is requried for a relative assets.

You are neither using the latest package nor providing screenshots whether `<img src="./foo.png" />` work. If `./` works, that's the expect behaviour since v0.x.

**Comment by Mister-Hope** [comment]
Also there is a possiable solution:

Build a markdown-it plugin by your own, which check every source link in the page, if it's not beginning with `/` or `./` append `./` at the beginning.

**Comment by meteorlxy** [comment]
@chris-dura Thanks for reporting.

@Mister-Hope You may misunderstand this issue. Things work well with markdown image syntax `![]()`, but fail with html `<img>` tag

**Comment by meteorlxy** [comment]
Pending for https://github.com/markdown-it/markdown-it/issues/796

**Comment by xiaoyu2er** [comment]
@Mister-Hope 
When I am in dev mode, I can find the images if I use `<img src="cover.jpg">` and I put the image in the public folder

But When I am in build mode, I cannot resolve the image

```
info Initializing VuePress and preparing data...
⠧ Compiling with vite[vite]: Rollup failed to resolve import "cover.jpg" from "docs/.vuepress/.temp/pages/en/xx/index.html.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

**Comment by Mister-Hope** [comment]
> @Mister-Hope When I am in dev mode, I can find the images if I use `<img src="cover.jpg">` and I put the image in the public folder
> 
> But When I am in build mode, I cannot resolve the image
> 
> ```
> info Initializing VuePress and preparing data...
> ⠧ Compiling with vite[vite]: Rollup failed to resolve import "cover.jpg" from "docs/.vuepress/.temp/pages/en/xx/index.html.vue".
> This is most likely unintended because it can break your application at runtime.
> If you do want to externalize this module explicitly add it to
> `build.rollupOptions.external`
> ```

I am not sure whether we should force throw an error in this case, but this could be an improvement though.

By default, a package called `cover.jpg` will be treated as first chiose, it seems that vite will fallback to public folder.

**Comment by xiaoyu2er** [comment]
> 



> > @Mister-Hope When I am in dev mode, I can find the images if I use `<img src="cover.jpg">` and I put the image in the public folder
> > But When I am in build mode, I cannot resolve the image
> > ```
> > info Initializing VuePress and preparing data...
> > ⠧ Compiling with vite[vite]: Rollup failed to resolve import "cover.jpg" from "docs/.vuepress/.temp/pages/en/xx/index.html.vue".
> > This is most likely unintended because it can break your application at runtime.
> > If you do want to externalize this module explicitly add it to
> > `build.rollupOptions.external`
> > ```
> 
> I am not sure whether we should force throw an error in this case, but this could be an improvement though.
> 
> By default, a package called `cover.jpg` will be treated as first chiose, it seems that vite will fallback to public folder.

Yes, it should be the same when in both modes.
