### ISSUE TITLE
[Bug report] Unable to set the sidebar as an object

### ISSUE THREAD

**Issue by liniiishui** [vuepress/vuepress-next#255]
### Description
When I set the config of the sidebar that is an object, I get an error that shows "Uncaught TypeError: sidebarConfig.map is not a function". However, I checked the official documentation and it can be set to an object.

###  my sidebar config
```js
// .vuespress/config.js
module.exports = {
  ... // other config
  themeConfig: {
       sidebar: {
            '/my-note/':   // one of navbar config link
            {
               text: 'my-note title',
               children: [
                   '/my-note/README.md',
                  '/my-note/one.md',
                  '/my-note/two.md'
              ]
            }
       }
   }
  ... // other config
}
```

### Environment info

- Browser: Google 91.0.4472.124
- System:  Win10
- vuepress verssion:  2.0.0-beta.20

**Comment by meteorlxy** [comment]
Please read the docs carefully:

> The value should be a sidebar array.
