### ISSUE TITLE
[Feature request] Support to copy codes in CodeGroupItem

### ISSUE THREAD

**Issue by chinesedfan** [vuepress/vuepress-next#258]
### Description

Not sure whether due to keeping things simple, the feature is very convenient I think.

### Proposed Solution

https://github.com/znicholasbrown/vuepress-plugin-code-copy

**Comment by Mister-Hope** [comment]
I think it's the plugin's work to support it, and plugins do can support it.

For examples, see https://vuepress-theme-hope.github.io/
