### ISSUE TITLE
Dicussion: not decouple styles and components in default theme

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#26]
Fist of all: Could you open the dicussion board?

---

I DO read through your codes. And below is a other thing I wanna say towards the `_variable.styl`.

The design goal of Vue SFC is to place the styles, template and script in one place. And I think there are several disadvantages for you to decouple styles and components in default theme, for just making a palette import more easily.

1. It's really hard for a user to be fully santisfied with another one's theme. It's quite common for others to edit it ( So that's why we have theme extending in V1)
2. Theme extending is bring the `@theme` and `@parent-theme` to let users easily overside some layouts and components while using the rest in a third-party theme (And I saw you drop it because of decouipling webpack). Decouping the styles with components means users have to think out a css selector with higher priority or use `!important` to overide the styles in `styles` folder when using theme extending and replace the components in default theme with theirs. While they can just write a component of them with most of the styles remain in component in V1.

Again, I DO think you do not take fully understand of uliuz's work before making changes on it! 🤔

**Comment by meteorlxy** [comment]
Discussion panel is open now.

>  I DO think you do not take fully understand of uliuz's work before making changes on it!

So call your ulivz back. Don't you realize why Evan wanted to drop vuepress and start vitepress?
