### ISSUE TITLE
[Bug report] Can't access pages by typing the urls directly in browser address bar

### ISSUE THREAD

**Issue by Benbinbin** [vuepress/vuepress-next#265]
## Bug report
I can't  access the page through typing the url directly in browser address bar, but after building and hosting the `dist` file, I can access all pages

### Description
I use Vuepress-next as a static site generator to build my blog, in my [project](https://github.com/Benbinbin/two-dishes-one-fish) I add extra homepage and some navigation pages refer to the [documentation method](https://v2.vuepress.vuejs.org/advanced/cookbook/adding-extra-pages.html), so I don't use the default theme navbar and homepage. Then I cannot access any markdown pages but just show the extra homepage and navigation pages in dev environment.

If I build the project it work fine, or change the bundler to webpack, I can access all pages in dev environment.

I think if I don't refer to the Markdown file in navbar or homepage, then I can't access it through typing the corresponding url directly in browser address bar.  Should I set any parameter in Vite to get it work in dev environment?

### Steps to reproduce

- Reproduction link / repo: a mini [DEMO](https://github.com/Benbinbin/vuepress-vite-demo)

### Screenshots
* use Vite as bundler in dev: 
  ![image](https://user-images.githubusercontent.com/40909550/124501471-2fe18680-ddf4-11eb-8a6d-72fb4a62e2dc.png)

  ![Snipaste_2021-07-06_00-28-00](https://user-images.githubusercontent.com/40909550/124500931-38858d00-ddf3-11eb-999f-be52129ac012.png)

* use Webpack as bundler in dev:
  ![image](https://user-images.githubusercontent.com/40909550/124501528-4e478200-ddf4-11eb-870b-c165abd4472e.png)

  ![Snipaste_2021-07-06_00-27-07](https://user-images.githubusercontent.com/40909550/124500933-39b6ba00-ddf3-11eb-9b8f-009805d4b8a6.png)

### Environment info

- Browser: Chrome
- System: Win10
- vuepress: 2.0.0-beta.21
- vuepress-vite: 2.0.0-beta.21

**Comment by Mister-Hope** [comment]
Appears on my project too

**Comment by meteorlxy** [comment]
This is a regression. Need to fallback all requests to `/index.html`
