### ISSUE TITLE
[Bug report]: Night mode buttons do not have an accessible name

### ISSUE THREAD

**Issue by jiazengp** [vuepress/vuepress-next#271]
### Discussed in https://github.com/vuepress/vuepress-next/discussions/270

<div type='discussions-op-text'>

<sup>Originally posted by **jiazengp** July  9, 2021</sup>
![image](https://user-images.githubusercontent.com/86162890/125058448-dbccef80-e0dc-11eb-8c22-eba86e38803a.png)
</div>

**Comment by meteorlxy** [comment]
Fixed in #275
