### ISSUE TITLE
[Feature request]  @vuepress/theme-default `Page` need a `content-bottom` sloat

### ISSUE THREAD

**Issue by xianghongai** [vuepress/vuepress-next#278]
## Feature request

If it is used as a blog, it can be used to add copyright information.

### Proposed Solution

```vue
<!-- ... -->
    <div class="theme-default-content">
      <Content />

      <slot name="content-bottom" />
    </div>
<!-- ... -->
```

**Comment by Mister-Hope** [comment]
Copy right infomatin should be added here:

https://github.com/vuepress/vuepress-next/blob/eb970c3aa4c4d650cd964b0c1f60d423a7d55125/packages/%40vuepress/theme-default/src/client/components/Page.vue#L7-L9

The div outside the `<Content />` is a wrapper. Plugins like picture preview, code copy will search into this wrapper and add some listener or make some changes. So event if you may want some copyright info or other content, we should better add it outside the wrapper.

**Comment by xianghongai** [comment]
Has been implemented by inheriting themes. 😀
