### ISSUE TITLE
[Feature request] `vuepress build` dist file support minify

### ISSUE THREAD

**Issue by xianghongai** [vuepress/vuepress-next#280]
## Feature request

`vuepress build` dist file support minify.

### Description

Or, the output code provides a different formatting configuration.

**Comment by meteorlxy** [comment]
Closing as the information you provided is too little for us to understand the feature

**Comment by xianghongai** [comment]
@meteorlxy The build file needs to compressing HTML code. /构建输出的 HTML 文件需要压缩。
