### ISSUE TITLE
[Bug report] The parameter 'base' has no effect.

### ISSUE THREAD

**Issue by tinyking** [vuepress/vuepress-next#284]
### Description

I config 'base' parameter as `/jarcoder/`, then build it, the `404.html` is right:
![image](https://user-images.githubusercontent.com/4127712/125382288-feeeec00-e3c7-11eb-84e6-5fd8bc785b02.png)

But, `index.html` is wrong:
![image](https://user-images.githubusercontent.com/4127712/125382319-0f9f6200-e3c8-11eb-9eb7-838ab8caf6e4.png)

### Environment info

```
"vuepress": "^2.0.0-beta.22"
```

**Comment by meteorlxy** [comment]
Please provide a reproduce repo

**Comment by tinyking** [comment]
Please close this issue.
When i rebuild at now, it is ok~~
