### ISSUE TITLE
[Feature request] multiple sidebar is not supported in vuepress2

### ISSUE THREAD

**Issue by maodou38** [vuepress/vuepress-next#285]
### Description

i find that vuepress can only show current page's titles in sidebar. when it was 1.X, the default theme has one function that can show multiple pages's title in one page by using [group](https://v1.vuepress.vuejs.org/zh/theme/default-theme-config.html#%E5%A4%9A%E4%B8%AA%E4%BE%A7%E8%BE%B9%E6%A0%8F)

### Proposed Solution

can someone help support this function

**Comment by Mister-Hope** [comment]
All the page are loaded async, which means you can not access other pages 's data sync.

And meteorlxy's idea is not accessing other pages. That will help increase dev and build speed.

**Comment by meteorlxy** [comment]
> show multiple pages's title in one page

Sidebar group is also supported. Please read the docs.

For example, in the `/guide/` page, you can see the title of the `/guide/getting-started.html` page and other pages.

![image](https://user-images.githubusercontent.com/18205362/125454555-7b4adcc9-1c3d-42e6-806b-a14bc996a006.png)


@Mister-Hope Well, I think you should try to understand issues correctly before leaving such "criticism".

**Comment by Mister-Hope** [comment]
Apologize for that, title do can be accessed through router, but not frontmatters.

**Comment by maodou38** [comment]
@meteorlxy i have tried docs's settings about sidebar yesterday.This is my config.js at that time:
![issue](https://user-images.githubusercontent.com/39987981/125562653-aebfc73f-873c-478a-8f71-889bf5ac1812.png)
but when i visit /docker/XXXX.html,i get the same side bar:Docker笔记 which is my setting on title.
Can you give me some idea,i need to prepare README.md in each folder?

**Comment by maodou38** [comment]
in v1,
![issue](https://user-images.githubusercontent.com/39987981/125563439-4d29f275-eee6-4f9e-a152-cd964b353ef6.png)

i can visit anyone .md and its sidebar is the whole folder's titles' summary.

**Comment by maodou38** [comment]
can you show me a example,need help.Thanks
