### ISSUE TITLE
Update default theme to support dark mode

### ISSUE THREAD

**Issue by jrappen** [vuepress/vuepress-next#29]
### Description

Please update the default theme to be dynamic, i.e. support dark mode.

### Proposed Solution

This was the best I could find:

https://github.com/tolking/vuepress-theme-default-prefers-color-scheme

as I personally believe a dynamic theme shouldn't expose any manual toggles to the user.

**Comment by Mister-Hope** [comment]
There are a lot of ways, e.g. https://vuepress-theme.mrhope.site/

**Comment by meteorlxy** [comment]
Bumping to v2 is a good time point to support dark mode.

**Comment by Mister-Hope** [comment]
I have a question, I saw the `evergreen` is set to `true` by default, and css `var()` is used in serveral plugins. So we are dropping IE support?

**Comment by tolking** [comment]
@meteorlxy We can write CSS Variables for default theme, and the unsupported browsers by postcss plugIn. then support dark mode for supported browsers by [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by tiziodcaio** [comment]
Does this feature request will applied?

**Comment by meteorlxy** [comment]
@tiziodcaio  It's listed in the [Roadmap](https://github.com/vuepress/vuepress-next/discussions/68)

**Comment by meteorlxy** [comment]
> I have a question, I saw the `evergreen` is set to `true` by default, and css `var()` is used in serveral plugins. So we are dropping IE support?

@Mister-Hope Now we can definitely say "YES" 😃

**Comment by tiziodcaio** [comment]
> @tiziodcaio It's listed in the [Roadmap](https://github.com/vuepress/vuepress-next/discussions/68)

Woops... Sorry
So happy ☺️☺️☺️
