### ISSUE TITLE
[Bug report] URLs without HTML extension don't always work

### ISSUE THREAD

**Issue by KnorpelSenf** [vuepress/vuepress-next#292]
### Description

When visiting a URL where the `.html` extension is missing, a 404 is rendered as soon as the site is hydrated. You can observe how the SSR version correctly loads, and then it is changed to 404.

### Steps to reproduce

1. Disable JS in your browser
2. Visit https://v2.vuepress.vuejs.org/reference/bundler/vite (note that the `.html` suffix is missing)
3. The page loads correctly.
4. Enable JS again
5. Reload the page
6. A 404 is rendered

### Expected behavior

The behaviour is consistent between both sites. I'd prefer if URLs without extension would just work, but if this is undesired for some reason then I'd expect the 404 to be rendered without JS already.

**Comment by meteorlxy** [comment]
It has nothing to do with VuePress. Should should change the configuration of the deployment platform to redirect `/vite` to `/vite.html`

**Comment by meteorlxy** [comment]
I might misunderstand what the problem is. This could be something we can enhance
