### ISSUE TITLE
[Bug report] the page created by createPage cannot be hot-reloaded

### ISSUE THREAD

**Issue by ZengTianShengZ** [vuepress/vuepress-next#294]
### Description

When the content of the file is changed, the page created by createPage cannot be hot-reloaded

```js
   const buttonPath = path.resolve(__dirname, '../../../packages/components/button/README.md')
    async onInitialized(app) {
        const homepage = await createPage(app, {
            path: '/button',
            filePath: buttonPath
        })
        app.pages.push(homepage)
    },
```
when i editor button/README.md, but button page cannot be hot-reloaded. but [vuepress@1.x](https://vuepress.vuejs.org/plugin/option-api.html#additionalpages) `additionalPages ` can  hot-reloaded

### Steps to reproduce

- Reproduction link / repo:

### Expected behavior

when i editor .md creatd by `createPage`, the page can  hot-reloaded

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```

**Comment by meteorlxy** [comment]
For now we only watch `pagesPattern`:

https://github.com/vuepress/vuepress-next/blob/f07589cfd85f3ed00c34f7e3c36f3c5c9230f055/packages/%40vuepress/cli/src/commands/dev/watchPageFiles.ts#L10-L13

**Comment by ZengTianShengZ** [comment]
Is there a way to monitor .md files outside the docs directory？
because our directory structure is like this：

```
.project
|---docs
    --- .vuepress
|---components
|    --- button
|           --- README.md
```

Our README.md file follows the component, so the design is more intuitive and uniform

**Comment by ZengTianShengZ** [comment]
I use this approach to meet my needs, but it doesn’t feel very elegant 😂

```
 const chokidar = require("chokidar");
 const utils = require("@vuepress/utils");
 const core = require("@vuepress/core");
 
 const handlePageChange = async (app, filePath) => {
     const pageIndex = app.pages.findIndex((page) => page.filePath === filePath);
     if (pageIndex === -1) {
         return;
     }
     const oldPage = app.pages[pageIndex];
     const changedPage = await core.createPage(app, {
         filePath,
     });
     oldPage.contentRendered = changedPage.contentRendered // Replace only necessary information
     oldPage.hoistedTags = changedPage.hoistedTags
     oldPage.content = changedPage.content
     app.pages.splice(pageIndex, 1, oldPage);
     await core.preparePageComponent(app, oldPage);
     await core.preparePageData(app, oldPage);
 };
 
 const watchPageFiles = (app, filePath) => {
     const pagesWatcher = chokidar.watch(`${filePath}/**/*.md`, {
         cwd: app.dir.source(),
         ignoreInitial: true,
     });
     pagesWatcher.on('change', (filePathRelative) => {
         utils.logger.info(`page ${utils.chalk.magenta(filePathRelative)} is modified`);
         handlePageChange(app, app.dir.source(filePathRelative));
     });
     return pagesWatcher;
 };
   
 module.exports = (app, filePath, routerPath, name) => {
     watchPageFiles(app, filePath);
 }
```

**Comment by meteorlxy** [comment]
As an alternative, you can try to add `../components/**/README.md` to `pagePatterns` option.

**Comment by meteorlxy** [comment]
Closing as it's not a common use case and already have work around.
