### ISSUE TITLE
[Bug report] Code block colors broken after accent color change

### ISSUE THREAD

**Issue by osipxd** [vuepress/vuepress-next#296]
### Description

Some of the colors for code highlight are inherited from the theme's colors.
For example:

```scss
.token.inserted {
    color: var(--c-text-accent);
}
```

It works only correctly with the default style colors.

### Steps to reproduce

1. Change `--c-text-accent` to red
2. Add code block to any page:
    ~~~markdown
    ```diff
    - Old value
    + New value
    ```
    ~~~
3. Look at the result

### Expected behavior

The colors used for syntax highlight should be red and green and it should be independent of the configured color theme.

### Screenshots

![image](https://user-images.githubusercontent.com/3684355/126355974-b508858c-0059-4bf6-ac33-606e3f8d31c3.png)

### Environment info

I don't think it is needed.

**Comment by meteorlxy** [comment]
We simply replaced all the color hex when migrating to css vars. This one should not be replaced 🤔
