### ISSUE TITLE
[Bug report] webpack启动的端口是8081，热更新失效

### ISSUE THREAD

**Issue by xwwei** [vuepress/vuepress-next#298]
### Description

我通过vuepress dev docs启动服务，端口是8081，但是当我更改.md文件时，热更新失效，
我看到热更新监听的端口还是8080，并没有同步更改

![image](https://user-images.githubusercontent.com/32604947/126631254-f4475797-194a-4079-8b5a-cc9ab55d3dc5.png)

这是我的config配置，当我在配置指定端口时，是可以热更新的，但是我认为这个不对的，因为这样我必须规定一个端口

```
import { defineUserConfig } from 'vuepress'
import type { DefaultThemeOptions } from 'vuepress'
import { navbar, sidebar } from './configs'

export default defineUserConfig<DefaultThemeOptions>({
  lang: 'zh-CN',
  title: 'ivy-comps',
  description: 'ivy-comps docs',

  locales: {
    '/en/': {
      lang: 'en-US',
      title: 'ivy component docs',
      description: 'Vue-powered Static Site Generator',
    },
    '/zh/': {
      lang: 'zh-CN',
      title: 'ivy组件文档',
      description: 'Vue 驱动的静态网站生成器',
    },
  },

  themeConfig: {
    logo: '/logo.png',
    locales: {
      '/zh/': {
        navbar: navbar.zh,
        sidebar: sidebar.zh
      },
      '/en/': {
        navbar: navbar.en,
        sidebar: sidebar.en
      }
    },
    sidebar: 'auto', // 侧边栏配置
    sidebarDepth: 2, // 侧边栏显示2级
  },
})

```
### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```

**Comment by meteorlxy** [comment]
You should provide a reproduce repo.

**Comment by xwwei** [comment]
Reproduction link / repo: https://github.com/xwwei/vuepress-demo.git
you can repeat the problem here.  you can see README.md

**Comment by meteorlxy** [comment]
@xwwei Could you help to confirm if this issue still exist in 2.0.0-beta.23 ?

We have bump webpack-dev-server to 4.0.0-rc.0, which might have solved this kind of issues.

**Comment by meteorlxy** [comment]
Closing as this issue is inactive

**Comment by xwwei** [comment]
I tested it. It's OK in 2.0.0-beta.23 version. I've been busy recently. I forgot to pay attention to this problem
