### ISSUE TITLE
[Feature request] Content excerpts

### ISSUE THREAD

**Issue by chris-dura** [vuepress/vuepress-next#301]
### Description

Folks building custom themes (in particular "Blogging" themes) use excerpts quite often.

### Proposed Solution

Perhaps there is a "better" way to do it for v2, but at the very least, the same functionality that was provided in v1 would be preferred.
https://vuepress.vuejs.org/theme/writing-a-theme.html#content-excerpt

**Comment by meteorlxy** [comment]
It's still supported, but has not been documented yet.

**Comment by meteorlxy** [comment]
https://v2.vuepress.vuejs.org/reference/node-api.html#excerpt
