### ISSUE TITLE
[Bug report] Character should be declared in the first 1024 bytes

### ISSUE THREAD

**Issue by jiazengp** [vuepress/vuepress-next#305]
### Description

Always declare the encoding of your document using a element with a attribute, or using the and attributes (called a pragma directive). The declaration should fit completely within the first 1024 bytes at the start of the file, so it's best to put it immediately after the opening tag.metacharsethttp-equivcontenthead

**Comment by jiazengp** [comment]
Character refers to

``` html
<meta charset="utf-8">
```

**Comment by meteorlxy** [comment]
Sorry but we could not understand what you were reporting
