### ISSUE TITLE
navbar，sidebar的显示出现xx.md

### ISSUE THREAD

**Issue by prayjourney** [vuepress/vuepress-next#307]
2.0.0-beta.22版本之中，在navbar，sidebar之中link，children，或者是字符页面路径写xxx.md，就会出现xxx.md的显示，有点难受
![image](https://user-images.githubusercontent.com/15311937/126879070-84366a5f-d96b-46de-b9e2-63a7910a2709.png)
![image](https://user-images.githubusercontent.com/15311937/126879073-b6b91968-c829-4573-87b4-e565f7543aa2.png)
![image](https://user-images.githubusercontent.com/15311937/126879078-4bacf339-8f2d-4b4f-892f-99964d4a3da0.png)

**Comment by ENDsoft233** [comment]
试试用 `{ text: '标题文本', link: '链接' }` 来替换 `链接` 吧

**Comment by prayjourney** [comment]
> 试试用 `{ text: '标题文本', link: '链接' }` 来替换 `链接` 吧

确实是可以去掉，目前我看文档上面还是旧的方式children: ['/foo/bar.md', '/foo/hello.md', '/foo/Hi.md'], 这种，这种去不掉.md
