### ISSUE TITLE
[Bug report] No such file or direcotory (plugin docsearch)

### ISSUE THREAD

**Issue by Spike-Leung** [vuepress/vuepress-next#312]
### Description

( English is not my native language; please excuse typing errors. ）

1.  I follow the `Getting Started`  to init vuepress-vite, but there is no `@vuepress/plugin-docsearch` install by default. 

when i want to integrate with docsearch, i need to install `@vuepress/plugin-docsearch` manual.

But there is no tips to tell me i should install manual in the docsearch plugin docs，may be can add some tips ?

2. After I install `@vuepress/plugin-docsearch` ，then config by  and run `vuepress build docs`,  i get an error below 

![image](https://user-images.githubusercontent.com/30440218/127259489-06297860-d65b-4673-b56d-43a62af4c7ca.png)

In `node_modules/@vuepress/plugin-docsearch/node_modules/@vuepress/client/lib/app.js`,  it try to import 
`/Users/spike/Documents/private-git/blog/docs/.vuepress/.temp/internal/pagesComponent`

Actully , there is no `/Users/spike/Documents/private-git/blog/docs/.vuepress/.temp/internal/pagesComponent`

there is `/Users/spike/Documents/private-git/blog/docs/.vuepress/.temp/internal/pagesComponents` (has a `s`)

### Steps to reproduce

- Reproduction link / repo:

### Expected behavior

1. add install `docsearch` plugin tips in `docsearch` plugin docs page or add `docsearch` in vuepress by default.
2. keep the `pagesComponent` name unified.

### Environment info

- Browser: Firefox
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
./node_modules/@vuepress/cli/bin/vuepress.js info

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 2.09 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Utilities:
    Git: 2.30.1 - /usr/bin/git
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Not Found
    Firefox: 90.0.2
    Safari: 14.1.1
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.22
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.22
    @vuepress/client:  2.0.0-beta.21
    @vuepress/core:  2.0.0-beta.22
    @vuepress/markdown:  2.0.0-beta.22
    @vuepress/plugin-active-header-links:  2.0.0-beta.22
    @vuepress/plugin-back-to-top:  2.0.0-beta.22
    @vuepress/plugin-container:  2.0.0-beta.22
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.22
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.22
    @vuepress/plugin-nprogress:  2.0.0-beta.22
    @vuepress/plugin-palette:  2.0.0-beta.22
    @vuepress/plugin-prismjs:  2.0.0-beta.22
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.22
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.21
    @vuepress/theme-default:  2.0.0-beta.22
    @vuepress/utils:  2.0.0-beta.21
    vue:  3.1.5
    vue-loader: Not Found
    vue-router:  4.0.10
    vuepress: Not Found
    vuepress-vite: ^2.0.0-beta.22 => 2.0.0-beta.22
```

**Comment by Spike-Leung** [comment]
> keep the pagesComponent name unified.

may be should update `docsearch`'s vuepress version in its package.json?

**Comment by Zhengqbbb** [comment]
you need to add Packages:
```sh
yarn add -D @vuepress/plugin-docsearch@next
```

**Comment by Spike-Leung** [comment]
> you need to add Packages:
> 
> ```shell
> yarn add -D @vuepress/plugin-docsearch@next
> ```

THANKS!! It works~
