### ISSUE TITLE
[Feature request] 在md中引用非常见图片格式时，渲染报错

### ISSUE THREAD

**Issue by roiding** [vuepress/vuepress-next#320]
### Description

我的图片都是放在.vuepress/public中，以前在md中我都是直接写生成后的图片路径地址，譬如:/XXX/XXX.jpg
为了写文档时图片也可即时显示，现在参考文档后发现可以写相对地址后，更改为了../.vuepress/XXX/XXX.jpg。并不会产生问题，但有些非常见文件格式，目前遇到了webp、jfif两种。在编译生成时就会出现报错。
还好目前这种图片数据量小，我是自己手动将图片格式转到了jpg
### Proposed Solution

希望相关的图片路径处理逻辑能够兼容这些非常见的图片格式

**Comment by meteorlxy** [comment]
放在 public 目录下的没有必要写相对路径，继续用绝对路径就好了。
