### ISSUE TITLE
Feature request : Store dark mode value in local storage.

### ISSUE THREAD

**Issue by ramesh-dada** [vuepress/vuepress-next#335]
Hello I would like to see a feature in which if someone triggers dark mode then the value should be stored in local storage of the browser that theme = dark. and we can use that from local storage and shift to dark mode if user is using dark.

**Comment by meteorlxy** [comment]
It's a theme-specific behavior. You can implement in your own theme.

Again, please follow the issue template

**Comment by ramesh-dada** [comment]
Sorry Next time I will follow issue template.

**Comment by ramesh-dada** [comment]
@meteorlxy THANK You So much for reopening this 🙏🙏

**Comment by ramesh-dada** [comment]
```
<script>
const btn = document.querySelector(".toggle-dark-button");

const currentTheme = localStorage.getItem("theme");
if (currentTheme == "dark") {
document.querySelector('.toggle-dark-button').click();
}

btn.addEventListener("click", function () {
let theme = "light";
if (document.querySelector('html').classList.contains("dark")) {
    theme = "dark";
  }
  localStorage.setItem("theme", theme);
});
</script>
```
But I am not sure that we can directly use this JS in vue template any ideas?
