### ISSUE TITLE
[Bug report] Build fails with Webpack 5.48.0

### ISSUE THREAD

**Issue by jbroutier** [vuepress/vuepress-next#336]
### Description

Build fails with Webpack 5.48.0, with the following error:

```bash
Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'
```

### Workaround

Pin `webpack` to version 5.47.1 in your package.json.

### Steps to reproduce

1. Setup a basic vuepress project.
2. Run `vuepress dev` command.

- Reproduction link / repo: none

### Expected behavior

Should work.

### Screenshots

none

### Environment info

- Browser: na
- Output of `vuepress info`:

```bash
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 7.74 GB / 15.48 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.6.0 - /usr/bin/node
    Yarn: Not Found
    npm: 7.20.2 - /usr/local/bin/npm
  Utilities:
    Git: 2.25.1 - /usr/bin/git
  Browsers:
    Chrome: Not Found
    Firefox: 90.0
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.23 
    @vuepress/cli:  2.0.0-beta.23 
    @vuepress/client:  2.0.0-beta.23 
    @vuepress/core:  2.0.0-beta.23 
    @vuepress/markdown:  2.0.0-beta.23 
    @vuepress/plugin-active-header-links:  2.0.0-beta.23 
    @vuepress/plugin-back-to-top:  2.0.0-beta.23 
    @vuepress/plugin-container:  2.0.0-beta.23 
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.23 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.23 
    @vuepress/plugin-nprogress:  2.0.0-beta.23 
    @vuepress/plugin-palette:  2.0.0-beta.23 
    @vuepress/plugin-prismjs:  2.0.0-beta.23 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.23 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.23 
    @vuepress/theme-default:  2.0.0-beta.23 
    @vuepress/utils:  2.0.0-beta.23 
    vue:  3.1.5 
    vue-loader:  16.4.0 
    vue-router:  4.0.10 
    vuepress: ^2.0.0-beta.23 => 2.0.0-beta.23 
    vuepress-vite: Not Found
```

**Comment by meteorlxy** [comment]
https://github.com/vuejs/vue-loader/issues/1859

**Comment by meteorlxy** [comment]
Bumping vue-loader to 16.4.1 could fix that problem.

**Comment by selah202133** [comment]
[webpack-cli] Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'
Require stack:
- C:\Users\yamileon\Desktop\practica\node_modules\vue-loader\lib\plugin-webpack5.js
- C:\Users\yamileon\Desktop\practica\node_modules\vue-loader\lib\plugin.js
- C:\Users\yamileon\Desktop\practica\node_modules\vue-loader\lib\index.js
- C:\Users\yamileon\Desktop\practica\node_modules\laravel-mix\src\components\Vue.js
- C:\Users\yamileon\Desktop\practica\node_modules\laravel-mix\src\components\ComponentRegistrar.js
- C:\Users\yamileon\Desktop\practica\node_modules\laravel-mix\src\Mix.js
- C:\Users\yamileon\Desktop\practica\node_modules\laravel-mix\setup\webpack.config.js
- C:\Users\yamileon\Desktop\practica\node_modules\webpack-cli\lib\webpack-cli.js
- C:\Users\yamileon\Desktop\practica\node_modules\webpack-cli\lib\bootstrap.js
- C:\Users\yamileon\Desktop\practica\node_modules\webpack-cli\bin\cli.js
- C:\Users\yamileon\Desktop\practica\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (C:\Users\yamileon\Desktop\practica\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\yamileon\Desktop\practica\node_modules\vue-loader\lib\plugin-webpack5.js:6:42)
    at Module._compile (C:\Users\yamileon\Desktop\practica\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\yamileon\\Desktop\\practica\\node_modules\\vue-loader\\lib\\plugin-webpack5.js',
    'C:\\Users\\yamileon\\Desktop\\practica\\node_modules\\vue-loader\\lib\\plugin.js',
    'C:\\Users\\yamileon\\Desktop\\practica\\node_modules\\vue-loader\\lib\\index.js',
    'C:\\Users\\yamileon\\Desktop\\practica\\node_modules\\laravel-mix\\src\\components\\Vue.js',
    'C:\\Users\\yamileon\\Desktop\\practica\\node_modules\\laravel-mix\\src\\components\\ComponentRegistrar.js',
    'C:\\Users\\yamileon\\Desktop\\practica\\node_modules\\laravel-mix\\src\\Mix.js',
    'C:\\Users\\yamileon\\Desktop\\practica\\node_modules\\laravel-mix\\setup\\webpack.config.js',
    'C:\\Users\\yamileon\\Desktop\\practica\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'C:\\Users\\yamileon\\Desktop\\practica\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'C:\\Users\\yamileon\\Desktop\\practica\\node_modules\\webpack-cli\\bin\\cli.js',
    'C:\\Users\\yamileon\\Desktop\\practica\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `mix`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yamileon\AppData\Roaming\npm-cache\_logs\2021-08-19T13_21_56_198Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yamileon\AppData\Roaming\npm-cache\_logs\2021-08-19T13_21_56_375Z-debug.log
Buenas tengo este error
