### ISSUE TITLE
[Feature request] Sitemap Page request

### ISSUE THREAD

**Issue by ramesh-dada** [vuepress/vuepress-next#337]
I like the vuepress a lot 😁, but in Seo I found a. Issue, I am using head yaml to add meta tags and schema tags in body as they are allowed in body also but what about sitemap the only thing preventing me to migrate. It will be great If sitemap will be included in the core.

**Comment by meteorlxy** [comment]
#277

**Comment by Mister-Hope** [comment]
Updated: for anyone who wants to use sitemap plugin ,the pr plugin is released under `vuepress-plugin-sitemap2`
