### ISSUE TITLE
[Feature request] Allow us to Remove site name from page title 

### ISSUE THREAD

**Issue by ramesh-dada** [vuepress/vuepress-next#338]
I want to remove my site name from every page I don’t want it every where I just want page title
![](https://forum.vuejs.org/uploads/default/original/3X/b/3/b314f9aca91992317f835e200fb4cdd738a8a49e.png)
I want to remove the highlighted part in image It will be great if we can do some configuration in config file.

**Comment by meteorlxy** [comment]
This problem also exists in VuePress v1.

I agree that we should provide a more flexible way to customize the content of `<title>` tag.

**Comment by meteorlxy** [comment]
What about providing a new client API to be called in `clientAppEnhance.ts` ?

For example:

```ts
import {
  defineClientAppEnhance,
  setResolvePageHeadTitle,
} from '@vuepress/client'

export default defineClientAppEnhance(() => {
  // this is the default behavior
  setResolvePageHeadTitle(
    (page, siteLocale) =>
      `${page.title ? `${page.title} | ` : ``}${siteLocale.title}`
  )

  // users can customize this way
  setResolvePageHeadTitle((page) => page.title)
})
```

**Comment by ramesh-dada** [comment]
Super Ultra Pro Thank You, @meteorlxy I see you added option.
Can you please tell me now after this how will I configure my vuepress static site to remove site title.

**Comment by meteorlxy** [comment]
It's not supported now, but you might modify it manually in `clientAppSetup` like this:

```ts
import { defineClientAppSetup, usePageData } from '@vuepress/client'
import { nextTick } from 'vue'
import { useRouter } from 'vue-router'

export default defineClientAppSetup(() => {
  const router = useRouter()
  const page = usePageData()
  const changeTitle = (): void => {
    if (document) {
      nextTick(() => {
        document.title = page.value.title
      })
    }
  }

  changeTitle()
  router.afterEach(() => changeTitle())
})
```

**Comment by ramesh-dada** [comment]
Can you please tell me location of this file after 1 hour I gave up.
