### ISSUE TITLE
[Feature request] Allow us to override default components

### ISSUE THREAD

**Issue by ramesh-dada** [vuepress/vuepress-next#339]
I know about the theme eject but in that case we won't get any updates but I need updates too as well as just for modifying 404 layout we have to eject, So what if vuepress provide us option to override it so that we can receive updates as well as no tention to lose changes, We can do something like Grav CMS, we can make something that you can make a folder customconfig in .vuepress and can override like in custom config /theme/layouts and then our layout so with this option we will get updates.

**Comment by meteorlxy** [comment]
https://vuepress.github.io/advanced/cookbook/extending-a-theme.html

BTW, please follow the issue template

**Comment by ramesh-dada** [comment]
@meteorlxy I am using Vuepress v2.0 beta 23 latest but this is not working, I am using index.js contents are the below,

```
const { path } = require('@vuepress/utils')

module.exports = {
  // inherit the default theme
  extends: '@vuepress/theme-default',

  // override the `404` layout
  layouts: {
    404: path.resolve(__dirname, 'layouts/404.vue'),
  },
}

```
