### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by YunYouJun** [vuepress/vuepress-next#344]
### Description

I try to custom a theme, but failed.

### Steps to reproduce

I follow this: https://v2.vuepress.vuejs.org/advanced/cookbook/extending-a-theme.html#extend-default-theme.

> I think it's easy to re-emerge.

Nothing happened.

So i tried to resolve it.

In `docs/.vuepress/config.js`

```js
const path = require("path");
module.exports = {
  theme: path.resolve(__dirname, "./theme"),
};
```

And then run it. I get this error in devtools.

```txt
[Vue warn]: injection "Symbol(themeLocaleData)" not found. 
  at <Layout> 
  at <Layout> 
  at <AsyncComponentWrapper> 
  at <Vuepress onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy > > 
  at <RouterView> 
  at <VuepressApp>
warn @ runtime-core.esm-bundler.js?5c40:38
```

### Expected behavior

I can preview my custom theme.

### Environment info

`vuepress`: ^2.0.0-beta.23

**Comment by meteorlxy** [comment]
Please provide a reproduce repo

**Comment by ramesh-dada** [comment]
I am also having the same issue, Unable to extend theme's 404 layout.

**Comment by ramesh-dada** [comment]
@meteorlxy Please help regarding this I am trying to extend from 5 hours but IDK what's the problem



```
const { path } = require('@vuepress/utils')
// .vuepress/theme/index.js
module.exports = {
  // inherit the default theme
  extends: '@vuepress/theme-default',

  // override the `404` layout
  layouts: {
    404: path.resolve(__dirname, 'layouts/404.vue'),
  },
}
```

404 File

```
<template>
  <div class="theme-container">
    <div class="theme-default-content">
      <h1>I am CUSTOM 404 PAGE</h1>

      <blockquote>Nothing to see here.</blockquote>

      <RouterLink to="/">
        Let's Go to Home
      </RouterLink>
    </div>
  </div>
</template>
```

**Comment by meteorlxy** [comment]
So could you please provide a reproducing repo, instead of copying and pasting code?

**Comment by ramesh-dada** [comment]
@meteorlxy here it is https://github.com/ramesh-dada/ramesh-dada.github.io
URL : https://ramesh-dada.github.io

**Comment by meteorlxy** [comment]
@ramesh-dada You didn't set the `theme` to your local directory.

https://github.com/ramesh-dada/ramesh-dada.github.io/blob/67dc261874fc8b6fc1c4fd6fda6d5c9a7021268b/.vuepress/config.js#L1-L11

**Comment by ramesh-dada** [comment]
@meteorlxy I did it now

**Comment by meteorlxy** [comment]
@ramesh-dada You even didn't put the `.vuepress` dir into `docs` dir ...

Please check carefully. Don't waste our time.

**Comment by jiazengp** [comment]
It is recommended that everyone go to Github discussions for help first, not issues🤔

**Comment by jiazengp** [comment]
And before that, it’s best to read the document carefully

**Comment by YunYouJun** [comment]
Hello, i think this is a reproduce repo.

> https://github.com/YunYouJun/element-theme-ink

Just clone it, then:

```bash
yarn
yarn build
yarn dev
```

I think I've taken the right approach based on the documentation.

But i get:

```txt
Uncaught (in promise) Error: useThemeLocaleData() is called without provider.
    at useThemeLocaleData (useThemeLocaleData.js:6)
    at useThemeLocaleData (useThemeData.js:3)
    at setup (Layout.vue:32)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7154)
    at setupComponent (runtime-core.esm-bundler.js:7110)
    at mountComponent (runtime-core.esm-bundler.js:5109)
    at processComponent (runtime-core.esm-bundler.js:5084)
    at patch (runtime-core.esm-bundler.js:4690)
    at componentEffect (runtime-core.esm-bundler.js:5221)
```

**Comment by meteorlxy** [comment]
@YunYouJun Please read docs carefully. `extend` has been migrated to `extends`. Thanks a lot.
