### ISSUE TITLE
[Feature request] Search Page

### ISSUE THREAD

**Issue by ramesh-dada** [vuepress/vuepress-next#347]
### Description
It will be better if we can make a indexed based search at /search as OpenSearch requires an additional search page in order to add tab to search in chromium or Mozilla browsers.

### Proposed Solution
Indexed Search page with javascript it will be great if it will be realtime also.
We can also convert our built in search to a search page we will just need to add a search page and a input field maybe will be very easier.

Expecting Something like this
![image](https://user-images.githubusercontent.com/75124237/128179725-2682f6c9-4913-449c-8088-eda21ee133e0.png) 

This type of page can be made easily once we have page contents in search index see https://github.com/vuepress/vuepress-next/issues/348

**Comment by meteorlxy** [comment]
The built-in search is just a light-weighted search for small scale websites.

It's not realistic to search all pages content with a pure front-end solution.
