### ISSUE TITLE
[Feature request] Index page contents also in Search

### ISSUE THREAD

**Issue by ramesh-dada** [vuepress/vuepress-next#348]
### Description
I seen that in the built in search whenever we search it only have indexed the page headings not contents but in algolia if i search page contents then also it gives me accurate results, So it will be great if VuePress in built search will also include contents of the page.

### Proposed Solution
We should include page contents here https://github.com/vuepress/vuepress-next/blob/main/packages/%40vuepress/plugin-search/src/client/components/SearchBox.ts#L137 and It should also highlight the text which is entered in search input like algolia.

**Comment by meteorlxy** [comment]
See https://github.com/vuepress/vuepress-next/issues/347#issuecomment-893378017

**Comment by ramesh-dada** [comment]
Hello I seen that chartjs vuepress site is using this type of search
![image](https://user-images.githubusercontent.com/75124237/128589419-a03e18eb-c322-4d67-91b8-9bb649cff65a.png)
It will be great if it will be present in core and people will no longer need algolia so no complications.

**Comment by meteorlxy** [comment]
Seems that it is supported by https://github.com/z3by/vuepress-plugin-flexsearch.

No need to include all community plugins into core.

**Comment by ramesh-dada** [comment]
hello meteorlxy Thanks a Lot but that developer is offline and maybe not going to update it so what's the procedure to request update for a community plugin?

**Comment by meteorlxy** [comment]
You can fork one and make a plugin yourself. This is open source.

**Comment by ramesh-dada** [comment]
But I don't know how to code very properly I am learning so will you help?

**Comment by Mister-Hope** [comment]
That's your own thing man. Currently I think we should make vuepress2 more stable and moving to have its stable release after Vue3.2

And even if meteorlxy has time, I think plugins like `blog` should be supported first.

At least you have alternatives now.

**Comment by ramesh-dada** [comment]
@Mister-Hope Please 🙏 any link or source to the alternative's

**Comment by Mister-Hope** [comment]
> @Mister-Hope Please 🙏 any link or source to the alternative's 

The algolia should be an alternative.

If you are making docs, you can apply one free.

Even not, algolia still provides free plans and the amount should be enough for small sites.
