### ISSUE TITLE
[Feature request] Search box

### ISSUE THREAD

**Issue by 1148177968** [vuepress/vuepress-next#35]
### Description

It seems that [Search Box](https://vuepress.vuejs.org/theme/default-theme-config.html#search-box) doesn't be supported in vuepress-next, I can't find it the doc and readme. 

### Solution
Support Search box

**Comment by meteorlxy** [comment]
The built-in search feature of vuepress v1 will be extracted into a standalone plugin.

**Comment by Hooper93** [comment]
But there isn't have a document of docsearch plugin /sad-face

**Comment by meteorlxy** [comment]
@Hooper93 On the way. You can checkout the setup of our docs for now.

https://github.com/vuepress/vuepress-next/blob/e552dec8e107b66196515c8245b5385de85e3dc3/docs/.vuepress/config.ts#L91-L105

**Comment by meteorlxy** [comment]
The documentation of docsearch plugin is available now:

https://vuepress.github.io/reference/plugin/docsearch.html

**Comment by mtslzr** [comment]
Any chance there is an option that doesn't require letting a third-party scrape our documentation?
