### ISSUE TITLE
[Feature request] Different Pages and Image Indexing

### ISSUE THREAD

**Issue by ramesh-dada** [vuepress/vuepress-next#353]
### Description
1. I tested out the sitemap extension good work but there is a must have feature that sitemap should be divided into different pages after a pages limit see how properly it's[ divided in WP](https://wordpress.org/plugins/sitemap-index-1.xml) 

2. Index Image also automatically get the first image and it's data.
```
<url>
<loc>https://example.com/test.html</loc>
<lastmod>2021-06-20T14:24:12+00:00</lastmod>
<image:image>
<image:loc>https://example.com/image.png</image:loc>
 <image:title><![CDATA[Example]]></image:title>
<image:caption><![CDATA[Example]]></image:caption>
</image:image>
</url>

```

**Comment by meteorlxy** [comment]
The sitemap plugin has not been merged yet. For now you'd better leave a comment to #277

**Comment by ramesh-dada** [comment]
ok I think @Mister-Hope will take a look

**Comment by Mister-Hope** [comment]
Hi there, I would like to share some ideas. 

---

The second one is good, and I will support it after the sitemap plugin is merged as an  enhancement.

But actually this feature is not important at all.

### Why?

Please notice not all the search engines are supporting that. Most search engines are just regarding sitemps as url maps, and they claw the html content themself, Google is just doing that, so if you are using an seo plugin like [@mr-hope/vuepress-plugin-seo](https://vuepress-theme-hope.github.io/seo/), infomation in `<meta>` tags are much more important and do have a higher preority than sitemaps info. Which means as long as you are providing all the information you wanna provide to search engine in meta tags, you should better not put it in sitemaps for size consideration.

---

For the first one, it's definately unneeded with VuePress.

## Why?

> You can provide multiple Sitemap files, but each Sitemap file that you provide must have no more than 50,000 URLs and must be no larger than 50MB (52,428,800 bytes). 

It's unpossible for a VuePress project to reach this limit. In my test, a over 1000 pages project already fails on Github Actions using vuepress2 (becuase action machines has 8 GB rams). So the time and memory cost of a project with more than 50000 pages in vuepress is unpossible. So we should leave things simple. One single sitemap files should be enough in most situations.

**Comment by ramesh-dada** [comment]
Hello @Mister-Hope Thanks for the reply ok then I no longer need first one but still need second one as I am using VuePress as a site other than documentation, However you are also right that this feature is not that useful so if you want feel free to close this issue.

**Comment by Mister-Hope** [comment]
> Hello @Mister-Hope Thanks for the reply ok then I no longer need first one but still need second one as I am using VuePress as a site other than documentation, However you are also right that this feature is not that useful so if you want feel free to close this issue.

Have you check what search engines are actually reading `<image:image>`? I am pretty sure google do not support it, because I made some investigation when I am building sitemaps plugin for v1 last year. Why do you actully needs this none standard item?

- If you care about SEO. you will probaly need a plugin like https://vuepress-theme-hope.github.io/seo/
- If you are using sitemap as feeds, you should probably provide a standard feed using plugins like https://vuepress-theme-hope.github.io/feed/

Actually I am not getting why images are needed in sitemaps. They are just maps describing urls for search engines telling them which pages they need to visit and claw.

**Comment by Mister-Hope** [comment]
Oh sorry, you need to sperate sitemaps?

If you are helding large sites, you should probably sperate them to several VuePress projects, so that you won't need to rebuild them all when you have little changes, so you can just generate a sitemap group by yourself referencing to each sitemap files in your vuepress projects.

**Comment by ramesh-dada** [comment]
> Oh sorry, you need to sperate sitemaps?
> 
> If you are holding large sites, you should probably sperate them to several VuePress projects, so that you won't need to rebuild them all when you have little changes, so you can just generate a sitemap group by yourself referencing to each sitemap files in your vuepress projects.

Sorry I dont need images feature I just need separate sitemap features I am not using different vuepress installations as my site is once loaded user will have to navigate to several pages and I don't want to reload the browser page with normal link that's the reason.

**Comment by Mister-Hope** [comment]
I am curious how much pages does your site have?

**Comment by ramesh-dada** [comment]
> I am curious how much pages does your site have?

For now it's 40 - 60 only but as it's a tutorial type website it will be having too much pages category and different things.

**Comment by Mister-Hope** [comment]
I am not sure if you understand what I am expressing.

You have to rebuild every time your content change, and for a 1000 pages site, the time is already around 10min. You will absolutely take more than 6 hours to build a site ( and GBs output) if your site is around 5w pages. Then vuepress is probably not the tool you should use. You should use tools based on server with database, where each your page is stored in database, and the server generate pages for you if you do needs lots of pages.

You will never reach a single file limit if you are in normal condition usage of VuePress.

**Comment by ramesh-dada** [comment]
I was using wordpress and many other things but I don't like the delay in page load in static site it's instant and in with database server generates site and then it works I like vuepress too much so I am planning to use it and do you mean 30 gb ram or rom ?? Also I am closing this issue I think that no one will make vuepress site like me

**Comment by Mister-Hope** [comment]
RAM, I am not tested that much, but 700 pages is already taking 7.2GB ln Ubuntu 20

**Comment by ramesh-dada** [comment]
> RAM, I am not tested that much, but 700 pages is already taking 7.2GB ln Ubuntu 20
> 
> (790 pages with lots of content BTW)

OK Then A bit off topic but do you know something that has theme similar to vuepress and navigates to different pages in realtime and it can be easily used without this problems that we are having and it can handle more than 50000 pages
