### ISSUE TITLE
[Bug report] register-components fail, [Vue warn]: Failed to resolve component: FooBar 

### ISSUE THREAD

**Issue by phpiscute** [vuepress/vuepress-next#357]
### Description

<img width="1775" alt="image" src="https://user-images.githubusercontent.com/87626576/128601223-73457e58-a8f0-4186-bfb1-312ae2e26d90.png">

### Steps to reproduce

- config.js
<img width="860" alt="image" src="https://user-images.githubusercontent.com/87626576/128601132-a9d05b05-7963-43b3-9f0e-ec4c8ede40ee.png">

- readme.md
<img width="623" alt="image" src="https://user-images.githubusercontent.com/87626576/128601102-b29a2097-beb2-4539-ac4b-44cdd8d55c7a.png">

- foobar.vue
<img width="778" alt="image" src="https://user-images.githubusercontent.com/87626576/128601197-8c991afb-0461-49db-8e47-c21a4a4b0bb9.png">

- Reproduction link / repo:

### Expected behavior

can render content in vue

### Environment info

- Browser: Chrome: 92.0.4515.131
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.5.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.20.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.1
  npmPackages:
    @vuepress/core:  2.0.0-beta.22
    @vuepress/theme-default:  2.0.0-beta.22
    vuepress: ^2.0.0-beta.22 => 2.0.0-beta.22
  npmGlobalPackages:
    vuepress: 1.8.2
```

**Comment by meteorlxy** [comment]
According to the output of `vuepress info`, you didn't install this plugin

**Comment by phpiscute** [comment]
thx

it is ok after install specify version.
```bash
npm i @vuepress/plugin-register-components@2.0.0-beta.23
```

**Comment by Jelledb** [comment]
Nice, the above fixed the same issue for me.

Maybe a tip for the maintainers: explicitly mention to install @2.0.0-beta.xxx. I just did a good ol' `yarn add ...` and it installed a `1.9.x` version for me.

**Comment by meteorlxy** [comment]
@Jelledb We already put `@next` tag in the docs:

![image](https://user-images.githubusercontent.com/18205362/149474646-6b2e7371-c4e6-4df4-99e1-794e75151cec.png)

**Comment by Jelledb** [comment]
> @Jelledb We already put `@next` tag in the docs:
> 
> ![image](https://user-images.githubusercontent.com/18205362/149474646-6b2e7371-c4e6-4df4-99e1-794e75151cec.png)

My bad. I just looked at the migration.md and assumed I can simply `yarn add ...`
