### ISSUE TITLE
[Feature request] Allow us to remove Meta Name Generator

### ISSUE THREAD

**Issue by ramesh-dada** [vuepress/vuepress-next#358]
### Description
`<meta name="generator" content="VuePress 2.0.0-beta.23">`
Sometimes I want to remove the meta generator as per the good customizations and other things I am proud to be a user of VuePress but I don't want that my audience sees it.

### Proposed Solution
A boolean so that the user can easily enable/disable it.

**Comment by ramesh-dada** [comment]
@meteorlxy I seen that you made some changes to code thanks a lot, Can you also make a new release? 

Also what should we add to config js to modify it?

**Comment by ramesh-dada** [comment]
@meteorlxy Now can you tell me what to do to remove this? As beta 23 is rolled out.

**Comment by meteorlxy** [comment]
Use you own template
