### ISSUE TITLE
[Bug report] CSS highlighting issue in chromium based browsers

### ISSUE THREAD

**Issue by ramesh-dada** [vuepress/vuepress-next#359]
### Description
What's the problem with this heading whenever I go to link that opens in a new tab but it's a in page link then this type of highlighting happens see the below image, I try to inspect it but it gets hidden when I open dev tools.
![JbnUgjctqc](https://user-images.githubusercontent.com/75124237/128628870-89868c0e-a695-416c-8272-e14bbc2f5157.gif)

### Steps to reproduce

- Simply go to the below link or right click and open it in new tab.
- https://v2.vuepress.vuejs.org/reference/plugin/docsearch.html#get-search-index

### Reproduction link / repo:
https://v2.vuepress.vuejs.org/reference/plugin/docsearch.html#get-search-index

### Expected behavior
It should not show that black border.

### Screenshots
![JbnUgjctqc](https://user-images.githubusercontent.com/75124237/128628870-89868c0e-a695-416c-8272-e14bbc2f5157.gif)

**Comment by meteorlxy** [comment]
Caused by `:focus-visible`, not sure if it should be considered as a bug 🤔

**Comment by ramesh-dada** [comment]
> In reply to @meteorlxy Caused by `:focus-visible`, not sure if it should be considered as a bug 🤔

Can I have css to disable it?

**Comment by jiazengp** [comment]
Maybe the following code can help you
``` css
:focus:not(:focus-visible) {
    outline: 0;
}
```

**Comment by ramesh-dada** [comment]
> In reply to @jiazengp 
> Maybe the following code can help you🤔
> 
> ```css
> :focus:not(:focus-visible) {
>     outline: 0;
> }
> ```

No It doesn't seems to work

**Comment by dtbj** [comment]
> @ramesh-dada  No It doesn't seems to work

This will work, I was also facing the same issue:

```
h1:focus, h2:focus, h3:focus, h4:focus, h5:focus, h6:focus {
outline: none !important;
}
```
