### ISSUE TITLE
[Bug report]When I add a plug-in in config.js, an error will be reported

### ISSUE THREAD

**Issue by qsyyke** [vuepress/vuepress-next#360]
Error message
```js
TypeError: plugins.reduce is not a function
    at Object.resolvePluginsFromConfig (E:\vue\blog\node_modules\@vuepress\core\lib\app\resolvePluginsF
romConfig.js:13:20)
    at Object.createBaseApp (E:\vue\blog\node_modules\@vuepress\core\lib\app\createBaseApp.js:47:48)
    at Object.createDevApp (E:\vue\blog\node_modules\@vuepress\core\lib\app\createDevApp.js:10:33)
    at dev (E:\vue\blog\node_modules\vuepress\node_modules\@vuepress\cli\lib\commands\dev\createDev.js:
27:28)
```
I want to use the vssue plugin in vuepress, but when I configure it in config.js, only the array method can be used to start successfully. If the object method is used, this error will occur

```js
module.exports = {
    plugins: {
            '@vssue/vuepress-plugin-vssue': {
                platform: 'github',
                clientId: '9566158....',
                clientSecret: '28787d76277...',
                owner: '',
                repo: '',
                
            },
        },
}
```

I use this method to report an error

**Comment by ramesh-dada** [comment]
This is because that the vssue plugin is not yet compatible with the latest version of VuePress v2.0 you can wait for the author to update it or If you are a coder you can fork repository and update it.

**Comment by meteorlxy** [comment]
What @ramesh-dada said is correct. Also, the **Object style** config is not supported in v2.

**Comment by qsyyke** [comment]
@ramesh-dada thanks very much

**Comment by qsyyke** [comment]
@meteorlxy @ramesh-dada I looked at the vuepress documentation and saw the plug-in where the object can be used. I thought something went wrong, thank you very much
