### ISSUE TITLE
[Bug report] TypeError: generateSW is not a function

### ISSUE THREAD

**Issue by Assone** [vuepress/vuepress-next#361]
### Description

build fail after use pwa plugins. after I printed it, I found out that generateSW was an object .

`console.log(111, generateSW) // 111 { generateSW: [AsyncFunction: generateSW] }`

```bash
$ vuepress build docs
info Initializing VuePress and preparing data...
✔ Compiling with webpack - done
✔ Rendering pages - done
✖ Generating service worker - failed
error error in hook onGenerated from @vuepress/plugin-pwa
TypeError: generateSW is not a function
    at Object.generateServiceWorker (/Users/reset0/Project/Note/node_modules/@vuepress/plugin-pwa/lib/node/generateServiceWorker.js:29:32)
    at /Users/reset0/Project/Note/node_modules/@vuepress/plugin-pwa/lib/node/pwaPlugin.js:19:110
    at /Users/reset0/Project/Note/node_modules/@vuepress/utils/lib/withSpinner.js:12:30
    at Object.onGenerated [as hook] (/Users/reset0/Project/Note/node_modules/@vuepress/plugin-pwa/lib/node/pwaPlugin.js:19:79)
    at Object.process (/Users/reset0/Project/Note/node_modules/@vuepress/core/lib/pluginApi/createHookQueue.js:26:48)
    at /Users/reset0/Project/Note/node_modules/@vuepress/cli/lib/commands/build/createBuild.js:51:43
error Command failed with exit code 1.
```

### Steps to reproduce

1. yarn add -D @vuepress/plugin-pwa@next
2. in config.ts add
```javascript
plugins: ["@vuepress/pwa",]
```
3. yarn docs:build

- Reproduction link / repo: https://github.com/Assone/Note/blob/main/docs/.vuepress/config/plugins.ts

### Expected behavior

build success.

### Screenshots

![image](https://user-images.githubusercontent.com/14324389/128634368-274d8ebc-b6e2-4e3b-9cdd-dd93d1f7806d.png)

### Environment info

- Browser:
- Output of `vuepress info`:

  System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
    Memory: 29.32 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /var/folders/s0/b7yx70dj0bgbf3lbbjmw1zwm0000gn/T/yarn--1628431285776-0.5154097858107565/node
    Yarn: 1.22.10 - /var/folders/s0/b7yx70dj0bgbf3lbbjmw1zwm0000gn/T/yarn--1628431285776-0.5154097858107565/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Utilities:
    Git: 2.31.1 - /usr/local/bin/git
  Browsers:
    Chrome: 92.0.4515.131
    Edge: 90.0.818.41
    Firefox: Not Found
    Safari: 14.1.2
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.23 
    @vuepress/bundler-webpack:  2.0.0-beta.23 
    @vuepress/cli:  2.0.0-beta.23 
    @vuepress/client:  2.0.0-beta.23 
    @vuepress/core:  2.0.0-beta.23 
    @vuepress/markdown:  2.0.0-beta.23 
    @vuepress/plugin-active-header-links:  2.0.0-beta.23 
    @vuepress/plugin-back-to-top:  2.0.0-beta.23 
    @vuepress/plugin-container:  2.0.0-beta.23 
    @vuepress/plugin-debug: ^2.0.0-beta.23 => 2.0.0-beta.23 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.23 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.23 
    @vuepress/plugin-nprogress:  2.0.0-beta.23 
    @vuepress/plugin-palette:  2.0.0-beta.23 
    @vuepress/plugin-prismjs:  2.0.0-beta.23 
    @vuepress/plugin-pwa: ^2.0.0-beta.23 => 2.0.0-beta.23 
    @vuepress/plugin-pwa-popup: ^2.0.0-beta.23 => 2.0.0-beta.23 
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: ^2.0.0-beta.23 => 2.0.0-beta.23 
    @vuepress/plugin-theme-data:  2.0.0-beta.23 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.23 
    @vuepress/theme-default:  2.0.0-beta.23 
    @vuepress/utils:  2.0.0-beta.23 
    vue:  3.1.5 
    vue-loader:  16.5.0 
    vue-router:  4.0.10 
    vuepress: ^2.0.0-beta.23 => 2.0.0-beta.23 
    vuepress-vite: ^2.0.0-beta.23 => 2.0.0-beta.23

**Comment by meteorlxy** [comment]
Should be caused by some internal breaking changes of `workbox-build@6.2.0`.

As a workaround, you can manually fix the version of `workbox-build` to `6.1.5`

**Comment by Assone** [comment]
> Should be caused by some internal breaking changes of `workbox-build@6.2.0`.
> 
> As a workaround, you can manually pin the version of `workbox-build` to `6.1.5`

Still not working

**Comment by ramesh-dada** [comment]
@meteorlxy Yes it's still showing same erorr I updated the plugin.
