### ISSUE TITLE
[Bug report] Vuepress v2 search 与 back-to-top 插件问题

### ISSUE THREAD

**Issue by Witee** [vuepress/vuepress-next#369]
### Description

@vuepress/plugin-search 插件无法显示
@vuepress/plugin-back-to-top 插件无法禁用

### Steps to reproduce

- Reproduction link / repo:

https://codesandbox.io/s/cocky-butterfly-do34k?file=/vuepress.config.js

package.json
```json
{
  "name": "vuepress",
  "version": "1.0.0",
  "scripts": {
    "start": "vuepress dev docs",
    "build": "vuepress build docs"
  },
  "dependencies": {
    "@vue/component-compiler-utils": "^3.2.2",
    "@vuepress/plugin-search": "^1.8.2",
    "@vuepress/shared-utils": "^1.8.2",
    "vuepress": "^2.0.0-beta.23"
  },
  "keywords": [],
  "description": ""
}
```

vuepress.config.js

```js
module.exports = {
  lang: "zh-CN",
  title: "Docs",
  theme: "@vuepress/default",
  themeConfig: {
    darkMode: false
  },
  plugins: [
    // 无法禁用 plugin-back-to-top
    { "@vuepress/plugin-back-to-top": false },
    // 搜索框无法显示
    [
      "@vuepress/plugin-search",
      {
        locales: {
          "/": {
            placeholder: "Search"
          },
          "/zh/": {
            placeholder: "搜索"
          }
        }
      }
    ]
  ]
};

```

点击右侧+号新建终端,  执行`npm start`, 会提示打开窗口, 然后点击使用新窗口按钮, 全屏显示.

![image](https://user-images.githubusercontent.com/3724622/128802425-6f83fe08-bc2a-4d93-8abd-84a69e66fbf0.png)

有以下两个问题:
1. 没有找到搜索框
2. back-to-top 无法禁用

![image](https://user-images.githubusercontent.com/3724622/128802569-3b3fb8ad-2f2f-498c-8f43-f4132702d8c6.png)

### Expected behavior

希望可以显示搜索框, 可以禁用 back-to-top.

**Comment by jiazengp** [comment]
你好，你可以参照下面代码禁用 `back-to-top` 插件或者其他已经集成到默认主题中的插件。

``` ts
// config.ts
import { defineUserConfig } from '@vuepress/cli'

import type { DefaultThemeOptions } from 'vuepress'

/**
 * @description Vuepress2 config
 * @link https://v2.vuepress.vuejs.org/reference/config.html
 */
module.exports = defineUserConfig<DefaultThemeOptions>({

  /**
   * @description Vuepress2 theme config
   * @link https://v2.vuepress.vuejs.org/reference/theme-api.html
   */
  themeConfig: {
    themePlugins: {
      backToTop: false,
    },
})
```

**Comment by jiazengp** [comment]
> ## Bug report
> ### Description
> @vuepress/plugin-search 插件无法显示
> @vuepress/plugin-back-to-top 插件无法禁用
> 
> ### Steps to reproduce
> * Reproduction link / repo:
> 
> https://codesandbox.io/s/cocky-butterfly-do34k?file=/vuepress.config.js
> 
> package.json
> 
> ```json
> {
>   "name": "vuepress",
>   "version": "1.0.0",
>   "scripts": {
>     "start": "vuepress dev docs",
>     "build": "vuepress build docs"
>   },
>   "dependencies": {
>     "@vue/component-compiler-utils": "^3.2.2",
>     "@vuepress/plugin-search": "^1.8.2",
>     "@vuepress/shared-utils": "^1.8.2",
>     "vuepress": "^2.0.0-beta.23"
>   },
>   "keywords": [],
>   "description": ""
> }
> ```
> 
> vuepress.config.js
> 
> ```js
> module.exports = {
>   lang: "zh-CN",
>   title: "Docs",
>   theme: "@vuepress/default",
>   themeConfig: {
>     darkMode: false
>   },
>   plugins: [
>     // 无法禁用 plugin-back-to-top
>     { "@vuepress/plugin-back-to-top": false },
>     // 搜索框无法显示
>     [
>       "@vuepress/plugin-search",
>       {
>         locales: {
>           "/": {
>             placeholder: "Search"
>           },
>           "/zh/": {
>             placeholder: "搜索"
>           }
>         }
>       }
>     ]
>   ]
> };
> ```
> 
> 点击右侧+号新建终端, 执行, 会提示打开窗口, 然后点击使用新窗口按钮, 全屏显示.`npm start`
> 
> ![image](https://user-images.githubusercontent.com/3724622/128802425-6f83fe08-bc2a-4d93-8abd-84a69e66fbf0.png)
> 
> 有以下两个问题:
> 
> 1. 没有找到搜索框
> 2. back-to-top 无法禁用
> 
> ![image](https://user-images.githubusercontent.com/3724622/128802569-3b3fb8ad-2f2f-498c-8f43-f4132702d8c6.png)
> 
> ### Expected behavior
> 希望可以显示搜索框, 可以禁用 back-to-top.

vuepress1.x 的插件不兼容 vuepress2，请检查你的依赖。

**Comment by Witee** [comment]
> > ## Bug report
> > ### Description
> > @vuepress/plugin-search 插件无法显示
> > @vuepress/plugin-back-to-top 插件无法禁用
> > ### Steps to reproduce
> > 
> > * Reproduction link / repo:
> > 
> > https://codesandbox.io/s/cocky-butterfly-do34k?file=/vuepress.config.js
> > package.json
> > ```json
> > {
> >   "name": "vuepress",
> >   "version": "1.0.0",
> >   "scripts": {
> >     "start": "vuepress dev docs",
> >     "build": "vuepress build docs"
> >   },
> >   "dependencies": {
> >     "@vue/component-compiler-utils": "^3.2.2",
> >     "@vuepress/plugin-search": "^1.8.2",
> >     "@vuepress/shared-utils": "^1.8.2",
> >     "vuepress": "^2.0.0-beta.23"
> >   },
> >   "keywords": [],
> >   "description": ""
> > }
> > ```
> 
> vuepress1.x 的插件不兼容 vuepress2，请检查你的依赖。

非常感谢, 问题解决了!
