### ISSUE TITLE
[Feature request] PWA offline page

### ISSUE THREAD

**Issue by ramesh-dada** [vuepress/vuepress-next#370]
### Description
I want something like [SuperPWA](https://superpwa.com/) WordPress plugin it asks us to add url of an [offline page](https://superpwa.com/superpwa-sw.js) that if the user is offline then as a fallback that page is shown and as soon as user enables his internet connection.

### Proposed Solution
We can use something like this in service worker
`const offlinePage='https://example.com/offline';`

**Comment by meteorlxy** [comment]
The pwa plugin accepts all options of `workbox-build`. You can make your own customization.
