### ISSUE TITLE
vuepress2.0的2.0.0-beta23版本，sidebarDepth设置无效

### ISSUE THREAD

**Issue by prayjourney** [vuepress/vuepress-next#375]
vuepress2.0的2.0.0-beta23版本，提取标题无效，下图是h2,h2的标题无法在左侧的侧边栏之中提出来，只有h1级别标题。
![image](https://user-images.githubusercontent.com/15311937/129159224-fcb199ed-4d6e-4020-9db9-abb94a815b57.png)
![image](https://user-images.githubusercontent.com/15311937/129159306-993b9ee7-5837-4598-84f1-dc259ad14d60.png)

**Comment by meteorlxy** [comment]
机器人有问题，先 lock 之后就没法评论了 🤔

**Comment by Xyuan-abs** [comment]
@meteorlxy  v2.0.0-beta.27 也有这个问题，有解决方法了吗

**Comment by prayjourney** [comment]
我已收到您的来信，谢谢！祝您生活愉快！
