### ISSUE TITLE
[Feature request] clientAppEnhance.js can't install any plugins on app instance.

### ISSUE THREAD

**Issue by Hooper93** [vuepress/vuepress-next#39]
### Description

enhanceApp.js, I can install `ElementUI` by 

```js
export default ({ Vue, options, router }) => {
  Vue.use(Element);
};
```

But I can't use `Vue.install` at this time. **And it seems like my clientAppEnhance.js doesn't work, I can't console.log or alert what you supported in it, this function seems not to be executed.**

Please add any docs on clientAppEnhance~

**Comment by meteorlxy** [comment]
1. The conventional file name has changed to `clientAppEnhance.js` / `clientAppEnhance.ts`


2. VuePress 2 is built on Vue 3, so you need to use `app.use`, etc.

https://github.com/vuepress/vuepress-next/blob/e552dec8e107b66196515c8245b5385de85e3dc3/packages/%40vuepress/client/src/types/clientAppEnhance.ts#L5-L9

**Comment by Hooper93** [comment]
I saw the way to solve this problem on the theme-default:

https://github.com/vuepress/vuepress-next/blob/f490b44008d7d52fdc135e1654fc1361e5ea7be3/packages/%40vuepress/theme-default/src/index.ts#L26

I set `clientAppEnhanceFiles` propty at `.vuepress/theme`, and all done.

```js
module.exports = {
    name: '@vuepress/theme-hooperui',
    clientAppEnhanceFiles: path.resolve(__dirname, './clientAppEnhance.js'),
}
```

**So the conclusion is that you must set `clientAppEnhanceFiles` on your index.{js|ts}, or clientAppEnhanceFiles.js will not be executed**

**Comment by meteorlxy** [comment]
For themes, you have to set it explicitly.

For users, the `.vuepress/clientAppEnhance.js` will be autoly load.

**Comment by Hooper93** [comment]
OK, thank you!
