### ISSUE TITLE
[Feature request] Allow us to run Production server without building static files

### ISSUE THREAD

**Issue by ramesh-dada** [vuepress/vuepress-next#391]
### Description
It will be great if there will be option to run production server like dev server in production server, we won't have to generate static files, we can serve page from server I mean Dynamic site, I know vuepress is static site generator but if we are having 50,000 or more than 50,000 pages then it's really very hard to run vuepress build as it requires too much RAM, @Mister-Hope told me that 700 pages takes 7.2 GB of Ram in ubuntu.

### Proposed Solution
Something like Dev server without hot reloading and pwa generation something like WordPress.

**Comment by Mister-Hope** [comment]
You can just host a devServer on your server.

![Screenshot_20210817-122811.jpg](https://user-images.githubusercontent.com/33315834/129663810-66f05426-8110-45eb-9154-385b32ba5f6b.jpg)

![Screenshot_20210817-122818.jpg](https://user-images.githubusercontent.com/33315834/129663800-ae8ac2ec-1027-4c80-a4ee-6eacdb889325.jpg)

Your request is probably out of scope with VuePress design.

**Comment by ramesh-dada** [comment]
OK I agree with you but If I am hosting dev server then heading's doesn't scroll and there is no page contents in source so a big loss in SEO.

**Comment by ramesh-dada** [comment]
@meteorlxy Any ideas will it be easy or hard ?

**Comment by meteorlxy** [comment]
I think it's possible to make a SSR server, but it would definitely have low priority

**Comment by meteorlxy** [comment]
Also, you'll still need to "build static files" as you are going to use in production mode.

**Comment by meteorlxy** [comment]
Thus, a "Production server without building static files" is not a good idea, and won't be officially supported. You can use dev-server at your own risk, you create a package yourself to support that.
