### ISSUE TITLE
[Bug report]Build fails when I used 'warningJs' in my project

### ISSUE THREAD

**Issue by coder666666** [vuepress/vuepress-next#392]
### Description
Using warningJs in a vuepress project will fail to build because the constant `__DEV__` in vuepress conflicts with the variable defined in warningJs

<img width="1387" alt="企业微信截图_53ac997c-fe42-4c4e-8da1-4d4765b841be" src="https://user-images.githubusercontent.com/49853519/129688617-3a3945ca-2da0-4925-a351-b7277c7a567b.png">

### Steps to reproduce

Using "ant-design-vue" in vuepress

- Reproduction link / repo:
@https://codesandbox.io/s/vuepress-next-kvwj5?file=/package.json
### Expected behavior
Building successfully

### Environment info
@https://codesandbox.io/s/vuepress-next-kvwj5?file=/package.json
- Browser:
- Output of `vuepress info`:
```bash
# Paste output of `vuepress info` here
```

**Comment by meteorlxy** [comment]
Oops, an unfortunate coincidence.

You can consider manually patching the source file before running VuePress

**Comment by meteorlxy** [comment]
Maybe we could use `__VUEPRESS_DEV__` to try to avoid this kind of conflicts 🤔

**Comment by coder666666** [comment]
Thanks very much!
