### ISSUE TITLE
[Feature request] sidebar support collapsable feature

### ISSUE THREAD

**Issue by jarvis-tang** [vuepress/vuepress-next#397]
### Description

My scenario is like this. My product is also open source software. The documentation involves more than 50 data tables and more than 100 API interfaces. With such a large number, the sidebar is very long, so I perform data tables and API documents. In this way, the sidebar is very refreshing, and there are not too many lists, which affects the look and feel.

### Proposed Solution

Sidebar groups are collapsable by default. Feature reference v1 collapsable
[https://vuepress.vuejs.org/theme/default-theme-config.html#sidebar-groups](https://vuepress.vuejs.org/theme/default-theme-config.html#sidebar-groups)

**Comment by Lemmingh** [comment]
It would be great if we can control it with fine granularity:

```typescript
export const enum GroupCollapseAvailability {
    /**
     * (Default availability) The group is always open.
     */
    AlwaysOpen = 0,

    /**
     * Collapsible. The group is collapsed by default.
     */
    CollapsedByDefault = 1,

    /**
     * Collapsible. The group is open by default.
     */
    OpenByDefault = 2,
}

export interface NavGroup<T> extends NavItem {
    isCollapsible: GroupCollapseAvailability;
    children: T[];
}
```

This should be more convenient than v1's `collapsable` and `initialOpenGroupIndex`:

```jsonc
{
    "text": "Group",
    "isCollapsible": 2,
    "children": ["/"]
}
```

**Comment by Aixzk** [comment]
I've been looking for the collaspable sidebar group for days until I found that it's only exist in VuePress 1.0. :(

**Comment by 0biWanKenobi** [comment]
Currently creating a very large documentation, really really need this!
