### ISSUE TITLE
[Bug report] Why is the introduction of local search invalid

### ISSUE THREAD

**Issue by jiangxiaowei0520** [vuepress/vuepress-next#403]
### Description

In my case, my document intends to reference the local search function, but there is no response after following the instructions in the document

### Steps to reproduce

![image](https://user-images.githubusercontent.com/60648068/130579919-3a25d236-30f7-4a69-8a81-f92d3dca981d.png)

![image](https://user-images.githubusercontent.com/60648068/130579993-d8b0b226-6520-4717-9513-5060dea58bce.png)

**Comment by jiazengp** [comment]
Please read docs carefully
Please check your dependencies
Please provide a reproduce repo, and provide vuepress info
