### ISSUE TITLE
[Bug report] use bundlerConfig.chainWebpack change publicPath not work

### ISSUE THREAD

**Issue by falstack** [vuepress/vuepress-next#413]
### Description

``` ts
import { defineUserConfig } from 'vuepress'
import type { DefaultThemeOptions,  } from 'vuepress'


export default defineUserConfig<DefaultThemeOptions>({
    bundlerConfig: {
      chainWebpack: (config) => {
        // next line not work
        config.output.publicPath = '//cdn.jsdelivr.net/gh/falstack/falstack.github.io@gh-pages/'
      }
    }
})
```

### Steps to reproduce

- Reproduction link / repo: https://github.com/falstack/falstack.github.io

### Expected behavior

`config.output.publicPath` can change assets baseUrl

### Environment info

```bash
> vuepress info


  System:
    OS: macOS 11.5.1
    CPU: (8) arm64 Apple M1
    Memory: 102.08 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.5/bin/yarn
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Utilities:
    Git: 2.30.1 - /usr/bin/git
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.2
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.24
    @vuepress/cli:  2.0.0-beta.24
    @vuepress/client:  2.0.0-beta.24
    @vuepress/core:  2.0.0-beta.24
    @vuepress/markdown:  2.0.0-beta.24
    @vuepress/plugin-active-header-links:  2.0.0-beta.24
    @vuepress/plugin-back-to-top:  2.0.0-beta.24
    @vuepress/plugin-container:  2.0.0-beta.24
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.24
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.24
    @vuepress/plugin-nprogress:  2.0.0-beta.24
    @vuepress/plugin-palette:  2.0.0-beta.24
    @vuepress/plugin-prismjs:  2.0.0-beta.24
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki:  2.0.0-beta.24
    @vuepress/plugin-theme-data:  2.0.0-beta.24
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.24
    @vuepress/theme-default:  2.0.0-beta.24
    @vuepress/utils:  2.0.0-beta.24
    vue:  3.2.6
    vue-loader:  16.5.0
    vue-router:  4.0.11
    vuepress: ^2.0.0-beta.24 => 2.0.0-beta.24
    vuepress-vite: Not Found
```

**Comment by falstack** [comment]
@meteorlxy

**Comment by weiyie** [comment]
> ## Bug report
> ### Description
> ```ts
> import { defineUserConfig } from 'vuepress'
> import type { DefaultThemeOptions,  } from 'vuepress'
> 
> 
> export default defineUserConfig<DefaultThemeOptions>({
>     bundlerConfig: {
>       chainWebpack: (config) => {
>         // next line not work
>         config.output.publicPath = '//cdn.jsdelivr.net/gh/falstack/falstack.github.io@gh-pages/'
>       }
>     }
> })
> ```
> 
> ### Steps to reproduce
> * Reproduction link / repo: https://github.com/falstack/falstack.github.io
> 
> ### Expected behavior
> `config.output.publicPath` can change assets baseUrl
> 
> ### Screenshots
> ### Environment info
> ```shell
> > vuepress info
> 
> 
>   System:
>     OS: macOS 11.5.1
>     CPU: (8) arm64 Apple M1
>     Memory: 102.08 MB / 8.00 GB
>     Shell: 5.8 - /bin/zsh
>   Binaries:
>     Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
>     Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.5/bin/yarn
>     npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
>   Utilities:
>     Git: 2.30.1 - /usr/bin/git
>   Browsers:
>     Chrome: 92.0.4515.159
>     Edge: Not Found
>     Firefox: Not Found
>     Safari: 14.1.2
>   npmPackages:
>     @vuepress/bundler-vite: Not Found
>     @vuepress/bundler-webpack:  2.0.0-beta.24
>     @vuepress/cli:  2.0.0-beta.24
>     @vuepress/client:  2.0.0-beta.24
>     @vuepress/core:  2.0.0-beta.24
>     @vuepress/markdown:  2.0.0-beta.24
>     @vuepress/plugin-active-header-links:  2.0.0-beta.24
>     @vuepress/plugin-back-to-top:  2.0.0-beta.24
>     @vuepress/plugin-container:  2.0.0-beta.24
>     @vuepress/plugin-debug: Not Found
>     @vuepress/plugin-docsearch: Not Found
>     @vuepress/plugin-git:  2.0.0-beta.24
>     @vuepress/plugin-google-analytics: Not Found
>     @vuepress/plugin-medium-zoom:  2.0.0-beta.24
>     @vuepress/plugin-nprogress:  2.0.0-beta.24
>     @vuepress/plugin-palette:  2.0.0-beta.24
>     @vuepress/plugin-prismjs:  2.0.0-beta.24
>     @vuepress/plugin-pwa: Not Found
>     @vuepress/plugin-pwa-popup: Not Found
>     @vuepress/plugin-register-components: Not Found
>     @vuepress/plugin-search: Not Found
>     @vuepress/plugin-shiki:  2.0.0-beta.24
>     @vuepress/plugin-theme-data:  2.0.0-beta.24
>     @vuepress/plugin-toc: Not Found
>     @vuepress/shared:  2.0.0-beta.24
>     @vuepress/theme-default:  2.0.0-beta.24
>     @vuepress/utils:  2.0.0-beta.24
>     vue:  3.2.6
>     vue-loader:  16.5.0
>     vue-router:  4.0.11
>     vuepress: ^2.0.0-beta.24 => 2.0.0-beta.24
>     vuepress-vite: Not Found
> ```

我也遇到了  你咋解决的

**Comment by falstack** [comment]
@weiyie 没有解决，被自动关闭了

**Comment by weiyie** [comment]
@falstack 嗯嗯 我看见了  vuepress里的源码干的好事。
![image](https://user-images.githubusercontent.com/19388725/140677766-e6a013d7-dee4-497e-b461-00ece05c9453.png)
