### ISSUE TITLE
[Bug report] Page with permalinkPattern set by extendsPageOptions fails to reload

### ISSUE THREAD

**Issue by Barnabas** [vuepress/vuepress-next#421]
### Description

If the `frontmatter.permalinkPattern` is set using the `extendsPageOptions` development hook, then any affected pages will fail to reload when changed and instead show the 404 error page. This is similar to issue #294.

Theoretically, this is related to this change [76292aa](https://github.com/vuepress/vuepress-next/commit/76292aac7000e2bf924c563ff7452624008102cd) for 2.0.0-beta.20. I have reproduced this with the bare minimum possible installation [here](https://github.com/Barnabas/vuepress2-demo/tree/reload_bug), but I have also seen this same behavior in a project using the Vite bundler.

### Steps to reproduce

- Reproduction link / repo: https://github.com/Barnabas/vuepress2-demo/tree/reload_bug

1. Clone that specific branch:
    ```
    git clone --single-branch --branch reload_bug git@github.com:Barnabas/vuepress2-demo.git
    ```
1. Install and run in development mode:
    ```
    npm install
    npm run dev:docs
    ```
1. [Go to the test page](http://localhost:8080/2021/08/30/test.html), note the URL.
1. Make any change to the file `2021-08-30-test.md`. It should reload the page, instead you see a 404 not found error message. If you return to the home page, note that the URL for the test page has changed.

### Expected behavior

- Changes to pages with `permalinkPattern` hot-reload as expected without causing a 404 error.
- The link from the home page should always have been `/2021/08/30/test.html` not `_posts/2021-08-30-test.html`, even though it appears to work until a change is made to the test page.

Workaround: you can hardcode the `permalinkPattern` and other frontmatter temporarily in the page as you work. This is a detail content authors shouldn't need to know.

### Screenshots

(unnecessary)

### Environment info

- Browser: Firefox 91.0.2
- Output of `vuepress info`:

```bash
  System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 297.25 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/opt/node@14/bin/npm
  Utilities:
    Git: 2.30.0 - /usr/local/bin/git
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Not Found
    Firefox: 91.0.2
    Safari: 14.1.2
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.25 
    @vuepress/cli:  undefined (2.0.0-beta.25)
    @vuepress/client:  2.0.0-beta.25 
    @vuepress/core:  2.0.0-beta.25 
    @vuepress/markdown:  2.0.0-beta.25 
    @vuepress/plugin-active-header-links:  2.0.0-beta.25 
    @vuepress/plugin-back-to-top:  2.0.0-beta.25 
    @vuepress/plugin-container:  2.0.0-beta.25 
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.25 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.25 
    @vuepress/plugin-nprogress:  2.0.0-beta.25 
    @vuepress/plugin-palette:  2.0.0-beta.25 
    @vuepress/plugin-prismjs:  2.0.0-beta.25 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.25 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.25 
    @vuepress/theme-default:  2.0.0-beta.25 
    @vuepress/utils:  2.0.0-beta.25 
    vue:  3.2.6 
    vue-loader:  16.5.0 
    vue-router:  4.0.11 
    vuepress: ^2.0.0-beta.25 => 2.0.0-beta.25 
    vuepress-vite: Not Found
```

**Comment by meteorlxy** [comment]
The reason is that we are using relative path when initializing app, but using absolute path when reloading pages.

**Comment by meteorlxy** [comment]
After the fix, the `filePath` in `extendsPageOptions` should always be absolute file path.
