### ISSUE TITLE
[Bug report] base URL not prepended to favicon

### ISSUE THREAD

**Issue by kingyue737** [vuepress/vuepress-next#422]
### Description

`base` config does not prepend the base URL to icon's `href`.

### Steps to reproduce

- Reproduction link / repo:
1. Clone the repo:
```bash
git clone https://github.com/NuStar-Nuclear/nustar-admin-template-docs.git
```
2. Build the docs:
```bash
npm install
npm run docs:build
```

### Expected behavior

`href` of favicon in index.html in dist folder should be "/nustar-admin-template-docs/nustar-vue.svg", but here is still "/nustar-vue.svg".

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```

**Comment by meteorlxy** [comment]
It's as expected. The head config is kept as is, because it's possible to use a url without base as the favicon. You should add it yourself.
