### ISSUE TITLE
[Feature request] The file path & route of default language and others should be flat

### ISSUE THREAD

**Issue by yuriguimaraes-hotmart** [vuepress/vuepress-next#423]
### Description

I think this feature is necessary. It makes finding files easier ,the management of files clearer, and developers can simply customize a welcome page through `docs/README.md` or just redirect to the index of language en as default page if needed.

Furthermore this is really needed for those who want to automate the translation/localization in orgs. 

As an example: https://docs.transifex.com/transifex-github-integrations/github-tx-ui#linking-a-specific-project-with-a-github-repository

Transifex uses a pattern of `[source-lang] > [target-lang]` that uses folders or file patterns to automate the integration with repositories. 

Although I can set a filter pattern for the target language, since `source` files are in the root folder above the `target`, is impossible to properly tell transifex a way to differentiate `source` files from `target` files since **`source` nested folders are in the same level as the root folder for the `target` translations**.

This is an example of the `yaml` config used for the integration:

```
filters:
- filter_type: dir
  file_format: GITHUBMARKDOWN
  source_file_extension: md
  source_language: en
  source_file_dir: docs/
  translation_files_expression: 'docs/<lang>'
```

If we have a structure like this:

````
docs
├─ README.md
├─ foo.md
├─ nested
│  └─ README.md
└─ zh
   ├─ README.md
   ├─ foo.md
   └─ nested
      └─ README.md
````

Not only `README.md` , `foo.md` and `nested/REAMDE.md` will be considered `source_language` but also every single file inside `zh`.

### Proposed Solution

The final structure would be:

```
docs/
  - .vuepress/
  - en/
    - foo/
    - qux/
    - api.md
    - README.md
  - ja/
    - foo/
    - qux/
    - api.md
    - README.md
  - zh/
    - foo/
    - qux/
    - api.md
    - README.md
  - README.md
```

Probably config would still look the way it looks today, only with an `default` optional parameter. Fallback is  `en` or first lang alphabetically. 

````
module.exports = {
    locales: {
        '/en/': {
            lang: 'en-US'
        },
        '/ja/': {
            lang: 'ja-JP'
        },
        '/zh/': {
            lang: 'zh-CN',
            default: true
        }
    },
}
```

**Comment by DerZade** [comment]
Isn't this possible already?
I used a similar pattern with Vuepress 1.x in [this repo](https://github.com/gruppe-adler/wiki.gruppe-adler.de). Granted this didn't include the nicest solution for the redirect. In 2.x you could just add a redirect route to VueRouter in `clientAppEnhance`, which would be much cleaner.

I don't see why this shouldn't be possible in 2.x
