### ISSUE TITLE
[Feature request] Clarify switch to Vite bundler instructions

### ISSUE THREAD

**Issue by Barnabas** [vuepress/vuepress-next#425]
### Description

In [Guide > Bundler > Vite](https://v2.vuepress.vuejs.org/guide/bundler.html#vite), it says:

> If you want to use Vite instead, you can switch to vuepress-vite package:
```
yarn add -D vuepress-vite@next
```

From this text, it is not clear that unless you **uninstall** the `vuepress` package, you will still have the default webpack bundler and all its dependencies installed, unnecessarily. ~However, if you remove the vuepress package, then the scripts suggested in [Getting Started > Manual Installation > Step 4](https://v2.vuepress.vuejs.org/guide/getting-started.html#manual-installation) stop working, unless they are changed to `vuepress-vite`.~ Edit: I was wrong, turns out the `bin` alias works.

### Proposed Solution

The current documentation describes changing the bundler via the `bundlerConfig` option, which is technically true but probably the least likely scenario. It seems more likely that a new user installed VuePress following standard instructions and then later wanted to switch from the default bundler to the webpack bundler.

General recommendations for documentation:

1. Consolidate and move the paragraphs about setting the `bundler` and `bundlerConfig` to the end of Guide > Bundler, as that is advanced information.
2.  Change the Vite section to instead describe the steps of switching from the default bundler to Vite, including uninstalling `vuepress`.

More long-term, please consider one or more of the following: 
- Rename the existing `vuepress` package to `vuepress-webpack`, makes the bundler choice explicit.
- Change the `vuepress` package to not include a bundler by default and instead make installing either `@vuepress/webpack` or `@vuepress/vite` similar to how [Vue 3 install instructions](https://v3.vuejs.org/guide/installation.html#npm) recommend installing `@vue/compiler-sfc`. 
- VuePress could automatically detect whether a suitable bundler is installed and just use it as if it had been configured manually with `bundler` in config.

If just the documentation recommendations were applied, the Guide > Bundler page content might look something like this (there is some slight copyediting also).

---

## Bundler

VuePress has been using [webpack] as the default bundler to develop and build sites. Since VuePress v2, other tools like [Vite] are also supported. Although it is possible to use other bundler packages made by community users, we recommend only using bundlers provided by the VuePress team.

### Webpack

When using the `vuepress` package, the `webpack` bundler is installed and used automatically. There's nothing further for you to do. [Read more about installing and configuring the webpack bundler here.] _link to reference/bundler/webpack_

### Vite

If you want to use the Vite bundler, uninstall the `vuepress` package and install the `vuepress-vite` package instead:

```bash
yarn remove vuepress
yarn add -D vuepress-vite@next
```

[Read more about installing and configuring the Vite bundler here.] _link to reference/bundler/vite_

### Advanced Configuration

You can specify the name of an installed bundler package and/or set additional configuration options in the config file:

```javascript
module.exports = {
  bundler: '@vuepress/vite', // or '@vuepress/webpack'
  bundlerConfig: {
    // bundler options
  },
}
```

**Comment by meteorlxy** [comment]
Good point.

We also provide `vuepress` bin command in `vuepress-vite` package, it should take effect if users only install that package.

https://github.com/vuepress/vuepress-next/blob/05246d1001a3728205d018c8b1dc647670bd258d/packages/vuepress-vite/package.json#L23-L26

**Comment by Barnabas** [comment]
You are correct about the bin alias. I wondered why it didn't work for me before, then made [a new branch to test](https://github.com/Barnabas/vuepress2-demo/tree/vite). I have updated the issue accordingly, thanks.
