### ISSUE TITLE
[Bug report] Google featured snippet text highlighting not working

### ISSUE THREAD

**Issue by ramesh-dada** [vuepress/vuepress-next#428]
Nowadays google just adds #text type thing in url so that it can be easily scrolled to the given word. 
But it doesn't seems to work with vuepress, please fix this.

Reproduce Link : https://v2.vuepress.vuejs.org/guide/#:~:text=During%20development%2C%20we%20start%20a%20normal%20dev-server%2C%20and%20serve%20the%20VuePress%20site%20as%20a%20normal%20SPA.%20If%20you%E2%80%99ve%20used%20Vue%20before%2C%20you%20will%20notice%20the%20familiar%20development%20experience%20when%20you%20are%20writing%20and%20developing%20with%20VuePress.

**Comment by DerZade** [comment]
Your link works for me in Chrome, Opera and Edge. However, it does not work in Firefox, although I don't know if Firefox even supports `#text`.

**Comment by Lemmingh** [comment]
Support for "Scroll to Text Fragment" takes place in **web browser**:

* <https://chromestatus.com/feature/4733392803332096>

* <https://github.com/WICG/scroll-to-text-fragment>

* <https://github.com/mozilla/standards-positions/issues/194>

* <https://technians.com/news/google-featured-snippet-now-highlights-relevant-text-on-your-website/>

* <https://brandastic.com/blog/google-featured-snippet-anchoring-text/>

I also see that Firefox is not aware of it. They seems not interested in it.

**Comment by ramesh-dada** [comment]
> Your link works for me in Chrome, Opera and Edge. However, it does not work in Firefox, although I don't know if Firefox even supports `#text`.

Oh Yeah you are right I tested in firefox only before now I tested in every browser and found that only firefox and brave is having issues with the #text link so maybe I should close this as it seems to be something related with browser not vuepress.

**Comment by ramesh-dada** [comment]
Hello 123 OK I did activity ..

**Comment by meteorlxy** [comment]
As you mentioned before, this issue is not related to VuePress.
