### ISSUE TITLE
How to use markdown plugin

### ISSUE THREAD

**Issue by Zhengqbbb** [vuepress/vuepress-next#433]
### Description
I need to use the CheckBox plugin(markdown-it-task-lists), but when I use the 1.0 version, I know it is used like this, but when I use it like this 2.0, an error will be reported

https://github.com/vuejs/vuepress/issues/2364
https://github.com/vuejs/vuepress/issues/986

```js
 markdown: {
    plugins: ['task-lists']
  }
```

### Proposed Solution

type error?
![image](https://user-images.githubusercontent.com/40693636/132108343-557cfdc5-acc3-4654-b451-e947eca03438.png)

**Comment by Lemmingh** [comment]
https://v2.vuepress.vuejs.org/guide/migration.html#markdown-plugins
