### ISSUE TITLE
[Bug report] The default theme does not have `navbar sidebar` slot.

### ISSUE THREAD

**Issue by Hongbusi** [vuepress/vuepress-next#440]
## Official website document
![image](https://user-images.githubusercontent.com/53554371/133243046-6ddcaed5-b3a7-4c36-9a95-5c97a35393a5.png)

## Default theme `Layout.vue` code
![image](https://user-images.githubusercontent.com/53554371/133242781-3ce48b04-be41-4523-a558-e95db4b191bf.png)

**Comment by meteorlxy** [comment]
https://github.com/vuepress/vuepress-next/blob/922c7275475a844a6621a0102b930bbbe5aeac0b/packages/%40vuepress/theme-default/src/client/layouts/Layout.vue#L8

https://github.com/vuepress/vuepress-next/blob/922c7275475a844a6621a0102b930bbbe5aeac0b/packages/%40vuepress/theme-default/src/client/layouts/Layout.vue#L21

**Comment by Hongbusi** [comment]
Thank you
