### ISSUE TITLE
[Feature request]I hope that vupress supports custom components that are not parsed in html, but directly displayed as strings

### ISSUE THREAD

**Issue by coder666666** [vuepress/vuepress-next#445]
## Feature request
Vuepress provides a way to display custom components after parsing md to html
### Description
Now the custom component will be fully parsed by vuepress when it generates html, but there is no way to display the custom component as a string

### Proposed Solution
Vuepress provides a special mark symbol to indicate that the component does not need to be resolved

**Comment by Mister-Hope** [comment]
？Isn't changing `<` and other symbols to `&lt;` format something you should do?

**Comment by coder666666** [comment]
Oh, You are right, thanks!
