### ISSUE TITLE
[Feature request] Git plugin: add createTime

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#45]
## Feature request

I saw V2 add a `date` field in frontmatter in here:

https://github.com/vuepress/vuepress-next/blob/55f780c4a516b2c0119328874906647af80ac73b/packages/%40vuepress/plugin-git/src/types.ts#L5-L15

And add a date field in page:

https://github.com/vuepress/vuepress-next/blob/55f780c4a516b2c0119328874906647af80ac73b/packages/%40vuepress/core/src/types/page.ts#L100-L105

Theme and plugin builders may want to fetch the page date and use it.
The date can also be infered from git log, but git plugin currently support only `updatedTime` and `contributors`. 

https://github.com/vuepress/vuepress-next/blob/55f780c4a516b2c0119328874906647af80ac73b/packages/%40vuepress/plugin-git/src/types.ts#L5-L15

I think adding a new field called `createTime`(first commit) would be better for theme and plugin builders to fetch the page date from git as a improvement instead of letting users fill in.

**Comment by meteorlxy** [comment]
I also considered to add that, but I'm not sure if it's really useful:

1. The time of first commit might not be the publish time of an article.
2. Blog users may prefer to put date in filename / directory name ? (Not sure about that)

**Comment by meteorlxy** [comment]
But as a plugin, providing this feature makes sense
