### ISSUE TITLE
[Feature request] [default-theme] Allow editLinkPattern per page (frontmatter)

### ISSUE THREAD

**Issue by Joelius300** [vuepress/vuepress-next#450]
### Description

I'm using VuePress@next with the default theme (love it btw :heart:) and generate a number of pages from json data using the `onInitialized` hook. You can see that [here](https://github.com/Joelius300/werewolf-guide/blob/master/guide/.vuepress/SSR-enhancements/characterDetails.ts) (and [here's the config.ts](https://github.com/Joelius300/werewolf-guide/blob/012576c3b95bfd501a29d5072515d6929af8080f/guide/.vuepress/config.ts#L73)).  
I have enabled the edit links and since the source is hosted on GitHub, it works perfectly out of the box for static content. However, all the generated pages will link to `github.com/../edit/../null` which obviously results in a 404. That's fine but I'd like to be able to set a different path for editing the content of the generated pages so I don't have to disable the link there.

I tried setting `editLinkPattern` in the frontmatter but it isn't used in [PageMeta.ts](https://github.com/vuepress/vuepress-next/blob/a5574b80e114c1f8426b9a7e3cf6de30c0c4e407/packages/%40vuepress/theme-default/src/client/components/PageMeta.vue#L73) so it doesn't have any effect (at least that's what I think is happening).

### Proposed Solution

Respect the setting of `editLinkPattern` in pages frontmatter. This would allow to set a custom path for generated pages (or any page for any reason).

### Alternatives

Maybe I'm doing this completely wrong, so take this request with a grain of salt, maybe I just need to learn how to do it properly :)

~~Ps. I think the way I'm doing the generated content works pretty well but unfortunately hot reload doesn't work (it used to trigger (although with a page reload required) but doesn't even trigger anymore when the json is edited). This is not part of this issue but if anyone has a reference of this being done better, I wouldn't say no 😇~~

I now understand how to do the hot reloading for my pages, thanks meteorlxy :)

**Comment by meteorlxy** [comment]
The hot-reloading won't work for your custom pages. You need to watch them yourself in `onWatched` hook.
