### ISSUE TITLE
[Bug report] [default-theme] `logoDark` isn't used when dark mode is switched on automatically

### ISSUE THREAD

**Issue by Joelius300** [vuepress/vuepress-next#453]
### Description

The default theme provides a nice dark mode which automatically switches when the device (and or browser, not sure) is configured for dark mode. It also allows to specify a `logo` and a `logoDark` which are used for light and dark mode respectively.

The `logoDark` works great when switching with the theme button but unfortunately it isn't used when dark mode is set automatically on page load (initial load or refresh). This is only when the page is built, when using the dev-server, it works.

### Steps to reproduce
- (Be on a machine or have a browser that triggers the automatic dark mode of the VuePress 2.0 default theme (I don't know what that all contains)).
- Clone repo: https://github.com/Joelius300/vuepress-next-light-dark-mode-repro
- `npm install`
- `npm run docs:build`
- `cd ./docs/.vuepress/dist/`
- Serve files in folder (e.g. with `python -m http.server 8001`)
- Navigate to site in a dark mode browser
- Make sure the site switches to dark mode on the initial page load and on all subsequent refreshes

### Expected behavior
Since the page is now in dark mode, the `logoDark` (white circle) should be used.  
Instead, the normal logo (black circle) is used.

### Screenshots
Expected:
![image](https://user-images.githubusercontent.com/52202086/134134613-579e706c-6234-40c7-af90-ab3f0d3da954.png)

Actual:
![image](https://user-images.githubusercontent.com/52202086/134134557-0f5f7842-3ab3-4cb0-97e0-511e0d69cb5e.png)

### Environment info

- Browser: Tested in both Firefox 92 and Edge (on latest Win10). This also happens on a real site I built and I can confirm it happens there also on linux and on mobile with firefox, brave and chrome.
- Output of `node .\node_modules\vuepress\bin\vuepress.js info`: 

```bash
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 6.21 GB / 15.81 GB
  Binaries:
    Node: 14.17.6 - ~\AppData\Local\Temp\fnm_multishells\19536_1632207758317\node.EXE
    Yarn: Not Found
    npm: 6.14.15 - ~\AppData\Local\Temp\fnm_multishells\19536_1632207758317\npm.CMD
  Utilities:
    Git: 2.31.1.
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.52)
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.26
    @vuepress/cli:  undefined (2.0.0-beta.26)
    @vuepress/client:  2.0.0-beta.26
    @vuepress/core:  2.0.0-beta.26
    @vuepress/markdown:  2.0.0-beta.25
    @vuepress/plugin-active-header-links:  2.0.0-beta.26
    @vuepress/plugin-back-to-top:  2.0.0-beta.26
    @vuepress/plugin-container:  2.0.0-beta.26
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.26
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.26
    @vuepress/plugin-nprogress:  2.0.0-beta.26
    @vuepress/plugin-palette:  2.0.0-beta.26
    @vuepress/plugin-prismjs:  2.0.0-beta.26
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.26
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.25
    @vuepress/theme-default:  2.0.0-beta.26
    @vuepress/utils:  2.0.0-beta.25
    vue:  3.2.12
    vue-loader:  16.6.0
    vue-router:  4.0.11
    vuepress: ^2.0.0-beta.26 => 2.0.0-beta.26
    vuepress-vite: Not Found
```

**Comment by meteorlxy** [comment]
Seems that it's caused by ssr hydration 🤔
