### ISSUE TITLE
Can you consider providing iframe mode? 能否考虑支持iframe模式

### ISSUE THREAD

**Issue by pangao66** [vuepress/vuepress-next#454]
## I hope to provide a iframe mode so that I can write my component in vuepress and only use the component's css style
我希望能够提供iframe模式,以便能够在vuepress中写组件但是仅仅使用组件自己的css样式
### Proposed Solution

now I want to write a ui frameworks
there is a 'x-table' component to show in vuepress
if I don't use iframe the style of vuepress theme will influence the style of 'x-table'
becase of the default theme of vuepress has write the style of table https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/styles/index.styl
even though I can rewrite the style to overwise the default style
but I only want not infulence the 'x-table' not all of the document of vuepress
比如 现在我需要写一个ui框架
有一个'x-table'组件需要在vuepress里面展示
如果不使用iframe, vuepress 默认的样式将会影响到这个'x-table'组件
因为vuepress 默认的主题已经写了一些table默认的样式
https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/styles/index.styl
虽然我可以重写样式覆盖默认的样式
但是我只想默认的样式不影响'x-table'组件而不是整个文档

https://github.com/vuejs/vuepress/issues/1548

**Comment by Mister-Hope** [comment]
I think you can use ShadowDom here.

**Comment by pangao66** [comment]
https://d.umijs.org/guide/basic#iframe-mode
There is a document tool for ui libraries was provide to react.
In this tool, every demo can be open in a new page 
why?  every demo will be build with a page  html, so every demo  has itself html page and it will be easy to use in a iframe
In this way , we can mark the document tool to be powerful.
![image](https://user-images.githubusercontent.com/20113031/134311037-a129e61f-2ad7-4df2-a108-7e87d0d2b052.png)
like this  we can mack it be a  demo for a mobile ui lib document 
if we don't use iframe  some mobile layout will be lose.

----
https://d.umijs.org/guide/basic#iframe-mode
这里有个react的组件库文档工具
在这个工具里,每个组件都能用一个新窗口打开
因为每一个demo都被打包成了一个独立的页面,因此能很容易的被使用在iframe里面
用这种方式, 能够让文档更充满活力
例如上面的图片,我们能够用文档构建一个移动端ui库的示例
如果不使用iframe ,一些移动端的布局将不好处理
