### ISSUE TITLE
[Bug report] Markdown 链接解析异常

### ISSUE THREAD

**Issue by Yue-plus** [vuepress/vuepress-next#456]
## Bug report

Markdown 链接解析异常

### Description

```markdown
[一个FTP链接](ftp://ws19/Yue_plus%20的共享/竞赛/网络搭建及安全部署项目/_软件/)
```

![image](https://user-images.githubusercontent.com/33195150/134610135-04dbed58-f07f-47b2-9096-9dacebaa3295.png)

```markdown
[一个 file 链接](file://ws19/Yue_plus%20的共享/竞赛/网络搭建及安全部署项目/_软件/)
```

![image](https://user-images.githubusercontent.com/33195150/134610311-9e32010d-ca7d-4d7e-a04f-1093289e8c11.png)
（↑↑↑这里被解析成了字符串↑↑↑）

### Steps to reproduce

- Reproduction link / repo:

### Expected behavior

应该在新标签页中打开原始链接：

![image](https://user-images.githubusercontent.com/33195150/134610573-9ccfad79-1d9d-4534-b673-0b166e18d712.png)

### Environment info

- Browser: Microsoft Edge 版本 93.0.961.52 (官方内部版本) (64 位)
- Output of `vuepress info`:

```bash
$ yarn vuepress info
yarn run v1.22.11
$ D:\code\NetNote\node_modules\.bin\vuepress info
- Collecting Environment Info

  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Memory: 7.22 GB / 15.89 GB
  Binaries:
    Node: 16.8.0 - ~\AppData\Local\Temp\yarn--1632452149749-0.07057864498427824\node.CMD
    Yarn: 1.22.11 - ~\AppData\Local\Temp\yarn--1632452149749-0.07057864498427824\yarn.CMD
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.33.0. - /mingw64/bin/git
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.52)
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.26
    @vuepress/cli:  2.0.0-beta.26
    @vuepress/client:  2.0.0-beta.26
    @vuepress/core:  2.0.0-beta.26
    @vuepress/markdown:  2.0.0-beta.25
    @vuepress/plugin-active-header-links:  2.0.0-beta.26
    @vuepress/plugin-back-to-top:  2.0.0-beta.26
    @vuepress/plugin-container:  2.0.0-beta.26
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.26
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.26
    @vuepress/plugin-nprogress:  2.0.0-beta.26
    @vuepress/plugin-palette:  2.0.0-beta.26
    @vuepress/plugin-prismjs:  2.0.0-beta.26
    @vuepress/plugin-pwa: ^2.0.0-beta.26 => 2.0.0-beta.26
    @vuepress/plugin-pwa-popup: ^2.0.0-beta.26 => 2.0.0-beta.26
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: ^2.0.0-beta.26 => 2.0.0-beta.26
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.26
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.25
    @vuepress/theme-default:  2.0.0-beta.26
    @vuepress/utils:  2.0.0-beta.25
    vue:  3.2.6
    vue-loader:  16.5.0
    vue-router:  4.0.10
    vuepress: ^2.0.0-beta.26 => 2.0.0-beta.26
    vuepress-vite: Not Found

Done in 2.87s.
```

**Comment by meteorlxy** [comment]
FTP 链接确实有问题。

File 链接 markdown-it 本身就是不支持的。[查看 demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%5B%E4%B8%80%E4%B8%AAFTP%E9%93%BE%E6%8E%A5%5D%28ftp%3A%2F%2Fws19%2FYue_plus%2520%E7%9A%84%E5%85%B1%E4%BA%AB%2F%E7%AB%9E%E8%B5%9B%2F%E7%BD%91%E7%BB%9C%E6%90%AD%E5%BB%BA%E5%8F%8A%E5%AE%89%E5%85%A8%E9%83%A8%E7%BD%B2%E9%A1%B9%E7%9B%AE%2F_%E8%BD%AF%E4%BB%B6%2F%29%5Cn%5Cn%5B%E4%B8%80%E4%B8%AA%20file%20%E9%93%BE%E6%8E%A5%5D%28file%3A%2F%2Fws19%2FYue_plus%2520%E7%9A%84%E5%85%B1%E4%BA%AB%2F%E7%AB%9E%E8%B5%9B%2F%E7%BD%91%E7%BB%9C%E6%90%AD%E5%BB%BA%E5%8F%8A%E5%AE%89%E5%85%A8%E9%83%A8%E7%BD%B2%E9%A1%B9%E7%9B%AE%2F_%E8%BD%AF%E4%BB%B6%2F%29%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D)
