### ISSUE TITLE
[Bug report] 🐛The sidebar of the title is unable to display normally.

### ISSUE THREAD

**Issue by GoogTech** [vuepress/vuepress-next#465]
### Description
The sidebar of the title is unable to display normally when the title of the article isn't a **first-level** header.

### Steps to reproduce
1. It's an article file named `chapter01.md`, and the title isn't a first-level header.
![image](https://user-images.githubusercontent.com/43493852/135022495-3357992e-fd54-4d17-83a6-f96c8a23d0ae.png)

2. It's a configuration file named `config.js`, and the file path of `chapter01.md` is shown below.
![image](https://user-images.githubusercontent.com/43493852/135022650-6535d185-230c-4666-8e1f-ee1bcf6b4f40.png)

3. Finally, Run it and find that the title sidebar is unable to display normally.
![image](https://user-images.githubusercontent.com/43493852/135023108-eb3226ec-4e01-4a74-8d28-86ff100f65b6.png)

#### How to Fix it
1. Change the article header to the first-level header.
![image](https://user-images.githubusercontent.com/43493852/135023263-4d75eddd-37e1-4f4b-a5a4-74c7b4544af1.png)

2. Then this bug is gone.
![image](https://user-images.githubusercontent.com/43493852/135023604-276a52ba-1285-4ff6-ad59-92be4d90aeff.png)

- Reproduction repo: https://github.com/googtech/note
- Reproduction link: https://goog.tech/note

### Expected behavior
Maybe it isn't a bug if you tell me that the article header must be a first-level header. looking forward to your reply, Thx.

### Environment info
- Browser: Google Chrome Version 93.0.4577.63
- Output of `vuepress info`: No error info in console or browser.

**Comment by meteorlxy** [comment]
https://v2.vuepress.vuejs.org/reference/frontmatter.html#title
