### ISSUE TITLE
[Bug report] Sass user style file not found error if absolute path contains spaces

### ISSUE THREAD

**Issue by ctrueblood-epri** [vuepress/vuepress-next#481]
### Description

If project's absolute path contains 1 or more space characters, then an error occurs when a user style file is loaded:

```bash
ERROR in ./node_modules/@vuepress/theme-default/lib/client/styles/index.scss (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-15.use[1]!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-15.use[2]!./node_modules/sass-loader/dist/cjs.js!./node_modules/@vuepress/theme-default/lib/client/styles/index.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  |
1 | @forward 'C:/Test 1/docs/.vuepress/styles/index.scss';
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  docs\.vuepress\.temp\styles\index.scss 1:1                              @use
  node_modules\@vuepress\theme-default\lib\client\styles\index.scss 20:1  root stylesheet
```

### Steps to reproduce

1. Create a parent directory that contains 1 or more spaces, such as `C:\Test 1\` (Windows 10 assumed).
2. Create a new VuePress project (v2.0.0-beta.26) inside the parent directory.
3. Create a user-defined style file `.vuepress/styles/index.scss` as described in https://v2.vuepress.vuejs.org/reference/default-theme/styles.html#style-file
4. Run `yarn docs:dev` to produce the error.

### Expected behavior

`.vuepress/styles/index.scss` should be found and loaded by Sass. In `.vuepress/.temp/styles/index.scss` we have an auto-generated line with the correct path:

```scss
@forward 'C:/Test 1/docs/.vuepress/styles/index.scss';
```

However, the presence of a space between "Test" and "1" in the path causes sass-loader to assume a relative path instead of absolute, which throws the "Can't find stylesheet to import" error.

### Suggested Fix

In `packages/@vuepress/plugin-palette/src/node/presetOptions.ts` line 22
https://github.com/vuepress/vuepress-next/blob/c8b42a3ffac29732c29653ba5f945d666ed31ee1/packages/%40vuepress/plugin-palette/src/node/presetOptions.ts#L22
we can prepend `file:///` to force the absolute path, like this:

```ts
importCode: (filePath) => `@forward 'file:///${filePath}';\n`,
```

### Environment info

Output of `vuepress info`:

```bash
$ "C:\Test 1\node_modules\.bin\vuepress" info

  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 16.10.0 - ~\AppData\Local\Temp\yarn--1634659621244-0.48943262668027554\node.CMD
    Yarn: 1.22.10 - ~\AppData\Local\Temp\yarn--1634659621244-0.48943262668027554\yarn.CMD
    npm: 7.24.2 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.26
    @vuepress/cli:  2.0.0-beta.26
    @vuepress/client:  2.0.0-beta.26
    @vuepress/core:  2.0.0-beta.26
    @vuepress/markdown:  2.0.0-beta.25
    @vuepress/plugin-active-header-links:  2.0.0-beta.26
    @vuepress/plugin-back-to-top:  2.0.0-beta.26
    @vuepress/plugin-container:  2.0.0-beta.26
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.26
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.26
    @vuepress/plugin-nprogress:  2.0.0-beta.26
    @vuepress/plugin-palette:  2.0.0-beta.26
    @vuepress/plugin-prismjs:  2.0.0-beta.26
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.26
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.25
    @vuepress/theme-default:  2.0.0-beta.26
    @vuepress/utils:  2.0.0-beta.25
    vue:  3.2.20
    vue-loader:  16.8.1
    vue-router:  4.0.12
    vuepress: ^2.0.0-beta.26 => 2.0.0-beta.26
    vuepress-vite: Not Found
```

**Comment by Longgererer** [comment]
I had the same error and had to rename the folder to remove Spaces.

**Comment by meteorlxy** [comment]
Sounds good to me. Would it also work for less/stylus/css?

**Comment by Trezedo** [comment]
I had the same error with the project path contains chinese, it disapeared after renamed.

**Comment by Mister-Hope** [comment]
> Would it also work for less/stylus/css?

Less is not having this kind of prolems in my test. Css @import should be a valid URI, so I not sure  what do you mean by css here, stylus probably works eidther.

Not tested with Chinese, but I think it's ok to add a PR fixing sass.
