### ISSUE TITLE
[Feature request] Provide both cjs and esm syntax for `@vuepress/client`

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#49]
## Why is this feature needed

Users may import `@vuepress/client` on node side for serveral reasons:

- To provide composables and export them in main.

   E.g.: A plugin may provide a `useXXX ` api. And we may want user to `import { useXXX } from 'YYY'` instead of `import { useXXX } from 'YYY/lib/composable'`

- To import some functions and use it in pluginObject. (Just as I ask in #47 such as `resolveSiteLocaleData`)

- To import types such as `PageFrontmatter` (ESM syntax on this situation is not causing issues)

If `@vuepress/client` only has esm syntax, we have to be extra careful to make sure the main entrance is not importing any functions, just it's types. Or we will get errors like `Unexpected token 'export'`.

So I hope `@vuepress/client` can export both with `main `and `module`

**Comment by meteorlxy** [comment]
The client package should not be imported in node side.

1. If you want to simplify the usage in client, you can provide a client side entry, and set `alias` in your plugin.

2. Use `resolveLocalePath` from the `shared` package to resolve the locale. In fact, there is no site data in node side. It's just a coincidence that the `SiteData` interface is compatible with `AppOptions`. 

3. Same as above. `PageFrontmatter` is available in `shared`

**Comment by Mister-Hope** [comment]
> 2. Use `resolveLocalePath` from the `shared` package to resolve the locale. In fact, there is no site data in node side. It's just a coincidence that the `SiteData` interface is compatible with `AppOptions`.

Nope, `resovleLocalePath` is definitly not what I want to. As I said in #47, I am accessing page lang in `extendsPage` data to provide i18n lang. A people who is not speaking english will more likely to use `/` as his mother language. It's unhelpful if a page has a routeLocale with `/`, so I want the `lang` actually.

So I think at least a function should be provided to let peple get a page's lang or something.

**Comment by meteorlxy** [comment]
That's another thing. This issue is asking for cjs build of client package.

**Comment by meteorlxy** [comment]
Just made siteData available on vuepress app 05b87ddf32f32c94cc131e0074365aeba70f85f2
