### ISSUE TITLE
[Bug report] Default theme: unexpected `rem` in styles

### ISSUE THREAD

**Issue by nsznsznjsz** [vuepress/vuepress-next#50]
### Description

I saw v1 use only `padding` in [styles/code](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/styles/code.styl#L71), this line split to `margin` and `padding` in v2, and an unexpected character `rem` was left. Is it on purpose?

https://github.com/vuepress/vuepress-next/blob/55f780c4a516b2c0119328874906647af80ac73b/packages/%40vuepress/theme-default/src/styles/_variables.styl#L29

https://github.com/vuepress/vuepress-next/blob/16d5686db3eab17bbc248f7ce9ceb6703c479fcc/packages/%40vuepress/theme-default/src/styles/code.styl#L105-L106

It works well now, stylus use it to override the unit of variable. However, if user set it with a different unit, this may cause an error:

```stylus
// stylus
$lineNumbersWrapperWidth: 3.5px;
margin-left: $lineNumbersWrapperWidth rem; 

// compiled css
margin-left: 3.5rem; 
```

Or eject default theme and change it to scss/less:

```scss
// scss
$lineNumbersWrapperWidth: 3.5px;
margin-left: $lineNumbersWrapperWidth rem; 

// compiled css
margin-left: 3.5px rem; 
```

### Steps to reproduce

None

### Expected behavior

Delete `rem`:

```css
margin-left: $lineNumbersWrapperWidth; 
```

### Screenshots

None

### Environment info

vuepress@2.0.0-alpha.19

**Comment by meteorlxy** [comment]
Should be a typo
