### ISSUE TITLE
[Bug report] VuePress doesn't work with Docker

### ISSUE THREAD

**Issue by PeppeL-G** [vuepress/vuepress-next#502]
### Description
I can run VuePress 2 on my Windows 10 Home computer without problem, but now I try to run it (in dev mode) using Docker, and that doesn't work (`docker-compose up` never seems to finish, and the web browser can't connect to the VuePress app, even though the output in the shell says it has started).

Not sure if the problem is with VuePress, Docker, or my setup, but I think one need knowledge of the VuePress 2 internals to debug it. If you help me, I can contribute with writing instructions for how to get it to work as thanks.

### Steps to reproduce
Here's a minimal reproduction:

https://github.com/PeppeL-G/vuepress-docker-not-working

The repo also contains the output from `docker-compose up`.

### Expected behavior
To be able to view the VuePress app in my web browser on [localhost:8080](http://localhost:8080) after I've run the command `docker-compose up`.

**Comment by meteorlxy** [comment]
Well, I think you'd better learn how docker works first.

A short suggestion is:

```diff
- RUN npm run docs:dev
+ CMD ["npm", "run", "docs:dev"]
```

**Comment by PeppeL-G** [comment]
Many thanks, that totally explains why the build never finishes and why it starts before that. My mistake!

Do you want me to write a short guide on how to get it to work with Docker? Would that be a new page in the [Guide](https://v2.vuepress.vuejs.org/guide/) section, or where would I place it?
