### ISSUE TITLE
[Feature request]Make all article pages appear on the home page

### ISSUE THREAD

**Issue by qcyblm** [vuepress/vuepress-next#505]
### Description

Please support the archive all articles page on the page, which is fixed in the main page, as shown below:

![image](https://user-images.githubusercontent.com/64412486/139616892-ad63a901-3b9e-4e6d-ad64-0a8464acda07.png)

### Proposed Solution

When Frontmatter is set to top:1, 2, 3, it displays more content at the top, otherwise it displays less content and sorts articles based on upload time.

**Comment by Mister-Hope** [comment]
I think you are using a third party theme, please come to its own repo for help.

**Comment by qcyblm** [comment]
> I think you are using a third party theme, please ahead to its own repo for help.

I use the default theme for secondary development (vuepress v2), and the screenshot uses the third-party theme (vuepress v1), and I want to inject that theme feature into the vuepress v2 default theme.

**Comment by Mister-Hope** [comment]
Let me explain more carefully:

- VuePress V1 never ever support the feature you describe, your third partry V1 theme implement by it’s own, with or without `@vuepress/plugin-blog`
- V2 may havev plans to support blog plugin, but it have poor priority, and even with no timetable.

So:

- If your V1 theme implement this feature by its own. Please ask it support V2, that’s not VuePress official’s job
- If your V1 theme implement this feature by plugin blog, please track #54 and wait patiently

**Comment by Mister-Hope** [comment]
If you have trouble implement it in V2, as `siteConfig.pages` Is removed for scalability consideration , a related PR has already been raised by me at #504 . Please wait for it.

**Comment by qcyblm** [comment]
https://github.com/vuepress/vuepress-next/discussions/72 Discussions, may find the answer

**Comment by qsyyke** [comment]
The author has answered this question in the discussion above, if you need all the data of the site, you need to implement it yourself #72

**Comment by qsyyke** [comment]
> https://github.com/vuepress/vuepress-next/discussions/72 Discussions, may find the answer

The author has answered this question in the discussion above, if you need all the data of the site, you need to implement it yourself #72
