### ISSUE TITLE
[Bug report] Can't use relative path for local theme

### ISSUE THREAD

**Issue by bcorcoran** [vuepress/vuepress-next#51]
I'm trying to create a Vuepress next site and running into a roadblock.

I can only specify a path to the local theme (`<repo>/.vuepress/theme`) by using an absolute path... this poses a problem because the path to the theme is different on my machine than another developer's. 

Why doesn't this work in `.vuepress/config.js`?

```
module.exports = {
     theme: '.vuepress/theme',
}
```

or 

```
module.exports = {
     theme: './theme',
}
```

**Comment by meteorlxy** [comment]
`path.resolve(__dirname, '....')`

**Comment by bcorcoran** [comment]
Ok, so for anyone looking for the same thing:

in `.vuepress/config.js`

```
var path = require('path')

module.exports = {
  theme: path.resolve(__dirname, 'theme'),
}
```
