### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by steele-cjf** [vuepress/vuepress-next#511]
### Description
vuepress@nextVueCompilerError: Illegal tag name. Use '&lt;' to print '<'.

### Steps to reproduce

markdown files inclue some symbol,it will crash

- Reproduction link / repo:

### Expected behavior

no error

### Screenshots

![image](https://user-images.githubusercontent.com/56427915/140468354-b84682f8-e3bf-40c0-8f27-a0e1c361d412.png)

### Environment info

- Browser: chrome
- "vuepress": "^2.0.0-beta.27"

```bash
"vuepress": "^2.0.0-beta.27"
```

**Comment by Mister-Hope** [comment]
I think this should be considered as. An invalid one, you should use `\<` to print `<`

**Comment by steele-cjf** [comment]
@Mister-Hope you are right，that's a solution
