### ISSUE TITLE
[Feature request] Improve documentation for newcomers

### ISSUE THREAD

**Issue by codenomnom** [vuepress/vuepress-next#517]
### Description

I'm brand new to VuePress and jumped to using v2 immediately. The first thing I wanted to do after running the installation was to create my own theme so I can modify the html skeleton.

And then I hit that wall.

I browse the guides, and went to [Theme](https://v2.vuepress.vuejs.org/guide/theme.html). I see how to create my own "Local Theme": first I create a local directory (:heavy_check_mark:). then "*set the absolute path of the theme directory to use it*":
```javascript
module.exports = {
  theme: path.resolve(__dirname, './path/to/docs/.vuepress/theme'),
}
```

Where to set it? Which file? Why? What other things I need to set there?

It say to refer to [Advanced > Writing a Theme](https://v2.vuepress.vuejs.org/advanced/theme.html). I go there - I need to read about plugins (:heavy_check_mark:). Then I see them theme is a plugin and it can look like this:

```javascript
const { path } = require('@vuepress/utils')

const fooTheme = {
  name: 'vuepress-theme-foo',
  layouts: {
    Layout: path.resolve(__dirname, 'layouts/Layout.vue'),
    404: path.resolve(__dirname, 'layouts/404.vue'),
  },
  // ...
}
```

Content seems fairly reasonable. But in which file should I put it in? In which directory? How to export that constant?! What other pieces are inside this file? It shows me how to publish it to `npm`. I still don't know how to even run it locally. I say well, okay, read again about plugins.

Absolutely same thing. Code samples without any context of where and what.

Then I go to the [Configuration](https://v2.vuepress.vuejs.org/guide/configuration.html) again. I figure out it's referred to as "VuePress Config", and that "Options outside `themeConfig` are Site Config, while options inside `themeConfig` are Theme Config". Fair enough.

Following the link in the "Theme Config" section leads me to [Default Theme Reference](https://v2.vuepress.vuejs.org/reference/default-theme/config.html). I don't want the default one, I want mine.

I go back and follow the link for the [Config Reference](https://v2.vuepress.vuejs.org/reference/config.html#site-config). It also contains the [Theme Config](https://v2.vuepress.vuejs.org/reference/config.html#theme-config). In there, there are two sub sections named [theme](https://v2.vuepress.vuejs.org/reference/config.html#theme) and [themeConfig](https://v2.vuepress.vuejs.org/reference/config.html#theme).
It's obvious I can change the theme by explicitly using `theme: path.resolve(__dirname, './path/to/local/theme')`, so `theme` is a key. **But I don't know where to put that line**, as this is the entire sample:
```javascript
module.exports = {
  theme: 'vuepress-theme-foo',
  theme: 'bar',
  theme: path.resolve(__dirname, './path/to/local/theme'),
}
```
Is this a new file? Which file is it? Where is it placed? It's part of the config, right?

This is the best part. Remember we said that "everything **inside** `themeConfig` is for the theme". Now I start to doubt what's going on, as I'm in the section for the theme config (so we're talking about `config.js :: module.exports.themeConfig`, right?). There cannot be another section with the same name.

By that time I start to realize that the example mentioned above is **part of the `config.js`** and is **on the same level** as `themeConfig`. So it should be something along the lines of:

```javascript
// config.js

module.exports = {
  theme: path.resolve(__dirname, './path/to/local/theme'),
  themeConfig: {
  }
}
```

And surely, that worked.

### Proposed Solution

See, probably that wouldn't happen if I was using VuePress 1, right? And it's super obvious for everyone around here. Or probably most people just extend existing themes.

But for the small amount of people like me, it would be extremely helpful if there's explicit context for those examples. Like on the top of each file there could be something like:
```javascript
// your-project/docs/.vuepress/config.js
module.exports = {
}
```

Also, instead of providing partials like the ones for the theme - make a full example! It's obvious how to define a theme. But how and where to exported is completely missing. Most of the people would publish to npm, I get it. Let's think about the rest.

Going through the docs from a complete newbie perspective and making sure all the samples are coming with a proper context, and the entire flow of creation/configuration/editing of both the existing solution and custom plugins/themes, would be extremely helpful.

Thanks!

**Comment by meteorlxy** [comment]
Thanks for the advice. Feel free to propose issues about docs if you find it is confusing.
