### ISSUE TITLE
[Feature request] toc component

### ISSUE THREAD

**Issue by gavinliu6** [vuepress/vuepress-next#52]
### Description

Please support TOC on a page which fixes on the right side of the page like this:

![toc](https://user-images.githubusercontent.com/29831211/106863492-95c1c900-6703-11eb-8034-12017bc04a71.png)

### Proposed Solution

When the browser width is greater than a certain size, such as 1200px, it shows up and there are merely the sidebar top-most items. Otherwise, it is hidden and the sidebar behaves normally according to configuration just like now.

`sidebarDepth` may be used to control nav levels not included `h1` head.

**Comment by meteorlxy** [comment]
It's more like a theme-specific feature, which is not so compatible with current default theme.

However, we have provided a toc plugin in 0ea1720ae3ed2007f0232123bfd7de77af6ae383 to help theme developers to implement this feature in their custom themes.

Let me know if you have any further ideas.

**Comment by gavinliu6** [comment]
That's great! I'm working on a theme with planning to include this feature.

**Comment by gavinliu6** [comment]
Preview: https://vuepress-theme-mix.vercel.app

**Comment by meteorlxy** [comment]
@gavinliu6 Cool, maybe the first vuepress 2 theme
