### ISSUE TITLE
[Bug report]  publickPath不生效，vuepress导致的bug

### ISSUE THREAD

**Issue by weiyie** [vuepress/vuepress-next#520]
### Description

webpack的publickPath不生效，vuepress导致的bug
![image](https://user-images.githubusercontent.com/19388725/140678097-9b5b52f5-685c-4018-9f81-11730c41fe52.png)

### Steps to reproduce

- Reproduction link / repo:

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```

**Comment by weiyie** [comment]
如果不支持 更新文档，如果要兼容 可以支持下

**Comment by weiyie** [comment]
@matej-marjanovic @daniellandau @JulioJu @DerZade

**Comment by DerZade** [comment]
@weiyie Is there any specific reason why you tagged me?

Firstly, I do not speak Chinese 😅. Secondly, I can not see any relation to any of the very few changes I contributed to this project.

**Comment by laoergege** [comment]
全局一张图...
