### ISSUE TITLE
footerHtml: true， but footer can not use customize component if  use app.component

### ISSUE THREAD

**Issue by steele-cjf** [vuepress/vuepress-next#527]
### Description
footerHtml: true， but footer can not use customize component if  use app.component

### Steps to reproduce

i want to use  customize component in footer

### Screenshots

![image](https://user-images.githubusercontent.com/56427915/141722310-2d7f5a3b-a8b2-46f5-b339-609ba8c05b2a.png)
![image](https://user-images.githubusercontent.com/56427915/141722374-443e5eb8-107e-4807-944c-7dbefb754785.png)

### Environment info

- Browser:
- Output of `vuepress info`:
  chrome
```bash
"devDependencies": {
    "@vuepress/bundler-vite": "^2.0.0-beta.27",
    "@vuepress/plugin-search": "^2.0.0-beta.27",
    "gh-pages": "^3.2.3",
    "stylus": "^0.54.8",
    "stylus-loader": "^3.0.2",
    "vuepress": "^2.0.0-beta.27"
  },
  "scripts": {
    "dev": "vuepress dev docs",
    "build": "vuepress build docs",
    "deploy": "gh-pages -d docs/.vuepress/dist"
  },
  "dependencies": {
    "view-design": "^4.0.0"
  }
}
```

**Comment by meteorlxy** [comment]
It's as expected. `footerHtml` only allows HTML, not vue template.
