### ISSUE TITLE
[Bug report] Missing error handling on page load

### ISSUE THREAD

**Issue by jansauer** [vuepress/vuepress-next#528]
### Description

When loading of the java-script file fails while navigating inside a vuepress website the loader bar at the top never finishes and no error is displayed. In our case this happens when the authentication cookie expires. The backend then responds with a 403. But this applies to all responses that do not include the expected content.

### Steps to reproduce

1. Start a vuepress project with at least two pages `vuepress dev`
2. Load a page in a Webbrowser
3. Stop the `vuepress dev` development server
4. Navigate to a different page

### Expected behavior

In cases where the loading of the needed files finishes with an error code or did not result in the expected content the loading bar should stop and a fitting error message should be displayed.
Also feasible would be to fall back on loading the page fresh by the browser and let the browser handle all errors.

### Environment info

- Browser:
  * Chrome 95.0.4638.69 (Official Build) (x86_64)
  * Firefox 94.0.1 (64-Bit)
- Output of `vuepress info`:
```bash
System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 6.78 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /var/folders/ls/x18vfxxj4hvfpj3brkvhc1f40000gn/T/fnm_multishells/85711_1636962342502/bin/node
    Yarn: Not Found
    npm: 8.1.0 - /var/folders/ls/x18vfxxj4hvfpj3brkvhc1f40000gn/T/fnm_multishells/85711_1636962342502/bin/npm
  Utilities:
    Git: 2.33.1 - /usr/local/bin/git
  Browsers:
    Chrome: 95.0.4638.69
    Edge: Not Found
    Firefox: 94.0.1
    Safari: 15.1
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack:  2.0.0-beta.27 
    @vuepress/cli:  2.0.0-beta.27 
    @vuepress/client:  2.0.0-beta.27 
    @vuepress/core:  2.0.0-beta.27 
    @vuepress/markdown:  2.0.0-beta.27 
    @vuepress/plugin-active-header-links:  2.0.0-beta.27 
    @vuepress/plugin-back-to-top: 2.0.0-beta.27 => 2.0.0-beta.27 
    @vuepress/plugin-container:  2.0.0-beta.27 
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.27 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom: 2.0.0-beta.27 => 2.0.0-beta.27 
    @vuepress/plugin-nprogress: 2.0.0-beta.27 => 2.0.0-beta.27 
    @vuepress/plugin-palette: 2.0.0-beta.27 => 2.0.0-beta.27 
    @vuepress/plugin-prismjs:  2.0.0-beta.27 
    @vuepress/plugin-pwa: 2.0.0-beta.27 => 2.0.0-beta.27 
    @vuepress/plugin-pwa-popup: 2.0.0-beta.27 => 2.0.0-beta.27 
    @vuepress/plugin-register-components: 2.0.0-beta.27 => 2.0.0-beta.27 
    @vuepress/plugin-search: 2.0.0-beta.27 => 2.0.0-beta.27 
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.27 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared: 2.0.0-beta.27 => 2.0.0-beta.27 
    @vuepress/theme-default:  2.0.0-beta.27 
    @vuepress/utils: 2.0.0-beta.27 => 2.0.0-beta.27 
    vue:  3.2.20 
    vue-loader:  16.8.2 
    vue-router:  4.0.12 
    vuepress: 2.0.0-beta.27 => 2.0.0-beta.27 
    vuepress-vite: Not Found
```

**Comment by jansauer** [comment]
Now I get the low number of open tickets. But this this is still something I would like to follow up. Can anyone reproduce this or comment on the intention of the current error handling?

**Comment by jansauer** [comment]
Bump

**Comment by jansauer** [comment]
Bump

**Comment by jansauer** [comment]
Bump

**Comment by jansauer** [comment]
Bump

**Comment by AnWeber** [comment]
Possibly I also had this error. I recently started using [beta.29 to create my documentation.](https://github.com/httpyac/httpyac.github.io/blob/main/docs/.vuepress/config.ts) I noticed that when all cookies are blocked, a white page is displayed. Tested on Android. I will try to reproduce the behavior on the PC.

**Comment by meteorlxy** [comment]
Maybe what you want is the `router.onError` handler ?

https://next.router.vuejs.org/api/#onerror
