### ISSUE TITLE
[Bug report] VueCompilerError: Illegal tag name. Use '&lt;' to print '<'.

### ISSUE THREAD

**Issue by yanglbme** [vuepress/vuepress-next#532]
### Description

In my markdown file, I got an `VueCompilerError`

### Steps to reproduce

My markdown content:

```md
<ol>
    <li>a <= 19</li>
</ol>
```

### Expected behavior

Expected result:

```md
1. a <= 19
```

### Screenshots

![image](https://user-images.githubusercontent.com/21008209/142712083-18599de0-e7a7-4263-b4d0-d8151722b4ce.png)

### Environment info

- Browser: Chrome 95.0.4638.69
- Output of `vuepress info`:

```bash
Compiled with problems:X

ERROR in ./docs/.vuepress/.temp/pages/guide/index.html.vue

Module Error (from ./node_modules/vue-loader/dist/index.js):

VueCompilerError: Illegal tag name. Use '&lt;' to print '<'.
at D:\repo\qcloud-im-server-sdk-java\docs\.vuepress\.temp\pages\guide\index.html.vue:20:12
18 |  </div>
19 |  <ol>
20 |      <li>a <= 19</li>
   |             ^
21 |  </ol>
```

**Comment by yanglbme** [comment]
It works succeed in Docsify.

**Comment by Mister-Hope** [comment]
Dumplicated from #511

**Comment by yanglbme** [comment]
My project contains quite a lot of md files, like this: https://github.com/doocs/leetcode/blob/main/solution/0000-0099/0001.Two%20Sum/README.md

```md
<ul>
	<li><code>2 <= nums.length <= 10<sup>3</sup></code></li>
	<li><code>-10<sup>9</sup> <= nums[i] <= 10<sup>9</sup></code></li>
	<li><code>-10<sup>9</sup> <= target <= 10<sup>9</sup></code></li>
	<li><strong>只会存在一个有效答案</strong></li>
</ul>
```

I'm looking for a better way to deal with the problem.

**Comment by yanglbme** [comment]
We use docsify to build our site : https://doocs.gitee.io/leetcode/#/solution/0000-0099/0001.Two%20Sum/README

And We're considering mirgation from Docsify to VuePress.

**Comment by Mister-Hope** [comment]
Maybe you can go to `vue-loader` repo for help, this is a bit out of scope in this repo. `vue-loader` and other vue eco-system tools all targeting standard html, which means code you provided is expect to throw errors.

**Comment by yanglbme** [comment]
In VSCode Preview:

![image](https://user-images.githubusercontent.com/21008209/142713068-dae392f9-56a1-4fc9-8b2a-062116adda72.png)

**Comment by Mister-Hope** [comment]
Like I said, there are some gaps between a readable html and a standard html. Vue compiler is always choosing the second one.

**Comment by Mister-Hope** [comment]
BTW, Even You is making this change by purpose in Vue3, e.g.: adding a new `isCustomElement` option so that unknown tags will also throw errors. I think he would want a standard and expected render function generated by template, so these non-stardard html snippets sure won't work.
