### ISSUE TITLE
[Bug report]plugin-docsearch will install @types/react

### ISSUE THREAD

**Issue by LiuWenXing1996** [vuepress/vuepress-next#533]
## Bug report
when install @vuepress/plugin-docsearch,it will install @types/react at the same time.This will cause Volar to make an error when checking the template type,like this https://github.com/johnsoncodehk/volar/discussions/592

### Description

- repo:https://github.com/LiuWenXing1996/vuepress-docsserach-types-issure

- before install @vuepress/plugin-docsearch

<img width="837" alt="iShot2021-11-24 01 49 38" src="https://user-images.githubusercontent.com/71174044/143082600-1b8d2add-648a-4065-89f5-0d72006c2590.png">

- after install @vuepress/plugin-docsearch

<img width="465" alt="iShot2021-11-24 02 30 37" src="https://user-images.githubusercontent.com/71174044/143083243-8c02fada-5297-4048-b468-367e4cc1c919.png">

<img width="1182" alt="iShot2021-11-24 01 55 05" src="https://user-images.githubusercontent.com/71174044/143082687-e3e68d88-e434-4173-a526-aff74511d473.png">

### Expected behavior

Is it possible to move @types/react to devDependencies? now it in dependencies

<img width="683" alt="iShot2021-11-24 02 11 45" src="https://user-images.githubusercontent.com/71174044/143081899-69f04603-38eb-408c-b6af-a0f7d16af39e.png">

### Environment info

- Editor:VS Code + Volar
- vuepress:2.0.0-beta.27
- @vuepress/plugin-docsearch: 2.0.0-beta.27

**Comment by Mister-Hope** [comment]
Nope, the plugin is exporting options for do search, and docsearch is requiring react type in it's options.

**Comment by LiuWenXing1996** [comment]
😂, okay, in my project, i setup tsconfig to avoid the problem. As suggested by the volar side discussion https://github.com/johnsoncodehk/volar/discussions/592#discussion-3625993 . Hope these can help others too.

```json5
// tsconfig.json
{
  "compilerOptions": {
    // ...
    "types": [
      "vite/client", // if using vite
      // ...
    ]
  }
}
```
