### ISSUE TITLE
Duplicate people in contributors list

### ISSUE THREAD

**Issue by roj1512** [vuepress/vuepress-next#537]
### Description

There will be different items in the contributors list pointing to the same people if someone commits under two names.

### Steps to reproduce

1. Edit a markdown file.
2. `git add`
3. `git commit --author "Foo <foo@bar.org>`
4. Edit the edited markdown file again.
5. `git add`
6. `git commit --author "Foo Bar <foo@bar.org`

### Expected behavior

Count authors with their emails, merge them if the names were duplicate in different commits.

**Comment by meteorlxy** [comment]
Users could handle the contributors list according to their needs in `extendsPageData` hook
