### ISSUE TITLE
[Bug report]Failed to reference static image 

### ISSUE THREAD

**Issue by RainMic1019** [vuepress/vuepress-next#538]
### Description

We quote static images in markdown documents, and the following errors occur during compilation.

```bash
ERROR in ./.temp/pages/AWTK/v1.7.0/AWTK Porting&Tailoring/1.第一章 简介.html.vue?vue&type=template&id=9412d81c (./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[2]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./.temp/pages/AWTK/v1.7.0/AWTK Porting&Tailoring/1.第一章 简介.html.vue?vue&type=template&id=9412d81c) 2:0-103
Module not found: Error: Can't resolve '@source/AWTK/v1.7.0/AWTK%20Porting&Tailoring/images/1.3AWTK_Operation_Flow.png' in 'E:\myopen\online_docs\.temp\pages\AWTK\v1.7.0\AWTK Porting&Tailoring'

webpack compiled with 1 error
```

### Steps to reproduce

Example：1.第一章 简介.md

```md
![AWTK运行流程图](./images/1.3AWTK_Operation_Flow.png)
```

### Expected behavior

Can quote pictures correctly 

### Screenshots

![image](https://user-images.githubusercontent.com/54098431/143735408-97113a36-cd64-4779-941f-dfdfefba1583.png)

### Environment info

```json
{
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  },
  "devDependencies": {
    "vuepress": "^2.0.0-beta.27"
  }
}
```

**Comment by meteorlxy** [comment]
The reason is the file path includes whitespace

**Comment by RainMic1019** [comment]
> The reason is the file path includes whitespace

@meteorlxy 
Thank you very much for your reply! I encountered this problem when migrating the project from VuePress 1. X to VuePress 2. X.

**Comment by meteorlxy** [comment]
Could you provide a reproduce repo and envrionment info? I found that I could not repro it in my linux machine :thinking:

**Comment by RainMic1019** [comment]
@meteorlxy 

> Could you provide a reproduce repo and envrionment info? I found that I could not repro it in my linux machine 🤔

Operating system：Windows 10 x64
Node.js：v14.15.3
VuePress：2.0.0-beta.27

**Comment by RainMic1019** [comment]
@meteorlxy

> Could you provide a reproduce repo and envrionment info? I found that I could not repro it in my linux machine 🤔

Reproduce:

The markdown document name can contain spaces, but if the name of the folder where the document is located contains spaces, it will cause compilation errors. 

Operating system：Windows 10 x64
Node.js：v14.15.3
VuePress：2.0.0-beta.27

**Comment by Mister-Hope** [comment]
Is this issue still exisit now? Becuz I can not reproduce it on my windows now.

**Comment by meteorlxy** [comment]
Remove the label for now as we could not repro it.
