### ISSUE TITLE
Sync active `CodeGroupItem` across all `CodeGroup`s on same page

### ISSUE THREAD

**Issue by jrappen** [vuepress/vuepress-next#541]
### Description

When making use of [`CodeGroupItem`](https://v2.vuepress.vuejs.org/reference/default-theme/components.html#codegroupitem) for fenced code blocks, I want to **sync the active selection** across all `CodeGroup`s on the same page.

**Comment by jrappen** [comment]
Any updates?

**Comment by jrappen** [comment]
@meteorlxy Not sure why your workflow automatically closes issues.

**Comment by DaveSanders** [comment]
I'd vote for and like to see this functionality, and support it with an optional cookie. It would be great if when a user switched to a specific language, that all code blocks on the site try to use that language by default.

**Comment by Mister-Hope** [comment]
This feature is already supported by vuepress-plugin-md-enhance

**Comment by meteorlxy** [comment]
I was going to support it in default theme, but it was blocked by https://github.com/vueuse/vueuse/issues/1595 at that time. Now seems that it has been fixed.

**Comment by Mister-Hope** [comment]
I still recommend to use my plugin https://plugin-md-enhance.vuejs.press/zh/guide/tabs.html

The default theme syntax is a bit complicated and hard to write, also, people may want to associate same id with different tab text
