### ISSUE TITLE
[Bug report] default theme NavbarGroup Item was actived falsely.

### ISSUE THREAD

**Issue by smart-town** [vuepress/vuepress-next#544]
### Description

When I set navbar like this:   
```js
{
    navbar: [
        { text: 'os', children: [ '/os/', '/os/linux_orders/' ] }
    ]
}
```
Then I can get a  `NavbarGroup` on the page. When I click `NavItem1`(link to `/os/linux_orders/`), then `NavItem1` was actived! But the item(link to `/os/`) was also actived! Both of them are green.(actived).

When I only click `NavItem2`(link to `/os/`), Vuepress works well.

### Steps to reproduce

1. init a vuepress-next project
2. create a folder like this:
    ```shell
    \OS
    |   linux_secure_check.md
    |   README.md
    |
    \---linux_orders
            001cut.md
            README.md
    ```
3. start app, and click the NavItem(linked to `/os/linux_orders/`)
- [Reproduction repo](https://github.com/smart-town/bug_report/tree/vuepress_next)

### Expected behavior

It should only one NavItem was actived when I just choosed one of them.( in NavbarGroup)
### Screenshots
*Both of them are actived:*

![image](https://user-images.githubusercontent.com/16263772/144716306-ad7ce96d-8061-419b-b997-04c7c5bb04e4.png)

*Correct display:*
![image](https://user-images.githubusercontent.com/16263772/144716340-32dcef0b-ed8d-4288-a453-798308d268ef.png)

### Environment info

- Browser: Microsoft Edge 96.0.1054.43
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
    Memory: 5.75 GB / 15.79 GB
  Binaries:
    Node: 14.16.1 - D:\javascript\nodejs\node14\node.EXE
    Yarn: Not Found
    npm: 7.21.1 - D:\javascript\nodejs\node14\npm.CMD
  Utilities:
    Git: 2.31.1.
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.43)
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.27
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.27
    @vuepress/client:  2.0.0-beta.27
    @vuepress/core:  2.0.0-beta.27
    @vuepress/markdown:  2.0.0-beta.27
    @vuepress/plugin-active-header-links:  2.0.0-beta.27
    @vuepress/plugin-back-to-top:  2.0.0-beta.27
    @vuepress/plugin-container:  2.0.0-beta.27
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.27
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.27
    @vuepress/plugin-nprogress:  2.0.0-beta.27
    @vuepress/plugin-palette:  2.0.0-beta.27
    @vuepress/plugin-prismjs:  2.0.0-beta.27
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.27
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.27
    @vuepress/theme-default:  2.0.0-beta.27
    @vuepress/utils:  2.0.0-beta.27
    vue:  3.2.23
    vue-loader: Not Found
    vue-router:  4.0.12
    vuepress: Not Found
    vuepress-vite: ^2.0.0-beta.27 => 2.0.0-beta.27
```

## About fix it
**And I have tried to fix it, after deal:**
![image](https://user-images.githubusercontent.com/16263772/144716468-4652db2d-ce7e-4c2d-8951-f1cfc4c44f84.png)

**Comment by smart-town** [comment]
@meteorlxy 

Hello, I am sorry for creating this issue. I found that documentation has provide the `activaMatch` option finally and it works well for my problem. **So close this issue, please~**

By the way,  I fell if vuepress can auto generate navbar and sidebar items will be more cool. :smile:  When I start it from a root path, then it can auto generate the two. Is there an option?

**Comment by meteorlxy** [comment]
> Hello, I am sorry for creating this issue. I found that documentation has provide the activaMatch option finally and it works well for my problem. So close this issue, please~

The `activaMatch` is only introduced in the `navbar` section, this issue is a reminder for adding it in the `sidebar` section.

> By the way, I fell if vuepress can auto generate navbar and sidebar items will be more cool. 😄 When I start it from a root path, then it can auto generate the two. Is there an option?

Instead of an extra option, we can provide a util function to help users to traverse the directory

**Comment by meteorlxy** [comment]
After thinking it over, I think we'd better not mention `activaMatch` in sidebar config, because sidebar and navbar has different activation mechanism.
