### ISSUE TITLE
Cannot use windi css as vite plugin

### ISSUE THREAD

**Issue by riderx** [vuepress/vuepress-next#548]
I decide to use vite bundler and use windi, like all my project but it doesn't seems to work
I followed the guide here :
https://v2.vuepress.vuejs.org/guide/bundler.html#choose-a-bundler
And then the vite windi guide here :
 https://windicss.org/integrations/vite.html
## Bug report

Config.ts
```
import type { ViteBundlerOptions } from '@vuepress/bundler-vite'
import { defineUserConfig } from '@vuepress/cli'
import type { DefaultThemeOptions } from '@vuepress/theme-default'
import WindiCSS from 'vite-plugin-windicss'

export default defineUserConfig<DefaultThemeOptions, ViteBundlerOptions>({
    title: 'Captime',
    description: 'Just playing around.2',
    theme: path.resolve(__dirname, './theme'),
    // options for vite bundler
    bundlerConfig: {
        viteOptions: {
            plugins: [WindiCSS()], 
        },
        },
    },
})
```
And Layout.vue
```
import 'virtual:windi.css'
import 'virtual:windi-devtools'

import type { ThemeObject } from '@vuepress/core'
import { path } from '@vuepress/utils'

const theme: ThemeObject = {
  // your theme
  name: 'vuepress-theme-1',
  // parent theme to extend
  extends: '@vuepress/theme-default',
  // override layouts of parent theme
  layouts: {
    Layout: path.resolve(__dirname, 'layouts/Layout.vue'),
  },
}

export default theme
```
issue
```
 …/captime-website  npm run docs:dev                                                                       1 ↵  11924  18:37:40

> captime-website@1.0.0 docs:dev /Users/martindonadieu/Documents/Projects.nosync/captime-website
> vuepress dev docs

Error: Cannot find module 'virtual:windi.css'
```

### Expected behavior

Import virtual should work like in vite.

**Comment by meteorlxy** [comment]
Theme entry is in node side. You should use windi only in client side

**Comment by riderx** [comment]
@meteorlxy how can i do that ?
i tried in theme to have support of devtools

**Comment by riderx** [comment]
@meteorlxy there are no documentation about vite in the v2, I tried in different way but without success, example can help.
Please don't close issue when people have issue but you don't considered it's not your problem it look rude.

**Comment by meteorlxy** [comment]
Here's the docs that explaining Node and Client:

https://github.com/vuepress/vuepress-next/blob/66c035402e01e63e465e82a03728fb8e135c6381/docs/advanced/architecture.md?plain=1#L12-L15

Well, if you have questions, please go to the discussion panel. Opening issue randomly looks rude.

**Comment by riderx** [comment]
@meteorlxy thanks for the doc, i never used discussion before, and I didn't saw you have them, I will do so :)
Sorry been rude, was not random for me it was real bug, made my misunderstood I agree.
