### ISSUE TITLE
代码行号错位，另外无法安装代码复制插件vuepress-plugin-code-copy

### ISSUE THREAD

**Issue by litaipingcq** [vuepress/vuepress-next#568]
![image](https://user-images.githubusercontent.com/37904197/146296978-a7545e37-bb68-4412-847a-075cb43b89c6.png)
行号错位
无法安装vuepress-plugin-code-copy

**Comment by meteorlxy** [comment]
Duplicate of #499.

---

vuepress-plugin-code-copy does not support vuepress 2 yet.
