### ISSUE TITLE
[Bug report]  vuepress-vite 中 element-plus引入语言包时打包会报错

### ISSUE THREAD

**Issue by Xyuan-abs** [vuepress/vuepress-next#570]
### Description

element-plus引入语言包时打包会报错

### Steps to reproduce

- 在clientAppEnhance.js中  import zhCn from 'element-plus/es/locale/lang/zh-cn
- 执行  vuepress build docs

### Expected behavior

能够正常打包

### Screenshots

![image](https://user-images.githubusercontent.com/64180387/146473082-cc7af40f-5161-4538-9913-839f4589f5d0.png)

### Environment info

- Browser: chrome、vuepress-vite^2.0.0-beta.27
- Output of `vuepress info`:
```bash
✔ Compiling with vite - done
✖ Rendering pages - failed
Error: Cannot find module 'F:\ins-ui\node_modules\element-plus\es\locale\lang\zh-cn'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:916:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:909:15)
    at resolveExports (internal/modules/cjs/loader.js:449:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Module.<anonymous> (F:\ins-ui\docs\.vuepress\dist\.server\app.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
error Command failed with exit code 1.

```

**Comment by Xyuan-abs** [comment]
加上后缀即可
import zhCn from 'element-plus/es/locale/lang/zh-cn.mjs'

**Comment by lyh0371** [comment]
加上后缀即可
import zhCn from 'element-plus/es/locale/lang/zh-cn.mjs' 还是报错，如下所示：

**Comment by lyh0371** [comment]
[vite]: Rollup failed to resolve import "element-plus/es/locale/lang/zh-cn.mjs" from "docs/.vuepress/clientAppEnhance.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external

**Comment by Mister-Hope** [comment]
The error message is already telling you what to do.

**Comment by lyh0371** [comment]
@Mister-Hope what should i do

**Comment by bobo456123** [comment]
> ## Bug report
> ### Description
> element-plus引入语言包时打包会报错
> 
> ### Steps to reproduce
> * 在clientAppEnhance.js中  import zhCn from 'element-plus/es/locale/lang/zh-cn
> * 执行  vuepress build docs
> 
> ### Expected behavior
> 能够正常打包
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/64180387/146473082-cc7af40f-5161-4538-9913-839f4589f5d0.png)
> 
> ### Environment info
> * Browser: chrome、vuepress-vite^2.0.0-beta.27
> * Output of `vuepress info`:
> 
> ```shell
> ✔ Compiling with vite - done
> ✖ Rendering pages - failed
> Error: Cannot find module 'F:\ins-ui\node_modules\element-plus\es\locale\lang\zh-cn'
>     at createEsmNotFoundErr (internal/modules/cjs/loader.js:916:15)
>     at finalizeEsmResolution (internal/modules/cjs/loader.js:909:15)
>     at resolveExports (internal/modules/cjs/loader.js:449:14)
>     at Function.Module._findPath (internal/modules/cjs/loader.js:489:31)
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:875:27)
>     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
>     at Module.require (internal/modules/cjs/loader.js:961:19)
>     at require (internal/modules/cjs/helpers.js:92:18)
>     at Module.<anonymous> (F:\ins-ui\docs\.vuepress\dist\.server\app.js:28:1)
>     at Module._compile (internal/modules/cjs/loader.js:1072:14)
> error Command failed with exit code 1.
> ```

你好，遇到个类似问题，我在vuepress2.x 中引入element-plus，配置了`clientAppEnhance.ts`，执行`npm run docs:build`打包命令时，报错如下：
![image](https://user-images.githubusercontent.com/36293167/166493455-429c1f1c-30f6-4012-ba9e-70a644eb6006.png)
#
clientAppEnhance.ts代码：
```
import { defineClientAppEnhance } from '@vuepress/client'

import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'

export default defineClientAppEnhance(({ app, router, siteData }) => {
  console.log("clientAppEnhance.ts");
  console.log(app, router, siteData);
  app.use(ElementPlus);
})
```

**Comment by meteorlxy** [comment]
@bobo456123 试一下配置 vite 的 `ssr.noExternal`:

```ts
import { viteBundler } from '@vuepress/bundler-vite'
import { defineUserConfig } from '@vuepress/cli'

export default defineUserConfig({
  bundler: viteBundler({
    viteOptions: {
      ssr: {
        noExternal: ['element-plus'],
      },
    },
  }),
})
```
