### ISSUE TITLE
Build directory cannot be outside project root

### ISSUE THREAD

**Issue by 0biWanKenobi** [vuepress/vuepress-next#574]
- [ x] I confirm that this is an issue rather than a question.

## Bug report

If the `dest` param of the Vuepress config is a directory outside the project root, the build will fail:
![image](https://user-images.githubusercontent.com/4061104/146646715-a0508066-4127-41c8-85c7-6fdcda01312d.png)

Same exact project will build just fine when `dest` is within the project root:

![buildok](https://user-images.githubusercontent.com/4061104/146646933-7688dbb8-5494-40cd-a231-8aaeeaaa8960.jpg)

#### Steps to reproduce

- Configure your `dest` to be a folder outside the project root
- Build with `vuepress build`

#### What is expected?

Should be able to build regardless of the destination folder.

#### What is actually happening?

The CLI copies the intermediate output to the dest folder and then tries to build from there, which eventually ends in failure if the dest is outside project root.

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 AMD Ryzen 3 3200G with Radeon Vega Graphics    
    Memory: 8.13 GB / 15.95 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.5 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.33.1.
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.57)    
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.27 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.27 
    @vuepress/client:  2.0.0-beta.27 
    @vuepress/core:  2.0.0-beta.27
    @vuepress/markdown:  2.0.0-beta.27
    @vuepress/plugin-active-header-links:  2.0.0-beta.27
    @vuepress/plugin-back-to-top:  2.0.0-beta.27
    @vuepress/plugin-container: ^2.0.0-beta.27 => 2.0.0-beta.27
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.27
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.27
    @vuepress/plugin-nprogress:  2.0.0-beta.27
    @vuepress/plugin-palette:  2.0.0-beta.27
    @vuepress/plugin-prismjs:  2.0.0-beta.27
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.27
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.27
    @vuepress/theme-default:  2.0.0-beta.27
    @vuepress/utils:  2.0.0-beta.27
    vue:  3.2.26
    vue-loader: Not Found
    vue-router:  4.0.12
    vuepress: Not Found
    vuepress-vite: ^2.0.0-beta.27 => 2.0.0-beta.27

**Comment by meteorlxy** [comment]
Currently the server bundle will be generated in `${dest}/.server` directory by default. We need to actually `require()` the server bundle in node side during ssr rendering, so it have to be put in a place where can `require()` the `node_modules` correctly.

As a workaround, you can build then `mv` the dest folder manually.

--

I think we can just add a tip to the `dest` option to remind users about that. 🤔  Any other suggestions?

**Comment by 0biWanKenobi** [comment]
Well, what if the build process 
1) uses a temp folder that lives within the project root to build
2) moves the build artifacts to the `dest` at the end

When a build fails, I noticed that some artifacts are created directly into the destination folder, but that puts a constraint on _where_ that folder can live. Usually not a issue at all, but consider this use case:
 - the user has the `dest` folder configured as an env variable, to decouple it from local folder structure
 - the user then runs the build process and makes use of that variable in` vuepress.config.ts`

This way the project doesn't need post build scripts, and anyone can `git clone` it and configure their env variable as they wish. For this use case, and for "moar flexibility!!!1 🤣 " in general, what do you think of my proposal?

**Comment by meteorlxy** [comment]
> uses a temp folder that lives within the project root to build

We want users to have full control over where to place the temp folder, so we also have a `temp` config for that.

- If we are going to output the server bundle into the temp folder, we also need to require the temp folder to be inside the project root.
- If we are going to use another implicit temp folder, then users would lose their "full control", or we need to add another config for that.

🤔

**Comment by 0biWanKenobi** [comment]
Argh! Didn't know about the `temp` config.

I've tried to set NODE_PATH to the project's node_modules folder, but that didn't work either ( not sure if it is still taken into account, seems to be a legacy thing?). 

The only thing that comes to mind would be a
 `temp `-> `build `-> `dest`
three step process, where the user can configure the `build` folder too. That folder _would_ have be under project root, but it would be the only step with that limitation. WDYT?

**Comment by meteorlxy** [comment]
After some consideration, we decided to generate `.server` inside `temp` dir (see 6b46922a463d749cf4c4034529510aec5286b77d).

The `temp` dir now is already required to be inside project root to resolve deps correctly (`vue`, `@vuepress/client`, etc), so we  don't have to add restrictions to the `dest` directory anymore
