### ISSUE TITLE
[Bug report] Image size smaller on vercel deployment environment

### ISSUE THREAD

**Issue by zhang13pro** [vuepress/vuepress-next#578]
## package.json 
 "devDependencies": {
    "vuepress-vite": "^2.0.0-beta.27"
  }

- PC System : windows
inspect image style
```css
<img class="medium-zoom-image>
```

[deployment url-0](https://13press.vercel.app/javascript/#%E4%BB%8B%E7%BB%8D)
[deployment url-1](https://13press.vercel.app/javascript/coercion.html#%E5%86%85%E7%BD%AE%E5%AF%B9%E8%B1%A1-build-in-object)

**Comment by meteorlxy** [comment]
Seems that it's caused by your own styles

**Comment by zhang13pro** [comment]
> Seems that it's caused by your own styles

I just don't understand why development environment is ok...🤨
