### ISSUE TITLE
[Feature request] 希望默认主题可以支持右侧锚点功能

### ISSUE THREAD

**Issue by Hccake** [vuepress/vuepress-next#583]
## Feature request

希望默认主题可以支持右侧锚点功能

### Description

虽然有些主题和插件实现了此功能，但是如果官方默认主题支持，可以最小化依赖项。
此外，第三方主题和插件，还有和官方版本的兼容问题，以及担心后续的更新支持。

基于以上，请考虑此功能集成的可行性，谢谢

**Comment by Zhengqbbb** [comment]
+ 1

**Comment by Zhengqbbb** [comment]
\+ 1

**Comment by Hccake** [comment]
unmark

**Comment by jiazengp** [comment]
其实我认为你完全用可以官方提供的
![image](https://user-images.githubusercontent.com/86162890/147896493-ea374a22-ad1b-4366-a802-8137d2cf13e4.png)
插件实现

**Comment by Hccake** [comment]
> 其实我认为你完全用可以官方提供的 ![image](https://user-images.githubusercontent.com/86162890/147896493-ea374a22-ad1b-4366-a802-8137d2cf13e4.png) 插件实现

有尝试过，作为一个服务端开发，调出来的样式实在太丑

**Comment by Hccake** [comment]
目前使用此插件解决 https://github.com/xuekai-china/vuepress-plugin-right-anchor

**Comment by Zhengqbbb** [comment]
> 目前使用此插件解决 https://github.com/xuekai-china/vuepress-plugin-right-anchor

可以举荐到 [awesome-vuepress](https://github.com/vuepress/awesome-vuepress/blob/main/v2.md) 让更多人知道
