### ISSUE TITLE
Blank page when cookies blocked

### ISSUE THREAD

**Issue by AnWeber** [vuepress/vuepress-next#589]
I recently started using [beta.29 to create my documentation.](https://github.com/httpyac/httpyac.github.io/blob/main/docs/.vuepress/config.ts) I noticed that when all cookies are blocked, a blank page is displayed. Tested on Android and Win10 in Chrome.

Steps: 
* Block Cookies in Browser
* Visit httpyac.github.io
* Site gets blank after first render
```
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://httpyac.github.io/assets/app.7644c1a0.js:7:14854
```
Probably created by [vueuse](https://github.com/vueuse/vueuse/blob/fa2a593e276610d4fc6010e66c2b9864c4b45137/packages/core/useStorage/index.ts#L82) by using `useStorage` in this [line](https://github.com/vuepress/vuepress-next/blob/e7c89264b0f0acb20e477ad1eda89e0f70057014/packages/%40vuepress/theme-default/src/client/composables/useDarkMode.ts#L29) for the use of darkMode. Should vuepress itself check the usage of the localStorage, or is this the task of vueuse?

**Comment by meteorlxy** [comment]
Uh, I think it might be better to open an issue in vueuse for that 🤔

**Comment by AnWeber** [comment]
@meteorlxy I have submitted a bug/feature request to vueuse. Until the change is incorporated into useStorage, would it be possible to implement [feature detection](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#feature-detecting_localstorage) in vuepress? I would provide both a PR for the merge and also for the deconstruction after a update is available.

**Comment by AnWeber** [comment]
PR provided
