### ISSUE TITLE
smoothScroll don't works

### ISSUE THREAD

**Issue by NatureK88** [vuepress/vuepress-next#590]
When I use vuepress 1.8.2，I add ` smoothScroll: true`, it works well, but when I comes to vuepress 2.0.0-beta.31, it don't work. Both are default theme.

config.js
```
module.exports = {
    plugins: ['vuepress-plugin-smooth-scroll'],    
    themeConfig: {
        smoothScroll: true,
        ...
```

I have tried to install that plugin, but it still has no effect.

**Comment by meteorlxy** [comment]
This repo is for vuepress v2

**Comment by NatureK88** [comment]
Thanks, I finally found the solution here, I miss the doc before, sorry.
[https://v2.vuepress.vuejs.org/zh/reference/default-theme/styles.html#style-文件](url)
