### ISSUE TITLE
[Bug report]Page is Error After F5 Refresh

### ISSUE THREAD

**Issue by Rhyheart** [vuepress/vuepress-next#592]
![image](https://user-images.githubusercontent.com/44357526/147527892-b81a9f34-2636-42cc-beda-a593a7019f60.png)

**Comment by Rhyheart** [comment]
F5刷新后，点击其他页面时会发现左边菜单栏不见了，控制台提示报错，我用的谷歌浏览器

**Comment by meteorlxy** [comment]
Ummm, seems that it only occurs in build mode. Need some investigation
