### ISSUE TITLE
How to access $frontmatter $lang and other mixins in setup?

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#6]
Is there a USE API now like `const frontmatter = useFrontmatter()` to access them in setup?

BTW: I would like to help with markdown and theme-default.

**Comment by meteorlxy** [comment]
```ts
import { usePageData } from '@vuepress/client'

// ...
setup() {
  const page = usePageData()
  const frontmatter = page.value.frontmatter

  // ...
}
```

**Comment by meteorlxy** [comment]
Contribution welcome.

Notice that everything is not so stable. So please make sure to keep your PR decoupled enough.

**Comment by Mister-Hope** [comment]
BTW, I hope we can optimize the build process.

![image](https://user-images.githubusercontent.com/33315834/96757515-1cc68c00-1408-11eb-8804-6f23cc1bf194.png)

[My blog](https://mrhope.site) has nearly 700 pages, and have more than 100MB (html + js + css) size.(Images and other files are not included).

And I need 6GB spare memory to build my blog. Hope V2 can have some improvements.

**Comment by Mister-Hope** [comment]
Since there is not any team members contribuiting on V1 repo, feature request there probably needs to build by myself, or they will be leave there. May I open some feature request in this repo? 😄 Most of them are related to core package.

**Comment by meteorlxy** [comment]
You can, but it's not suggested.

We should firstly handle features migration and solve some old issues in vuepress 1.x version.

You must understand that, "Please optimize the build process" is not a feature request, it's just a complaint

**Comment by meteorlxy** [comment]
Now these utils are available:

```ts
import { usePageFrontmatter, usePageLang } from '@vuepress/client'
```
