### ISSUE TITLE
[Feature request] Export Vuepress content to PDF

### ISSUE THREAD

**Issue by SrChach** [vuepress/vuepress-next#601]
### Description

It would be nice to have a plugin or extension that allows to export the Vuepress site to a PDF. The use cases are using docs offline and for clients that require PDF documentation

I have seen related features on plugins like @ulivz/vuepress-plugin-export and @SnowdogApps/vuepress-plugin-pdf-export, but I know that it would be hard to incorporate.

### Proposed Solution

I have no proposed solution. Just a Feature Request.

**Comment by hustcer** [comment]
@github-actions Reopen this issue please
