### ISSUE TITLE
[Bug report] Rendering issues with <wbr> tags

### ISSUE THREAD

**Issue by KnorpelSenf** [vuepress/vuepress-next#602]
### Description

It seems like inserting `<wbr>` tags somehow duplicates the text in a paragraph. Originally asked in https://github.com/vuepress/vuepress-next/discussions/551, I was able to reproduce the issue without any plugins in a fresh project with a single README file containing a single line of text.

### Steps to reproduce

Run the following shell script.

```bash
mkdir repro
cd repro
npm init -y
npm i -D vuepress-vite@2.0.0-beta.27
echo 'A <wbr> `0` <wbr> B <wbr> `1` C `2` <wbr> D <wbr> [E](./)' > README.md
npx vuepress-vite build
```

Serve the `.vuepress/dist` folder and open it in your browser.

### Expected behavior

The page displays:

> A `0` B `1` C `2` D [E](./)

### Actual behavior

The page displays:

> A `0` B `1` C `2` D [E](./) `0` B `1` C `2` D [E](./)

Interestingly, the page:

- renders correctly with JavaScript disabled in the browser
- renders correctly when viewing it with `npx vuepress-vite dev`
- renders correctly when changing just about anything in the line of the README file

### Screenshots

Serving the assets built by `npx vuepress-vite build`:
![image](https://user-images.githubusercontent.com/12952387/147710000-0fc1c7e1-86d5-490a-b99c-c1eec8d38a3c.png)

Serving via `npx vuepress-vite dev`:
![image](https://user-images.githubusercontent.com/12952387/147710281-9167fbd4-a5c9-49b9-b6c9-7d1bb834a6c6.png)

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
$ npx vuepress-vite info

  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
    Memory: 1.67 GB / 7.53 GB
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 17.3.0 - ~/.nvm/versions/node/v17.3.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v17.3.0/bin/npm
  Utilities:
    Git: 2.30.2 - /usr/bin/git
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 91.4.1esr
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.27 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.27 
    @vuepress/client:  2.0.0-beta.27 
    @vuepress/core:  2.0.0-beta.27 
    @vuepress/markdown:  2.0.0-beta.27 
    @vuepress/plugin-active-header-links:  2.0.0-beta.27 
    @vuepress/plugin-back-to-top:  2.0.0-beta.27 
    @vuepress/plugin-container:  2.0.0-beta.27 
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.27 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.27 
    @vuepress/plugin-nprogress:  2.0.0-beta.27 
    @vuepress/plugin-palette:  2.0.0-beta.27 
    @vuepress/plugin-prismjs:  2.0.0-beta.27 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.27 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.27 
    @vuepress/theme-default:  2.0.0-beta.27 
    @vuepress/utils:  2.0.0-beta.27 
    vue:  3.2.26 
    vue-loader: Not Found
    vue-router:  4.0.12 
    vuepress: Not Found
    vuepress-vite: ^2.0.0-beta.27 => 2.0.0-beta.27 

```

**Comment by KnorpelSenf** [comment]
This reproduces identically with the `beta.32` release.

```bash
$ npx vuepress-vite info

  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
    Memory: 1.50 GB / 7.53 GB
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 17.3.0 - ~/.nvm/versions/node/v17.3.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v17.3.0/bin/npm
  Utilities:
    Git: 2.30.2 - /usr/bin/git
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 91.4.1esr
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.32 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.32 
    @vuepress/client:  2.0.0-beta.32 
    @vuepress/core:  2.0.0-beta.32 
    @vuepress/markdown:  2.0.0-beta.32 
    @vuepress/plugin-active-header-links:  2.0.0-beta.32 
    @vuepress/plugin-back-to-top:  2.0.0-beta.32 
    @vuepress/plugin-container:  2.0.0-beta.32 
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.32 
    @vuepress/plugin-git:  2.0.0-beta.32 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.32 
    @vuepress/plugin-nprogress:  2.0.0-beta.32 
    @vuepress/plugin-palette:  2.0.0-beta.32 
    @vuepress/plugin-prismjs:  2.0.0-beta.32 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.32 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.32 
    @vuepress/theme-default:  2.0.0-beta.32 
    @vuepress/utils:  2.0.0-beta.32 
    vue:  3.2.26 
    vue-loader: Not Found
    vue-router:  4.0.12 
    vuepress: Not Found
    vuepress-vite: ^2.0.0-beta.32 => 2.0.0-beta.32 
    vuepress-webpack: Not Found
```

**Comment by KnorpelSenf** [comment]
Bump

**Comment by Mister-Hope** [comment]
Does wbr a standard tag? If not, config Vue option  `isCustomComponent` to let Vue ignore it. Search this repo, you can find similar issues like usage of `center`

**Comment by KnorpelSenf** [comment]
Yes, it's a standard tag. It's listed here: https://www.w3schools.com/TAGS/default.ASP

Also confer https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr

Either way, I'll try your suggestion, thank you!

**Comment by KnorpelSenf** [comment]
bump

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/vuepress-next/blob/6d66a46a274c2b82a3d13a14555cbc6b77aff36e/packages/%40vuepress/bundler-vite/src/plugins/createConstantsReplacementPlugin.ts#L8

https://github.com/vuepress/vuepress-next/blob/6d66a46a274c2b82a3d13a14555cbc6b77aff36e/packages/%40vuepress/bundler-vite/src/plugins/createConstantsReplacementPlugin.ts#L52-L69

Updated. It must be related with the lines above, probably needs meteorlxy check what he is doing here.

**Comment by KnorpelSenf** [comment]
@meteorlxy are there any updates on this? Are you planning on working on this?

**Comment by Mister-Hope** [comment]
It does have a every low prority, meteorlxy is trying to add esm support, then we will probably split repo into `vuepress/ecosystem` and `vuepress/core`. And we may add some improvements to bundler config, and finally we will relook into this issue.

**Comment by Mister-Hope** [comment]
This issue is probably related with a vite workaround, so you should be able to bypass it using webpack as bundler.

**Comment by KnorpelSenf** [comment]
> This issue is probably related with a vite workaround, so you should be able to bypass it using webpack as bundler.

You mean, use webpack instead of vite?

**Comment by Mister-Hope** [comment]
Yes, though I did not test, it should work well with wepack

**Comment by KnorpelSenf** [comment]
Thanks! I will try this.

**Comment by KnorpelSenf** [comment]
> https://github.com/vuepress/vuepress-next/blob/6d66a46a274c2b82a3d13a14555cbc6b77aff36e/packages/%40vuepress/bundler-vite/src/plugins/createConstantsReplacementPlugin.ts#L52-L69
> 
> Updated. It must be related with the lines above, probably needs meteorlxy check what he is doing here.
> 
> This plugins seems to be built as a workaround to prevent some special contents being resolved by vite. But i am not full understand what it did here.

As far as I can tell, this code is unrelated to the problem. The respective part of the plugin is related https://vitejs.dev/guide/env-and-mode.html#production-replacement. Also, I am able to reproduce the problem with the `transform` function returning exactly the same data as it receives, hence effectively being a no-op. In addition, the bug is only introduced client-side during hydration. (Note how disabling JS in the browser prevents the bug from happening.) This seems to me like the problem does not happen during rendering.

**Comment by Mister-Hope** [comment]
Emmm, is webpack working fine?

**Comment by KnorpelSenf** [comment]
> Emmm, is webpack working fine? This bug may come from vue and vite, and may not be releated to vuepress.

I can try webpack simply by using `vuepress` instead of `vuepress-vite`, correct? If so, then no, webpack does not work. The following script reproduces the issue.

```shellscript
mkdir repro
cd repro
npm init -y
npm i -D vuepress@2.0.0-beta.38
echo 'A <wbr> `0` <wbr> B <wbr> `1` C `2` <wbr> D <wbr> [E](./)' > README.md
npx vuepress build
```

> But only the above code in vuepress is related with `<wbr>` tags. And it is using this tag to hack the replacement.
> 
> If you ensure that the above code is not related with this issue, then probably it's not a vuepress bug.

I am like 92 % sure, it's not my project so there might be some odd behaviour that I am not aware of. However, I think the above code is not running in the browser, and I have confirmed that it has no effect during rendering. What's more, the docs say it's about env vars, and my reproduction does not use any of those, so it should not apply. So I'd be very surprised if that was the offending plugin.

If it's not a vuepress bug, then what is it? I assume that vuepress uses the SSR feature of Vue, should I open an issue there?

**Comment by KnorpelSenf** [comment]
> I have confirmed that it has no effect during rendering

What I basically did was to do a `console.log` at the end of `transform` which compared the function's return value `=== code`. This check was always true, so `transform` always returns the same value as it recieves.

**Comment by KnorpelSenf** [comment]
This is affecting more and more places in our site. Is there any workaround for this? The respective parts are not interactive. For example, can we partially disable the hydration for certain nodes?

I also don't mind investigating this, but I simply have no clue where to start. If you could give me a few 30,000ft-view guesses about which code is affected, I could move on from there.

**Comment by meteorlxy** [comment]
I'll look into it tomorrow

**Comment by meteorlxy** [comment]
You can bump to 2.0.0-beta.46 and run `build` command with `--debug` flag, then check the browser console. It's a hydration mismatch error. I'm afraid it is an internal issue of vue core.

![image](https://user-images.githubusercontent.com/18205362/170408349-622a31db-bbff-49a0-9fda-7fc443f63e4b.png)

**Comment by meteorlxy** [comment]
Reported here: https://github.com/vuejs/core/issues/6008

**Comment by KnorpelSenf** [comment]
Thanks. I had played around with vuepress enough to have a feeling that it's in the Vue core lib, but I would've never figured it out.

I'll close this in favour of https://github.com/vuejs/core/issues/6008.
