### ISSUE TITLE
[Feature request] googleTranslate button

### ISSUE THREAD

**Issue by helpotcreator** [vuepress/vuepress-next#603]
### Description
I think, if there is a googleTranslate button in my vuepress .md pages(or header), then will be.... very useful for foreigners.
ex  (https://www.w3schools.com/howto/howto_google_translate.asp)

thanks.

**Comment by GregoireF** [comment]
Hi @helpotcreator,

I think that for the moment the module that would correspond the most to your expectation would be the linguistic translation system i18n proposed as current translation system in VuePress, moreover i18n proposes several plugins such as https://www.npmjs.com/package/i18next-google-translate which I think, can be why not an alternative also to your request?

Cheers

**Comment by helpotcreator** [comment]
thanks.
