### ISSUE TITLE
[Bug report] SidebarItem that are not links are not keyboard focusable

### ISSUE THREAD

**Issue by damiencornu** [vuepress/vuepress-next#604]
### Description

`SidebarItem` that contain children but that are not link themselves are not keyboard accessible because they are rendered as `<p>` without ARIA attribute. _For visual reference, this will happen only for SidebarItem rendered with an 'arrow' after them._

### Steps to reproduce

- Repo: [this repo docs](https://github.com/vuepress/vuepress-next)
- Link: [example page](https://v2.vuepress.vuejs.org/reference/cli.html)

When on the page start using your `Tab` key to navigate, you'll never land on `VuePress Reference`, `Bundlers Reference`, `Default Theme Reference` or `Official Plugins Reference` therefore you could not access those categories and explore their content from the sidebar.

### Expected behavior

While navigating using `Tab` / `shift`+`Tab` I expect to go through the top levels menu item even if they are not direct link to another page.

### Screenshots

<img width="300" alt="SidebarNavigation" src="https://user-images.githubusercontent.com/359119/147751726-22ed284f-cea9-4d01-930a-af269870aa4a.png">

### Environment info

```
  Browsers:
    Chromium: 93.0.4577.82
    Firefox: 95.0.2
    Safari: 15.1

  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.32
    @vuepress/bundler-webpack:  2.0.0-beta.32
    @vuepress/cli:  2.0.0-beta.32
    @vuepress/client:  2.0.0-beta.32
    @vuepress/core:  2.0.0-beta.32
    @vuepress/markdown:  2.0.0-beta.32
    @vuepress/plugin-active-header-links:  2.0.0-beta.32
    @vuepress/plugin-back-to-top:  2.0.0-beta.32
    @vuepress/plugin-container:  2.0.0-beta.32
    @vuepress/plugin-debug:  2.0.0-beta.32
    @vuepress/plugin-docsearch:  2.0.0-beta.32
    @vuepress/plugin-external-link-icon:  2.0.0-beta.32
    @vuepress/plugin-git:  2.0.0-beta.32
    @vuepress/plugin-google-analytics:  2.0.0-beta.32
    @vuepress/plugin-medium-zoom:  2.0.0-beta.32
    @vuepress/plugin-nprogress:  2.0.0-beta.32
    @vuepress/plugin-palette:  2.0.0-beta.32
    @vuepress/plugin-prismjs:  2.0.0-beta.32
    @vuepress/plugin-pwa:  2.0.0-beta.32
    @vuepress/plugin-pwa-popup:  2.0.0-beta.32
    @vuepress/plugin-register-components:  2.0.0-beta.32
    @vuepress/plugin-search:  2.0.0-beta.32
    @vuepress/plugin-shiki:  2.0.0-beta.32
    @vuepress/plugin-theme-data:  2.0.0-beta.32
    @vuepress/plugin-toc:  2.0.0-beta.32
    @vuepress/shared:  2.0.0-beta.32
    @vuepress/theme-default:  2.0.0-beta.32
    @vuepress/utils:  2.0.0-beta.32
    vue:  3.2.24
    vue-loader:  16.8.3
    vue-router:  4.0.12
    vuepress:  2.0.0-beta.32
    vuepress-vite:  2.0.0-beta.32
    vuepress-webpack:  2.0.0-beta.32
```

**Comment by damiencornu** [comment]
I'm not an expert in accessibility nor very familiar with Vue but would happily propose a fix myself and contribute to the repo if this is worth fixing in your opinion.

**Comment by meteorlxy** [comment]
@damiencornu Of course. A11y is important for sure. Contribution welcome!

**Comment by Lemmingh** [comment]
<https://github.com/vuepress/vuepress-next/blob/0934a5d6685922e0dc6391622b00a3b89140492c/packages/%40vuepress/theme-default/src/client/components/SidebarItem.vue#L54>

What about changing `<p>` to `<button>`, just like what MDN does, which can also get the accessibility tree nice.

**Comment by damiencornu** [comment]
If we switch to button we would have a default browser button style like so:

<img width="335" alt="Using button markup" src="https://user-images.githubusercontent.com/359119/149570730-91c548ea-9cee-41c5-a6be-1b4c258cd7b0.png">

The most straightforward in this case is to use the `tabindex="0"` property. Then the `<p>` markup would become keyboard focusable but the screen reader would not describe it well.

> just like MDN does

@Lemmingh I don't know exactly which part of the doc using button you were actually referring to but I went to a [random page](https://developer.mozilla.org/en-US/docs/Web/JavaScript) on their documentation and I see they are using the `details` and `summary` markups, maybe that's a good option.
I initially thought of using the [ARIA recommendation for accordions](https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html) approach but I fear this would not behave well in case of two levels imbrication.
Doing some tests using the MDN approach and will post my findings here.

**Comment by Lemmingh** [comment]
> If we switch to button we would have a default browser button style

I believe a serious designer won't rely on UA styles, unless they are critical for accessibility.

---

> use the `tabindex="0"` property. Then the `<p>` markup would become keyboard focusable but the screen reader would not describe it well.

That's expected, because **the accessibility tree goes wrong**!

Using the `tabindex` attribute on non-interactive elements is also **discouraged by accessibility guidelines**.

---

> I don't know exactly which part of the doc using button you were actually referring to

MDN uses `<button>` in navbar, and `<details>` in sidebar.

`<button>` makes customization easy.

**Comment by meteorlxy** [comment]
Implement with `tabindex="0"`. Feedback welcome

**Comment by meteorlxy** [comment]
@Lemmingh We almost reply in the same time lol.

Feel free to keep giving your suggestions 😄
