### ISSUE TITLE
[Bug report] User config dependencies are not watched on windows

### ISSUE THREAD

**Issue by richardmward** [vuepress/vuepress-next#611]
## Bug report
Modifying user config dependencies do not trigger the dev server to restart on windows.

### Description
`resolveDevUserConfig.ts` contains a method `resolveDeps` which does not work on windows because the paths are not in the correct format. The `filename` passed into the method is in the format `C:/dev/src/.../docs/.vuepress/config.js`, whereas the `require.cache` is in the format `C:\\dev\\src\\...\\docs\\.vuepress\\config.js`.

### Steps to reproduce
Create a `config.js` file which `require`s another dependency. Modify the dependency. The dev server does not restart.

### Expected behavior
The dev server to restart.

### Screenshots

Not applicable

### Environment info

- Browser: Firefox
- Output of `vuepress info`:

```bash
  System:
    OS: Windows 10
  ...
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.32
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.32
    @vuepress/client:  2.0.0-beta.32
    @vuepress/core:  2.0.0-beta.32
    @vuepress/markdown:  2.0.0-beta.32
    @vuepress/plugin-active-header-links:  2.0.0-beta.32
    @vuepress/plugin-back-to-top:  2.0.0-beta.32
    @vuepress/plugin-container:  2.0.0-beta.32
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.32
    @vuepress/plugin-git:  2.0.0-beta.32
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.32
    @vuepress/plugin-nprogress:  2.0.0-beta.32
    @vuepress/plugin-palette:  2.0.0-beta.32
    @vuepress/plugin-prismjs:  2.0.0-beta.32
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search:  2.0.0-beta.32
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.32
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.32
    @vuepress/theme-default:  2.0.0-beta.32
    @vuepress/utils:  2.0.0-beta.32
    vue:  3.2.26
    vue-loader: Not Found
    vue-router:  4.0.12
    vuepress: ^2.0.0-beta.32 => 2.0.0-beta.32
    vuepress-vite:  2.0.0-beta.32
    vuepress-webpack: Not Found
```

**Comment by Lemmingh** [comment]
<https://github.com/vuepress/vuepress-next/blob/0934a5d6685922e0dc6391622b00a3b89140492c/packages/%40vuepress/cli/src/commands/dev/resolveDevUserConfig.ts#L14>

<https://github.com/vuepress/vuepress-next/blob/0934a5d6685922e0dc6391622b00a3b89140492c/packages/%40vuepress/cli/src/commands/dev/resolveDevUserConfig.ts#L53>

Might be solved by [path normalization](https://nodejs.org/api/path.html#pathnormalizepath) before looking up the `require.cache`.

For example:

```javascript
require.cache[path.normalize(filename)]
```

**Comment by richardmward** [comment]
I think that it is already using `path.normalize` earlier in the chain - and that's the issue. The path library being uses always creates linux style paths, whereas require.cache will always use the OS's path style

**Comment by Lemmingh** [comment]
I'm talking about Node.js's `path`:

<https://github.com/nodejs/node/blob/69f487efc734f2b9bb67f46f99cd98e1c1e13d9b/lib/path.js#L1543>

Not VuePress's `path`:

<https://github.com/vuepress/vuepress-next/blob/0934a5d6685922e0dc6391622b00a3b89140492c/packages/%40vuepress/utils/src/index.ts#L9>

---

Node.js is OS-aware.

**Comment by richardmward** [comment]
Apologies - I didn't follow your link to the node path lib and assumed you meant the upath lib. In which case, I agree that should hopefully do it!
