### ISSUE TITLE
Unclear docs on plugin usage

### ISSUE THREAD

**Issue by avivace** [vuepress/vuepress-next#615]
Information on how to actually enable plugins (and write config for it) is a bit fragmented on the 2.x documentation.

E.g.: if I start looking in the Shiki page (https://v2.vuepress.vuejs.org/reference/plugin/shiki.html) I just find `npm i -D @vuepress/plugin-shiki@next`, nothing about how to enable the plugin in config.js.

For instance, 

```
plugins: [
    [plugin-shiki'), {'langs': ['asm']}],
  ],
```

Won't work with `plugin-shiki`, `vuepress-plugin-shiki` or`shiki`..

**Comment by meteorlxy** [comment]
We are assuming that users have read the basic guide https://v2.vuepress.vuejs.org/guide/plugin.html

Any advice for improvement?

**Comment by avivace** [comment]
> We are assuming that users have read the basic guide https://v2.vuepress.vuejs.org/guide/plugin.html
> 
> Any advice for improvement?

I think the confusion comes from this information not being in the Reference, but in the Guide, although "Install" steps are present in the in the Reference. I would at least link to the Guide page in the plugins page of the Reference. E.g. at least add something like "then enable it in your config.js as explain in the Plugins guide", after the `npm i -D` command.
What do you think? I can open up a PR if that makes sense.

**Comment by kylebutts** [comment]
I agree with @avivace, having also just struggled with getting shiki to work :-)
