### ISSUE TITLE
[Bug report] Maximum call stack size exceeded when extending default theme

### ISSUE THREAD

**Issue by MeFelixWang** [vuepress/vuepress-next#616]
## Bug report

Maximum call stack size exceeded when extending default theme.

### Description

I'm trying to extend the default theme according to doc, 

server started sucessfully without any warning or error, 

but the page is blank and `Maximum call stack size exceeded` shows in the console.

I'm not sure  what is wrong,

any help will be appreciated.

### Steps to reproduce

Step 1, create index.js under folder .vuepress/theme, and copy every code from doc into index.js

Step 2, create Layout.vue under folder .vuepress/theme/layouts, and copy every code from doc into Layout.vue

Step 3, copy every code from doc into .vuepress/config.js

Step 4, npm run docs:dev

### Expected behavior

A custom footer should appear at the bottom of the page

### Screenshots

Catalogue

![(B8}{F)5Z${W KTG@}PY~FE](https://user-images.githubusercontent.com/26833355/148521761-4d3ad61c-4708-4c66-a4bb-d998cf1d4635.png)

`.vuepress/theme/index.js`

![QQ截图20220107172121](https://user-images.githubusercontent.com/26833355/148521988-7c0777c3-94fc-4b98-973c-8aea2a311886.png)

`.vuepress/theme/layouts/Layout.vue`

![QQ截图20220107172145](https://user-images.githubusercontent.com/26833355/148522051-921e0296-e2e8-442c-9913-eccaca717a09.png)

`.vuepress/config.js`

![QQ截图20220107172316](https://user-images.githubusercontent.com/26833355/148522272-6e4b4a73-68a3-4ddd-89bb-3dcd6342308e.png)

warning and error in the console

![QQ截图20220107172547](https://user-images.githubusercontent.com/26833355/148522652-e8f1ab7e-3d2f-4730-bfcc-55d7cfbe4712.png)
![QQ截图20220107172559](https://user-images.githubusercontent.com/26833355/148522658-2724a563-343a-408c-93a8-da9f911cfb82.png)

### Environment info

- Browser:Chrome 96.0.4664.110
- Output of `vuepress info`:

```bash
System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    Memory: 5.45 GB / 15.88 GB
  Binaries:
    Node: 12.22.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.1 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.20.1.
  Browsers:
    Chrome: 86.0.4240.111
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.32
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  undefined (2.0.0-beta.32)
    @vuepress/client:  2.0.0-beta.32
    @vuepress/core:  2.0.0-beta.32
    @vuepress/markdown:  2.0.0-beta.32
    @vuepress/plugin-active-header-links:  2.0.0-beta.32
    @vuepress/plugin-back-to-top:  2.0.0-beta.32
    @vuepress/plugin-container:  2.0.0-beta.32
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.32
    @vuepress/plugin-git:  2.0.0-beta.32
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.32
    @vuepress/plugin-nprogress:  2.0.0-beta.32
    @vuepress/plugin-palette:  2.0.0-beta.32
    @vuepress/plugin-prismjs:  2.0.0-beta.32
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: ^2.0.0-beta.32 => 2.0.0-beta.32
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.32
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.32
    @vuepress/theme-default:  2.0.0-beta.32
    @vuepress/utils:  2.0.0-beta.32
    vue:  3.2.26
    vue-loader: Not Found
    vue-router:  4.0.12
    vuepress: ^2.0.0-beta.32 => 2.0.0-beta.32
    vuepress-vite:  undefined (2.0.0-beta.32)
    vuepress-webpack: Not Found
```

**Comment by meteorlxy** [comment]
Try removing the name of the component or renaming it
