### ISSUE TITLE
[Bug report] `@vuepress/plugin-shiki` not up to date

### ISSUE THREAD

**Issue by kylebutts** [vuepress/vuepress-next#623]
### Description

The `@vuepress/plugin-shiki` is about 10 months old and therefore has fewer themes and languages than the most up-to-date version of shiki. Is it possible to update the plugin please? https://www.npmjs.com/package/@vuepress/plugin-shiki

**Comment by meteorlxy** [comment]
> ... is about 10 months old

Sorry? 😅 

![image](https://user-images.githubusercontent.com/18205362/149084194-8e7a5d64-354e-476d-99ad-9db238802757.png)

**Comment by kylebutts** [comment]
that’s embarrassing! I totally read the original creation date. Sorry about that 🤦🏻‍♂️
