### ISSUE TITLE
vuepress markdown-it-mathjax3 build error[Bug report]

### ISSUE THREAD

**Issue by cloakscn** [vuepress/vuepress-next#633]
package.json
![image](https://user-images.githubusercontent.com/58796846/149668739-7b20cdb0-6b88-4a1b-a133-8bbfb96bcc95.png)
config.ts
![image](https://user-images.githubusercontent.com/58796846/149668758-aa682858-b936-4497-ac31-f1b96429ad95.png)
![image](https://user-images.githubusercontent.com/58796846/149668765-9df1cd75-c866-4f84-862f-0658830a4a19.png)
yarn dev is success,but yarn build is error
![image](https://user-images.githubusercontent.com/58796846/149668815-b3b881d5-ee0b-473a-90e7-f034210e36e4.png)
![image](https://user-images.githubusercontent.com/58796846/149668854-d7bdf448-d5d6-4415-8a17-472a0752b1c3.png)
When I saw this problem, the whole person collapsed

My guess is that the relevant types do not fit

### Steps to reproduce

- Reproduction link / repo:

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```

**Comment by meteorlxy** [comment]
See #328
