### ISSUE TITLE
[Bug report] Loading TailwindCSS through Vite postcss options breaks hot reload & randomly throws

### ISSUE THREAD

**Issue by LeBenLeBen** [vuepress/vuepress-next#642]
### Description

If you use the Vite bundler and setup custom PostCSS plugins, at least TailwindCSS, hot reload stop working when saving Markdown files. Also it randomly, but very often, display a blank page after refresh, with an error like the following in the console:

```
Uncaught ReferenceError: can't access lexical declaration 'defineClientAppEnhance' before initialization
    <anonymous> http://localhost:8080/@fs/Users/leben/Sites/chusho/packages/docs/node_modules/@vuepress/plugin-medium-zoom/lib/client/clientAppEnhance.js?t=1642606611699:9
clientAppEnhance.js:9:1
    <anonyme> http://localhost:8080/@fs/Users/leben/Sites/chusho/packages/docs/node_modules/@vuepress/plugin-medium-zoom/lib/client/clientAppEnhance.js?t=1642606611699:9
    InnerModuleEvaluation self-hosted:2388
    InnerModuleEvaluation self-hosted:2388
    InnerModuleEvaluation self-hosted:2388
    InnerModuleEvaluation self-hosted:2388
    InnerModuleEvaluation self-hosted:2388
    InnerModuleEvaluation self-hosted:2388
    InnerModuleEvaluation self-hosted:2388
    InnerModuleEvaluation self-hosted:2388
    evaluation self-hosted:2349
```

The plugin isn’t important here as the error randomly cycle through installed VuePress plugin.

### Steps to reproduce

See https://github.com/LeBenLeBen/vuepress-tailwindcss-bug

If you don’t see the ReferenceError the first time, try saving the file a couple of times.

### Expected behavior

The page should be hot-reloaded and no errors should be thrown.

### Screenshots

Not applicable

### Environment info

```bash
  System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 745.85 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.2/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Utilities:
    Git: 2.32.0 - /usr/local/bin/git
  Browsers:
    Chrome: 97.0.4692.71
    Edge: 97.0.1072.62
    Firefox: 96.0.1
    Safari: 15.1
  npmPackages:
    @vuepress/bundler-vite: ^2.0.0-beta.33 => 2.0.0-beta.33
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  undefined (2.0.0-beta.33)
    @vuepress/client:  2.0.0-beta.33
    @vuepress/core:  2.0.0-beta.33
    @vuepress/markdown:  2.0.0-beta.33
    @vuepress/plugin-active-header-links:  2.0.0-beta.33
    @vuepress/plugin-back-to-top:  2.0.0-beta.33
    @vuepress/plugin-container:  2.0.0-beta.33
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.33
    @vuepress/plugin-git:  2.0.0-beta.33
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.33
    @vuepress/plugin-nprogress:  2.0.0-beta.33
    @vuepress/plugin-palette:  2.0.0-beta.33
    @vuepress/plugin-prismjs:  2.0.0-beta.33
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.33
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.33
    @vuepress/theme-default:  2.0.0-beta.33
    @vuepress/utils:  2.0.0-beta.33
    vue:  3.2.27
    vue-loader: Not Found
    vue-router:  4.0.12
    vuepress: ^2.0.0-beta.33 => 2.0.0-beta.33
    vuepress-vite:  undefined (2.0.0-beta.33)
    vuepress-webpack: Not Found
```

**Comment by Zhengqbbb** [comment]
em... I saw your repo, it should be wrong configuration. TailwindCSS needs to be introduced and used in vite/webpack with postcss.
Show you the code: https://github.com/Zhengqbbb/vuepress2-template.
Maybe you will be inspired, I also suffered a lot at the beginning.

**Comment by frknasir** [comment]
@LeBenLeBen Hey, man! how did you get to make vuepress and tailwind to work? Ive going in cycles and I dont know what I am missing. I'd really appreciate your help. Thanks.

**Comment by Zhengqbbb** [comment]
Maybe this repo can help you: https://github.com/Zhengqbbb/vuepress2-template

**Comment by Zhengqbbb** [comment]
> @LeBenLeBen Hey, man! how did you get to make vuepress and tailwind to work? Ive going in cycles and I dont know what I am missing. I'd really appreciate your help. Thanks.

Maybe this repo can help you: https://github.com/Zhengqbbb/vuepress2-template
If it helps you, please give me a star in the plugin list. [star](https://github.com/Zhengqbbb/zhengqbbb.github.io)

**Comment by LeBenLeBen** [comment]
@frknasir You have examples for both Webpack and Vite [in this discussion](https://github.com/vuepress/vuepress-next/discussions/116), but as reported here, it doesn’t work properly, at least with Vite.

In the meantime, I set up a parallel process using Tailwind CLI, like they explain [in the docs](https://tailwindcss.com/docs/installation).

**Comment by Zhengqbbb** [comment]
> In the meantime, I set up a parallel process using Tailwind CLI, like they explain [in the docs](https://tailwindcss.com/docs/installation).

That is to say I need to run a Tailwind cli and Vuepress cli.Is that right ? 🤔

**Comment by LeBenLeBen** [comment]
@Zhengqbbb Yes, see https://tailwindcss.com/docs/content-configuration#it-just-isn-t-working-properly

**Comment by frknasir** [comment]
> https://github.com/Zhengqbbb/vuepress2-template

Thanks alot! Ill be trying that out.

**Comment by ctrlaltdylan** [comment]
Could I get some guidance on exactly how you guys are solving this problem?

I'm trying to run `tailwind` CLI alongside a `vuepress docs:dev` process, but `index.scss` is causing an infinite reload.

```javascript
// tailwind.config.js
module.exports = {
  purge: [
    "./index.html",
    "./docs/**/*.{vue,js,ts,jsx,tsx}",
  ],
  content: [
    "./docs/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

```javascript
// package.json
  "scripts": {
    "docs:dev": "vuepress dev docs --clean-cache",
    "docs:build": "vuepress build docs --clean-cache",
    "docs:info": "vuepress info",
    "start:css": "tailwindcss -o docs/.vuepress/styles/tailwind.css --watch",
    "build:css": "NODE_ENV=production tailwindcss -o src/tailwind.css -m"
  },

```

```scss
// docs/.vuepress/styles/index.scss
@import 'tailwind';
```

Running both commands results in an infinite update loop within the vite build during `vuepress docs:dev`:

```bash
[vite] hmr update ...
[vite] hmr update ...
[vite] hmr update ...
[vite] hmr update ...
[vite] hmr update ...
[vite] hmr update ...
```

**Comment by LeBenLeBen** [comment]
You shouldn’t import Tailwind in the styles already handled by Vuepress. You need a separate file that is only handled by the Tailwind CLI. I build mine in the Vuepress ˋpublic` directory and inject it manually in the head.

See:
- https://github.com/liip/chusho/blob/main/packages/docs/package.json
- https://github.com/liip/chusho/blob/main/packages/docs/.vuepress/config.js

**Comment by ctrlaltdylan** [comment]
Thanks @LeBenLeBen that's so helpful!

The only change I needed to make was include the `docs` subdirectory to the path in your `tailwind` command, but it works like a charm
