### ISSUE TITLE
[Bug report] When deploying a PWA, a service worker exists on desktop but not on mobile

### ISSUE THREAD

**Issue by 185driver** [vuepress/vuepress-next#647]
### Description

When a deployed project using the pwa plugin is opened on the desktop, a service worker is present and the app can be used offline. The same project opened on mobile cannot be used offline. No service worker is found.

### Steps to reproduce

1. Using a desktop browser, open the minimal reproduction project deployed on GitHub [here](https://185driver.github.io/vp2-min-pwa/).
2. Set the browser to offline mode using dev tools and note that it still functions normally.
3. Repeat the steps above, but on a mobile browser (Android or iOS) and note that the project no longer functions if offline.

- Reproduction link / repo:
- https://github.com/185driver/vp2-min-pwa
- https://185driver.github.io/vp2-min-pwa/

### Expected behavior

Behavior should be the same on mobile and desktop. The PWA should be usable offline on mobile too.

### Environment info

- Browser: Chrome Beta 98 on Windows and Android, Safari on iOS 15.2

### Additional Observations

Using the ADB plugin on Chrome Windows, I connected my deployed project on Android Chrome via USB to my desktop dev tools and noted that there was no service worker found in the mobile version. Though I don't know the cause of the missing service worker, I can confirm this is the presenting problem.

**Comment by Mister-Hope** [comment]
Hey, the link you are providing does not have a valid sw.

![image](https://user-images.githubusercontent.com/33315834/150663162-518980aa-becf-4f0e-943a-a152b51aa4bc.png)
![image](https://user-images.githubusercontent.com/33315834/150663171-aab66f7a-59bb-4fcd-baa6-a803899e2260.png)

The actual problem is that sw failed to fetch some of the resources registed in sw. So please check your deployment or other configs.

**Comment by 185driver** [comment]
Thanks for your feedback. I'm happy to make needed changes to the repro to make it work, but I'm seeing success with the sw and assets you mention, on desktop:

<img width="292" alt="sw" src="https://user-images.githubusercontent.com/1835454/150663464-ca0ba538-aac1-4040-8429-e2d32d30adb9.png">
<img width="370" alt="fetch" src="https://user-images.githubusercontent.com/1835454/150663470-822e2bbd-7d4d-498f-887a-70befdaa4ece.png">

For minimal repro purposes, I'm not aware that using absolute or relative links are an issue, but your point is well taken in general.

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/150667240-c76b1b1f-8c01-4642-9207-291b2ed8faa7.png)

**Comment by 185driver** [comment]
Well, that sure looks functional to me on mobile, especially given the presence of the A2HS banner. Thank you for testing it for me.

I'm not sure what to think about this as I didn't want to needlessly submit an issue, and yet my own experience appears to be the opposite of yours.  I cannot get a service worker to load on mobile using the vuepress pwa plugin, and I've tried it:

* across two separate projects
* on multiple devices
* on Android and iOS
* using Safari, Firefox, Edge, and three versions of Chrome

It's simply a no go here, except on desktop, which works just fine. I've not seen a PWA capable app behave this way before, so am wondering where to go from here.
