### ISSUE TITLE
[Bug report] absolute internal link with base option

### ISSUE THREAD

**Issue by jzz4012650** [vuepress/vuepress-next#652]
### Description

Absolute path in Link won't be translated to `<router-link>` but translated to `<a>`.

### Steps to reproduce

- Set `base` to `'/aaa'` in `docs/.vuepress/config.js`
- Write down absolute link in markdown file: `[Guide](/guide/README.md)` (example from [official docs](https://v2.vuepress.vuejs.org/guide/markdown.html#links))

### Expected behavior

The link  is translated to `<a href="/aaa/guide/">` but got `<a href="/guide/README.md" ...>` instead.

### Environment info

- Browser: latest Chrome.
- Output of `vuepress info`:

```bash
System:
    OS: macOS 12.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 1.81 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Utilities:
    Git: 2.32.0 - /usr/bin/git
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Not Found
    Firefox: 94.0.1
    Safari: 15.1
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.35 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.35 
    @vuepress/client:  2.0.0-beta.35 
    @vuepress/core:  2.0.0-beta.35 
    @vuepress/markdown:  2.0.0-beta.35 
    @vuepress/plugin-active-header-links:  2.0.0-beta.35 
    @vuepress/plugin-back-to-top:  2.0.0-beta.35 
    @vuepress/plugin-container:  2.0.0-beta.35 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.35 
    @vuepress/plugin-git:  2.0.0-beta.35 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom: ^2.0.0-beta.35 => 2.0.0-beta.35 
    @vuepress/plugin-nprogress:  2.0.0-beta.35 
    @vuepress/plugin-palette:  2.0.0-beta.35 
    @vuepress/plugin-prismjs:  2.0.0-beta.35 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: ^2.0.0-beta.35 => 2.0.0-beta.35 
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.35 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.35 
    @vuepress/theme-default:  2.0.0-beta.35 
    @vuepress/utils:  2.0.0-beta.35 
    vue:  3.2.29 
    vue-loader: Not Found
    vue-router:  4.0.12 
    vuepress: Not Found
    vuepress-vite: ^2.0.0-beta.35 => 2.0.0-beta.35 
    vuepress-webpack: Not Found
```

**Comment by meteorlxy** [comment]
![image](https://user-images.githubusercontent.com/18205362/150912007-db0f54ce-d6e5-413d-9560-d89a445768f8.png)

![image](https://user-images.githubusercontent.com/18205362/150912123-3133cf49-3b19-41a4-a14d-3bcbed3bda4d.png)

**Comment by Mister-Hope** [comment]
哈哈哈哈哈哈哈，图收了

**Comment by Mister-Hope** [comment]
Honestly, I can fully understand this issue, because v1 does support it, and it’s not mentioned in https://v2.vuepress.vuejs.org/guide/migration.html

maybe we should add a warning in this page?

**Comment by jzz4012650** [comment]
> ![image](https://user-images.githubusercontent.com/18205362/150912007-db0f54ce-d6e5-413d-9560-d89a445768f8.png)
> 
> ![image](https://user-images.githubusercontent.com/18205362/150912123-3133cf49-3b19-41a4-a14d-3bcbed3bda4d.png)

看过文档才提的；

看了 [源码](https://github.com/vuepress/vuepress-next/blob/fbb805cee7650d6308857d1c5ac8365b7bd066f8/packages/%40vuepress/shared/src/utils/isLinkExternal.ts#L14) 之后，猜想是因为如果同时部署了多个不同 `base` 的文档在同一个域下的时候，简单粗暴将 `/` 开头的地址都转为了 `<router-link>`，将会误伤跳转到另一个 `base` 的 path，导致无法跳出当前 `base`，只能手动加上完整域名（端口）；

不过是否可以考虑提供一种方式设置当前 `base` 内的绝对路径跳转，毕竟用相对路径，文档一句话描述起来简单，真的写起来还是挺难受的，且不利于文档路径（文件目录）的调整；

当下用正则批量替换了绝对路径的 Link，改为了 `<router-link>`，正则如下，供后面遇到同样问题的小伙伴参考：

`\[([^\]]*)\]\((\/[^)]*)\)` => `<router-link to="$2">$1</router-link>`

**Comment by jzz4012650** [comment]
> Honestly, I can fully understand this issue, because v1 does support it, and it’s not mentioned in https://v2.vuepress.vuejs.org/guide/migration.html
> 
> maybe we should add a warning in this page?

Migration 里提下就很好；

**Comment by meteorlxy** [comment]
> 看过文档才提的；

那你提的应该是 Feature Request 而不是 Bug Report

**Comment by meteorlxy** [comment]
> Honestly, I can fully understand this issue, because v1 does support it, and it’s not mentioned in [v2.vuepress.vuejs.org/guide/migration.html](https://v2.vuepress.vuejs.org/guide/migration.html)
> 
> maybe we should add a warning in this page?

Just looked back at v1's implementation, it simply treats all `/$` `.md$` or `.html$` links as router-link without checking the base 🤔 

> 看了 源码 之后，猜想是因为如果同时部署了多个不同 base 的文档在同一个域下的时候，简单粗暴将 / 开头的地址都转为了 <router-link>，将会误伤跳转到另一个 base 的 path，导致无法跳出当前 base，只能手动加上完整域名（端口）；

是的，最初迁移的时候是这个想法，不过如果在实际使用过程中这种情况反而很少见的话，按照你说的默认加 `base` 肯定是更好的做法

**Comment by Mister-Hope** [comment]
我觉得这里完全可以做一个markdown插件来处理这个问题。把以.md结尾/开头的路径通过插件补base，自己决定是否调用插件就好了。

上述插件应该挺好写的。@jzz4012650
