### ISSUE TITLE
[Feature request] 设置 base 选项的时候，站内绝对路径不需要改为相对路径

### ISSUE THREAD

**Issue by jzz4012650** [vuepress/vuepress-next#653]
### Description

关联讨论 #652 

设置了 `base` 选项的时候，希望能够自动将站内绝对路径转为 `<router-link>`，而现在会转为 `<a>`，导致需要将绝对路径改为相对路径；（关联[文档](https://v2.vuepress.vuejs.org/guide/markdown.html#links)）

### Proposed Solution

以 `base` 为 `/foo` 的情况为例：

- 对于跳转站内地址：在 Markdown 中直接编写绝对路径，例如：`[Guide](/guide/)`
- 对于跳转同一域下的其他地址（非当前 `base` 地址开头）：
  - 可以指定完整 URL 信息：`[Guide](https://some-site.com/bar/guide/)`
  - 或者换用 `<a>` 标签：`<a href="/bar/guide/">Guide</a>`

> 以上提议基于站内跳转比较频繁，同域跨站跳转相对小众的情况考虑；

PS：Vue-Press 是个优秀的静态站点生成工具，插件化设计尤其棒，感谢开发组同学们的付出 ❤️ ！

**Comment by Mister-Hope** [comment]
Just inspired by #694, maybe we could add a hack here make the following different?

Probably in core or as a new plugin?

- `/abc.html` pointing to base root as expected
- `$abc.html` poiting to host root

E.g.: with base `/demo/`:

- `/abc.html` is `/demo/abc.html`
- `$abc.html` is `/abc.html`

@meteorlxy is this ok for you?

**Comment by KevinBrother** [comment]
> Just inspired by #694, maybe we could add a hack here make the following different?
> 
> Probably in core or as a new plugin?
> 
> * `/abc.html` pointing to base root as expected
> * `$abc.html` poiting to host root
> 
> E.g.: with base `/demo/`:
> 
> * `/abc.html` is `/demo/abc.html`
> * `$abc.html` is `/abc.html`
> 
> @meteorlxy is this ok for you?

Does it supported now?

**Comment by Mister-Hope** [comment]
I will share some other advantages when using relative links.

1. It benifits when your user are browsering source markdown files, relative links works in editors and git provider like github, but an absolute link will be broken in that case.
2. It's not recommanded to change your doc structure very often, as users may add them as bookmark, or reference theme in other places, it's allways good to choose a good link wisely at the beginning, and even if you change the url, you would bettr keep the old link available, just see what vue is doing at [here](https://v2.vuejs.org/v2/guide/?redirect=true) And if you make sure the old link is available, there would be no broken links even if you forgot some.

But on the other hand, I do agree that it's good to have something I mention above to provide users more choise.

**Comment by Mister-Hope** [comment]
@meteorlxy I am planning to work on this, and I want to make sure that if this is ok to you:

Starting with `base: '/base/` as an exmple.

All markdown links should be resolved as `<RouterLink />` so:

```md
[Home](/README.md)
[Guide](/guide.md)
```

should be 

```html
<RouterLlink to="/">Home</RouterLink>
<RouterLlink to="/guide.html">Guide</RouterLink>
```

which is acutally:

```html
<a href="/base/">Home</a>
<a href="/base/guide.html">Guide</a>
```

And when user want some thing without base, they should use a link not ending with `.md`, and we will keep them as is:


```md
<!-- /index.html should be the same--> 
[Home](/)
[Guide](/guide.html)
```

should be 

```html
<!-- or /index.html when setting /index.html --> 
<a href="/">Home</a>
<a href=/guide.html">Guide</a>
```

**Comment by ascott18** [comment]
For anyone else running into this while the linked PR is not yet merged, you can solve this with a simple inline plugin that hacks markdown-it to prepend the base URL:

``` ts
const baseUrl = "/SomeBaseUrl"
export default {
  base: `${baseUrl}/`,
  plugins: [
    {
      // Workaround for https://github.com/vuepress/vuepress-next/issues/653
      // Prepend absolute URLs with base URL.
      name: "baseify-link",
      extendsMarkdown(md) {
        const old = md.normalizeLink;
        md.normalizeLink = (url) => {
          url = old(url);
          if (url.startsWith("/") && !url.startsWith(baseUrl)) {
            url = baseUrl + url
          }
          return url;
        }
      }
    },
  ]
}
```

**Comment by ascott18** [comment]
@meteorlxy the fix in the linked commit doesn't work for `.md` links that include a fragment. E.g. it works for `/some/file.md`, but does not work for `/some/file.md#heading`.

Would you like me to open a new issue, or do you want to reopen this one to track this?

**Comment by meteorlxy** [comment]
@ascott18 It's better to open another bug report for that.
