### ISSUE TITLE
[Bug report] Vite `Error: Could not load @vuepress/plugin-palette/style`

### ISSUE THREAD

**Issue by chris-dura** [vuepress/vuepress-next#663]
### Description

Running build with local theme that extends default-theme causes vite to throw error:
```
ENOENT: no such file or directory, open '@vuepress/plugin-palette/style
```
Console output:

```zsh
> vuepress-starter@1.0.0 docs:build
> vuepress build src --debug

info Initializing VuePress and preparing data...
⠋ Compiling with vitevite v2.7.13 building for production...
vite v2.7.13 building SSR bundle for production...
✓ 126 modules transformed.
[vite:vue] Could not load @vuepress/plugin-palette/style?vue&type=style&index=1&src=89f7fb6e&lang.scss (imported by src/.vuepress/theme/layouts/Layout.vue): ENOENT: no such file or directory, open '@vuepress/plugin-palette/style'
✖ Compiling with vite - failed
Error: Could not load @vuepress/plugin-palette/style?vue&type=style&index=1&src=89f7fb6e&lang.scss (imported by src/.vuepress/theme/layouts/Layout.vue): ENOENT: no such file or directory, open '@vuepress/plugin-palette/style'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at Object.load (/Users/P2185561/code/vuepress-starter-kiteds/node_modules/@vitejs/plugin-vue/dist/index.js:4811:37)
    at /Users/P2185561/code/vuepress-starter-kiteds/node_modules/rollup/dist/shared/rollup.js:22815:37
...
```

### Steps to reproduce

1. Create a local theme that extends default-theme: https://v2.vuepress.vuejs.org/reference/default-theme/extending.html#extending
2. Add palette support to local theme `Layout.vue`: https://v2.vuepress.vuejs.org/reference/plugin/palette.html#palette

```vue
// .vuepress/theme/layouts/Layout.vue

<script setup>
	import ParentLayout from '@vuepress/theme-default/lib/client/layouts/Layout.vue';
</script>

<template>
	<ParentLayout>
		<template #page-bottom>
			<div class="my-footer">This is my custom page footer</div>
		</template>
	</ParentLayout>
</template>

<style lang="scss">
	@import '@vuepress/plugin-palette/palette';

	.my-footer {
		text-align: center;
	}
</style>

<style lang="scss" src="@vuepress/plugin-palette/style"></style>
```

- Reproduction link / repo: n/a

### Expected behavior

- Project builds with no errors.

### Environment info

- Browser: not related
- Output of `vuepress info`:

```bash
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 339.95 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: Not Found
    npm: 7.24.1 - ~/.nvm/versions/node/v14.18.0/bin/npm
  Utilities:
    Git: 2.31.0 - /usr/local/bin/git
  Browsers:
    Chrome: 97.0.4692.99
    Edge: 97.0.1072.76
    Firefox: 96.0.2
    Safari: 15.3
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.35 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.35 
    @vuepress/client:  2.0.0-beta.35 
    @vuepress/core:  2.0.0-beta.35 
    @vuepress/markdown:  2.0.0-beta.35 
    @vuepress/plugin-active-header-links:  2.0.0-beta.35 
    @vuepress/plugin-back-to-top:  2.0.0-beta.35 
    @vuepress/plugin-container:  2.0.0-beta.35 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.35 
    @vuepress/plugin-git:  2.0.0-beta.35 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.35 
    @vuepress/plugin-nprogress:  2.0.0-beta.35 
    @vuepress/plugin-palette:  2.0.0-beta.35 
    @vuepress/plugin-prismjs:  2.0.0-beta.35 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.35 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.35 
    @vuepress/theme-default:  2.0.0-beta.35 
    @vuepress/utils:  2.0.0-beta.35 
    vue:  3.2.29 
    vue-loader: Not Found
    vue-router:  4.0.12 
    vuepress: ^2.0.0-beta.35 => 2.0.0-beta.35 
    vuepress-vite:  2.0.0-beta.35 
    vuepress-webpack: Not Found
```

**Comment by chris-dura** [comment]
The staleness bot is a bit aggressive I think...

**Comment by Mister-Hope** [comment]
Vite is a **VERY SIMPLE** tool, and as it's tarting great speeed, so it's very agressive

e.g: you are not allowed to use `process.env.` in strings.

Since Vite plugin vue doesn't tell you that alias work in style block, so probably it do not support it. And I am assuming you know that `vuepress/plugin-palette/style` is a alia.

```html
<style lang="scss" src="@vuepress/plugin-palette/style"></style>
```

Here is some recommandation:

1. Switch to `bundler-webpack` to see if the issue still exists, if not, try posting issue in Vite plugin Vue.
2. If so, welcome to feedback and we are happy to have another check.

**Comment by chris-dura** [comment]
> Vite is a **VERY SIMPLE** tool, and as it's tarting great speeed, so it's very agressive
> 
> e.g: you are not allowed to use `process.env.` in strings.
> 
> Since Vite plugin vue doesn't tell you that alisas work in style block, so probably it do not support it. And I am assuming you know that `vuepress/plugin-palette/style` is a alisa.
> 
> ```
> <style lang="scss" src="@vuepress/plugin-palette/style"></style>
> ```
> 
> Here is some recommandation:
> 
> 1. Switch to `bundler-webpack` to see if the issue still exists, if not, try posting issue in Vite plugin Vue.
> 2. If so, welcome to feedback and we are happy to have another check.

@Mister-Hope -- I followed the documentation for `@vuepress/plugin-palette` here:
https://v2.vuepress.vuejs.org/reference/plugin/palette.html#usage

Why do you think this is an issue with the webpack/vite bundlers, and not the official `@vuepress/plugin-palette`?

**Comment by Mister-Hope** [comment]
So is webpack working?

**Comment by chris-dura** [comment]
> So is webpack working?

I tried following the docs to [switch to webpack](https://v2.vuepress.vuejs.org/guide/bundler.html#choose-a-bundler)
```sh
npm uninstall vuepress
npm install -D vuepress-webpack@next
```
... but I got a `Error: Cannot find module 'vuepress'` when I run `npm run docs:build`

So, I tried this, instead:
```sh
npm install -D vuepress@next
npm install -D vuepress-webpack@next
```
But, the `npm run docs:build` still was using `vite`, so I switched the npm script to use the `vuepress-webpack` package:

```json
  "scripts": {
    "docs:dev": "vuepress-webpack dev src --debug",
    "docs:build": "vuepress-webpack build src --debug",
```
This gets the project to build with no warnings, so I assume (?) it compiled and the palette plugin is working as the examples.

Summary:

1. The [Choose a Bundler](https://v2.vuepress.vuejs.org/guide/bundler.html#choose-a-bundler) docs don't work for a user who goes through the [Getting Started](https://v2.vuepress.vuejs.org/guide/getting-started.html#getting-started) steps first. (seems that `npm i -D vuepress-webpack@next` needs to install the `vuepress` module?)
2. The [palette plugin Usage example](https://v2.vuepress.vuejs.org/reference/plugin/palette.html#usage) doesn't work properly with `vite` (which is the default bundler).

**Comment by meteorlxy** [comment]
@chris-dura Wierd, the `vuepress-webpack` package also provide a `vuepress` binary:

https://github.com/vuepress/vuepress-next/blob/73d297f321750de098c22c8c774dbe934475ddcb/packages/vuepress-webpack/package.json#L23-L26

**Comment by chris-dura** [comment]
> @chris-dura Wierd, the `vuepress-webpack` package also provide a `vuepress` binary:
> 
> https://github.com/vuepress/vuepress-next/blob/73d297f321750de098c22c8c774dbe934475ddcb/packages/vuepress-webpack/package.json#L23-L26

I thought so too... I tried a "fresh" `npm install`, but I'm still getting the same error... 🤷 

```sh
npm i -D vuepress-webpack@next
rm -rf package-lock.json
rm -rf node_modules/
npm install
```

```sh
npm run docs:build

> vuepress-starter@1.0.0 docs:build
> vuepress build src --debug

Error: Cannot find module 'vuepress'
Require stack:
- /Users/P2185561/code/vuepress-starter/src/.vuepress/config.ts
- /Users/P2185561/code/vuepress-starter/node_modules/@vuepress/cli/lib/config/loadUserConfigEs.js
- /Users/P2185561/code/vuepress-starter/node_modules/@vuepress/cli/lib/config/loadUserConfig.js
- /Users/P2185561/code/vuepress-starter/node_modules/@vuepress/cli/lib/config/index.js
- /Users/P2185561/code/vuepress-starter/node_modules/@vuepress/cli/lib/commands/build/createBuild.js
- /Users/P2185561/code/vuepress-starter/node_modules/@vuepress/cli/lib/commands/build/index.js
- /Users/P2185561/code/vuepress-starter/node_modules/@vuepress/cli/lib/commands/index.js
- /Users/P2185561/code/vuepress-starter/node_modules/@vuepress/cli/lib/index.js
- /Users/P2185561/code/vuepress-starter/node_modules/@vuepress/cli/bin/vuepress.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/P2185561/code/vuepress-starter/src/.vuepress/config.ts:28:34)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.require.extensions..ts (/Users/P2185561/code/vuepress-starter/node_modules/@vuepress/cli/lib/utils/allowTs.js:11:11)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```
