### ISSUE TITLE
[Feature request] markdown 内使用「vue3」import 同目录下的 name.ts 文件

### ISSUE THREAD

**Issue by xiaoxunyao** [vuepress/vuepress-next#666]
### Description
在跟markdown文件的同级文件下，创建了一个「datas.ts」，想将这个ts文件import进入markdown文件的「<script setup>」标签内，但是出现下面的错误。

```shell
下午8:11:11 [vite] Internal server error: Failed to resolve import "./datas" from "src/.vuepress/.temp/pages/blog/content/content.html.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/xiaoxunyao/Documents/vue/inet.org/src/.vuepress/.temp/pages/blog/content/content.html.vue
```

### Proposed Solution

我已经开始头疼了，我没有解决方案。

出现问题的github地址：[地址](https://github.com/xiaoxunyao/inet.org/tree/master/src/blog/content)

**Comment by Mister-Hope** [comment]
You should use a full path to import, vite is not directly importing markdown files, instead, it transpile the markdown files in "prepare" stage, and transform it in to a standard vue component js files and store it in `.vuepress/.temp/internal/`. In this way there won't be a "data.ts" inside that folder.

So you should try placing all you code in a source folder (code fodler) make an alias for that folder then import it with alisas you set.

Is this description clear enough for you?

**Comment by xiaoxunyao** [comment]
Thank you. I will modify it according to your description!

**Comment by xiaoxunyao** [comment]
Thank you very much, the problem has been solved
