### ISSUE TITLE
[Bug report] the default value of docsDir should be `'docs'` rather than `''`

### ISSUE THREAD

**Issue by zh-lx** [vuepress/vuepress-next#667]
### Description

When I click `edit this page` without setting `docsDir` option of Locale configuration, the page of github that is opened will be 404 because the path is error. By default, the `.md` files are in `docs` folder, so I think the default value of docsDir should be `'docs'` rather than `''`. And in this case, the page of github that is opened will be correct when I click `edit this page` without setting `docsDir` option.

### Steps to reproduce
- click `edit this page` without setting `docsDir` option

**Comment by Mister-Hope** [comment]
### It's just **your personal taste**.

- there are a lot repos, which is using /README.md as the docs entry
- also lots of project are placing docs in a sperate repo (e.g.: https://github.com/vuejs/docs using src)
-  also there are some repo using `doc` `reference` or other folders ,(e.g.: https://github.com/remarkjs/remark)

As we have already told everyone in the docs that the `docsDir` is `''` by default, there is not **"A Bug"** here. Basicly I have plenty of reservations about your "change‘
