### ISSUE TITLE
[Feature request] Allow different prism color schemes for light and dark mode

### ISSUE THREAD

**Issue by hughlv** [vuepress/vuepress-next#670]
### Description

The current version of plugin vuepress-plugin-prism does not provide userful configuration options. Under light mode of Vuepress, a light background of code block is more appropriate for reading, like the VS color scheme. Currently the default color scheme only fits the dark background.

Different prism color scheme configurations for light and dark modes are very required.

### Proposed Solution

Two options of plugin-prism in config.ts: `colorScheme : <string>` and `colorSchemeDark : <string>`

**Comment by meteorlxy** [comment]
I think it's better to importing the prism theme manually 🤔 

The documentation should be improved

**Comment by Mister-Hope** [comment]
vuepress-theme-hope supports it, you can see it's implementation. I think it's not necessary for default theme to support it if we want the theme to be simple.
