### ISSUE TITLE
[Bug report]upgrade vuepress@2.0.0-beta.35 get error: Cannot access 'clientAppEnhances' before initialization

### ISSUE THREAD

**Issue by daiwanxing** [vuepress/vuepress-next#673]
### Description

When I upgrade vuepress 2.0.0-beta.25 to 2.0.0-beta.35 and run dev then I get a error, `Uncaught (in promise) ReferenceError: Cannot access 'clientAppEnhances' before initialization`. I didn't get it why happend this error?

### Steps to reproduce

- Reproduction link / repo:

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```
![image](https://user-images.githubusercontent.com/37327614/152713210-dc96aa9c-1416-40b9-8fce-5862a61dbad8.png)

**Comment by artiely** [comment]
I had the same problem

**Comment by artiely** [comment]
I encountered the same problem, but it doesn't seem to be directly related to the version. I am developing a theme, and this problem occurs when I install the dependencies in the theme directory. When I delete the node_modules under the theme, install the dependencies to  When the project root directory, everything works fine.  I also don't know what is causing this problem.

**Comment by artiely** [comment]
I seem to have solved my problem, in my case I can no longer depend on vuepress or any packages under @vupress/* in the theme package.
