### ISSUE TITLE
build 资源引用出错

### ISSUE THREAD

**Issue by sunsboyxu** [vuepress/vuepress-next#679]
# vuepress docs build 资源引用出错
## 版本号
- vuepress: 2.0.0-beta.35
![资源引用错误](https://infosalons.oss-cn-shanghai.aliyuncs.com/upload/error1.png "代码截图1")
![资源引用错误](https://infosalons.oss-cn-shanghai.aliyuncs.com/upload/error2.png "代码截图2")
![资源引用错误](https://infosalons.oss-cn-shanghai.aliyuncs.com/upload/error3.png "代码截图3")

**Comment by Mister-Hope** [comment]
No offense, but do you configue your server correctly? Any file which has a J's extension should be regarded as a JavaScript file, but it seems that your server is providing a MIME type of html.

So why is this fault related to VuePress and why do you post here?

**Comment by meteorlxy** [comment]
Please follow the template when reporting issues, or go to the Discussion panel to ask questions.

As @Mister-Hope pointed out, it seems that there are something wrong with your server.
