### ISSUE TITLE
[Bug report] Inline code with backticks(`) mistakenly parsed as mustache

### ISSUE THREAD

**Issue by noyidoit** [vuepress/vuepress-next#683]
### Description
Some of inline code (using ``) may be mistakenly parsed as mustache, and will incur fatal error.

### Steps to reproduce
Add such text in markdown file
```plain
...
we can use `@csrf`
and `{{ csrf_field() }}` works too
...
```
then run `npm run docs:dev`, in browser, we can see the whole page does work like the screenshot.

- Reproduction link / repo: https://codesandbox.io/s/exciting-pine-sm67u?file=/README.md

### Expected behavior

Inline code work as markdown inline code, not parse as vue code

### Screenshots

![image](https://user-images.githubusercontent.com/26378591/153530626-652cc010-23a1-4310-850e-edf9b1ce9324.png)

### Environment info

- Browser: Edge in linux, Version 97.0.1072.21 (Official build) beta (64-bit)
- Output of `vuepress info`:
```bash

> docs:info
> vuepress info


  System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 1.34 GB / 15.54 GB
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.17.1 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
  Utilities:
    Git: 2.25.1 - /usr/bin/git
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: Not Found
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.35 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.35 
    @vuepress/client:  2.0.0-beta.35 
    @vuepress/core:  2.0.0-beta.35 
    @vuepress/markdown:  2.0.0-beta.35 
    @vuepress/plugin-active-header-links:  2.0.0-beta.35 
    @vuepress/plugin-back-to-top:  2.0.0-beta.35 
    @vuepress/plugin-container:  2.0.0-beta.35 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.35 
    @vuepress/plugin-git:  2.0.0-beta.35 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.35 
    @vuepress/plugin-nprogress:  2.0.0-beta.35 
    @vuepress/plugin-palette:  2.0.0-beta.35 
    @vuepress/plugin-prismjs:  2.0.0-beta.35 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: ^2.0.0-beta.35 => 2.0.0-beta.35 
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.35 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.35 
    @vuepress/theme-default:  2.0.0-beta.35 
    @vuepress/utils:  2.0.0-beta.35 
    vue:  3.2.30 
    vue-loader: Not Found
    vue-router:  4.0.12 
    vuepress: ^2.0.0-beta.35 => 2.0.0-beta.35 
    vuepress-vite:  2.0.0-beta.35 
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
That's expected.

create a div out side your code block and add `v-pre` attr:

```
<div v-pre>
...
we can use `@csrf`
and `{{ csrf_field() }}` works too
...
</div>
```

**Comment by noyidoit** [comment]
First of all, thanks for reply.

> As each file is parsed as a comonent , mustache has the hightest property is the expected behaviour.

While code block (```) works fine, code in backticks (`) doen't work, I guess if that's related with priority, either both of them work, or both of them does not work.

> You should aviod parsing them yourself.

I'm not parsing anything, I just write markdown (not vuepress.theme or vuepress.plugin or anything else), and I expect `` `{{ csrf_field() }}` `` work as `` `@csrf` ``, like raw markdown does.

**Comment by noyidoit** [comment]
@Mister-Hope 
I think wrap code with `v-pre` is not a solution for user, but a workaround, because it's more like html rather than markdown. (I know markdown is a superset of html)

Leave that philosophical questions, the actual problem is:

As the [document](https://v2.vuepress.vuejs.org/guide/markdown.html#wrap-with-v-pre) says:

> VuePress will add v-pre directive to your code blocks by default

As it says, vuepress will add v-pre for code blocks and everything will be kept as is by default, as the reproduction link shows, inline code between backticks(`) will compiled by Vue, not kept as is, while code block and inline code will both kept as is in markdown. Such an inconsistency doesn't look like was designed.

**Comment by Mister-Hope** [comment]
Didnot notice v2 change that.

If @meteorlxy  agrees that it make sence that inline `<code>` tag should  wrapped with `v-pre`, I can open a pr for that.
