### ISSUE TITLE
[Bug report]v2.0.0-beta.35,侧边栏sidebar配置children，使用{}方式。触发菜单后无法展示页面标题

### ISSUE THREAD

**Issue by 407365100** [vuepress/vuepress-next#684]
### Description
1.配置文件

```
sidebar: {
    '/pages/': [
        {
	    text: '部署环境',
	    children: [
		    'file1.md',//第1处
		    {
			text: 'file2.md',//第2处
			link: 'file2.md'
		    }    
	    ]
        }
    ]
},
```

2.file1.md、file2.md文件：

```

## 1.标题1

测试测试测试测试测试

## 2.标题2

测试测试测试测试测试

```

### Steps to reproduce

点击侧边栏菜单file1.md，能够展示子菜单【1.标题1、2.标题2】；
点击侧边栏菜单file2.md，无法展示子菜单

- Reproduction link / repo:

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```

**Comment by Mister-Hope** [comment]
Reproduction repo link plz?

**Comment by meteorlxy** [comment]
https://github.com/vuepress/vuepress-next/blob/4488cb31d01cf9a198124631f5e3296d1d0f12ab/docs/reference/default-theme/config.md?plain=1#L287-L290

The children will autoly generated only when you use string as the sidebar item
