### ISSUE TITLE
[Feature request]: Footnotes similar to Github

### ISSUE THREAD

**Issue by matthiasg** [vuepress/vuepress-next#685]
### Description

When writing documentation it is often helpful to have section or page footnotes. 

### Proposed Solution

Basically the implemenation could be similar to how github does it.

(https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/)

Similarily an implementation can be found at https://github.com/markdown-it/markdown-it-footnote

I believe this is a fundamental feature of the markdown renderer and could arguably become part of vuepress without a plugin.

**Comment by Mister-Hope** [comment]
Nope, instead vuepress2 are trying to decouple everthing.

You can easily have it done through plugins or use extendsmarkdown yourself.

Here is a recommandation: https://vuepress-theme-hope.github.io/v2/md-enhance/

**Comment by ArsalaBangash** [comment]
I agree with @Mister-Hope about keeping the markdown parser simple, but maybe a CLI tool to help somebody configure additional markdown features would be helpful for some. 

For now I would [enable footnotes on the MD Enhance plugin](https://vuepress-theme-hope.github.io/v2/md-enhance/guide/footnote.html#configuration)

**Comment by matthiasg** [comment]
github markdown is already supported and not "simple".

As footnotes is a feature also supported by GitHub since last year I would assume the parser in cue press should follow those conventions to ensure less confusion for newcomers.

Otherwise a more simplified markdown parser should be used and GitHub parsing be an optional feature, possibly be provided by a plug-in.

**Comment by Mister-Hope** [comment]
> Otherwise a more simplified markdown parser should be used and GitHub parsing be an optional feature, possibly be provided by a plug-in.
Why are you sticking to GFM? 

> github markdown is already supported and not "simple".
We are using `markdown-it` and `markdown-it` do not support footnote by default, also it doesn't support tasklist, delete line which Github supports. 

All the features you need are already provided in plugins. That's VuePress design goal : A statice generator with plugin supported.

Your need is reasonable, but I think the currect behavior is also resonable as we are making only a few edits on markdown-it.

**Comment by Mister-Hope** [comment]
My personal opinion is if there is something we should add in the docs, it's only emphasizing we support CommonMark in [this page](https://v2.vuepress.vuejs.org/guide/markdown.html) All our built-in enhancement are at code blocks.

**Comment by matthiasg** [comment]
I think I was misled by the comments on GFM at that page maybe they should be taken out. Staying with markdown-it is fine with me.  I will see what markdown-it stands on foot notes

**Comment by Mister-Hope** [comment]
Hi bro, Markdown-it supports commonmark only.

**Comment by Mister-Hope** [comment]
Also, your idea about adding a plugin to add full support to GFM is fine to me. But I disagree it should be add to core.

I will add a new GFM option in vuepress-plugin-md-enhance in future verions, and thanks for that suggestion.

**Comment by Mister-Hope** [comment]
Update: `vuepress-plugin-md-enhance` now adds a `gfm` option to align behavior with gfm.
