### ISSUE TITLE
[Bug report] $withBase / alias not working as expected

### ISSUE THREAD

**Issue by Jojoshua** [vuepress/vuepress-next#694]
### Description

I am referencing https://v2.vuepress.vuejs.org/guide/assets.html#base-helper to fix the prefixes in my internal markdown links and observing that the alias isn't working. 

For example, the base in config.ts is...  base: "/testsite"

When I use [test] ($withBase/intro) the resulting url is http://192.168.56.1:8080/testsite/$withBase/intro

I attempted to bybasss $withBase and try a custom vite alias (https://vitejs.dev/config/#resolve-alias) but had the exact same type of result.

### Steps to reproduce

1. Add a base url to the config
2. Use $withBase in a markdown link to reference another page in the internal site

- Reproduction link / repo:

### Expected behavior

I expected when using [test] ($withBase/intro) that the result url would be http://192.168.56.1:8080/testsite/intro

### Screenshots

N/A

### Environment info

- Browser: Chrome
- vuepress: 2.0.0-beta.35
- Output of `vuepress info`: N/A

```bash
# Paste output of `vuepress info` here How is this obtained?
```

**Comment by Jojoshua** [comment]
I noticed that doing [test] (. /intro) produces the intended result. Is this something I can count on going forward?

**Comment by Mister-Hope** [comment]
$withBase is a function, not a marker.
