### ISSUE TITLE
Can this version be made available as a package for testing?

### ISSUE THREAD

**Issue by songololo** [vuepress/vuepress-next#7]
Would it be possible to please make this repo available as a package via `npm` or `yarn`?

Attempts to install directly from git raise `Can't add undefined: invalid package version undefined` errors.

Thanks.

**Comment by meteorlxy** [comment]
We are planning to publish an alpha version until the default theme is migrated, or at least have minimal features.

For now, you can clone this repo and play with it.

**Comment by meteorlxy** [comment]
Alpha version is already released
