### ISSUE TITLE
[Bug report] The navigation bar is not underlined when a subpath is activated

### ISSUE THREAD

**Issue by 1148177968** [vuepress/vuepress-next#70]
The navigation bar is not underlined when a subpath is activated

[demo](https://vuepress2.netlify.app/zh/guide/configuration.html)

the guide  is not underlined  in navbar

**Comment by meteorlxy** [comment]
It's the title of the dropdown menu, which does not have an active status.

**Comment by meteorlxy** [comment]
It's caused by the breaking change of vue-router:

https://github.com/vuejs/rfcs/blob/master/active-rfcs/0028-router-active-link.md#unrelated-but-similiar-routes
