### ISSUE TITLE
[Feature request]请问还有支持Vuepress2的评论插件吗

### ISSUE THREAD

**Issue by Aaron-clou** [vuepress/vuepress-next#707]
### Description

用了vuepress-plugin-comment的gittalk和valine，照着官网一步步弄下来没有出现评论，接着用了官方插件Vssue，然后报error说只支持vuepress1，所以Vuepress2还要推荐的能用的还在维护的，评论插件吗？

### Proposed Solution
我想用个评论插件给我Vuepress2博客加个评论，找了很久没找到还在维护的能用的？

希望能教下怎么加评论功能，实在不会。感激万分！

**Comment by Mister-Hope** [comment]
vuepress-plugin-comment2 currently support waline.
