### ISSUE TITLE
[Bug report] vite config can not work

### ISSUE THREAD

**Issue by PerryHuan9** [vuepress/vuepress-next#712]
### Description
I use some vite config in  vuepress.config.ts file, but it not work.
<img width="888" alt="image" src="https://user-images.githubusercontent.com/31561213/155651769-bede64c4-25c5-4433-a693-e200d285fe3a.png">
<img width="707" alt="image" src="https://user-images.githubusercontent.com/31561213/155651857-f6a70742-6a3a-458b-88a6-6fb0aa2d6cac.png">

**Comment by Mister-Hope** [comment]
Set base in config file directly
