### ISSUE TITLE
[Bug report] The browser respond "not found" when Setting "editLinkPattern"

### ISSUE THREAD

**Issue by coulsonzero** [vuepress/vuepress-next#723]
## Bug report
Using `v2.0.0-beta.35`:

### 1. Description

> When setting editLinkPattern in .vuepress/config.js like this:
```ts
module.exports = {
  themeConfig: {
    docsRepo: 'https://gitlab.com/owner/name',
    docsBranch: 'master',
    docsDir: 'docs',
    editLinkPattern: ':repo/-/edit/:branch/:path',
  },
}
```

### 2. Environment info
> it will be respond "not found" in the brower !

**Browser**:
- display `not found`

### 3. Solution
> If we remove the "-/" it will be accessed normally !
```ts
editLinkPattern: ':repo/edit/:branch/:path',

**Comment by Mister-Hope** [comment]
I am not sure what you are reporting.

When you are setting a wrong editPattern, you are expected to get a broken editlink.
