### ISSUE TITLE
[Feature request] switch webpack to development mode when use "--debug"

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#734]
### Discussed in https://github.com/vuepress/vuepress-next/discussions/530

<div type='discussions-op-text'>

<sup>Originally posted by **huww98** November 16, 2021</sup>
Hi all, today I spent hours trying to debug the client-side error "Hydration completed but contains mismatches". To view the warnings from vue, I ended up adding the following to my config:

```javascript
  bundlerConfig: {
    configureWebpack(config, isServer, isBuild) {
      return { mode: 'development' };
    }
  },
```

How about we can simplify this by enabling the development mode by default when invoked as `yarn build --debug`
</div>

**Comment by meteorlxy** [comment]
I'd ever considered about that, but you know that, `--debug` and development mode are slightly different. 🤔
