### ISSUE TITLE
[Bug report] assets got 404 under path containing CJK characters.

### ISSUE THREAD

**Issue by Megasu** [vuepress/vuepress-next#740]
### 错误描述

测试静态资源-相对路径写法，相对路径在本地预览失败⁉️⁉️

- 相对路径设置参考：[参考地址](https://v2.vuepress.vuejs.org/zh/guide/assets.html#%E7%9B%B8%E5%AF%B9%E8%B7%AF%E5%BE%84)
- 通过 `![An image](./image.png)` 引入本地图片。
- 运行  `docs:dev`  在本地开发预览图片异常。

### 已经做过的尝试

1. 排除 Node 版本问题， `14.17.0` 版本和 `v16.14.0`  都出现同样问题。😑
2. Windows10 和 Windows11 皆会出现同样问题。😑
3. 运行  `docs:build` 图片路径为正常，无上述问题。👌
4. 若使用  `VitePress`  搭建项目，同样的文档，使用相对路径图片正常展示，无上述问题。👌

### 遇到问题的代码仓库

[遇到问题的仓库-demo](https://gitee.com/Megasu/vuepress2-relative-urls-error)

### 预期行为

- 相对路径在本地预览，方便本地使用其他编辑器文档和开发效果预览。

### 截图

![image](https://user-images.githubusercontent.com/7400870/156879418-4c9508ae-5388-4b7a-a866-edb62859c449.png)

### 环境信息

1. Window 10 专业版 / Windows 11 家庭版
2. Node 14.17.0 / Node 16.14.0
3. 浏览器 Chrome  101.0.4925.0（正式版本）canary （64 位）

**Comment by Megasu** [comment]
开源不易，期待作者完善该功能，辛苦了。🌹🌹🌹

**Comment by Mister-Hope** [comment]
A valid mininal reproduction repo link is required.

**Comment by Megasu** [comment]
sorry，my repo is public now。

**Comment by Mister-Hope** [comment]
Some update on this:

> ![](https://user-images.githubusercontent.com/7400870/156879418-4c9508ae-5388-4b7a-a866-edb62859c449.png)

The path is expected

![image](https://user-images.githubusercontent.com/33315834/156905838-e3ad114f-c371-4fd3-bbc6-0a6f7c24024f.png)

The acuall problem is that vite failed to recognize gif and failed providing it.

@meteorlxy  May need some investigation here. As vite [says that it can handle gif](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/constants.ts) and vitepress is working fine in user report.

**Comment by Mister-Hope** [comment]
Hi there, some new updates.  I downloaded some gif from the web just to make sure it's not the gif's problem, and  in deed all of them are working fine. 

And after some refreshs , your image is working on my env. (Also I failed to reproduce what you are reporting since that, even after cleaning cache)


![image](https://user-images.githubusercontent.com/33315834/156906123-98844068-2318-4430-b0ea-7617ed1805c3.png)

I believe this gif is made by yourself, so could you please check if you are outputing a standard gif? @Megasu Also could you check to make sure that other gif is broken in your env as well?

**Comment by Mister-Hope** [comment]
Also, I check the code, we are not makeing edits on Vite default behavior, so if vitepress works, probably it will work on vuepress with bundler-vite too.

**Comment by Megasu** [comment]
This is  Working  Normal  in  VitePress ，assets  URL  is  start with   `/`。

![image](https://user-images.githubusercontent.com/7400870/156918614-8816658e-809b-41d0-beda-33c5fdbcc5c5.png)

**Comment by Megasu** [comment]
Still  No  Working  Normal  in  VuePress2。
![image](https://user-images.githubusercontent.com/7400870/156918802-1d199946-775c-4978-b143-6ebb11f3f6d8.png)

**Comment by Megasu** [comment]
Screenshot  form  VitePress。

![image](https://user-images.githubusercontent.com/7400870/156919324-e5ae3d77-3a05-4d0b-ad49-fc22b65b2f02.png)

**Comment by Megasu** [comment]
你们测试没有问题，应该不是代码本身问题，所以我就在思考到底是哪里错误。
> 终于定位到问题所在了，祖先级文件夹出现中文就不行了。

- 疑问：不知道 `VuePress2` 是否计划解决这个中文路径问题。
- 参考：`VitePress` 之所以没有出问题的原因也是因为它是 `/` 开头的服务器路径，可以避免出现上述问题。

![image](https://user-images.githubusercontent.com/7400870/156919819-2b43a816-f35c-4ea6-83cc-af7a55ade94f.png)

**Comment by Mister-Hope** [comment]
> Updated: noticing you are using a folder containing CJK characters, try with and without those to make sure that they are not actual reasons

I told you that.

@meteorlxy I prefer to regard this as vite’s bug. Any suggestions?

**Comment by Mister-Hope** [comment]
Emmm,  I still can not reproduce it. That's weird.

![image](https://user-images.githubusercontent.com/33315834/156921924-d96e439b-e3e0-4e5e-a3e8-8b66a84979c8.png)

**Comment by Mister-Hope** [comment]
@Megasu Hi, sorry to bother you, but could you try provide another reproduction? Also your whole env infomation?

**Comment by Megasu** [comment]
> @Megasu Hi, sorry to bother you, but could you try provide another reproduction? Also your whole env infomation? Since I cannot search any related error in Vite, which means probably vite works fine with paths `/@fs/` containing CJK characters. And my local test result also shows that a path like `@fs/C:/projects/vuepress-theme-hope/测试/图标.png` works in my env.

can u send ur repo url to me？I test ur repo，because my repo still no working 。

**Comment by Megasu** [comment]
> 

![image](https://user-images.githubusercontent.com/7400870/157191530-4ca7dde0-9a1e-42da-a229-980c41604767.png)

**Comment by Megasu** [comment]
> VitePress

VitePress always working normal，I don't know what's going on。👀

**Comment by Megasu** [comment]
> > Updated: noticing you are using a folder containing CJK characters, try with and without those to make sure that they are not actual reasons
> 
> I told you that.
> 
> > 参考：VitePress 之所以没有出问题的原因也是因为它是 / 开头的服务器路径，可以避免出现上述问题，是否可以借鉴其解决方案。
> 
> Nope, thanks for that suggestion, but we have total different logic on handling markdown.
> 
> Also, could you check when the source code folder or image name itself contains cjk characters, is VitePress still working? @Megasu I believe not.
> 
> @meteorlxy I prefer to regard this as vite’s bug. Any suggestions?

VitePress always working normal，I don't know what's going on。👀

**Comment by Mister-Hope** [comment]
Try `npm init vuepress-theme-hop@next test` in any chinese folder. It's working in my env.

**Comment by Megasu** [comment]
> Try `npm init vuepress-theme-hop@next test` in any chinese folder. It's working in my env.

megas@Megasu MINGW64 /d/Users/megas/Desktop/测试
$ npm init vuepress-theme-hop@next test
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-vuepress-theme-hop - Not found
npm ERR! 404
npm ERR! 404  'create-vuepress-theme-hop@next' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404

**Comment by Mister-Hope** [comment]
My fault, hope, e is missing in the end

**Comment by Mister-Hope** [comment]
Any update? Starting the template could be esay.
