### ISSUE TITLE
[Feature request] --no-cache in CLI

### ISSUE THREAD

**Issue by justforuse** [vuepress/vuepress-next#744]
### Description

In Vuepress v1 , there is an cli option: `--no-cache`, which can not generate cache files under `docs`, but in v2, it disappears, it maybe helpful in some situations

### Proposed Solution

add `--no-cache` support in CLI

**Comment by Mister-Hope** [comment]
We are expecting users to read our docs, in fact they are not 😑

1. V1's `--no-cache` doesn't mean "do not generate cache"

![image](https://user-images.githubusercontent.com/33315834/157365071-c83d0bf2-49fe-4c33-a0db-98f392b317e0.png)

2. We rename it to `--clean-cache`  See https://v2.vuepress.vuejs.org/reference/cli.html
![image](https://user-images.githubusercontent.com/33315834/157365123-9b760545-4202-4f40-aa90-04ec091eaf2a.png)

**Comment by justforuse** [comment]
Maybe I misunderstand the meaning of `--no-cache`, but what I want is not generate the `.cache` and `.temp` folders when run `vuepress dev docs`, just feel a little annoying😅.

In v1 `--no-cache` works as expected.

**Comment by Mister-Hope** [comment]
How can vuepress require and use temp files while build and dev when they are not generated.

Or in a other word, how can you get a fried egg, when you tell the cook, don’t use egg.

**Comment by justforuse** [comment]
Maybe Chinese is more clear, 好奇这些缓存文件在vuepress dev运行中（或者hot reload）是必要的吗？是的话就没问题了。

主要就是不想看到这些缓存文件😂

**Comment by Mister-Hope** [comment]
Cache files is necessary in Vite to perform “prebundle” options. Also, a lot of tools are generating temp files.

If you just do want to “see” them, set cache and temp option to `node_modules/.cache` and `node_modules/.temp`
