### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by heshimang** [vuepress/vuepress-next#749]
## Bug report

 Github pages not take effect

### Description

When deploying a simple vuepress app to github pages using github actions. This seems success , but open the url 'https://heshimang.github.io/vuepressv2-blog/', is show 404.

Please see below.

github repo
https://github.com/heshimang/vuepressv2-blog

deploy Link
https://heshimang.github.io/vuepressv2-blog/

### Steps to reproduce

When i push code every time.

- Reproduction link / repo: https://github.com/heshimang/vuepressv2-blog

### Expected behavior

Normal page display.

### Screenshots

![image](https://user-images.githubusercontent.com/19547994/157834187-83d43aae-75f2-49fc-9629-05cbbdad0d74.png)
<img width="1694" alt="image" src="https://user-images.githubusercontent.com/19547994/157834309-f1a6c617-66b6-45c3-b103-71a345f14aa3.png">
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/19547994/157834386-89db513a-3e50-4b0b-b5eb-c4b0ab126fed.png">

### Environment info

- Browser: 99.0.4844.51
- Output of `vuepress info`: 
I don't konw how to get it. So Sorry.

```bash
# Paste output of `vuepress info` here
```

**Comment by Mister-Hope** [comment]
? Please make sure you opened github pages.

![image](https://user-images.githubusercontent.com/33315834/157908543-d9532a81-2141-42b4-9b43-f512677bcc54.png)


https://docs.github.com/cn/pages/getting-started-with-github-pages/creating-a-github-pages-site#creating-your-site

**Comment by heshimang** [comment]
Thanks for you first, but i make sure opened github pages.
I find out why. I don't change the branch options on github pages, which defaults to mian. I changed it to gh-pages and it worked!
