### ISSUE TITLE
[Feature request] I don't want the "base" effect everywhere, if i can control it don't work. 

### ISSUE THREAD

**Issue by KevinBrother** [vuepress/vuepress-next#753]
### Description
I don't want the "base" effect everywhere, if i can control it don't work. 

### Proposed Solution
#653 
E.g.: with base /demo/
- /abc.html is /demo/abc.html
- $abc.html is /abc.html

**Comment by Mister-Hope** [comment]
Try not opening duplicate issues, you are free to share your ideas in the original issue.
