### ISSUE TITLE
[Feature request] plugin-external-link-icon: add option to configure `target` and `rel`

### ISSUE THREAD

**Issue by olets** [vuepress/vuepress-next#760]
### Description

plugin-external-link-icon adds an external link icon, and it also adds `target="_blank" rel="noopener noreferrer"`. Whether a developer wants to add an icon to external links in independent of whether they want them to open in a new tab (`target="_blank" rel="noopener"`) and of whether they want them to pass referrer data (`rel="noreferrer"`).

Not looking to start a debate and I don't have numbers on how many people don't/want new tabs, but it feels like I should provide at least a little evidence. Here's the take of one influential front end developer: https://css-tricks.com/use-target_blank/

It'd be great if Vuepress supported external link icons without also forcing new tabs and forcing blocking referrer info.

### Proposed Solution

Something like

`themePlugins.externalLinkIcon : <ExternalLinkConfigObject, boolean>`, default `true`

where `ExternalLinkConfigObject` has keys `target` and `rel`
- `target: <false, TargetKeyword>`
  - default `_blank`
  - target keys can be any arbitrary string (or only those HTML supports?)
  - if `false`, no `target` attribute is added
- `rel: <false, LinkTypesString`
  - default `"noopener noreferrer"`
  - or maybe `<false, LinkTypesArray`, default `["noopener", "noreferrer"]`?
  - link types can be any arbitrary string (or only those HTML supports?)
  - if `false`, no `rel` attribute is added

--

Alternatively it could be even more generic

`themePlugins.externalLinkIcon : <ExternalLinkAttributeConfigArray, boolean>`
- default `{ target: "_blank", rel: "noopener noreferrer" }`
- each `ExternalLinkAttributeConfig` in `ExternalLinkAttributeConfigArray` is `<Attribute>: <ValueString>`
  - or maybe `<Attribute>: <ValuesArray>`, default `{ target: ["blank"], rel: ["noopener", "noreferrer"] }`

**Comment by olets** [comment]
I see NuxtLink has a new `no-rel` https://twitter.com/nuxt_js/status/1503691568078888962 which opts out of `target="_blank" rel="noopener noreferrer"`.

That's probably all that's needed - I expect the need to provide other values for target and rel is very rare. The only thing missing is a way to easily select external links that don't have the attributes added (for further customizing with CSS or JS).

So I now like my second API idea better than my first.

**Comment by Mister-Hope** [comment]
Sounds resonable. PR is always welcome

**Comment by narumishi** [comment]
Is there anyway to remove the external link icon? When I use external link on home page's button, it seems....uncomfortable
![image](https://user-images.githubusercontent.com/56487872/162421796-d2079a51-0fba-4495-ba55-cdb17e0c5bd0.png)

**Comment by Mister-Hope** [comment]
You may overide HomePage related content to achieve this with alias.

**Comment by narumishi** [comment]
@Mister-Hope you mean eject theme then modify? that's a solution though but not a good choice.

I found this
https://github.com/vuepress/vuepress-next/blob/c7fd81580a9061b22f1a60a735fdc9a527ef1bfd/docs/reference/default-theme/config.md#themepluginsexternallinkicon
But:
![image](https://user-images.githubusercontent.com/56487872/162470312-8934a545-d8b0-42a1-bbd0-f79c75a43903.png)
vscode cannot recognize it and also no effect. Where should we place `themePlugins`?

**Comment by meteorlxy** [comment]
@narumishi `themeConfig.themePlugins`

It's part of the config of default theme.

https://v2.vuepress.vuejs.org/reference/default-theme/config.html#themeplugins

**Comment by meteorlxy** [comment]
@olets The `rel` and `target` are not added by plugin-external-link-icon. It's handled by the [markdown parser](https://v2.vuepress.vuejs.org/reference/config.html#markdown-links).

But yes, it's not documented clearly now, as the config of markdown is a little verbose.

Try this:

```ts
// ...
  markdown: {
    links: {
      externalAttrs: {
        rel: '',
        target: '',
      },
    },
  },
// ...
```

**Comment by narumishi** [comment]
@meteorlxy thanks for reply.
I am not familiar with vuepress yet, but where should I add `themePlugins.externalLinkIcon: false` if not in config.ts

**Comment by meteorlxy** [comment]
@narumishi I think I just replied in previous comment 😅

**Comment by olets** [comment]
Aha! Thanks meteorlxy.

If anyone else is reading along, note that I had to upgrade vuepress from 2.0.0-beta.36 to 2.0.0-beta.39, and @vuepress/plugin-docsearch and @vuepress/plugin-shiki from 2.0.0-beta.36 to 2.0.0-beta.38 (all of those are the latest as of this writing), to resolve build errors.
