### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by leedom92** [vuepress/vuepress-next#768]
## Bug report
medium-zoom's problem

### Description

When I click on the mask outside the picture, the mask disappears but the enlarged picture doesn't disappear with it.

### Steps to reproduce

- Reproduction link / repo: https://docs.leedom.me/handbook/git/sshkey.html#%E6%B7%BB%E5%8A%A0%E5%85%AC%E9%92%A5

### Expected behavior

I hope when I click on the mask outside the picture, the mask and the picture disappear together

### 第一步
<img width="630" alt="1" src="https://user-images.githubusercontent.com/30711792/159405648-48c6b4a9-6548-4820-99dc-6eeab113a0cc.png">

### 第二步
<img width="630" alt="2" src="https://user-images.githubusercontent.com/30711792/159405812-15abe46d-1468-4db6-a5f8-bec51871f9ac.png">

### 第三步
<img width="619" alt="3" src="https://user-images.githubusercontent.com/30711792/159405882-1c1a35fb-fc44-469c-8499-18ec9defdcf3.png">

### Environment info

- Browser: Chrome: 99.0.4844.74
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.74
    Firefox: 89.0.2
    Safari: 14.1.2
  npmPackages:
    @vuepress/core:  2.0.0-beta.36 (2.0.0-beta.33, 2.0.0-beta.4)
    @vuepress/theme-default:  2.0.0-beta.36 
    vuepress: ^2.0.0-beta.36 => 2.0.0-beta.36 
  npmGlobalPackages:
    vuepress: 0.8.4
```

**Comment by Mister-Hope** [comment]
https://v2.vuepress.vuejs.org/advanced/architecture.html#overview

The official website is not having any issues.

**Comment by leedom92** [comment]
> https://v2.vuepress.vuejs.org/advanced/architecture.html#overview
> 
> The official website is not having any issues.

I remove some unnecessary dependencies, then it works well!
thx 4 ur reply!
