### ISSUE TITLE
[Bug report] Building by vite several times cause the same output with different inputs

### ISSUE THREAD

**Issue by MicrowaveDev** [vuepress/vuepress-next#772]
### Description

I have an application, where i need to build several static sites from one runtime in series: build after build. But i got a strange behavior. After first build i got second with same output as first, while i have different inputs. I made a simple repo to reproduce error.

### Steps to reproduce

```
git clone https://github.com/MicrowaveDev/vuepress-test.git
cd vuepress-test
npm start
```
### Expected behavior

1. After first build: includes "Test 1" in `.vuepress/dist/index.html` content with output `includes 1: true` in console log
1. After second build: includes "Test 2" in `.vuepress/dist/index.html` content with output `includes 2: true` in console log

### Logs

```
START
initialize and prepare
build
⠦ Compiling with vite@vuepress/client doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
✔ Compiling with vite - done
⠋ Rendering pages⠋ Rendering pages /404.html[Vue warn]: App already provides property with key "Symbol(ssrContext)". It will be overwritten with the new value.
[Vue warn]: App already provides property with key "Symbol(ssrContext)". It will be overwritten with the new value.
✔ Rendering pages - done
process onGenerated hook
DONE


includes 1: true


not exists: true


START
initialize and prepare
build
@vuepress/client doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix. (x2)
✔ Compiling with vite - done
⠋ Rendering pages⠋ Rendering pages /404.html[Vue warn]: App already provides property with key "Symbol(ssrContext)". It will be overwritten with the new value.
[Vue warn]: App already provides property with key "Symbol(ssrContext)". It will be overwritten with the new value.
✔ Rendering pages - done
process onGenerated hook
DONE


includes 2: false
```

### Environment info

- Browser: Without browser, only cli
- Output of `vuepress info`:

```bash
Environment Info:

  System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 98.0.1
  npmPackages:
    @vuepress/core: 2.0.0-beta.36 => 2.0.0-beta.36 
    @vuepress/theme-default: Not Found
    vuepress: Not Found
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by Mister-Hope** [comment]
Also, you are expected to clean page temp files when having advanced usage with api to create your page.

**Comment by MicrowaveDev** [comment]
Ok, i downgraded to 35, but dont understand your versioning. Some packages have 36 and some don't have. I though i should to use the last versions of all packages.

Also added whole .vuepress directory cleaning. I tried to clean it before, but it did not work, and i saw that temp file had the actual data of second build.

Repo updated: https://github.com/MicrowaveDev/vuepress-test/commit/7005f30c6ba9e3dfc3057881055d2dce51b6785a

What do you mean about adding the workflow? I made a repo with script that reproduced the error

**Comment by Mister-Hope** [comment]
> I though i should to use the last versions of all packages.
Emm, just realize that 

I will have a look later

**Comment by MicrowaveDev** [comment]
Hello, any news about this issue?

**Comment by Mister-Hope** [comment]
Not a bug at all. Try not share the same vuepress instance. See https://github.com/Mister-Hope/vuepress-test

call.js works, but exec.js does not work.

**Comment by MicrowaveDev** [comment]
Thank you for sample with using child process, but i know about this workaround and hoped not to use it because i have many data to pass to site generator. I think it's a bug, that library in one process makes the same output with different inputs, and hope that one day it will be solved and can be used without child processes

**Comment by Mister-Hope** [comment]
This is every hard to check, and I am not interest in it becuz you already have a workaround and this is not a normal usage.

Maybe you can see if @meteorlxy can find some time investigate it. (But I am afraid he cannot in the comming few months)

**Comment by meteorlxy** [comment]
The require cache of the server entry causes the issue:

https://github.com/vuepress/vuepress-next/blob/f71cb5020da1d84cac54e5f02812f36c02dd85f4/packages/%40vuepress/bundler-vite/src/build/createBuild.ts#L57-L62
