### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by abelit** [vuepress/vuepress-next#783]
### Description

When Install vuepress from step 1 to step 7 following  vuepress office website: "https://v2.vuepress.vuejs.org/guide/getting-started.html#manual-installation." 
![image](https://user-images.githubusercontent.com/10794056/160968338-9dba8cf8-f145-4147-bc84-d8714f0aef3e.png)
but open http://localhost:8080/ with google chrome, the home page is blank.
![image](https://user-images.githubusercontent.com/10794056/160968483-e755ae58-f009-4d5a-a319-3212fb8b26a3.png)

### Steps to reproduce

- Reproduction link / repo:

### Environment info

- Browser:
- Output of `vuepress info`:
![image](https://user-images.githubusercontent.com/10794056/160968895-8c349e0a-026f-4db4-b675-2ec0a4f79512.png)

```bash
# Paste output of `vuepress info` here
```

**Comment by Mister-Hope** [comment]
#781
