### ISSUE TITLE
Using markdown plugins

### ISSUE THREAD

**Issue by vmihailenco** [vuepress/vuepress-next#79]
Looking at https://github.com/vuepress/vuepress-next/blob/main/packages/%40vuepress/markdown/src/markdown.ts I don't see any way to use markdown-it plugin, e.g.:

```ts
  markdown: {
    plugins: { 'markdown-it-include': {} },
  },
```

Am I missing something or this is not supported yet?

**Comment by meteorlxy** [comment]
https://vuepress2.netlify.app/reference/plugin-api.html#extendsmarkdown

Please move to the correct place to ask questions
