### ISSUE TITLE
[Feature request] Configuring Prism inside `@vuepress/plugin-prism` plugin

### ISSUE THREAD

**Issue by dhruvkb** [vuepress/vuepress-next#793]
### Description

I wanted to customise Prism to change the Bash functions (https://github.com/PrismJS/prism/issues/3361). Prism's recommended solution is to overwrite `Prism.languages.bash.function.pattern` as follows.

```
Prism.languages.bash.function.pattern = 
```

To be able to do this I need to access Prism inside the `resolveHighlighter` function.

https://github.com/vuepress/vuepress-next/blob/6a4733f2fe3acfe72f0d7611d6f604fade44d5dc/packages/%40vuepress/plugin-prismjs/src/node/resolveHighlighter.ts#L1

### Proposed Solution

I want to be able to access Prism to tweak some settings before this line where it is used for highlighting code blocks in Markdown.

https://github.com/vuepress/vuepress-next/blob/6a4733f2fe3acfe72f0d7611d6f604fade44d5dc/packages/%40vuepress/plugin-prismjs/src/node/resolveHighlighter.ts#L43

**Comment by dhruvkb** [comment]
I just realised that adding the following code to `config.js` does what I intended.

```js
const Prism = require("prismjs");
const loadLanguages = require('prismjs/components/');

loadLanguages(['bash']);
console.log(Prism.languages.bash.function.pattern = /(^|[\s;|&]|[<>]\()(?:add|pls)(?=$|[)\s;|&])/);
```

Feel free to close this issue if you see no further use for it.

**Comment by Mister-Hope** [comment]
Nice catch, just as the plugin does, prism can be modifyed one place and take affect at other places during a node process.

**Comment by Mister-Hope** [comment]
So pesonally, I don't think adding a function and let the plugin call it in initialization is needed. Any sences  that a edit must be made between the 2 lines?

https://github.com/vuepress/vuepress-next/blob/6a4733f2fe3acfe72f0d7611d6f604fade44d5dc/packages/%40vuepress/plugin-prismjs/src/node/prismjsPlugin.ts#L30-L31

If you can list some, we can add an option.

**Comment by dhruvkb** [comment]
I can't think of any specific thing needed here.

**Comment by Mister-Hope** [comment]
Same problem exisits with vue, vue-router @vueuse/core @vue/shared, vite and so more. If you meet version mismatch very offen, consider adding pnpm.overrides field. That ensure only the version set in overrides is in the deps tree.

**Comment by Guyutongxue** [comment]
> Same problem exisits with vue, vue-router @vueuse/core @vue/shared, vite and so more. If you meet version mismatch very offen, consider adding pnpm.overrides field. That ensure only the version set in overrides is in the deps tree.

Thanks for your suggestion!
