### ISSUE TITLE
[Enhancement] Improve bundler config

### ISSUE THREAD

**Issue by ptandler** [vuepress/vuepress-next#795]
I started to migrate my homepage from VuePress 1 to 2 and also used this opportunity to give Vite a try.

With VuePress 1 and web pack, I used the [`vue-svg-loader`](https://vue-svg-loader.js.org/) plugin to allow inline SVG. I'm stuck to port this to VuePress 2 and Vite.

I found [`vite-svg-loader`](https://github.com/jpkleemans/vite-svg-loader) which looks pretty comparable. But I've got no idea how to use it.

In the [documentation](https://v2.vuepress.vuejs.org/reference/bundler/vite.html) I read that one can add custom Vite config via `viteOptions`:

```js
const svgLoader = require('vite-svg-loader')
// ...
module.exports = {
// ...
  bundlerConfig: {
    viteOptions: {
      plugins: [svgLoader()]
    }
  },
// ...
}
```

and within a custom Vue component I do:
'm stuck
```vue
<template>
    <ComponentLogo/>
</template>
<script>
import logo from "./stack-overflow-logo.svg?inline"

export default {
    name: "name",
    props: {
// ...
    },
    components: {ComponentLogo: logo},
//...
  }
</script>
```

But I get an error:
```
Uncaught (in promise) DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('.../global-components/Social/stack-overflow-logo.svg?inline') is not a valid name.
    at createElement
```

I interpret this that the imported SVG is treated as HTML or JS, but not SVG. Correct?

Coming back from this specific case to my general point: I really would appreciate to get a better explanation, and ideally also some complete and working examples of how to use Vite options and plugins. Thanks! :pray:

**Comment by Mister-Hope** [comment]
```ts
// .vuepress/config.ts
import svgLoader from "vite-svg-loader";

export default {
  // ...
  plugins: [
    // ...
    {
      name: "svg-loader",
      onInitialized: (app) => {
        if (app.bundler.endsWith("vite")) {
          app.bundlerConfig.viteOptions.plugins.push(svgLoader());
        } else {
          // done samethign with webpack
        }
      },
    },
  ],
};
```

Try this

**Comment by ptandler** [comment]
Hi @Mister-Hope, thanks for your suggestion. I just needed to tweak it a bit: The first thing I noticed is that it should be `app.options.bundler`, while `app.bundler` is undefined. And then, the plugins array can be empty. So I use this now:

```
// .vuepress/config.ts
import svgLoader from "vite-svg-loader";

export default {
  // ...
  plugins: [
    {
      name: "svg-loader",
      onInitialized: (app) => {
        console.log(JSON.stringify(app.options))
        if (app.options.bundler.endsWith("vite")) {
          app.options || (app.options = {});
          app.options.bundlerConfig || (app.options.bundlerConfig = {});
          app.options.bundlerConfig.viteOptions || (app.options.bundlerConfig.viteOptions = {});
          app.options.bundlerConfig.viteOptions.plugins || (app.options.bundlerConfig.viteOptions.plugins = []);
          app.options.bundlerConfig.viteOptions.plugins.push(svgLoader());
        } else {
          // do samething with webpack
        }
      },
    },
  ]
};
```

However, my original issue remains: This should be part of the docs!

**Comment by Mister-Hope** [comment]
It seems that svgloader needs to be loaded after vueLoader to work, but currently it can only be loaded before vueLoader, I had a discussion with meteorlxy of this, we will add a new option in feature to solve this, allowing you edit the config after vuepress config is injected.

**Comment by Mister-Hope** [comment]
It's not part of documentation thing.

**Comment by Mister-Hope** [comment]
You may need to wait a little bit for this, see https://github.com/vuepress/vuepress-next/issues/602#issuecomment-1088649726

**Comment by meteorlxy** [comment]
Closing as I've tested with `import IconComponent from './foo.svg?component'` as it works well.
