### ISSUE TITLE
[Bug report] appId of docsearch is required

### ISSUE THREAD

**Issue by leedom92** [vuepress/vuepress-next#797]
### Description

>Docsearch does not work! 
appId is required now.

<img width="407" alt="vuepress-algolia" src="https://user-images.githubusercontent.com/30711792/161917233-15768886-4d46-40a5-937d-2897fbc462b8.png">

<img width="308" alt="algolia-appid" src="https://user-images.githubusercontent.com/30711792/161917459-d2f151af-2c78-46c1-8cdd-d72d75b3cf70.png">

**Comment by Mister-Hope** [comment]
@meteorlxy  Any update?

**Comment by Mister-Hope** [comment]
Just make an update, we contacted with algolia docsearch team, but we stil not grant access to the exisiting application and get new apikey yet. So the search box is still not working.

**Comment by Mister-Hope** [comment]
Any chance to trigger docs update? Now it's only changed when new version is released.

**Comment by nitrocode** [comment]
So is the solution to include an appId?

We're hitting the same issue on https://runatlantis.io with this config

https://github.com/runatlantis/atlantis/blob/main/runatlantis.io/.vuepress/config.js
