### ISSUE TITLE
[Bug report] docs: algolia search gives no results

### ISSUE THREAD

**Issue by ghostrider-05** [vuepress/vuepress-next#799]
### Description

When searching on https://v2.vuepress.vuejs.org/ the algolia search is not giving any results. The following error is thrown in the console:
```txt
Unreachable hosts - your application id may be incorrect. If the error persists, contact support@algolia.com.
```

- [Original Discord discussion](https://discord.com/channels/872332690840514570/872370983644823562/961360397896679454)

### Steps to reproduce

- Reproduction link / repo: https://v2.vuepress.vuejs.org/

### Screenshots

![image](https://user-images.githubusercontent.com/52837878/162065602-56632023-1e5b-457b-987d-0a91bc3c9c5b.png)

### Environment info

- Browser: chrome 100.0.4896.75
- Output of `vuepress info`: not related

```bash
# Paste output of `vuepress info` here
```

**Comment by Mister-Hope** [comment]
#797
