### ISSUE TITLE
Scalability discussion

### ISSUE THREAD

**Issue by meteorlxy** [vuepress/vuepress-next#8]
> Original issue: https://github.com/vuejs/vuepress/issues/2689

As some users were trying to use vuepress on large scale projects, there might be some scalability issues to be solved.

I'll update some concerns and testing results here.

#### 1. https://github.com/zumasys/docs by @itsxallwater

- total pages: ~2040

- theme: unfinished default theme

- plugins: no

- dev: ~80s
	- intialization and preparation: ~8s
	- webpack compilation: ~70s
- build: ~200s
	- intialization and preparation: ~4s
	- webpack compilation: ~155s
	- pages rendering: ~40s

**Comment by meteorlxy** [comment]
@itsxallwater

I got different result from https://github.com/vuejs/vuepress/issues/2689#issuecomment-725034732.

Also, found some issues of your site, which might work in vue 2, but fail in vue 3:

### Invalid component usages

```md
</PageFooter>
```

> https://github.com/zumasys/docs/blame/master/site/mv-connect/mvdbtoolkit/mvdbtoolkit-config/README.md#L13

### Wrapping some contents with `<>`

the `<>` won't be escaped and will be put into `.vue` SFC as is

```md
<http://my.pickserver.com:8180/config>
```

> https://github.com/zumasys/docs/blame/master/site/mv-dashboard/installation-guide/configuration/README.md#L11


```md
which is translated to mean <CTRL>+G or CHAR(7)
```

> https://github.com/zumasys/docs/blame/master/site/jbase/howto/create-terminal-definitions-for-jbase/modify-existing-terminfo-definition/README.md#L54

### Obsolete HTML tag

```md
<center>
...
</center>
```

> https://github.com/zumasys/docs/blame/master/site/jbase/miscellaneous/multitenancy/README.md#L17-L25

**Comment by itsxallwater** [comment]
I saw those other fails as well, we'll definitely get them cleaned up. Thanks for the work so far!

**Comment by meteorlxy** [comment]
> I saw those other fails as well, we'll definitely get them cleaned up. Thanks for the work so far!

In fact, those issues make your build failed, but our cli didn't terminate the process, so you thought it was stuck.

**Comment by meteorlxy** [comment]
Closing as the original issue has been fixed in v2.
