### ISSUE TITLE
[Feature request] add flowchart and mermaid support the default theme.

### ISSUE THREAD

**Issue by xiaoyunwu** [vuepress/vuepress-next#801]
## Feature request
add flowchart and mermaid support the default theme.
### Description

It is useful to add support for flowchart and mermaid support the default theme.

### Proposed Solution
I notice there are plugin already, just do not know how to integrate it, and I think it is possible as theme-hope has that.

**Comment by Mister-Hope** [comment]
This is not your personal theme and most people won't need this.

Stop posting any feature unless we are all no doubt that >80% people will be interested in it.

Also, VuePress plugin system is designed to let users use their own features according to their needs.
