### ISSUE TITLE
[Bug report]  No highlights on build gh-pages

### ISSUE THREAD

**Issue by Arhell** [vuepress/vuepress-next#812]
### Description

No highlights on build gh-pages but locally everything works fine

### Steps to reproduce

- [repo:](https://github.com/consolidation/website)

**Comment by Arhell** [comment]
@Mister-Hope
Repo https://github.com/consolidation/website
example
https://consolidation.github.io/website/docs/getting-started.html#getting-started
![Screenshot_1](https://user-images.githubusercontent.com/26163841/163249416-12e91f42-f936-4518-9520-7803e1cf1662.png)
php code no color but locally there is color
![Screenshot_2](https://user-images.githubusercontent.com/26163841/163249582-7ec61699-44ab-47c4-b6e4-3575e79f71c8.png)
`npm run dev`

**Comment by Mister-Hope** [comment]
So you found the issues right?
