### ISSUE TITLE
Unknown conflict issue with Element-Plus after 'yarn docs: build'

### ISSUE THREAD

**Issue by hyp530** [vuepress/vuepress-next#813]
**Vuepress 2.0.0-beta36**:  Unknown conflict issue with Element-Plus after `yarn docs: build`

**1. Reproduction:** 
       Repo: https://github.com/hyp530/vp2test  (Note: This Repo works under `yarn docs: dev` but failed after `yarn docs: build`.)
       Deployment: https://vp2test.vercel.app/test/test1/bs1.html  
       Description: Please enter the deployment url, randomly click a sidebar item (say 'Test002'), and you'll see the errors in F12 Console. The error is trigerred by an ELement-Plus component in `https://github.com/hyp530/vp2test/blob/main/docs/test/test1/bs1.md`
![image](https://user-images.githubusercontent.com/4817812/163315178-c8702462-b588-46e3-8332-9e3f558e3d36.png)

**2. Screenshot of the errors:** 
![123](https://user-images.githubusercontent.com/4817812/163226852-8132fac9-1b6d-431e-9866-959c6e2b83aa.png)

**Comment by Mister-Hope** [comment]
Try fixing the problem yourself, please try to figure out the issue belong to which one of these:

- Element Plus breaks VuePress App (not possible)
- VuePress App breaks Element plus  (not possible)
- Element Plus and VuePress App register same directives or same Component, so they "break each outher (maybe)
- Element Plus do not work well with VuePress SSR (maybe)
- Other weird reasons

Unless you are sure that this is sitition 2, do not expect our actions. Both VuePress team and Element Plus team have no duty to read the other's code. So it's your job.

If you found something that proof this is situation 2, a new issue with detailed infoamtion is welcomed.

**Comment by Mister-Hope** [comment]
BTW, again try reading your repo, situation 4 has the highest suspicion. You may need to focus on that.

**Comment by hyp530** [comment]
Thanks. I'm an amateur user without such a capability to do my job. I will try to integrate vuepress with some others (e.g., ant design) and see if it works.
