### ISSUE TITLE
Configuration with SidebarItem objects: <h2> and <h3> headers to be generated in the sidebar

### ISSUE THREAD

**Issue by hyp530** [vuepress/vuepress-next#824]
### Description
Reproduction:  https://vp2test.vercel.app/test/test2/test888.html#headerh2-1
Repo: https://github.com/hyp530/vp2test

With SidebarItem string, <h2> and <h3> headers will be automatically generated from the page headers. However, this doesn't work with SidebarItem objects.
![~JZVEG0_BP%PI@ 566 VDOO](https://user-images.githubusercontent.com/4817812/163379619-006650d6-995f-411d-aa5f-86852d232388.png)

### Proposed Solution
Add the feature simiar to configuration with SidebarItem string.

**Comment by Mister-Hope** [comment]
Setting an object means keeping the configurattion as is (so you acually should use `.html` suffix intead of `.md`.

This also means you no longer want a link bind with markdown files. So headings are not displayed.
