### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by sachinbro** [vuepress/vuepress-next#826]
## Code
![image](https://user-images.githubusercontent.com/34100453/163659456-a96622cf-ab5d-40df-9fe8-fa9429628ee3.png)

## Output
![image](https://user-images.githubusercontent.com/34100453/163659484-46f14785-1d62-473b-9507-b616bfca8532.png)

## Expected Output
![image](https://user-images.githubusercontent.com/34100453/163659512-c8ce9be7-90b9-40b7-8dd2-510c163dc771.png)

**Comment by Mister-Hope** [comment]
Do not indent code blocks.

See https://github.com/vuepress/vuepress-next/blob/main/docs/README.md?plain=1
