### ISSUE TITLE
medium-zoom not functional if base URL is a sub path

### ISSUE THREAD

**Issue by nicpitsch** [vuepress/vuepress-next#84]
### Description

[medium-zoom](https://vuepress2.netlify.app/reference/plugin/medium-zoom.html#medium-zoom) Plugin isn't functional if [`base` in config.ts](https://vuepress2.netlify.app/reference/config.html#base) is set to a sub path like `base: '/bar/'`. 

### Steps to reproduce

- Set `base: '/bar/'` in config.ts.
- Add an image to folder *./.vuepress/public/images*, like *myimage.jpg*.
- Reference that image within a readme.md several times and start *npm run docs:dev*:
  1.  `![myimage](/images/myimage.jpg)` &rarr; image doesn't display, as expected.
  2.  `![myimage](/bar/images/myimage.jpg)` &rarr; image displays and medium-zoom is functional, but we have 'hardcoded' the relative path.
  3.  `<img :src="$withBase('/images/myimage.jpg')" alt="">` &rarr; image displays but medium-zoom is **not** functional, that's the issue.

### Expected behavior

*medium-zoom* Plugin should be functional together with *$withBase*, means when clicking on image with option *iii* above the image should be zoomed. 

### Environment info

- Browser: Edge
- npm run docs:dev: *vuepress2@1.0.0*
- package.json: *"vuepress": "^2.0.0-beta.6"*

**Comment by meteorlxy** [comment]
It's not related to the `base`.

The reason is the medium-zoom selector was set to `.theme-default-content :not(a) > img`

However, using `<img>` tag directly in markdown will result in `.theme-default-content > img`.

**Comment by nicpitsch** [comment]
Shouldn't the first css-child selector within your commit 832bd6f be omitted? Correct selector to:

```css
selector:
  '.theme-default-content img, .theme-default-content :not(a) > img',
```

Thanks a lot for your great contribution to vuepress-next.

**Comment by meteorlxy** [comment]
@nicpitsch If so, the second selector will have no effects
