### ISSUE TITLE
[Bug report] icon is lost after packaging and deployment

### ISSUE THREAD

**Issue by junjieweb** [vuepress/vuepress-next#841]
### Description
icon is lost after packaging and deployment.
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.

### Steps to reproduce

- Reproduction link / repo:

### Screenshots
![image](https://user-images.githubusercontent.com/90107547/164251374-8e26a474-dadb-4ce0-a7e1-a9e316fc1316.png)
![image](https://user-images.githubusercontent.com/90107547/164251413-fb8d6ee3-ea4b-4422-a121-6dc0852d0c64.png)
![image](https://user-images.githubusercontent.com/90107547/164251674-ef43147e-8593-4c5d-9ee9-f7762e18335c.png)

### Environment info

- Browser:chrome github pages
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```

**Comment by junjieweb** [comment]
```
    head: [
        ['link',
            {
                rel: 'icon',
                // type: 'image/svg',
                href: '/icon/favicon.ico'
            }
        ]
    ],
```

**Comment by junjieweb** [comment]
```
export default defineUserConfig<DefaultThemeOptions>({
  head: [['link',{rel: 'icon',href: '/icon/favicon.ico'}]],
}
```

**Comment by Mister-Hope** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by junjieweb** [comment]
`config.ts`

```typescript
import {defineUserConfig} from 'vuepress'
import type {DefaultThemeOptions} from 'vuepress'

export default defineUserConfig<DefaultThemeOptions>({
    // 站点配置
    base: '/Front-end-Developer/',
    lang: 'zh-CN',
    title: 'Junjie',
    description: 'Front-end web developer',
    head: [
        ['link',
            {
                rel: 'icon',
                href: '/images/favicon.ico'
            }
        ]
    ],
    // 主题和它的配置
    theme: '@vuepress/theme-default',

})
```

`File Directory`

```
|-- .vuepress
  |-- public
    |-- images
      |-- favicon.ico
```

normal in dev mode，GitHub pages deployment icon does not work

**Comment by Mister-Hope** [comment]
reprodution repo please

**Comment by Mister-Hope** [comment]
Add base to your head link manually
