### ISSUE TITLE
[Bug report] Public dir warning about import a json from public directory

### ISSUE THREAD

**Issue by lyrebirth** [vuepress/vuepress-next#844]
### Description

A warning message appears when I  import a json from public directory...

my vite versions is 2.8.0

### Screenshots

![image](https://user-images.githubusercontent.com/62588055/164593165-26a27146-3842-4542-9345-d3e5943cd0ab.png)

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```

**Comment by Mister-Hope** [comment]
expected
