### ISSUE TITLE
[Bug report] SyntaxError: Illegal '/' in tags.

### ISSUE THREAD

**Issue by junjieweb** [vuepress/vuepress-next#845]
## Bug report

SyntaxError: Illegal '/' in tags.

### Description

`npm run docs:build` An error occurred `SyntaxError: Illegal '/' in tags.`

### Steps to reproduce
```markdown
## <img width="50px" src="https://raw.githubusercontent.com/ms314006/ms314006/basic/resource/gqsm.png" >
```
`npm run docs:build` An error occurred `SyntaxError: Illegal '/' in tags.`

- Reproduction link / repo:

### Screenshots
![image](https://user-images.githubusercontent.com/90107547/164774801-5fd8f977-1a72-4314-861b-81a6017b4cd7.png)

![image](https://user-images.githubusercontent.com/90107547/164775065-3608fa65-474d-4651-b28c-087f48667cf1.png)

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```

**Comment by Mister-Hope** [comment]
@meteorlxy  needs invistigation here, vite is yelling this after it release 2.9.5.

**Comment by meteorlxy** [comment]
Could not reproduce. Please check your code again, especially if you are using a valid whitespace.

It's obviously not an issue of vuepress. Your eslint-plugin-vue is also reporting error to you.
