### ISSUE TITLE
[Bug report] `collapsible: true,` fail

### ISSUE THREAD

**Issue by junjieweb** [vuepress/vuepress-next#864]
### Description

```typescript
import { defineUserConfig } from 'vuepress';

export default defineUserConfig({
  base: '/',
  title: 'VuePress Starter',
  description: 'VuePress Starter Project in Stackblitz',
  theme: '@vuepress/theme-default',
    themeConfig: {
      navbar: [
        {
          text: 'guide',
          link: '/guide/',
        },
        {
          text: 'test',
          link: '/test/',
        }
      ],
      sidebar: {
        '/guide/': [
            {
              text: 'test1',
              children: ['/guide/c.md', '/guide/d.md'],
            },
        ],
        '/test/': [
          {
            text: 'test1',
            collapsible: true,
            children: ['/test/a.md', '/test/b.md'],
          },
        ],
      },
    },
});

```
/test/ in `collapsible: true,` fail

### Reproduction

https://stackblitz.com/edit/vuepress-urhlna?file=docs%2F.vuepress%2Fconfig.ts

### Used Package Manager

npm

### System Info

```shell
no error
```

**Comment by Mister-Hope** [comment]
https://user-images.githubusercontent.com/33315834/166157094-739026e8-69de-4d04-856d-32fa6fd9e622.mp4

**Comment by junjieweb** [comment]
Sorry, the problem seems to have disappeared just now, but there seems to be something wrong with this one without configuration items, it can be turned on and off by clicking
![image](https://user-images.githubusercontent.com/90107547/166157515-edba4a39-00fa-4fee-ad57-f591d79a1dbe.png)

![image](https://user-images.githubusercontent.com/90107547/166157529-e00d0ee3-dc80-4911-b3d7-02885c938b8a.png)

**Comment by junjieweb** [comment]
The two problems seem to come in turns, either `test` cannot be folded, or `guide` can be folded, one has a problem, the other is fine

**Comment by junjieweb** [comment]
Reproduction
https://stackblitz.com/edit/vuepress-urhlna?file=docs%2F.vuepress%2Fconfig.ts

**Comment by Mister-Hope** [comment]
Updated, I am be able to reproduce in latest version.

https://stackblitz.com/edit/vuepress-7oyrkr?file=docs%2F.vuepress%2Fconfig.ts
