### ISSUE TITLE
[Bug report] Removing Themeconfig broke theme dir

### ISSUE THREAD

**Issue by devPaulRS** [vuepress/vuepress-next#868]
### Description

Since removing themeConfig and placing it inside theme.. can't use theme to route to my theme directory which extends the default theme

e.g:
```JS
theme: path.resolve(__dirname, "./theme")
```

What now, i also see this problem in all other themes now, can't extend.

### Reproduction

v2.vuepress.vuejs.org/new 

### Used Package Manager

npm

### System Info

```shell
nothing to see here
```

**Comment by meteorlxy** [comment]
```js
theme: require("./theme")
```
