### ISSUE TITLE
[Bug report] docs: missing alias config reference or broken link

### ISSUE THREAD

**Issue by its2easy** [vuepress/vuepress-next#880]
### Description

There is a link at the end of the last [section](https://v2.vuepress.vuejs.org/guide/assets.html#packages-and-path-aliases) to `alias` reference, but that [page](https://v2.vuepress.vuejs.org/reference/config.html#alias) doesn't have alias docs. I have found alias documentation only on plugin api page, but it works when I use it as top level .vuepress/config option without plugins.

### Reproduction

-

### Used Package Manager

npm

### System Info

```shell
-
```

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/167627478-eb15da46-3e34-4273-a004-a4f88eea6f0e.png)
