### ISSUE TITLE
Asset with special characters fail in vite

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#890]
报错日志如下:
[vite:asset] Could not load /home/runner/work/jiange1236.GitHub.io/jiange1236.GitHub.io/notes/work/设计.assets/Q0%7DK_%7D30WUFM.png (imported by notes/.vuepress/.temp/pages/work/设计.html.vue): ENOENT: no such file or directory, open '/home/runner/work/jiange1236.GitHub.io/jiange1236.GitHub.io/notes/work/设计.assets/Q0%7DK_%7D30WUFM.png'
✖ Compiling with vite - failed
详细报错信息可查看:
https://github.com/jiange1236/jiange1236.GitHub.io/runs/6422944653?check_suite_focus=true

_Originally posted by @jiange1236 in https://github.com/vuepress/vuepress-next/discussions/889_

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/168410911-04b4df41-82ad-4606-8459-6b352a983db3.png)
![image](https://user-images.githubusercontent.com/33315834/168410918-3ae5317f-23b3-44b6-8da5-6f5c6bcf1a83.png)

**Comment by jiange1236** [comment]
blank space(which shows "%20" in markdown) will also cause that problem

**Comment by Mister-Hope** [comment]
Wait I cannot reproduce it, could you please point out which file you import this image?

**Comment by jiange1236** [comment]
> Wait I cannot reproduce it, could you please point out which file you import this image?

@Mister-Hope https://github.com/jiange1236/jiange1236.GitHub.io/blob/main/notes/work/%E8%AE%BE%E8%AE%A1.md

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/168415497-4673c5c4-3bfe-4d2e-9ec3-fc5e9fb74c02.png)

You should keep links like this "as is" intead of encoding them.

**Comment by jiange1236** [comment]
yes, usually i didnt notice that and let typora automatically generate the link.
typora works fine with it,but it goes wrong in here.

**Comment by Mister-Hope** [comment]
The bundler needs the "real file path" of images to fetch them, instead of placing them using the same structure as local file system when deploying.

So you cannot encode the image path.

To solve this, you might need to write a custom `markdown-it` plugin, and decode all the image links for you.

**Comment by Mister-Hope** [comment]
Sadly, we cannot have this feature built in, because users do get a chance where they just has a filename which fits URL encoding (e.g: a%20b.png), and if that's the real image, a default behavior of `decodeURI`  will result `a b,.png` which is an unexisiting image.

**Comment by Mister-Hope** [comment]
> To solve this, you might need to write a custom `markdown-it` plugin, and decode all the image links for you.

V1 encode image url by the way, so I write a plugin to fix this, you may import and use this plugin directly (if all your image links are encoded)

https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/v1/packages/md-enhance/src/node/markdown-it/decode-url.ts

**Comment by jiange1236** [comment]
> > To solve this, you might need to write a custom `markdown-it` plugin, and decode all the image links for you.
> 
> V1 encode image url by the way, so I write a plugin to fix this, you may import and use this plugin directly (if all your image links are encoded)
> 
> https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/v1/packages/md-enhance/src/node/markdown-it/decode-url.ts

It may be a little bit diffecult for beginners like me but thanks for your help again.
I will be more careful using it next time.

**Comment by Mister-Hope** [comment]
Copy the file to your repo.

In your config file:

```ts
// .vuepress/config.ts
import { decodeURL } from './path/to/the/file';
// ...

export default defineUserConfig({
  // ...
  extendsMarkdown: (md) => {
    md.use(decodeURL)
  },
});
```

What's the actual difficulty here?
