### ISSUE TITLE
[Bug report] page is blank after new set new bundler option

### ISSUE THREAD

**Issue by liujunjia1996** [vuepress/vuepress-next#891]
### Description

i gave this change to my project ：

1. update version
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/43411944/168412579-2d2ecfa1-d0fe-4d67-95f8-7366dab0bc8f.png">
2. change config 
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/43411944/168412561-5d131996-70ea-4acb-856c-0fd18acf5f83.png">

after build, open index.html, and my page become blank， how can I do to fix this problem

### Reproduction

https://github.com/liujunjia1996/liujunjia1996.github.io

### Used Package Manager

npm

### System Info

```shell
"@vuepress/bundler-vite": "2.0.0-beta.43"
```

**Comment by Mister-Hope** [comment]
Try not to waste others time. Read changelog carefully please.

https://github.com/vuepress/vuepress-next/blob/main/CHANGELOG.md#200-beta40-2022-04-25

**Comment by liujunjia1996** [comment]
sorry for that, thanks for your help
