### ISSUE TITLE
[Bug report] Uncaught SynctaxError: Unexpected token '.' with Chrome 78.0.3904.70

### ISSUE THREAD

**Issue by lpaz010** [vuepress/vuepress-next#894]
### Description

![image](https://user-images.githubusercontent.com/39051367/168446322-f0a1a508-7f97-4ac2-b1bf-bd10d4f50f1f.png)

Windows 10 and chrome 78 seems not worked.

### Reproduction
follow the getting-start [link](https://v2.vuepress.vuejs.org/guide/getting-started.html#prerequisites) then runs in windows10 and chrome 78

### Used Package Manager

npm

### System Info

```shell
windows 10
chrome 78.0.3904.70
node 16.15.0
vuepress 2.0.0-beta.45
```

**Comment by Mister-Hope** [comment]
That's expected. Vite does not make polyfill.

![image](https://user-images.githubusercontent.com/33315834/168455745-4cc3535e-a031-452a-b3da-89cd7eb1c014.png)

If you do want to use lower version of browsers when developing, use webpack as bundler.

**Comment by lpaz010** [comment]
thanks.
