### ISSUE TITLE
[Bug report] Customize homepage features, switch languages disappear

### ISSUE THREAD

**Issue by Zhengqbbb** [vuepress/vuepress-next#897]
### Description

Hi ! I am Q.ben author of [cz-git](https://github.com/Zhengqbbb/cz-git)

## Clear  Description
Custom features **disappear** when switching languages

https://user-images.githubusercontent.com/40693636/168727287-a7bc71ab-c81b-4ee0-97a3-a2f37eb603d7.mp4

## Background
Recently, I am developing the documentation of cz-git, and there is a requirement: **custom embedded HTML tags** can be satisfied in the feature block.
So I wrote HTML tags `<div class="features">` `<div class="feature">` to implement in markdown, but if the document **contains markdown elements** `- hello`, the bug will be triggered when packaged online.

## How to reproduce
1. Write the features html tag
2. Also include markdown elements
3. **Build** and deploy online
4. Switch language

> Since it can only be reproduced after building, it will be difficult to debug

```
git clone --branch bug/features https://github.com/Zhengqbbb/vuepress-test.git 
cd vuepress-test && yarn && yarn docs:build && yarn docs:serve
```

<img width="832" alt="image" src="https://user-images.githubusercontent.com/40693636/168727675-6e2ac692-a2e9-4c65-b84f-76d72ebc224f.png">

## Expect
1. Switching languages can render normally `<div class="theme-default-content custom"></div>`
2. Sure if possible, I think **features yml** can support html tag like footer, currently only string can be supported. native rendering will be faster

## My current solution
Currently this issue is circumvented by creating pure static components using `@vuepress/plugin-register-components`. 

### Reproduction

https://github.com/Zhengqbbb/vuepress-test/tree/bug/features

### Used Package Manager

yarn

### System Info

```shell
yarn run v1.22.18
$ vuepress info

  System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 577.98 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /var/folders/p3/55bvbjg57lzb1d2b_mwbzykw0000gn/T/yarn--1652760396447-0.9673345963323681/node
    Yarn: 1.22.18 - /var/folders/p3/55bvbjg57lzb1d2b_mwbzykw0000gn/T/yarn--1652760396447-0.9673345963323681/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Utilities:
    Git: 2.30.1 - /usr/bin/git
  Browsers:
    Chrome: 101.0.4951.64
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.1
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.45
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.45
    @vuepress/client:  2.0.0-beta.45
    @vuepress/core:  2.0.0-beta.45
    @vuepress/markdown:  2.0.0-beta.45
    @vuepress/plugin-active-header-links:  2.0.0-beta.45
    @vuepress/plugin-back-to-top:  2.0.0-beta.45
    @vuepress/plugin-container:  2.0.0-beta.45
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.45
    @vuepress/plugin-git:  2.0.0-beta.45
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.45
    @vuepress/plugin-nprogress:  2.0.0-beta.45
    @vuepress/plugin-palette:  2.0.0-beta.45
    @vuepress/plugin-prismjs:  2.0.0-beta.45
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.45
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.45
    @vuepress/theme-default:  2.0.0-beta.45
    @vuepress/utils:  2.0.0-beta.45
    vue:  3.2.33
    vue-loader: Not Found
    vue-router:  4.0.15
    vuepress: ^2.0.0-beta.45 => 2.0.0-beta.45
    vuepress-vite:  2.0.0-beta.45
    vuepress-webpack: Not Found

✨  Done in 1.91s.
```

**Comment by Mister-Hope** [comment]
I personally think this is the same as #688

**Comment by meteorlxy** [comment]
I'm afraid there is some issue of vue core about fragment. Wrapping the markdown content with an extra `<div>` would solve this.
