### ISSUE TITLE
[Bug report] 内置组件 <CodeGroupItem> 缩进问题

### ISSUE THREAD

**Issue by yuangexin** [vuepress/vuepress-next#900]
### Description

默认主题内置组件 ``</CodeGroupItem>``  结束标签缩进不允许大于等于4个空格

### Reproduction

````
<CodeGroup>
	<CodeGroupItem title="NPM">

```bash:no-line-numbers
yarn
```

	</CodeGroupItem>

</CodeGroup>
````

### Used Package Manager

yarn

### System Info

```shell
Element is missing end tag.
```

**Comment by meteorlxy** [comment]
It should be a valid markdown syntax first.

Check the "source" panel: http://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3CCodeGroup%3E%5Cn%5Ct%3CCodeGroupItem%20title%3D%5C%22NPM%5C%22%3E%5Cn%5Cn%60%60%60bash%3Ano-line-numbers%5Cnyarn%5Cn%60%60%60%5Cn%5Cn%5Ct%3C%2FCodeGroupItem%3E%5Cn%5Cn%3C%2FCodeGroup%3E%22%2C%22defaults%22%3A%7B%22html%22%3Atrue%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22src%22%7D%7D

**Comment by yuangexin** [comment]
I don't understand

**Comment by yuangexin** [comment]
I think I get it
