### ISSUE TITLE
Line number and code block lines misalign in some devices

### ISSUE THREAD

**Issue by dingqianwen** [vuepress/vuepress-next#901]
### Description

目前版本：`2.0.0-beta.45`  

当代码块行数很多时，行号与代码对应不齐问题，如下图所示  
![image](https://user-images.githubusercontent.com/38466535/169662058-389579dc-2bd1-4dc3-83c9-43aad716a0db.png)

通过重写`div[class*=language-].line-numbers-mode .line-numbers .line-number`样式`height: 1.377em;`自行修复后如下所示  
![image](https://user-images.githubusercontent.com/38466535/169662099-ff9ce5bc-6ef4-450e-bbc7-3c5eb10e9960.png)

### Reproduction

https://apidocs.cn/blog/front/css/%E5%A5%BD%E7%9C%8B%E7%9A%84%E5%8A%A0%E8%BD%BD%E5%8A%A8%E7%94%BBCSS%E6%A0%B7%E5%BC%8F.html

### Used Package Manager

npm

### System Info

```shell
***@localhost my-blog % vuepress info

  System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 540.20 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.5.5 - /usr/local/bin/npm
  Utilities:
    Git: 2.32.1 - /usr/bin/git
  Browsers:
    Chrome: 94.0.4606.71
    Edge: Not Found
    Firefox: 100.0.1
    Safari: 15.4
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.45 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.45 
    @vuepress/client:  2.0.0-beta.45 (2.0.0-beta.5)
    @vuepress/core:  2.0.0-beta.45 (2.0.0-beta.5)
    @vuepress/markdown:  2.0.0-beta.45 (2.0.0-beta.5)
    @vuepress/plugin-active-header-links:  2.0.0-beta.45 
    @vuepress/plugin-back-to-top:  2.0.0-beta.45 
    @vuepress/plugin-container:  2.0.0-beta.45 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.45 
    @vuepress/plugin-git:  2.0.0-beta.45 
    @vuepress/plugin-google-analytics: ^2.0.0-beta.45 => 2.0.0-beta.45 
    @vuepress/plugin-medium-zoom:  2.0.0-beta.45 
    @vuepress/plugin-nprogress:  2.0.0-beta.45 
    @vuepress/plugin-palette:  2.0.0-beta.45 
    @vuepress/plugin-prismjs:  2.0.0-beta.45 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: 2.0.0-beta.45 => 2.0.0-beta.45 
    @vuepress/plugin-search: 2.0.0-beta.45 => 2.0.0-beta.45 
    @vuepress/plugin-shiki: ^2.0.0-beta.5 => 2.0.0-beta.5 
    @vuepress/plugin-theme-data:  2.0.0-beta.45 
    @vuepress/plugin-toc: 2.0.0-beta.45 => 2.0.0-beta.45 
    @vuepress/shared:  2.0.0-beta.45 (2.0.0-beta.4)
    @vuepress/theme-default:  2.0.0-beta.45 
    @vuepress/utils:  2.0.0-beta.45 (2.0.0-beta.5)
    vue:  3.2.33 
    vue-loader: Not Found
    vue-router:  4.0.15 
    vuepress: 2.0.0-beta.45 => 2.0.0-beta.45 
    vuepress-vite:  undefined (2.0.0-beta.45)
    vuepress-webpack: Not Found
```

**Comment by dingqianwen** [comment]
同时，咱们官网也有一样的问题，虽然代码块只有20行，如下图所示  

![image](https://user-images.githubusercontent.com/38466535/169662273-9186b3c1-5c28-4d7a-8d86-e9a6cf3f95e8.png)
 
请问，我是否可以提交一个PR🥺

**Comment by Mister-Hope** [comment]
欢迎，但请你在PR里写清楚问题发生的原因以及行高的计算过程。

我印象中我没有在最近的版本更改过相关代码，而且我也不记得哪里有  1.377em

**Comment by dingqianwen** [comment]
> 欢迎，但请你在PR里写清楚问题发生的原因以及行高的计算过程。
> 
> 我印象中我没有在最近的版本更改过相关代码，而且我也不记得哪里有 1.377em

_好的，谢谢，是出问题的是目前`1.4` 经过多次计算与测试改为 `1.377`是正常的，我正准备提交PR

**Comment by dingqianwen** [comment]
修复后的官网效果下图所示，同时我自己博客的代码块也经过大量测试，等待合并PR中😊

![image](https://user-images.githubusercontent.com/38466535/169663520-0fb0d7f9-bd69-4e92-aa65-b07318854ebe.png)

**Comment by Mister-Hope** [comment]
我的问题是 0.0333 em 是在哪查出来的。

**Comment by dingqianwen** [comment]
> 我的问题是 0.0333 em 是在哪差出来的。

一行差这么多，行越多，差的越多，100多行后都跑外面去了。

**Comment by Mister-Hope** [comment]
我跟你对话这么费劲呢？如果这是你凑出来的，你只能说明当前你使用的 Chrome 浏览器，在使用 1.377作为行高是正常的。

它不能说明：

- Safari 1.377 也正常
- Firefox 也正常
- 其他诸如手Q浏览器（X5内核） 等其他内核浏览器也正常。

**Comment by dingqianwen** [comment]
> 我跟你对话这么费劲呢？如果这是你凑出来的，你只能说明当前你使用的 Chrome 浏览器，在使用 1.377作为行高是正常的。
> 
> 它不能说明：
> 
> * Safari 1.377 也正常
> * Firefox 也正常
> * 其他诸如手Q浏览器（X5内核） 等其他内核浏览器也正常。
> 
> 在找到一个完整的解释，解答为什么在 Chrome 全部（或特定）版本正常使用和代码行高相同的1.4em会出现“对不齐”的问题，以及一个完整的计算，差出的是多少之前，我拒绝任何此类PR。

👍，这里代码2022.5.14日有人改过这里的样式，我说怎么突然这样了，换成以前的版本没问题

**Comment by Mister-Hope** [comment]
我刚才debug一下，我毫无头绪，我自己第主题是正常的，但是我自己的主题和官方主题的样式几乎一样（至少在字号布局方面我没看到有什么不一样的地方）。

代码那边行高就是 1.4，原则上行号这边1.4应该和我主题一样是对齐的。有兴趣你可以接着研究研究。凑数是不行的，我刚才看了一下我的ipad，我肉眼看官网文档没看到很明显的越来越对不齐的痕迹。

这个问题我觉得不是很着急，有空看看@meteorlxy有没有什么思路，至少我现在是没有任何头绪差的这一丁点是哪出来的。

你可以先自行按照你凑出来的自己覆盖一下样式。

**Comment by dingqianwen** [comment]
> 我刚才debug一下，我毫无头绪，我自己的主题是正常的，但是我自己的主题和官方主题的样式几乎一样（至少在字号布局方面我没看到有什么不一样的地方）。
> 
> 代码那边行高就是 1.4，原则上行号这边1.4应该和我主题一样是对齐的。有兴趣你可以接着研究研究。凑数是不行的，我刚才看了一下我的ipad，我肉眼看官网文档没看到很明显的越来越对不齐的痕迹。
> 
> 这个问题我觉得不是很着急，有空看看@meteorlxy有没有什么思路，至少我现在是没有任何头绪差的这一丁点是哪出来的。
> 
> 你可以先自行按照你凑出来的自己覆盖一下样式。

👍，好的，辛苦了，早点睡吧

**Comment by Mister-Hope** [comment]
你的复现现在已经失效了，meteorlxy不能复现，你有什么改动么？我有留意到你加了一行height:auto，但禁用它并没有什么变化。

**Comment by soeasyjx** [comment]
请问你使用的 vuepress 是2.x 的版本么

**Comment by Tarocch1** [comment]
我这里在 chrome 上是正常的，但是 safari 有问题，包括 mac、iphone 和 ipad。

<img width="894" alt="image" src="https://user-images.githubusercontent.com/15124068/173229556-a07f6b1a-83de-41ab-93cf-b99c44c4eb43.png">

试了一下，删掉 `.line-number` 的 `height` 属性可以解决问题：

<img width="865" alt="image" src="https://user-images.githubusercontent.com/15124068/173229586-57c7c253-d99f-433d-8883-c688eab661b2.png">

正式修复之前，应该可以先在自己页面上设置 `auto` 临时处理一下：

```css
.line-number {
  height: auto !important;
}
```

**Comment by nibazshab** [comment]
我这里 chrome，safari, edge 都有问题，且无论 height 设为多少都无法对齐，最多只能让某一个代码块的行号对齐，另一个代码块会发生更严重的错位
