### ISSUE TITLE
[Feature request] add support for cdn

### ISSUE THREAD

**Issue by darkyzhou** [vuepress/vuepress-next#904]
### Clear and concise description of the problem

Here is an example build `dist`:
```
.
├── 404.html
├── assets
│   ├── some.css
│   └── some.js
├── index.html
...
```

From what I have learned, [vuepress uses `${app.options.base}${outputEntryChunk.fileName}` as the `src` for tags like `<script>`, `<link>`, etc](https://github.com/vuepress/vuepress-next/blob/HEAD/packages/@vuepress/bundler-vite/src/build/renderPageScripts.ts#L14). And the `app.options.base` can only be a relative path(is it because the field is also consumed by the router?).

I think this prevents user from uploading the files in `assets` to the cdn and configure vuepress to point to it.

### Suggested solution

It will be much helpful to add an extra field called `cdnUrl` so that vuepress can use it to prefix the urls of static resources.

Would like to help making a PR if this is a good idea.

**Comment by Mister-Hope** [comment]
I am very confused, as VuePress uses SSR to generate HTML files for better seo. So a better practice is mirroring your whole site on CDN, (or in another word, set domain of your CDN to currect domain).

If you are talking about assets in public folder, then we recommand you to make public folder a git submodule, and try to manage it sperately and upload it to CDN, also this means you should use full urls with CDN domain to access them in VuePress. The other resources generated by vuepress should work pretty well.

**Comment by Mister-Hope** [comment]
Also, if you not accelate your html files, you won't get any accelation with FCP.

**Comment by darkyzhou** [comment]
Thank you for explaining. I have some misunderstandings about vuepress and cdn.

**Comment by huaasto** [comment]
> I am very confused, as VuePress uses SSR to generate HTML files for better seo. So a better practice is mirroring your whole site on CDN, (or in another word, set domain of your CDN to currect domain).
> 
> If you are talking about assets in public folder, then we recommand you to make public folder a git submodule, and try to manage it sperately and upload it to CDN, also this means you should use full urls with CDN domain to access them in VuePress. The other resources generated by vuepress should work pretty well.

I have a problem: If I change my contents in md file, the html will not change because of cdn cache, unless I clear the cache.It's not a good idea.So finally I still need to depart my static source and bundled html.Is there any solution to solve the problem?

**Comment by meteorlxy** [comment]
Using proper cdn cache rules should be a good idea. Why you think it's not?
