### ISSUE TITLE
[Feature request] More targeted search functionality

### ISSUE THREAD

**Issue by rogier-stegeman** [vuepress/vuepress-next#910]
### Clear and concise description of the problem

Currently I'm using frontmatter tags to enhance search functionality. However, the most this can do is bring you to the correct page. I would like to be able to provide tags for specific locations on a page. This would be very helpful for large pages that cover a lot of topics, without having to rely on creating a ton of headers.

Current simplified example setup:

config.ts
```
  plugins: [
    searchPlugin({
      getExtraFields: (page) => page.frontmatter.tags ?? []
    }),
  ],
```

knights-of-camelot.md
```
---
{
    tags: [ 'Knights of Camelot', 'Aglovale de Galis', 'Arthur the Less', 'Bleoberis', 'Brandelis'],
}
---
# Knights of Camelot

## Starting with A

- Aglovale de Galis
- Arthur the Less

## Starting with B

- Bleoberis
- Brandelis
```

### Suggested solution

- Ability to search full text.
- Ability to specify tags per header in frontmatter block.
    ```
    ---
    {
        tags: {
            'Knights of Camelot': ['Knights of Camelot', 'Round table'],
            'Starting with A': ['Aglovale de Galis', 'Arthur the Less'],
            'Starting with B': ['Bleoberis', 'Brandelis'],
    }
    ---
    ```
- Ability to declare tags either at a header or anywhere. Not sure how to do this without creating something very custom.
    ```
    ## Starting with A
    <!-- tags: ['Aglovale de Galis', 'Arthur the Less'] -->
    
    - Aglovale de Galis
    - Arthur the Less
    
    ## Starting with B
    <!-- tags: ['Bleoberis', 'Brandelis'] -->
    
    - Bleoberis
    - Brandelis
    ```

### Alternative

- Creating a ton of headers would improve targeted search, but would make the documentation less readable. Besides, the search does not go any deeper than headers of level 3, so this would still be limited.

**Comment by Mister-Hope** [comment]
> . Besides, the search does not go any deeper than headers of level 3, so this would still be limited.

You can config markdown options in config file to let vuepress extract deeper level of headers.

I think currectly the built in search plugin is workable enough, as you should use a search provider for a good search experience, instead of forcing people to download a "Search Database" when visiting the first page.
