### ISSUE TITLE
[Bug report] Would it be better to hide the APIkey of docsearchPlugin?

### ISSUE THREAD

**Issue by henryhuanghenry** [vuepress/vuepress-next#912]
### Description

Hello, 
It is a gentle reminder. I don't know whether the API key of the docsearchPlugin is confidential information.
So I raise this issue to remind who it may concern.
I hope it would not cause any inconvenience.

Best,

### Reproduction

In doc: https://github.com/vuepress/vuepress-next/blob/main/docs/.vuepress/config.ts

### Used Package Manager

npm

### System Info

```shell
None.
```

**Comment by meteorlxy** [comment]
https://docsearch.algolia.com/docs/DocSearch-program#can-i-share-the-apikey-in-my-repo
