### ISSUE TITLE
[Feature request] Remove header anchor when scrolling to page top

### ISSUE THREAD

**Issue by KnorpelSenf** [vuepress/vuepress-next#913]
### Clear and concise description of the problem

When I open a page, there is no header anchor in the URL. As I scroll down, the URL is automatically adjusting to the section I'm reading. However, when I scroll back up to the very top of the page, the first header is still included in the URL.

### Suggested solution

When I scroll back up before the first section, the header should be removed, so that the URL is identical again to the once I see when I visit the page initially.

### Alternative

Alternatively, if “up before the first section” is not easy enough to define, it would be okay if the anchor was removed as soon as the scrolling index hits 0, i.e. the page is scrolled fully to the top.

### Additional context

When I want to share a link to the docs, I commonly open a page, scroll a bit down to see if it contains all the concepts I want to explain, and then scroll back to the top to copy the link. However, now it contains an anchor, which I have to remove manually every time.

**Comment by Mister-Hope** [comment]
Nice catch, I already had a dicusion with meteorlxy, and I was going to open one, but just forgot it.

PR welcomed.
