### ISSUE TITLE
[Feature request] Add more functionality to sidebar

### ISSUE THREAD

**Issue by devPaulRS** [vuepress/vuepress-next#914]
### Clear and concise description of the problem

Navigation and sidebars without dynamic support makes it difficult to develop on custom menus.

I tried using plugins but they constantly break with your updates 🤷🏻‍♂️

### Suggested solution

Please add the following:

1. Directory Based Auto Navigation (as an optional addition)

2. Allow for Navigation parts to be visible or invisible based on events.

3. Why does updating the menu mean a total restart of the server.. ridiculous.

### Alternative

Provide a method to hide and show submenu category and children of the menu depending on a button click.

Note it shouldnt render that part of the menu at all if the button is not toggled.

### Additional context

Tried so many ways but it's rather difficult to work on vuepress with limitations , im actually quite supprised.

**Comment by Mister-Hope** [comment]
For point 3 You are setting your config at node side, and a such changes means restarting the server. 

Also I prefer to vote no to all of your requests. We provide alias for components, and youcan use that option to override navbar and sidebar to provide a new component you like. And if you want to get used of the internal events you can just copy the existing ones and catch those events, anyway,I am not seeing any inefficiency here, just do exactly what you are developing a Vue application

**Comment by meteorlxy** [comment]
> Why does updating the menu mean a total restart of the server.. ridiculous.

It's not because of the menu. Modifying the config file will restart the server.

As you know, we are using plugins / setting theme / setting bundler in config file. Without furthor analysis of the modification, the most reasonable way to handle the config file update is to totally restart the dev server.

**Comment by devPaulRS** [comment]
@meteorlxy This causes downtime when you deploy new menu items, there should be a way to do so without needing to restart.

Could we seperate the menu from config as it's own menu config?

**Comment by Mister-Hope** [comment]
Again, we support plugin and theme api, and we have no idea which option is not inflecting the apllication and can be handled through HMR.

For example a theme is providing a `blog` option, we have no idea whether this option is only used as client side, or it does register/not register a blog layout, does/doesn't generate a temp file and does/doesn't change alias and defining  variables.

So it's impossible to provide such abilities under common scenarios

**Comment by devPaulRS** [comment]
@Mister-Hope 

Thanks for the reply, i understand your point of view and what you're saying makes sense.

Though if as you mentioned they specify theme type as blog option, since we don't know if it's going to be client side of if it should register a blog layout etc.

It makes sense then to have a option to specify if it should be client side rendered or not and if it is specified in the guide it can state that there are limitations etc.

This makes it so that it's still the same, and for those that aren't using blog layout or need the above mentioned so that they can still do client-side rendering.

**Comment by devPaulRS** [comment]
@Mister-Hope 

I just don't think it's practical to restart the server to update a menu item, deploying changes like a menu item should naturally update the menu, but in-staid it completely restarts it.

While i can see this is needed for common scenarios, downtime in general means traffic or movement loss, in any business down-time for example equates to expense and for deploying just a simple menu item such as adding a additional guide completely restarts for everyone, i hope you can understand the frustration behind that.

**Comment by Mister-Hope** [comment]
> This wasn't a issue in v1.

Is it? I don't think that V1 has any HMR with navbar or sideabrs, I may be wrong, but I still want you to confirm that.

**Comment by Mister-Hope** [comment]
> A possible solution is to totally separate "node config file" and "client config file". Then configs like sidebar/navbar should go into client config file.
> 
> We have already considered about that, and might be implement in a future release (with breaking changes for sure)

Yes, this makes sence.

**Comment by devPaulRS** [comment]
@meteorlxy That sounds ideal thanks.

@Mister-Hope Yes, there were work-around that use to work but because of v2 additional things and bundler etc it made it impossible to work around it, otherwise i wouldn't have bothered writing here as i could have done it myself, so for now i'll just have restarts until the future release as you guys mention.
