### ISSUE TITLE
[Feature request] V2 The child definition level of the sidebar does not take effect

### ISSUE THREAD

**Issue by limingqiang-git** [vuepress/vuepress-next#923]
### Clear and concise description of the problem

Hi, Author, I am vuepress fan , To record daily knowledge, I am a user of V1. Now I want to upgrade and migrate wiki documents to V2 version, 
but I find that when deploying and configuring sidebar, **sidebardepth:0** does not take effect. Previously, it was in config.js  , can also be configured. It can also be configured in the sidebar of the child level. Can't this be written in the V2 version now

### Suggested solution

<img width="577" alt="image" src="https://user-images.githubusercontent.com/37126870/171605186-06438dbd-fd60-4df4-9826-8228cfe83e1d.png">

- V2 The child definition level of the sidebar does not take effect

**Comment by Mister-Hope** [comment]
We do not support this in V2, if you want, you may set it in page frontmatter.
