### ISSUE TITLE
[Feature request] Ability to set the source directory

### ISSUE THREAD

**Issue by sebnitu** [vuepress/vuepress-next#924]
### Clear and concise description of the problem

**Context** 

I'm currently looking to add documentation for a monorepo project. The current structure of the monorepo is a `packages` directory containing all the modules with their own `README.md` files. Ideally, I want to use Vuepress to create documentation using this pretty standard monorepo structure.

**Problem**

The problem I'm running into is that I don't see a way to change what vuepress uses as the `sourceDir`, so I can't tell vuepress to use the markdown files that already exist in the project.

### Suggested solution

Allow users to set the `sourceDir` so instead of having to put all my markdown files in `docs`, I could set the source directory to the root of the project`/` and keep the structure of the monorepo.

**Comment by Mister-Hope** [comment]
> Allow users to set the sourceDir so instead of having to put all my markdown files in docs, I could set the source directory to the root of the project/ and keep the structure of the monorepo.

```
vuepress dev [dir]

vuepress build [dir]
```

So if you want abc

```
vuepress dev abc
vuepress build abc
```

If you want rootDir

```
vuepress dev .
vuepress build .
```

What's the problem here?
