### ISSUE TITLE
[Bug report] Menu items with the same name will conflict

### ISSUE THREAD

**Issue by ilgnefz** [vuepress/vuepress-next#925]
### Description

If I have the following items in the sidebar

```
Menu A
    ----- A
    ----- B
Menu B
    ----- B
    ----- C
```

At this time, the ids of the four elements A, B, and C are a, b, and c, respectively.

When I click on B in Mnue A, B in Menu B is also selected to expand.

I tried adding a parent prefix to these same options, like it:

`link: "#b"` -> `link: "MenuA.#b"`,
 `link: "#b"` -> `link: "MenuB.#b"`

When I click on their parent option, it's selected by default

project's repo: <https://github.com/ilgnefz/flame-cn>

project's site: <https://ilgnefz.github.io/flame-cn/guide/started.html>

You can try clicking the following options in sequence:
Flame -> 组件  &  其他模块 -> Oxygen

configuration files:
.vuepress -> config -> sidebar -> flame -> components.js
&
.vuepress -> config -> sidebar -> other_modules -> oxygen.js

### Reproduction

https://github.com/ilgnefz/flame-cn

### Used Package Manager

npm

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 7.92 GB / 15.88 GB
  Binaries:
    Node: 16.13.1 - D:\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.11.0 - D:\nodejs\npm.CMD
  Utilities:
    Git: 2.36.1.
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.30)
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.45
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.45
    @vuepress/client:  2.0.0-beta.45
    @vuepress/core:  2.0.0-beta.45
    @vuepress/markdown:  2.0.0-beta.45
    @vuepress/plugin-active-header-links:  2.0.0-beta.45
    @vuepress/plugin-back-to-top:  2.0.0-beta.45
    @vuepress/plugin-container:  2.0.0-beta.45
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.45
    @vuepress/plugin-git:  2.0.0-beta.45
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.45
    @vuepress/plugin-nprogress:  2.0.0-beta.45
    @vuepress/plugin-palette:  2.0.0-beta.45
    @vuepress/plugin-prismjs:  2.0.0-beta.45
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.45
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.45
    @vuepress/theme-default:  2.0.0-beta.45
    @vuepress/utils:  2.0.0-beta.45
    vue:  3.2.34
    vue-loader: Not Found
    vue-router:  4.0.15
    vuepress: ^2.0.0-beta.45 => 2.0.0-beta.45
    vuepress-vite:  2.0.0-beta.45
    vuepress-webpack: Not Found
```

**Comment by henryhuanghenry** [comment]
I have read the files 
> .vuepress -> config -> sidebar -> flame -> components.js 
> .vuepress -> config -> sidebar -> other_modules -> oxygen.js
 
I think I might know the reason for this problem.

In function ["isActiveSidebarItem.ts "](https://github.com/vuepress/vuepress-next/blob/1cb6c97a8250aa641a8e1ecf01e047bf705165cd/packages/@vuepress/theme-default/src/client/utils/isActiveSidebarItem.ts):
- The link is compared with the "router.hash". For example, if we are at the link "#A" and the current router.hash is also "#A", the sidebar of "#A" is active and selected, and would not be collapsed.
- If link!=router.hash, the link and the router.path would be normalized (In the link, "#whatever_behind" would be removed from the string.). Then the normalized link would be compared to the "router.path". 

Thus, in your case:
```JavaScript 
module.exports = {
    text: "组件",
    collapsible: true,
    link: "/guide/flame/components.md", //when we are at this link
    children: [
        {
            text: "PositionComponent",
            link: "/guide/flame/components.md#positioncomponent",  //the normalized(router.path) here is also equal to normalized(that link), so PositionComponent would also be selected.
        },
... omit whatever below 
```

**Comment by ilgnefz** [comment]
> I have read the files
> 
> > .vuepress -> config -> sidebar -> flame -> components.js
> > .vuepress -> config -> sidebar -> other_modules -> oxygen.js
> 
> I think I might know the reason for this problem.
> 
> In function ["isActiveSidebarItem.ts "](https://github.com/vuepress/vuepress-next/blob/1cb6c97a8250aa641a8e1ecf01e047bf705165cd/packages/@vuepress/theme-default/src/client/utils/isActiveSidebarItem.ts):
> 
> * The link is compared with the "router.hash". For example, if we are at the link "#A" and the current router.hash is also "#A", the sidebar of "#A" is active and selected, and would not be collapsed.
> * If link!=router.hash, the link and the router.path would be normalized (In the link, "#whatever_behind" would be removed from the string.). Then the normalized link would be compared to the "router.path".
> 
> Thus, in your case:
> 
> ```js
> module.exports = {
>     text: "组件",
>     collapsible: true,
>     link: "/guide/flame/components.md", //when we are at this link
>     children: [
>         {
>             text: "PositionComponent",
>             link: "/guide/flame/components.md#positioncomponent",  //the normalized(router.path) here is also equal to normalized(that link), so PositionComponent would also be selected.
>         },
> ... omit whatever below 
> ```

So what can I do to solve this problem? If I delete "router.path", others with the same "#whatever_behind" will also expand.

**Comment by henryhuanghenry** [comment]
I don't know whether it is a bug. 
This is a remained question for the maintainers.
I might have a simple solution for your problem.

I think you could change the codes in [isActiveSidebarItem.ts](https://github.com/vuepress/vuepress-next/blob/1cb6c97a8250aa641a8e1ecf01e047bf705165cd/packages/@vuepress/theme-default/src/client/utils/isActiveSidebarItem.ts):
```javascript
const isActiveLink = (
  link: string,
  route: RouteLocationNormalizedLoaded
): boolean => {
  if (route.hash === link) {
    return true
  }
  const currentPath = normalizePath(route.path)
  const targetPath = normalizePath(link)
  return currentPath === targetPath
}
```

To:

```javascript
const isActiveLink = (
  link: string,
  route: RouteLocationNormalizedLoaded
): boolean => {
  if (route.hash === link) {
    return true
  }
  const currentPath = normalizePath(route.path)
  const targetPath = normalizePath(link)
  if (decodeURI(link).match('#.*$') != null) { // The link is a path and is attached with anchor.
    return currentPath === targetPath && route.hash === decodeURI(link).match('#.*$')[0] // compare the path and the anchor of the link
  }
  return currentPath === targetPath
}
```

I have not tested it yet.....

**Comment by meteorlxy** [comment]
You should not include the path in your case, i.e.

```diff
        {
            text: "PositionComponent",
-           link: "/guide/flame/components.md#positioncomponent",
+           link: "#positioncomponent",
        },
```

Also, I'd suggest you not to set those anchors manually.
