### ISSUE TITLE
[Feature request] Remove header and HTML tag in excerpt

### ISSUE THREAD

**Issue by longern** [vuepress/vuepress-next#934]
### Clear and concise description of the problem

This is my markdown document:
```md
# Another hello world

As my previous personal website will expire after my graduation, I have to move my blog to a permanent service provider.

<!-- more -->

...
```

Up to version v2.0.0-beta.46, the excerpt of my document will be rendered as something like:
```
<h1 id="another-hello-world" tabindex="-1"><a class="header-anchor" href="#another-hello-world" aria-hidden="true">#</a> Another hello world</h1> <p>As my previous personal website will expire after my graduation, I have to move my blog to a permanent service provider.</p>
```

What I expect is a more human-readable version:
```
As my previous personal website will expire after my graduation, I have to move my blog to a permanent service provider.
```

### Suggested solution

Remove `<h1>` tag and other html tags such as `<p></p>` to make the excerpt more human-readable (something like `innerText`?).

### Alternative

Provide some ways to manually remove them.

**Comment by Mister-Hope** [comment]
Could you please reorganize your issue so that others could understand them? 

> Title and HTML tags are also included which may not suitable for homepage.

What do you mean by title and what do you mean by html tags?

> may not suitable for homepage.

Why to say that? Are you setting excerpt for homepage? What do you want?

**Comment by longern** [comment]
> Could you please reorganize your issue so that others could understand them?
> 
> > Title and HTML tags are also included which may not suitable for homepage.
> 
> What do you mean by title and what do you mean by html tags?
> 
> > may not suitable for homepage.
> 
> Why to say that? Are you setting excerpt for homepage? What do you want?

An example is added. Review it?

**Comment by Mister-Hope** [comment]
I think you are describing a behavior we have not changed from V1.

You are expected to use `v-html` to inject those thing into places you want.

If you don't want h1, do:

```
---
title: Your title
---

Your excerpt.

<!-- more -->

...
```

instead.

**Comment by Mister-Hope** [comment]
Also I would like to correct some expressions you made.

You should use heading1, heading2, or h1, h2 for "headings", when you are talking about "title" along with html tags, people will likely regard them as `<title>` tag in html head. So that's why I am confusing. Also, I am not seeing this related to "HomePage"

**Comment by Mister-Hope** [comment]
Anyway,since we can't covert markdown content (and even VueComonent) to be plain text, we are unable to provide a similar featreus, and we point out you can use `extendsPage` hook to generate a plain excerpt yourself and use it. So we are closing this

**Comment by longern** [comment]
A possible solution(need `jsdom` package):
```ts
import { JSDOM } from "jsdom";

extendsPage(page) {
  const excerptDOM = new JSDOM(page.excerpt || page.contentRendered);
  const excerptDocument: Document = excerptDOM.window.document;
  page.excerpt = <string>excerptDocument.querySelector("p")?.textContent;
},
```
