### ISSUE TITLE
[Bug report] docs:dev and docs:build run successfully; serving production build throws router(?) errors and removes the app from the page

### ISSUE THREAD

**Issue by adamdehaven** [vuepress/vuepress-next#935]
### Description

I linked to a PR on our `beta` branch with [a working deploy preview](https://deploy-preview-656--kongponents.netlify.app/) where you can view the actual errors.

In the [reproduction PR](https://github.com/Kong/kongponents/pull/656), I am upgrading our VuePress beta version (and related dependencies) from `vuepress@^2.0.0-beta.37` to `vuepress@^2.0.0-beta.48`

🟢  When I run `docs:dev` the local VuePress site spins up successfully with no issues  
🟢  When I run `docs:build` the docs directory is properly built with zero errors or messages  

🔴  When the built `docs/.vuepress/dist` files are served (either locally using `yarn docs:preview` in the repo, or on the Netlify deploy preview) the site loads successfully for a split second; however, then starts throwing the errors shown below:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/2229946/173242139-fdca00e6-d94e-418a-b41f-4878bf9fd42f.png">

When I inspect the page, I can see that the errors that were thrown have cleared out the entire contents of the VuePress app

<img width="280" alt="image" src="https://user-images.githubusercontent.com/2229946/173242187-1e8d371a-018f-44f6-8f6d-3182997f5cf8.png">

- If I remove the `sidebar` entry from the `theme: defaultTheme({ /* ... */ })` config, the site will properly render (without clearing the content); however, navigation is still completely broken, which leads me to believe this bug is somehow related to the router.
- I have tried disabling VuePress plugins, and have noticed that if I disable any of the plugins that utilize `router.afterEach` the number of errors is reduced

### Reproduction

https://github.com/Kong/kongponents/pull/656

### Used Package Manager

yarn

### System Info

<details>

<summary>Click to expand system info</summary>

```shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 5.41 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /var/folders/mg/3ttphynn3f13__q7wph27bbm0000gq/T/yarn--1655049285146-0.9745900856344969/node
    Yarn: 1.22.17 - /var/folders/mg/3ttphynn3f13__q7wph27bbm0000gq/T/yarn--1655049285146-0.9745900856344969/yarn
    npm: 8.6.0 - ~/Development/kongponents/node_modules/.bin/npm
  Utilities:
    Git: 2.32.1 - /usr/bin/git
  Browsers:
    Chrome: 102.0.5005.115
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.48
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.48
    @vuepress/client:  2.0.0-beta.48
    @vuepress/core:  2.0.0-beta.48
    @vuepress/markdown:  2.0.0-beta.48
    @vuepress/plugin-active-header-links:  2.0.0-beta.48
    @vuepress/plugin-back-to-top: ^2.0.0-beta.48 => 2.0.0-beta.48
    @vuepress/plugin-container:  2.0.0-beta.48
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.48
    @vuepress/plugin-git:  2.0.0-beta.48
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.48
    @vuepress/plugin-nprogress:  2.0.0-beta.48
    @vuepress/plugin-palette:  2.0.0-beta.48
    @vuepress/plugin-prismjs:  2.0.0-beta.48
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: ^2.0.0-beta.48 => 2.0.0-beta.48
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.48
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.48
    @vuepress/theme-default:  2.0.0-beta.48
    @vuepress/utils:  2.0.0-beta.48
    vue: ^3.2.37 => 3.2.37
    vue-loader: Not Found
    vue-router: 4.0.12 => 4.0.12 (4.0.16)
    vuepress: ^2.0.0-beta.48 => 2.0.0-beta.48
    vuepress-vite:  2.0.0-beta.48
    vuepress-webpack: Not Found
```

</details>

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/173289956-e010a40b-9dc6-45bd-afe7-12d3743a1d49.png)
![image](https://user-images.githubusercontent.com/33315834/173290015-18e2bd75-ef68-4e3e-b353-31f2a46344d8.png)

👎Try not to waste others time.
