### ISSUE TITLE
[Bug report] 模块“"@vuepress/client"”没有导出的成员“defineClientConfig”。

### ISSUE THREAD

**Issue by tomiaa12** [vuepress/vuepress-next#936]
### Description

![image](https://user-images.githubusercontent.com/34568691/173292979-e5bc2d07-63c4-4a7c-ac83-11b07915d584.png)
 文章中提到`defineClientConfig`
但是引入会提示没有导出此成员
![image](https://user-images.githubusercontent.com/34568691/173293083-1dd4b815-1130-4fd7-853f-cfc6c6cccc98.png)

### Reproduction

https://v2.vuepress.vuejs.org/zh/advanced/cookbook/usage-of-client-config.html

### Used Package Manager

npm

### System Info

```shell
模块“"@vuepress/client"”没有导出的成员“defineClientConfig”。
```

**Comment by Mister-Hope** [comment]
> Reproduction
> https://v2.vuepress.vuejs.org/zh/advanced/cookbook/usage-of-client-config.html

This is NOT Reproduction.

**Comment by tomiaa12** [comment]
解决了，这是vuepress包没有更新到 "^2.0.0-beta.48" 导致的
