### ISSUE TITLE
[Feature request] 支持指定忽略 sourceDir 下的文件或文件夹

### ISSUE THREAD

**Issue by hashiqi12138** [vuepress/vuepress-next#938]
### Clear and concise description of the problem

当指定 sourceDir 后，sourceDir 下的所有文件和文件夹都会被处理

如果 sourceDir 下有 node_modules 时，启动和编译非常慢

且 node_modules 中的一些 md 会导致编译失败

### Suggested solution

支持指定忽略 sourceDir 下的文件或文件夹

**Comment by Mister-Hope** [comment]
https://v2.vuepress.vuejs.org/reference/config.html#pagepatterns

I guess that you have `node_modules` in sub folder, so you may override the default one.
