### ISSUE TITLE
[Feature request] Edit assets name in back-to-top

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#950]
### Clear and concise description of the problem

Unfortunally, "back-to-top" is a word which will active some adblocks like ADGUARD:

![image](https://user-images.githubusercontent.com/33315834/173736005-2892f6ab-d32f-4afd-b513-c1a3ac55dd48.png)

Instead of this page there are reports and issues which user can not see back-to-top button, because the default svg will be output as `back-to-top.xxxx.svg` under `assets`, and tools like ADGUARD choose to add `display: none` to them.

### Suggested solution

Rename `back-to-top.svg` to something else to avoid triggering this.

**Comment by meteorlxy** [comment]
I tried to search the keyword in Adguard Github Org but didn't find the result: https://github.com/search?q=org%3AAdguardTeam+back-to-top&type=code

Could we confirm that it is triggered by adblock tools? 🤔
