### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by Js-Man-H5** [vuepress/vuepress-next#979]
### Description

子页面刷新，页面显示不正常

### Reproduction

https://biuat.ibaiqiu.com/tqa-docs/tqa/scoreTemplate.html

### Used Package Manager

npm

### System Info

```shell
module.exports = {
    base: "/tqa-docs/",
    lang: "zh-CN",
    head: [["link", { rel: "icon", href: "/imgs/favicon.ico" }]],
    title: "TQA 使用 文档",
    description: "TQA使用文档",
    // 主题和它的配置
    theme: defaultTheme({
        logo: "/imgs/favicon.ico",
        navbar: [
            {
                text: "TQA使用文档",
                link: "/tqa/",
            },

        ],
        sidebar: {
            '/tqa/': [
                {
                    text: '质量管理',
                    children: ['/tqa/scoreTemplate.md', '/tqa/rule.md', '/tqa/wangwangConfig.md', '/tqa/qualityInspection.md'],
                },
            ]
        }
    }),
    plugins: [
        nprogressPlugin(),
        backToTopPlugin(),
        searchPlugin({
            locales: {
                "/": {
                    placeholder: "Search",
                },
                "/zh/": {
                    placeholder: "搜索",
                },
            },
        })

    ],

}
```

**Comment by Js-Man-H5** [comment]
这是我package配置 {
  "name": "tqa-docs",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "vuepress": "^2.0.0-beta.48"
  },
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  },
  "dependencies": {
    "@vuepress/plugin-back-to-top": "^2.0.0-beta.48",
    "@vuepress/plugin-external-link-icon": "^2.0.0-beta.48",
    "@vuepress/plugin-medium-zoom": "^2.0.0-beta.48",
    "@vuepress/plugin-nprogress": "^2.0.0-beta.48",
    "@vuepress/plugin-search": "^2.0.0-beta.48",
    "@vuepress/theme-default": "^2.0.0-beta.48"
  }
}

**Comment by Mister-Hope** [comment]
Closing as no production provided.
