### ISSUE TITLE
[Bug report] The effect of production and development is different

### ISSUE THREAD

**Issue by Fatpandac** [vuepress/vuepress-next#982]
### Description

```js
// client.js
export default defineClientConfig({
  enhance({ router }) {
    router.beforeEach((to, from, next) => {
      if (to.path === "/zh-cn") {
        next("/");
      } else if (to.path === "/en-us") {
        next("/en");
      } else if (to.path.indexOf("/doc/en") === 0){
        next("/en/doc" + to.path.slice(7));
      } else {
        next()
      }
    })
    router.afterEach((to, from) => {
      if (to.fullPath !== from.fullPath) {
        addOldDocsContributors();
      }
    });
  },
});
```

I use the router to redirect some paths to another path, it works well in the development environment. Still, in the production environment, it first navigates to the 404 page and then redirects to the right path with the wrong layout.

visit [https://arthas.vercel.app/zh-cn](https://arthas.vercel.app/zh-cn), it will navigate to the 404 page and then redirect to [https://arthas.vercel.app](https://arthas.vercel.app) then show a wrong layout home page of an empty sidebar.

### Reproduction

https://arthas.vercel.app/

### Used Package Manager

npm

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 159.53 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Utilities:
    Git: 2.32.1 - /usr/bin/git
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.48 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.48 
    @vuepress/client:  2.0.0-beta.48 
    @vuepress/core:  2.0.0-beta.48 
    @vuepress/markdown:  2.0.0-beta.48 
    @vuepress/plugin-active-header-links:  2.0.0-beta.48 
    @vuepress/plugin-back-to-top:  2.0.0-beta.48 
    @vuepress/plugin-container:  2.0.0-beta.48 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.48 
    @vuepress/plugin-git:  2.0.0-beta.48 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.48 
    @vuepress/plugin-nprogress:  2.0.0-beta.48 
    @vuepress/plugin-palette:  2.0.0-beta.48 
    @vuepress/plugin-prismjs:  2.0.0-beta.48 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components:  2.0.0-beta.48 
    @vuepress/plugin-search: ^2.0.0-beta.48 => 2.0.0-beta.48 
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.48 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.48 
    @vuepress/theme-default:  2.0.0-beta.48 
    @vuepress/utils:  2.0.0-beta.48 
    vue:  3.2.37 
    vue-loader: Not Found
    vue-router:  4.0.16 
    vuepress: ^2.0.0-beta.48 => 2.0.0-beta.48 
    vuepress-vite:  2.0.0-beta.48 
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
Invalid, you'd better learn what's ssr.

1. you do not have any pages called `/zh-cn`.
2. Visiting the link actually fallback to `/404.html` on vercel

  ![image](https://user-images.githubusercontent.com/33315834/178106878-1fd9bb78-36fa-4594-9355-ddaa1c883faa.png)

3. The vuepress app hydrates and active router, then it found out it should perform a redirect

4. You are finally being redirected to correct page

**Comment by Fatpandac** [comment]
很开心收到你的回复，十分感谢。
不过另有一个问题，为什么重定向后首页会出现空白的 sidebar 呢？

**Comment by Mister-Hope** [comment]
If you want to preform a faster redirect, you may need https://vuepress-theme-hope.github.io/v2/redirect/.

> 为什么重定向后首页会出现空白的 sidebar 呢？

You can open a new issue with a mininal reproduction repo.

**Comment by Fatpandac** [comment]
The vuepress site folder is [here](https://github.com/Fatpandac/arthas/tree/feat/refactor_docs_site/site-vuepress). I just write some code in [client.js](https://github.com/Fatpandac/arthas/blob/feat/refactor_docs_site/site-vuepress/docs/.vuepress/client.js).
