### ISSUE TITLE
[Feature request] Add license dialog support

### ISSUE THREAD

**Issue by taozuhong** [vuepress/vuepress-next#983]
### Clear and concise description of the problem

provide a way to show the license dialog and download some thing:

Use case 1:elementary OS download 
![image](https://user-images.githubusercontent.com/13451009/178179850-0ceb2ef3-b04d-4683-b661-06ab0e1cdffb.png)

Use case 2: agree the agreement then download

### Suggested solution

make a new plugin to do this?

**Comment by Mister-Hope** [comment]
You can register component and support thay on your own
