### ISSUE TITLE
[Feature request] Support layout option in userConfig

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#984]
### Clear and concise description of the problem

It would be greate if users can register new layouts and cover exisiting ones through `layouts` option in config file, instead of creating a local theme and extend the theme he want to use. The second option is a bit complicated and is not good for newcomers.

### Suggested solution

Provide logic to handle `layouts` option in user config file which has the highest priority.

**Comment by meteorlxy** [comment]
`layouts` could be merged into client config. We can track this in #946
