### ISSUE TITLE
[Bug report] 2.0.0-beta.47 resets query params on the initial page load

### ISSUE THREAD

**Issue by vmihailenco** [vuepress/vuepress-next#991]
### Description

It looks like this commit https://github.com/vuepress/vuepress-next/commit/268fa6d0848829c97433bd8bbe57c21bb26c8423 introduced in 2.0.0-beta.47 removes any query params on the initial page load, for example,  https://vuepress2.netlify.app/guide/getting-started.html?foo=bar is redirected to https://vuepress2.netlify.app/guide/getting-started.html and `route.query` is empty in setup function.

2.0.0-beta.46 works as expected and query params are preserved.

### Reproduction

https://v2.vuepress.vuejs.org/new

### Used Package Manager

pnpm

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 5.90 GB / 15.65 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.11.0 - /usr/bin/npm
  Utilities:
    Git: 2.25.1 - /usr/bin/git
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 102.0
  npmPackages:
    @vuepress/bundler-vite: ^2.0.0-beta.49 => 2.0.0-beta.49 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.49 
    @vuepress/client:  2.0.0-beta.49 
    @vuepress/core:  2.0.0-beta.49 
    @vuepress/markdown:  2.0.0-beta.49 
    @vuepress/plugin-active-header-links:  2.0.0-beta.49 
    @vuepress/plugin-back-to-top:  2.0.0-beta.49 
    @vuepress/plugin-container:  2.0.0-beta.49 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.49 
    @vuepress/plugin-git:  2.0.0-beta.49 
    @vuepress/plugin-google-analytics: 2.0.0-beta.49 => 2.0.0-beta.49 
    @vuepress/plugin-medium-zoom:  2.0.0-beta.49 
    @vuepress/plugin-nprogress:  2.0.0-beta.49 
    @vuepress/plugin-palette:  2.0.0-beta.49 
    @vuepress/plugin-prismjs:  2.0.0-beta.49 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: 2.0.0-beta.49 => 2.0.0-beta.49 
    @vuepress/plugin-search: 2.0.0-beta.49 => 2.0.0-beta.49 
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.49 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.49 
    @vuepress/theme-default: 2.0.0-beta.49 => 2.0.0-beta.49 
    @vuepress/utils:  2.0.0-beta.49 
    vue:  3.2.37 
    vue-loader: Not Found
    vue-router:  4.1.2 
    vuepress: 2.0.0-beta.49 => 2.0.0-beta.49 
    vuepress-vite:  2.0.0-beta.49 
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
nice catch, we should preserve query

发自我的iPad

在 2022年7月19日，17:10，Vladimir Mihailenco ***@***.***> 写道：

﻿

Description

It looks like this commit 268fa6d<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvuepress%2Fvuepress-next%2Fcommit%2F268fa6d0848829c97433bd8bbe57c21bb26c8423&data=05%7C01%7C%7C937ec298d03141b4964108da696682e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637938186266000910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ce4psubxkzaiMQK9Nf661Jxx5C9%2FFgKR0Vll2maqqb4%3D&reserved=0> introduced in 2.0.0-beta.47 removes any query params on the initial page load, for example, https://vuepress2.netlify.app/guide/getting-started.html?foo=bar<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvuepress2.netlify.app%2Fguide%2Fgetting-started.html%3Ffoo%3Dbar&data=05%7C01%7C%7C937ec298d03141b4964108da696682e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637938186266000910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=R%2BiEKpUVDTOgX6JGwrD8c7X9Cb6oRrfwOghAPz9xpFI%3D&reserved=0> is redirected to https://vuepress2.netlify.app/guide/getting-started.html<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvuepress2.netlify.app%2Fguide%2Fgetting-started.html&data=05%7C01%7C%7C937ec298d03141b4964108da696682e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637938186266000910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vULEIvd1LzPtbEnT6M8kmykwBpLOV%2BJhB93UaV76Un8%3D&reserved=0> and route.query is empty in setup function.

2.0.0-beta.46 works as expected and query params are preserved.

Reproduction

https://v2.vuepress.vuejs.org/new<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fv2.vuepress.vuejs.org%2Fnew&data=05%7C01%7C%7C937ec298d03141b4964108da696682e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637938186266000910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nB%2Fego0WhXbzJ7D%2FzdxYZTXwaNSaDTwsk3aIe5g5pi4%3D&reserved=0>

Used Package Manager

pnpm

System Info

System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 5.90 GB / 15.65 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.11.0 - /usr/bin/npm
  Utilities:
    Git: 2.25.1 - /usr/bin/git
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 102.0
  npmPackages:
    @vuepress/bundler-vite: ^2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.49
    @vuepress/client:  2.0.0-beta.49
    @vuepress/core:  2.0.0-beta.49
    @vuepress/markdown:  2.0.0-beta.49
    @vuepress/plugin-active-header-links:  2.0.0-beta.49
    @vuepress/plugin-back-to-top:  2.0.0-beta.49
    @vuepress/plugin-container:  2.0.0-beta.49
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.49
    @vuepress/plugin-git:  2.0.0-beta.49
    @vuepress/plugin-google-analytics: 2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/plugin-medium-zoom:  2.0.0-beta.49
    @vuepress/plugin-nprogress:  2.0.0-beta.49
    @vuepress/plugin-palette:  2.0.0-beta.49
    @vuepress/plugin-prismjs:  2.0.0-beta.49
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: 2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/plugin-search: 2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.49
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.49
    @vuepress/theme-default: 2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/utils:  2.0.0-beta.49
    vue:  3.2.37
    vue-loader: Not Found
    vue-router:  4.1.2
    vuepress: 2.0.0-beta.49 => 2.0.0-beta.49
    vuepress-vite:  2.0.0-beta.49
    vuepress-webpack: Not Found
